== Chapter III.

A Vindication of Sound Doctrine and Practice--Three Epistles to Friends.

And now to clear my conscience in the presence of the Lord God,
that the minds of the simple may be informed,
and that those who are in unbelief and who persecute the Truth,
may be left without excuse, I shall declare what I bear testimony of,
and what I bear witness against.
He that hath an ear, let him hear, and let him that is spiritual judge.

I witness that Christ Jesus is the Light of the world,
and enlightens every one that cometh into the world; and he testifieth against the world,
that its deeds are evil;
and that it is his Light which makes manifest in the consciences of you men and women,
the lusts of your hearts; and shows you that you should not live in covetousness, pride,
envy, anger, swearing, lying, cursed-speaking, drunkenness, lust and uncleanness,
pleasures and wantonness, dissembling, backbiting and hypocrisy;
and the same Light which witnesses against these things, and discovers them to be evil,
is the condemnation of the whole world, which hates the Light;
and all you who do those things which are evil--you hate the Light.

You who are covetous and proud, you hate the Light: you who are angry and malicious,
you hate the Light; and all you that are swearers, liars, and cursed-speakers,
you hate the Light; and all you who are drunkards, lustful ones,
lovers of pleasures and pastimes, you hate the Light, and love darkness rather,
because your deeds are evil.
And here is your condemnation, that Light is come into the world,
and convinces you of sin; and you love sin, rather than to walk in the Light.
And in your own consciences and knowledge the Light
will witness that your condemnation is just;
and you shall be forced to acknowledge that God is righteous,
when he rewards you according to your works.
Therefore repent, and turn to the Lord while you have time.

And all you who turn to the Lord, and love the Light,
with which Christ has enlightened you, which discovers to you the evil of your hearts,
and calls for purity and holiness, and amendment of life,
and walk in it--it will lead you out of darkness and your evil deeds,
up to God the Father of lights; and, walking in the Light, as God is in the Light,
you will have fellowship one with another,
and you will witness the blood of Jesus Christ cleansing you from all sin;
(1 John 1:7-9) which none of those can witness, whose minds are from the Light,
walking in darkness and the love of the world,
though they may make a profession of Christ,
and talk of justification through faith in his blood,
with that mind which lusts to do evil, which is enmity to God and to Christ.
Therefore, all you that love your souls, love the Light and walk in it;
for all of you have a measure which discovers in your consciences the works of darkness.
Though some object and say,--have unbelievers the Light of Christ?
I answer, yea, and it shines in darkness, and they hate it, and love darkness rather,
because their deeds are evil: and the counsel of Christ, from whom the Light comes,
to such is, "`Walk while ye have the Light, lest darkness come upon you;
and believe in the Light, that ye may be the children of the Light.`"
(John 12:35-36)

And I witness that the free grace of God, which bringeth salvation,
hath appeared to all men; and it teacheth us to deny all ungodliness and worldly lusts,
and to live soberly, righteously, and godly, in this present evil world.
(Titus 2:11-12) So, by the free grace of God we are saved,
(Eph. 2:8-10) as the saints ever were; which grace taught them, and teacheth us,
to deny all self-works and self-righteousness, which are as filthy rags.
And all you are found in self-works, who live in ungodliness,
dissimulation and hypocrisy, professing God in words but denying him in works,
and turn the free grace of God into wantonness, and stand in your own wills,
which brings destruction upon yourselves.
And God is just, who delights not in the death of a sinner, but rather that he may turn,
and come to life, which life is in Christ,
who lighteth every one that cometh into the world,
with a measure sufficient to lead out of darkness all that love it,
and which is the condemnation of all that hate it,
and turn the grace of God into wantonness.

But some object and say, if all have a measure of light,
which leads to life those who love it, and condemns those who hate it;
is not this to hold salvation by works, in man`'s loving or hating the light?
and, whether hath man free will to love or hate the Light?

I answer, no: man is not saved by his own works,
neither hath he free will of himself to love the Light; but God has first so loved man,
that in his free grace he has given him a measure of Light;
and by his grace is the love to the Light begotten,
and man`'s own works and his own will are denied,
in which the enmity and desire to do evil lodge.
And all his works now come to be wrought in God, in the cross to man`'s will;
which cross is the power of God unto salvation.
And this grace of God which brings salvation, by which the love to the Light is begotten,
hath appeared to all men;
(Titus 2:11-12) and would gather you into the love of the light,
as Christ would have gathered Jerusalem, but they would not;
and no more will you be gathered now, who stand in your own wills;
for you reject the counsel of God, slight the day of your visitation,
and turn the grace of God into wantonness.

So here I witness, that it is by grace that man loves the Light and is saved;
and by his own will he hates the Light and is destroyed.
For God willeth not that any should perish, neither tempteth he any man to do evil,
nor to hate the Light.
Therefore put your mouth in the dust, and let the Truth judge you,
who stand in your own wills, which are enmity to God, and live at ease in the flesh,
in pride, pleasures and secret lusts, sporting yourselves in the daytime,
and yet would charge the fault upon God and make him the author of these things;
whereas he, by his Spirit,
has often reproved you in your consciences for the evil of your doings;
which reproofs you have rejected; the God of this world having blinded your eyes,
because you did not abide in the love of the Truth, but had pleasure in unrighteousness,
which has hardened your hearts, that you are become past feeling,
and in the reprobate sense, commit iniquity with greediness,
and live without the fear of God, doing despite unto his Spirit of Grace.
Because he endures with long patience and forbearance, your wicked works,
(which fit you for destruction,) and doth not speedily execute his judgments upon you,
therefore you harden your necks.

But knowest thou not, O man, that the goodness of God leadeth to repentance;
and that his Spirit shall not always strive with man;
but that he will render tribulation and anguish,
wrath and vengeance upon the children of disobedience, who join to the serpent`'s seed,
which is accursed and reprobate from God.
And in that day of his power you cannot resist nor escape the day of his wrath,
which shall burn as an oven, if you follow the serpent,
who leads you into lust and filthiness;
and none can save you from the wrath of Almighty God,
but you shall perish in your abomination; having sown to the flesh,
you shall of the flesh reap corruption,
and be punished with everlasting perdition from God who is pure,
and from his holy angels.
Therefore, prize your time, and take heed to the Light,
which secretly reproves you for sin, and it will bring you to repentance,
and into the fear of God; but disobeying it is your condemnation.
Remember you are warned in your life-time, all you that live without the fear of God,
at ease in the flesh, and who commit sin because grace abounds.

And I witness that the Spirit of Truth, which convinceth the world of sin,
is sufficient to lead and guide into all Truth, and convinceth also of unbelief,
of righteousness and of judgment.
And here let the Truth judge you, who say that the Light,
which convinceth the world of sin, doth not convince them also of unbelief;
or who say that the Spirit of Christ doth not convince an unbeliever of sin,
and is not sufficient to lead into all Truth without the teachings of men.
For Christ saith that the Spirit of Truth shall convince the world of sin;
and they are the world, who believe not on him; and it convinceth them of unbelief,
and will lead those who submit themselves to be guided by it, into all truth.
And he who denies that He is come, who convinceth the world of sin,
is a deceiver and an antichrist.
Therefore all people, take heed to that which convinceth you of sin,
and calls you to repent and amend your lives, and lets you see your secret lusts,
corruption, hypocrisy, hardness of heart and unbelief, and reproves you for it;
for that is the Spirit of Truth, and as you walk in it,
it will not let you satisfy the lusts of the flesh;
but it will bring a cross to your wills and lusts,
and so you will witness the flesh crucified with the affections and lusts,
as the saints did and do, who rejoiced in the cross of Christ,
and walked and do walk in the Spirit, which leads in at the strait gate of self-denial:
and in the strait path of self-denial you must walk,
and take up the daily cross of Christ to your wills and lusts,
or you cannot be the disciples of Christ, nor enter into the kingdom of God;
for the broad way leadeth to destruction: and Christ Jesus, who is the way to the Father,
the Truth and the Life, and the Light of the world, has said,
"`If any man will come after me, let him deny himself, and take up his cross daily,
and follow me; and he shall not abide in darkness, but shall have eternal life.`"

And I witness that the gift of God is free, and is eternal life;
which life is Jesus Christ, who tasted death for every man.
And I witness that faith in his blood justifieth; which faith is the gift of God,
given to all those that wait on him in the Light; and the same faith that justifies,
purifies the heart; and the blood of Jesus cleanseth them who are in the faith,
from all sin.
And this faith, which purifies and works by love, +++[+++and brings the soul]
into the obedience of Jesus Christ, is not a dead talk, and barren profession,
in which the world lives; but it is living, and stands in Jesus Christ;
and Christ is in him that hath it,
"`the hope of glory:`" and this faith is the victory
whereby the saints overcome the world,
and put off the body of the sins of the flesh by the putting on of the body of Christ:
and here the old man is put off with his deeds,
and the enmity slain by the blood of his cross,
and the new man created after God in righteousness and true holiness,
in the image of God that was in the beginning, who is perfect and sins not,
neither can he, because he is born of God, and his Seed remains in him.
You who read this, prove yourselves, whether you be in the faith or not;
and profess no more than you possess.

For I stand a witness against all you who make a profession of God and of Christ,
and talk of faith in him, and redemption by his blood, and free justification,
and yet say that no one can be made free from sin whilst he is in this life;
and who yourselves live in sin, and in the love of the world,
and conformity to its spirit.
For you are they, who say and do not, and are enemies to Christ,
and make him a cloak for your sins.
You who walk in darkness, cannot witness redemption through his blood;
and your faith is dead and vain, who are yet in your sins,
and believe that you must live in them whilst you are in the body.
For here you are found in the slothful servant`'s condition, who murmur and complain,
and walk after your ungodly lusts, and say you have not power to subdue them;
and then sit down at ease, to eat, drink, and be drunken;
and so are overcome by the cares of this life, and refuse to take up the cross,
which the Apostle preached,
"`the power of God unto salvation;`" and look for a power
to come and destroy sin when you go out of the body,
and expect never whilst here,
to have your carnal lusts and desires crucified in the cross.
And by the light of Christ you are seen to be they
who put him to an open shame by your works of darkness,
and vain imaginings that no one can be saved from sin whilst he is in the body;
whereas the Scripture saith that "`He is able to save to the uttermost,
all those that come to God by Him;`" and the saints that did and do follow him,
were and are "`made free from sin,`" and "`become the servants of righteousness,`"
and "`have their fruit unto holiness and the end everlasting life.`"
And in this state, some of you who make a profession of Christ,
are found--putting the day of the Lord afar off;
and I warn you to "`awake unto righteousness and
sin not:`" for the "`Judge standeth before the door,
and the wages of sin is death.
He that hath an ear to hear, let him hear.`"

And I witness that a minister of Christ is not made such by the will of man,
nor fitted for his ministry by human learning, or by the sharpness of his wit,
or by any natural gift; but by the gift of the Spirit of Jesus Christ;
which gift cannot be bought or sold for money, nor limited to times or persons,
but is free; and it constrains him who hath received it, freely to minister it to others.
And I stand a witness against all those who say, they are gifted to preach the Gospel,
and limit themselves to a particular time, people, and place;
and there sell their gift for money: for these are they who go in Balaam`'s way,
and through feigned words and high expressions, make merchandise of the people.

And I witness against all those, who profess themselves to be ministers of Christ,
and deny that he "`lighteth every man that cometh
into the world;`" or who call his Light,
which lighteth every man that cometh into the world, a natural light;
and who deny the immediate call to the ministry by the Spirit of Christ;
and say that they are fitted for the ministry by human learning,
and called and approved by men, for they are such as are disapproved of God;
and they cause the people to err by their lies,
in denying that Christ lighteth every man that cometh into the world;
and in calling his Light natural, which Light is the very way to God.

And these are building without the corner-stone, and their building is Babel:
for they run, and were never sent of God,
and speak a divination of their own brain-study, and not from the mouth of the Lord;
they use their tongue when the Lord hath not spoken to them;
but they steal the word from their neighbour.
The Lord is and ever was against such;
and he hath shaken his hand against their dishonest gain,
who for "`filthy lucre`" run when he hath not sent them;
therefore they shall not profit the people at all.

By their fruits they are known;
and though they come "`in sheep`'s clothing,`" and
profess themselves to be ministers of Christ,
yet I witness against all those who abide not in the doctrine of Christ,
but do those things against which the true prophets and Christ witnessed;
for they are inwardly ravening wolves, who seek for their gain from their quarter,
and clothe themselves with the fleece, and feed themselves with the fat,
and bite with their teeth, and cry, Peace, peace,
and prepare war against them who put not into their mouths; and preach for hire,
and divine for money.
Against such as these, the true prophets of the Lord witnessed,
as the Scriptures testify.

And I witness against all those who profess to be ministers of Christ,
and receive tithes, which were appointed under the first covenant,
to pay the first priesthood; which covenant was found faulty, and its priesthood changed:
and against such as sue people at law for tithes or for wages,
to whom they neither minister spiritual or temporal things;
for these things are not only contrary to the doctrine of Christ,
and the practice of his true ministers, but even the false prophets,
deceivers or hirelings, never sued any at law for tithes or wages,
that we read of in the Scriptures: and here you, who do such things, are,
by the Light of Christ, seen to outstrip them all in oppression.

O! blush for shame, and let the Truth judge you,
who profess to be teachers of others and do such things.
"`Ye generation of vipers, how can you that are evil, speak good things?
How can you escape the damnation of hell!`" who profess
yourselves to be ministers of Christ,
but abide not in his doctrine, but do those things against which he cried, woe!
And I witness against all you who profess yourselves to be ministers of Christ,
and live in covetousness, strife and contention; swearing,
drunkenness and false accusing, pride and headiness, lording it over God`'s heritage;
and against all you who have a form of godliness, but deny the power,
which leads out of sin; and who keep the people ever learning,
but never able to come to the knowledge of the Truth, which makes free those who know it,
and walk in it.--Now, you who call this,
"`railing against the ministers of Christ,`" speak against the Scriptures,
which bear testimony to what is here declared:
and the Light of Christ will condemn you eternally from God,
who are found in these practices, which are contrary to Scripture, except you repent.

But all the true ministers of Christ I own: by their fruits they are known:
they have received Christ, and are sent by his Spirit to preach:
they abide in his doctrine, and freely declare that which they have freely received:
they walk in the Spirit, and bring forth the fruit of it, which is love, joy, peace,
long-suffering, gentleness, goodness, faith, meekness, temperance, brotherly kindness,
and the like.
And these, who are the true ministers of Christ, are no hirelings, nor covetous ones;
nor proud, self-willed, incontinent, heady, unholy ones;
nor despisers of those that are good; nor persecutors, nor false accusers,
nor truce-breakers, nor resisters of the Truth, nor deniers of the power of godliness,
+++[+++nor of those who are]
ever learning, yet never come to the knowledge of the Truth.
But the ministers of Christ walk in the power of godliness; and go from city to city,
and from village to village, preaching the kingdom of God,
and enter into the houses of those who are worthy;
and bring people to the knowledge of the Truth, which leads all who love it out of sin.
And these I own and honour, "`who give no offence in any thing,
that their ministry be not blamed;
but do in all things approve themselves as the ministers of God, in much patience,
in afflictions, in necessities, in distresses, in stripes, in imprisonments, in tumults,
in labours, in watchings, in fastings; by pureness, by knowledge, by long-suffering,
by kindness, by the Holy Ghost, by love unfeigned, by the Word of Truth,
by the power of God, by the armour of righteousness on the right hand and on the left,
by honour and dishonour, by evil report and good report; as deceivers, and yet true;
as unknown, and yet well known; as dying, and behold they live; as chastened,
and not killed; as poor, yet making many rich; as having nothing,
and yet possessing all things.`"
And those who thus approve themselves, I own and esteem;
they are not known or approved by the world, but hated and persecuted by it.

And I also own and witness the ordinances of Christ,
as self-denial and the daily cross,--love one to another,--to do to all men,
as we would be done unto,--not to swear at all,--if any smite on one cheek,
to turn the other,--to feed the hungry and clothe the naked, and the like.
And I also own preaching and prophesying according to the proportion of faith,
as every one hath received of the Lord; and praying with the Spirit,
and singing with the Spirit, and with the understanding also, as the Lord moves.
And I own and witness baptism by one Spirit into one body,
which brings down into death with Christ, and into the fellowship of his sufferings.
And I own and witness the communion of saints at the table of the Lord,
where they feed on the living bread, and all drink into one Spirit,
which makes them of one heart and one soul; praises forever unto the Lord!
But I know that the sons of Hagar, the Egyptian woman, who are born after the flesh,
will scoff at the moving of the Spirit of the Lord, and say, "`Aha,
aha! these people will do nothing, but what the Spirit moves them to.`"
But I tell you who scoff at the moving of the Spirit of the Lord, that you are they who,
Peter said, should come in the last time.
But yet a little while, and the scorners shall be consumed, and you,
who turn from the Spirit of the Lord and work wickedness, be cut off;
but they who are led by the Spirit of God, are the sons of God,
and they shall inherit the kingdom which fades not, and shall abide in it forever.
And here is a true testimony declared against all you who falsely say,
I disown or rail against the ordinances of Christ.

But I freely testify against the inventions and traditions of men, as preaching for hire,
a divination of their own brain-study, limiting themselves by the hour,
and standing praying in the synagogues, for a pretence making their prayers long,
whilst they regard iniquity in their hearts, and are exercised with covetous practices,
and do those things against which Christ cried,
woe!--and singing David`'s Psalms in rhyme and metre;
proud men and men of strife and contention sing these words, turned into rhyme: "`Lord,
my heart is not haughty, nor my eyes lofty,
neither do I exercise myself in great matters, nor in things too high for me.
Surely I have behaved and quieted myself as a child that is weaned of his mother;
my soul is even as a weaned child.`"
And those that live without the fear of God,
and never come into any true sense of their sins, but live in jollity and wantonness,
sing: "`All my flesh trembles, I am afraid of thy judgments: I go mourning all the day:
all the night make I my bed to swim.`"
Thus poor, ignorant people sing lies to the Lord, whereby he is dishonoured.

And these things, and sprinkling infants, for which there is no Scripture,
are counted the ordinances of Christ, by those who know not God.
But I witness against them,
and against that which the world calls a "`sacrament,`" where a company of carnal people,
who discern not the Lord`'s body, meet at a carnal table,
to eat and drink carnal bread and wine, which feed the carnal man:
for these are they who "`eat and drink damnation
to themselves;`" some of whom live in covetousness,
oppression and hard-heartedness; others in envy, hatred, rashness, self-willedness,
and persecution of the innocent; others in pleasures, drunkenness, lust and uncleanness;
others in dissimulation and hypocrisy, having a form of godliness but denying the power.
And Christ never commanded you any such things as you practise and call his ordinances,
neither were they practised by the saints; for they dwelt in the Light and Life,
and possessed the substance.
Therefore cease from your inventions and traditions, and walk in the Light of Christ,
which reproves you for sin, and calls for holiness and truth in the inward parts;
in which Light is the unity and communion of saints.

And whereas I am accused of railing against and contemning authority,
I declare in the presence of God, it is false:
for my soul is subject to the higher powers for conscience-sake.
And I own magistracy, which is the ordinance of God,
ordained for the punishment of evil doers, and for the praise of them that do well:
and those magistrates who are guided by the light of Christ, which is equal and just,
and who do justice according to the law of God without respect of persons,
I own and honour in my soul; not with flatteries and deceit,
as the custom of the world is, but with submission to the law of God:
"`he is the minister for good`" who respects no man`'s person,
but punishes the evil doer, and countenances him that doeth well.
But against him who is in the place of a magistrate, and turns from the light of Christ,
casts the law of God behind his back, respects the persons of men, perverts all equity,
causes justice to stand afar off, lets the evil-doer go free,
but punishes the innocent who walk in the law of God and are subject to
every ordinance of man for the Lord`'s sake,--against him do I witness,
without respecting his person.
Yet no power do I resist, but dwell in that which suffers all things, hopeth all things;
and am subject to the will of God,
in whom I have that peace which the world cannot give nor take from me;
praised be the name of the Lord forever.

[.asterism]
'''

+++[+++During this imprisonment in Northampton Jail,
John Whitehead wrote the three following Epistles:]

An Epistle +++[+++of Christian Counsel and Encouragement,]
to be Read Among Friends, When they are Met Together to Wait upon God in His Fear.

Dear Friends,--

Whose minds are turned to the Light,--in the name
and power of our Lord Jesus Christ dwell;
that the pure Light which comes from him,
may guide your minds up to God the Father of Light:
to which Light all the world must bend,
and by it must they all be condemned who act contrary to it,
though they make a profession of it, and get the words that were declared from it.
Therefore I warn you all, in it walk and wait; and take heed of hypocrisy and deceit,
and of reasoning with flesh and blood; for there you go from the Pure into the earth,
and take counsel of that which is sensual and not of the Lord;
there the carnal will is fed and the heart waxeth wanton, and kicketh against the Lord;
it goeth down into Egypt,
and then takes counsel at that wisdom which leads
the mind to take pleasures in her treasures,
and which is of the earth, and feeds the earthly nature which doth crucify the Just;
and blinds the eye, that the eternal riches are not seen; and makes the heart gross,
that it cannot savour the things that be of God.
Then carelessness and deadness follow--hard thoughts of God,
and much reasoning against him; and it will be said in the heart,
Wherefore should we wait any longer?--what profit
is there in it?--we walk not as others do.
And then reason looks forth into the world; and the devil, the enemy of your souls,
presents a glory and beauty in it,
and shows you how pleasantly the children of the world live in it,
and are not troubled as you are;
and then the earthly affections not being kept in the cross, join with the tempter,
who carries you headlong into the world, to delight in its pleasures, profits,
and vanities, and beggarly lusts; but "`the end of these things is death.`"

And woe be unto you who turn from the pure Light,
whose portion is in the world! for you are on slippery places;
and the delights of your heart shall be cut off from you and fade away;
and then cometh the destruction, which you have brought upon yourselves,
and the reward of your hands shall be given you.
Your portion is not as Jacob`'s portion, which abides forever,
which is the Lord of Sabaoth, who is the rewarder of all the faithful ones,
and in whom they have rest and an inheritance forevermore.

Therefore I say unto you all, abide in the pure Light of Christ manifested;
and standing single in mind to the Lord and single-eyed,
the whole body will be full of Light; you will see the joy set before you,
and the glory that shall be revealed in you at the appearance of Jesus Christ,
whom you whose eyes are single, beholding as in a glass, with open face,
are translated into the same image, from glory to glory,
even by the Spirit of Jesus Christ, which did first convince you of sin,
of righteousness and judgment.

But all you who have turned from the Spirit which convinced you of sin,
a veil is drawn over your hearts, and the glory of the Lord is not seen.
The carnal desire goes forth into the glory of the world, lets in pollutions,
and then the "`pure mind`" groans under the burden and is unsatisfied;
and here is the double-minded man who is unstable in all his ways.
Therefore dwell in the Pure that discovers these desires which go into the earth,
and judge them by the Light; stand in the power of Christ Jesus to deny them,
and then wait in the pure desires which breathe after God;
for that which breathes after him is begotten of him; and they who witness this,
can savour the things which are of him; and shall, as surely as God is faithful,
be filled with his living mercies and love which nourish unto eternal life.
And this you will come to feel and know and taste of, if you faint not,
but continue patiently waiting in the Light,
and to know your minds kept by it out of all that would choke the pure Seed of God;
and so you will come daily to witness a growth in the inner man,
and your faith will be increased, and love will abound amongst you,
and your delight will be in meeting together in the Lord,
and you will receive wisdom from him, to watch over one another,
and to build up one another in that which is pure.

But I warn you to take heed of uttering words from your own comprehensions and wisdom,
whilst you do not dwell in the Life nor in the possession of it; for he is the hypocrite,
who speaks of what he possesses not, and in which he does not dwell.
So all of you dwell in the pure Life,
then coldness and hardness of heart will be kept out; from which arise grudgings,
evil surmisings, whisperings and backbitings, which rend one from another,
and make divisions, and so let in the enemy of your souls,
who then drives away those who halt and are weak.

Therefore I say unto you all, judge these things, every one in particular,
and in the spirit of meekness and wisdom reprove one another, and exhort one another:
for that joins together and builds up, which is done in the Spirit.
And if any offend or be overtaken through weakness, with a fault,
in the spirit of meekness, you that are spiritual restore such an one,
and bear nothing in mind of evil one against another;
but as God in Christ hath forgiven you, so forgive one another;
and walk together as little children, in love and in wisdom,
that by the pure wisdom of God in you, you may be justified.
All of you abide and wait in this pure Light which comes from Christ Jesus;
so that you may come to receive Him in whom is no iniquity:
that by the working of his power, you may witness the bond of it broken,
and sin finished, which hath oppressed the just, and the soul to be set free;
then by the Spirit of our Lord Jesus you will witness
the covenant of life sealed to your souls,
and you will all grow up in unity, in the pure love of God, who is blessed forever;
to whom be eternal praises and glory forevermore.

And with that love which is not feigned, which seeks not itself,
which is not easily provoked, which thinketh no evil, love one another;
for it is the very bond of perfection; and by that you being bound together,
all the world cannot break you; but must bend to that which hath gathered you,
and by it be broken, or else be ground to powder and perish.

Therefore to the true Light which comes from Christ Jesus, which was from the beginning,
which did first convince you of sin and discover to you the vanities of the world,
and hath in measure gathered you out of the world--to this Light take heed,
and to it be faithful, even to the end;
that you may all come to witness the enjoyment of that which endures forever;
where I am with you, who am a prisoner for the testimony of Jesus Christ,
but at liberty in the eternal Spirit forevermore; praises be to the Lord God,
who is worthy, blessed forever.

All take heed of halting, and feeding on that which is past; but mind your growth,
and take heed of formality, and of resting in your former knowing and owning the Truth,
lest you lose your tenderness,
and a boasting spirit get up in the sight of that which you possess not.

From the Common Jail in Northampton, where we are eight in prison for the Truth`'s sake;
but the presence of God is our life and liberty.

The 5th day of the Third Month, 1655.

An Epistle +++[+++Exhorting to Abide in the Light.]

All Dear Friends In The Truth,

With whom I am present in spirit--take heed of deceit,
and do not reason nor consult with flesh and blood in this day of trial,
lest your minds be drawn down into unbelief and earthliness, and the fear of vain man,
whose breath is in his nostrils, whose glory must wither and be laid in the dust.
But all abide in your measure of light,
that by it you may be led into the power and life of Jesus Christ,
who came not to do his own will, but the will of the Father;
and was contradicted by sinners, endured the cross,
and hid not his face from shame and spitting, but gave his cheek to the smiter,
and his head to them that pulled off the hair.
He learned obedience by the things which he suffered,
and through sufferings was made perfect, and became a faithful high priest;
who having been tempted like us, is able and willing to succour them that are tempted.

Therefore all wait in his Light, which discovereth that nature which is contrary to him,
and it will judge and condemn that mind which is sensual, unbelieving,
and faints because of the rage of the enemy.
Abiding in the Light which judgeth the sensual mind and will, which is contrary to God,
it will lead you into the power and life of Christ Jesus,
where your souls will receive virtue and strength
to stay and support you in the day of trial,
enabling you to stand perfect and immoveable in the will of God
(to do it and not your own) which you will witness sanctifying
you through the obedience of the Spirit of Jesus Christ;
which Spirit will lead you into the fellowship of his sufferings,
and therein arm you with the same patience and meekness,
to endure the cross and despise the shame which is to be met with in the narrow way,
that leads through the world, in which the trouble is,
into the joy which is set before you.
And in the Light look up to Christ in whom is the power
which leads to the mark and prize of the high calling;
in which power all you who are fruitful and armed,
do trample upon and rejoice in the light afflictions which are but for a moment,
and are not to be compared to the weight of glory revealed in Christ Jesus.

Therefore dear friends, in the Light and power dwell,
that your minds may be established in the eternal God:
look not down to things that are seen, which are temporal and fading;
lest while you look down at the flourishing of the wicked,
or at the rage and cruelty of the enemy, within or without, you lose your guide,
and so faint in your minds at the great fights of afflictions
and tribulations that are suffered to assault you,
whose minds are illuminated for the trial of your faith,
which is more precious than gold which perisheth;
though for the present it seems not joyous but grievous,
yet it brings forth the pleasant fruits of righteousness.
And blessed are you that abide the trial, and are found faithful until you overcome;
for you shall inherit all things, and be made pillars in the temple of God,
in whose presence is joy forevermore.

Therefore mind your Guide, the Light, and look unto Jesus,
the author and finisher of your faith,
that in the faith you may be kept and not discouraged,
because the devil casts some of you into prison;
neither fear ye any of those things that you or we shall suffer,
for the tribulation is for an appointed time.
Therefore inasmuch as Christ hath suffered for you, arm yourselves with the same mind,
and take for an example of suffering in patience,
the prophets and apostles and dear saints of God,
who ever suffered by the unrighteous seed,
and were tried and proved in sufferings--who received
joyfully the spoiling of their goods--were mocked,
stoned, and imprisoned, and were in necessities, distresses, and tribulations.
And these things they suffered patiently, and saw the end of the Lord to be good;
and that he was of tender compassion to those that feared him,
who witnessed that tribulation wrought patience, and patience experience,
and experience hope, which made them not to be ashamed,
because the love of God was shed abroad in their
hearts by the Holy Spirit which was given unto them,
a measure of which Spirit ye all have received; and if you walk in it,
you will witness the life of the Scriptures,
and the same love shed abroad in your hearts,
which the holy men of God witnessed who gave forth the Scriptures.

And by the light of the Spirit of Jesus Christ you will see the Scriptures opened,
and the world`'s enmity and persecution to be the same that was foretold
of the dragon and his angels warring against Michael and his angels,
who shall prevail, and cast him into the lake.
But you must witness the parable opened, and see the thorny ground,
and the highway ground, and the stony ground, which, after the seed is sown,
brings not forth fruit; but the cares of this life choke it in some,
and the fowls of the air catch it and fly away with it in others;
and such are they who are quick to speak of what they see in the comprehension,
and abide not in the Life which bridles the tongue and makes fruitful.
And others receive the Word of Life gladly,
and joy arises in the convincement and illumination of the mind;
but these not sinking down into the power of the Spirit that doth enlighten,
that by it the will and inordinate affections may be judged and condemned
and crucified in the cross which is the power of God to salvation,
and their hearts not being cleansed and seasoned with grace,
when persecution and affliction come for the Word`'s sake,
then such as come not unto the Life are offended, and stumble, and turn aside;
not being willing to bear the shame, take up the cross,
and endure the contradiction of sinners.

But the honest heart sinks down into the Light,
to be guided--dwells in the power of the living God,--is seasoned with his grace,
and made willing to endure the cross,
that it may be made fruitful in the power of Jesus Christ,
who makes all things work together for good to those that abide in him.

Therefore own not that which begets hard thoughts of God, and murmurs against him,
when things fall out contrary to your wills;
but deny it and judge it by the Light of Christ,
with which read your conditions and see what fruit you bring forth.
For now is the time of trial; and whosoever loves father or mother, wife or children,
friends or acquaintance, house or lands, more than Christ, is not worthy of him.
So all in his Light judge and deny the lust,
which could retain a delight or love to the world and the things that be in it,
which must pass away: for "`if any one love the world,
the love of the Father is not in him.`"

Therefore all abide in the unchangeable Light,
which judges the love of the world and the changeable
mind which retains not God in its knowledge;
and the Light, which judges that mind, as you abide in it, will judge you,
and keep you in the pure knowledge and love of God,
in which you will have pure refreshment and springings in of life, peace and joy,
which fade not away.
The almighty, powerful God be with you all, and keep you innocent, clean and pure,
in unity and peace one with another in his own power,
singly to rest stayed and unmoveable in his will,
where there is no weariness nor fainting;
that you all may be found faithful improvers of the talent which Christ hath given you,
in watching one over another with the single eye, in tender love,
that you may enter into the joy of the Lord,
and receive dominion to judge and rule over all the powers of darkness
which would cause you to faint in the way to eternal life.
With tender bowels of love I salute all dear babes of God,
who am your dear brother in the everlasting covenant of our Father`'s love,
and a prisoner of Jesus Christ.

John Whitehead.

Northampton Jail, the 11th of the Sixth Month, 1655.

An Epistle +++[+++Against Worldliness, etc.]

Dear Friends,

Every one, in the measure of Light, wait and be faithful;
that in the pure life and power you may all grow up,
and witness bread within to feed upon,--salt within to savour you withal;
and that you may all be guided up to God by the pure Light of Christ Jesus,
which witnesses against all formality, vain words, earthliness and carelessness;
and that by his Spirit you may be taught to deny all worldly lusts, strife,
mastery and unprofitable judging one another, which begets murmurings,
whisperings and backbitings.
These spring from the root of bitterness which troubles, and is out of the Truth,
veils the Pure, and draws you out of the pure love of God,
with which you ought to love one another, and not to be self-lovers, high-minded,
and profane as Esau.

Therefore all by the Light judge, and deny that mind which is carnal,
in which these things lodge which are contrary to the Light.
And walk in the daily cross, having the conversation without covetousness;
and take heed of slighting the day of the visitations wherein
the Lord waits to manifest his love unto you,
by giving way to your slothful, earthly spirits,
that savour not the things that be of God,
but draw down the mind to delight in and love earthly things which must perish,
which keep you from being made partakers of the durable riches that are in Christ Jesus,
laid up for all that are faithful.
So every one prize your time,
and be faithful and diligent in meeting together to wait upon the Lord,
whom ye will see present, refreshing you that are faithful,
who wait upon him in his Light.
This will unite your hearts together in love, to watch one over another,
and to bear one another`'s burdens, and so fulfill the law of Christ your Head,
who hath called you to be members of his body, and one of another:
and as you abide in his life,
it will cause you to remember those that are in bonds among you,
as bound with them--to be sensible of their sufferings, as being yourselves in the body,
and to minister to them in what they have need;
that in this day of trial you may be made as instruments
to come forth and support one another,
that God over all may be honoured and delighted in;
that none of you may draw back or come short of the
everlasting inheritance whereto you are called.

With tender bowels of love salute all those who breathe after God.
His eternal power keep you all; stand in his Light and Life,
that by his pure love your souls may be refreshed and nourished up to eternal life.
All wait in the pure fear, to retain the pure wisdom,
and take heed of forwardness to imitate any thing in your wills to be seen of men,
which is hypocrisy and deceit; but all wait to be led by the spirit,
which will keep your hearts pure and single in the sight of God.

From the Common Jail in Northampton,
where I am a prisoner for the testimony of Jesus Christ.

The 12th day of the Eighth Month 1655.
