== Chapter IV.

[.chapter-synopsis]
* His release from Northampton Jail
* Letter to William Dewsbury
* Account of two meetings in Yorkshire
* Testimonies to John Whitehead`'s qualifications as a gospel minister
* An Address to certain professors

+++[+++After having been confined nearly ten months in Northampton Jail,
John Whitehead and his fellow-prisoners were liberated in the Twelfth Month, 1655,
by an order from Oliver Cromwell.

It appears by the following letter, copied from the [.book-title]#Records of York Quarterly Meeting,#
and dated--Newport-Pagnel, the 24th of the Twelfth Month, 1655,
that John Whitehead resumed his gospel labours about as soon as he was set at liberty.]

[.embedded-content-document.letter]
--

[.letter-heading]
To William Dewsbury

[.salutation]
Dear Brother,

[.offset]
In the pure unchangeable love I do salute thee.

Since I was with thee,
I have had certain meetings in Buckinghamshire--at
Buckingham and Captain Draper`'s house,
which are near together.
A small remnant are there convinced, and come together.
When I was with them at three meetings, the Witness was raised,
and they persuaded to meet in silence.
And having cleared, my conscience to them, I passed to Winslow,
where not any would meet at all, but only one family which is convinced;
yet near that town I had a meeting at a Baptist`'s house:
about twelve of that people came together: some of them were tender,
but the greater part gainsaid the truth.
And from thence I passed to Wingrave,
where a General Meeting was appointed on the First-day before this;
and much people came together, and were all silent before the Truth;
and the meeting being ended, the Baptist people who met at the same town,
sent to challenge me to meet them on the next day,
to discourse of things in difference between them and us; which, for the Truth`'s sake,
I consented unto, that they might not boast against it; and many people,
both Baptists and others, came to hear the dispute, which was carried on with moderation,
and the deepest subtlety that ever I met with, on their part.
Yet out of their snares, in the power of Truth, I was preserved over them,
and it cleared itself to the single eye.

After that I had three meetings amongst Friends about Aylesbury;
and having received thy note, I appointed a meeting at Stratford this day,
where certain Friends met; and after we had been together about four hours,
we parted in peace, and I, with certain stayed Friends,
went to the Baptist meeting near Hartley, and I spoke much to the preacher face to face,
and the Truth stood clear over him: his people did moderately hear,
and on their heads I left it, and parted in peace.

From thence I came to Newport, where I have had a precious meeting this night;
and shall now, if God permit, pass towards those Friends about Aylesbury again,
and have certain meetings amongst them this week, and at Hempstead next First-day.
Then shall I leave them to the Lord, who alone is able to perfect his work in them;
and shall pass toward London,
and onward in the work of the Lord (which I have told thee of) as he leads me;
that so I may be eased of the burden that lies upon me,
continually pressing until I go on in it.
My dearly beloved, cease not to pray for me,
that I may go on in the dread and power of the living God, who is over all,
and causes the heathen to fall before him to his own praise and glory.

[.signed-section-signature]
John Whitehead.

[.postscript]
====

As thou art free, let me hear from thee what way thou movest;
and if Joseph Storr be with thee, salute me to him, and to Sebastian Elthorp, who,
I hear, is come up to thee.
I shall be about Henry Heaves on the next Fifth-day.

Anne Sherwood dearly salutes thee in the Lord.
To Wm. Dewsbury, at Baldock, or elsewhere he is, these.

====

--

+++[+++In the year 1656, John Whitehead held some meetings in Yorkshire.
T+++.+++ Thompson gives the following circumstantial account of two of them:]

[quote]
____
Upon the 25th day of the Third Month, 1656, being the first-day of the week,
he had a meeting at Hunmanby, on the Wolds,
+++[+++an elevated tract of country in the East Eiding], where no Friends had been before;
and there not being a convenient room in the house at which the meeting was appointed,
we assembled in a little close adjoining.
But there came a great number of rude people,
who made much stir and noise and threw stones at Friends in a desperate manner;
so that we could not enjoy our meeting at that place.
Then we withdrew into a barn, where for a little time the people were more quiet,
and the Truth was, through John Whitehead, freely declared.
But it was not long before some rude and wicked persons began to make a disturbance,
and with great fury sought to make their way through the press to John, who stood still,
and with great boldness and power declared the Truth.
Now Friends standing close, both before and on each side of John,
they could not easily come to him; notwithstanding, they pressed earnestly towards him,
violently pulling many Friends out of their way.
And truly the Lord wonderfully chained them at that time;
for when they were even mad with wrath and fury,
and had pulled most of the Friends out of their way,
so that very few were left between John and them,
Robert Barwick and I standing close together right before him,
and a woman or two on each side, no other Friends being left near us;
and the rude rabble furiously striving above an hour before us, in much choler, wrath,
and madness, shaking their fists at us, swearing many terrible oaths,
and desperately threatening us in a cruel manner; yet,
blessed be God! they had not power to lay a hand upon us to hurt us,
nor to pull us from our standing.
So they could not satisfy their wicked minds: forever praised be the Lord God of power,
who chains and limits the strongest and stoutest-hearted of the sons of men,
according to his pleasure.

After they had striven a long time and prevailed nothing,
they suddenly turned their backs, leaving us in our places, and departed from the room.
Then we had a precious time in waiting upon the Lord,
and J. Whitehead was preciously opened in his testimony,
to the comforting and edifying of Friends, who were refreshed in the love of God;
and in our freedom we parted, in the dominion and power of the Lord, who reigns over all.
So Truth reigned that day, and the opposers of it were confounded;
glory over all be to the Lord God of life and power,
who liveth and reigneth forevermore.

On the 4th of the following month, John Whitehead had a meeting at Bainton,
a village on the West Wolds.
No meeting of Friends had been held here before.
To this meeting many strangers came; and John, as moved of the Lord,
declared the Truth in much power and plainness, to the reaching of divers states.
The people heard peaceably and with much attention a good season; till a man,
named Colson, stood up, in a busy mind, to oppose the truth,
and charged John with using vain repetitions.
John asked him, what one vain word he had spoken since he came into that place?
To which Colson answered little, for he could make none appear against him,
but said he repeated things several times over.
Then he was asked a second time if they were vain?
and was called upon to prove his assertion, or own condemnation for his false accusation.
But he could not prove anything of that nature, only saying, as he did before,
that John repeated some things several times over.
Then John, for the opening of things to the understanding of the people, said,
there must be precept upon precept and line upon line, to such people as were rebellious,
etc.

Then Colson asked him whether man had power of himself to turn unto the Lord?
To which John answered, "`It is not in man that walketh to direct his steps.`"
Then Colson charged him with contradicting himself,
because he had before exhorted the people to search and try their hearts,
and turn unto the Lord.
To which John answered to this effect,--"`The same prophet who said unto the people,
'`Search and try your ways, and turn unto the Lord,`' also said,
'`It is not in man that walketh to direct his steps;`' yet did not he contradict himself,
as in the book of Jeremiah, and in his Lamentations,
may be read;`" with some other words for the further clearing of the matter.
So the people were generally well satisfied;
and Colson not being able to gainsay what was spoken, went his way.
After he was gone, we had a precious meeting; the people were well satisfied,
and Friends were comforted in the goodness of the Lord;
praises over all be ascribed to our God, who is God of heaven and earth, blessed forever.
____

+++[+++As a minister of the gospel,
John Whitehead was highly esteemed by his brethren for his work`'s sake;
and it may not be improper to introduce in this place the testimony of some of
them respecting his diligence and qualifications in this character:--]

[.embedded-content-document.testimony]
--

Dear John was indeed wonderfully qualified and richly fitted for the work of the ministry,
into which he was called of the Lord; and he was valiant for the Truth upon the earth,
quitting himself as a man of God, where he was ordered of the Lord;
and his testimony in those days was very reaching and affecting,
both to Friends and others.
While he was young he travelled much and laboured in the work of the Lord;
and many were turned to God through his ministry in divers parts of this kingdom.
And when at any time he returned to his outward being, and had respite from travel,
his manner was, to appoint meetings where there had not been any before,
that so the sound of Truth might go forth to all; and if possible some might be gained,
and brought from the evil of their ways,
and turned to the Lord.--From _T. Thompson`'s Testimony._

In much sincerity of heart, he used to exhort his friends to wait upon the living God,
that in a true waiting place they might feel the
power and presence of the Lord near them.
It was his manner to use great plainness of +++[+++speech,]
and his words reached to the witness of God in many of those
who heard him declare the Word near in the heart,
that they might hear it and obey it.
I, with many more, have cause to praise and magnify the name of the Lord on his behalf;
for his doctrine did distil upon my heart as the small rain
upon the tender herbs.--From _Thomas Matthews`' Testimony._

Oh! his labour and travail amongst Friends,
and also people of the world! that they who knew not the Lord,
might have their understandings opened into those
weighty matters which relate to +++[+++the salvation of]
the soul--that they might be turned from darkness unto light,
and from the power of Satan to the power of God.
This was his work and service nearly forty years--this
was his labour and travail from one year to another,
until his days were at an end.
A worthy servant indeed! an honourable one in the Lord!
His labour and care were very great,
that Friends might be kept to their first love in the Lord God.
He was endued with great power and wisdom,
and could divide the word aright to his hearers:
a heavenly testimony he had for all sorts of people--a word in due season from the Lord:
in his preaching never very large, but short, sound,
and very weighty.--From _John Burton`'s Testimony._

--

+++[+++The following letter,
entitled "`A Reproof from the Lord,`" is addressed "`to certain professors,
whose habitations are in and about Hull and Beverley,
who take delight in approaching to God and to know his ways,
as a people that do righteousness, and yet seek to limit him, and stumble at his Light,
in which the knowledge of his ways are received.`"

It was written the 14th of Tenth Month, 1656.
The occasion of writing it appears to have been a
visit to one of their meetings at Hessle,
near Hull, in the previous Seventh Month; where,
after three of their own ministers had spoken,
he claimed the right of addressing them according to the order of the true Church,
that "`all may speak one by one;`" and if anything be revealed to one that sitteth by,
the first should hold his peace:
but he was interrupted by their "`breaking out into a confused uproar,
many speaking together to stop the declaring of Truth.`"
These professors were in a very disjointed and unsettled state,
not having become subject to the guidance of the Holy Spirit,
but by their own wills and appointments in matters of religion, limiting his operations.
Therefore, as might be expected,
they despised that testimony which John Whitehead had to bear,
to the manifestations of the Light, and its sufficiency for every good word and work;
for truly this doctrine was not such as "`fed that which reached to the tree
of knowledge,`" but taught rather a subjection of the heart to the divine requirings,
and tended to humble the pride and wisdom of the natural man.]

[.embedded-content-document.letter]
--

[.blurb]
=== A Reproof from the Lord

[.salutation]
Friends,

Consider how you are puffed up in your knowledge, and your hearts waxed fat,
and your eyes blinded by the god of this world, and your ears become dull of hearing,
that you cannot savour the things of God nor rejoice in the Truth,
but account Jesus Christ, preached as the Light of the world,
who enlighteneth every man that cometh into the world,--a fancy,
and foolishness or simpleness, to what you have attained;
though few of you know any thing of the "`fellowship of his sufferings,`" or "`the power
of his resurrection,`" or the virtue of his life made manifest in you,
but have only got the report and fame thereof to talk of;
and in your prudence and comprehensions are prescribing
a way and seeking to limit the Holy One in it.

And being lifted up in your knowledge,
you account it a needless thing to lay amongst you
the foundation of repentance from dead works,
though you be even found therein,
as the Light of Christ in all your consciences will witness,
which shows you your secret lust, pride and high-mindedness, covetousness,
love for and conformity to this world; as also your respect of persons,
anger and peevishness, with your false accusing, deriding, foolish laughter,
wantonness and so forth; which dead works,
and your saying that you have not power against them,
are a clearer testimony of your unbelief and disowning of Christ,
than all your profession of faith in him and talking of his excellency in words,
can be for you;
which profession and fair-saying is nothing but hypocrisy
whilst you do not the things which you say;
and the hope you have in the carnal nature is not sure and stedfast,
but must be cut off and perish, and you also except you repent:
and this you shall witness to be truth declared in plainness,
when the workers of iniquity are forced to depart from Christ and are rewarded "`according
to the deeds done in the body,`" and those only who have done the Father`'s will,
enter into the kingdom.
May this be a warning to all that mention the name of the Lord Jesus Christ,
no longer to deceive yourselves with a vain hope that purifies not.

Neither let any deceive you with vain words; but believe in the Light of the Lord Jesus,
and singly wait, that therein you may receive power for obedience to the faith.
And put away the evil of your doings and the abominations that are in your hearts,
which shut out your prayers that they pass not through unto God;
but you ask and receive not, desire to have and have not,
because you ask amiss to consume it on the lust of your own wills,
which are not subjected in the cross.
Although a joy arises in some of your affections at the uttering
forth of words that make mention of the thing you want,
which joy for a time you may feed on; yet anon it withers and fades away,
and you are but where you were before, at a loss in yourselves,
sticking fast in the mire and clay,
and in bondage to the corruption and evil of your hearts.
And not believing in the Light, which opens the blind eye,
you know not where to find the power which should slay the
enmity and crucify the flesh with the affections and lusts,
but are struggling and striving by what you can do to enter,
often pleading your actions before the Lord and filling your mouths
with arguments to persuade him to accept your endeavours and prayers.
These are seen to be exacted labours and a forced work,
performed in the strength of the natural understanding and wisdom,
by which you neither know God nor his mind, but have a zeal not according to knowledge;
(from which arises many deceitful workings,
as crying and the like) in which you call for fire from heaven,
not knowing of what spirit you are.

But the Lord who searcheth all hearts and knoweth your intents,
hath shut out your wisdom from knowing him or his way;
and you cannot come to touch the tree of life by all your climbing, turning and striving;
the flaming sword being set to keep its way, you cannot pass through to feed on it,
whilst you live in that wisdom and nature wherein pride,
strife and every evil work lodge.
Before you have a right to the tree of life, you must become fools,
and cast down your crowns at the feet of Christ,
who lighteth every man that cometh into the world;
and own his witness who hath kindled a burning under your glory,
and testifies of your works that they are evil.
In his Light stand still,
and you will see condemnation upon all your own willing
and running and acting in your strength,
as also upon all your wickedness and self-righteousness,
which are both abomination to God.

A profession of faith, and a talk of Christ and his kingdom to come,
will not serve to cover you that are found therein,
and will not that the Lamb should reign over you in Spirit.
He humbled himself to the cross; his appearance you cannot own nor the glory thereof,
which is not the glory of this world,
nor of the princes of this world which shall come to nought;
but it stands in righteousness, judgment and purity; and he +++[+++who can own it]
receives in this world suffering and reproaches,
whipping and imprisonment in dungeons and holes, and is numbered among transgressors,
buffetted, stoned, spit upon, and accounted a devil, a deceiver, etc.,
even by such as have got the Scriptures to talk of, which testify of Christ.

Yet in all these things the Lamb reigneth and shall reign,
till all rule and all authority be put under Him; though, I say,
his appearance and glory in this world can no more
be owned by such as look for an outward kingdom,
power and dominion, whilst they live in the pride, fashions and lusts of the world,
than it could be by the Jews,
who looked for his appearance in an outward pomp
and for an outward restoration of his kingdom,
and when He appeared, did not know Him, nor the voices of their own prophets,
but fulfilled them in crucifying Him, who was not born by the will of man,
nor appeared according to their expectation and thoughts of Him.
And how like your thoughts and expectations of his appearance are unto theirs,
let his Light in your consciences judge; unto which you may do well to take heed,
until He be manifest, who brings to light that which hath been hid in darkness,
and makes known the counsels of the heart.
Then will you cease from all outward expectations of his coming,
"`lo here`" and "`lo there;`" and know his kingdom to be within,
and feel the sceptre of it, which is righteousness,
smiting at the feet of that glorious image which is set up in your comprehensions,
but must be dashed in pieces by the stone cut out of the mountain without hands,
which is stumbled at, set at nought and rejected by your builders,
who will not acknowledge Him as the Light of the world,
which enlighteneth every man that cometh into the world.

This Light, when preached, you account a low, mean thing and a fancy,
and something that is insufficient for salvation without a further light.
But this I say unto you and testify in the Lord, that you cannot comprehend his height,
who is far above all the powers of darkness, and was from the beginning with God,
by whom all things were made and do consist; whose name is called the Word of God,
who is the Life and Light of men, shining in darkness, though thereby not comprehended;
who was testified in due time, and became flesh and dwelt among men,
and the saints beheld his glory, as of the only begotten Son of God.
And what they heard and saw they witnessed forth; and we know that their witness is true,
who testified of Him that He is "`the true Light that lighteth
every man that cometh into the world;`" and there is not
any besides Him that makes manifest the deeds of darkness,
or can lead out therefrom.

So all that expect or hold out another light than that which lighteth every man,
and deny its sufficiency, are in the fancy,
exalted and puffed up in their own knowledge and wisdom,
with which they cannot understand the Scriptures,
nor experimentally know that the power of the Lord Jesus Christ,
who is the Light of the world, is sufficient to lead out of darkness;
for he who followeth: him shall not abide in darkness, but shall have the Light of Life.
And here the Stone which the builders reject is made the head of the corner,
and is a precious, sure foundation to all them that believe and walk in his Light,
who are witnesses of the virtue of his blood (which
by vain talkers is made a cloak for sin),
washing and cleansing from all sins.

And of His fulness, who is able to save to the uttermost,
have we received power to become the sons of God
in that obedience and righteousness which is perfect,
where all that are found are justified.
This righteousness is revealed from faith to faith in all them that believe in the Light,
which manifests and condemns sin in the flesh;
by which Light all you that stumble at it are seen
to come short of the righteousness of God,
and are shut out of the covenant of grace and light,
wherein salvation and the power against sin is placed.

Yet you are left without excuse, because Light is come into the world,
lighting every man,
in which Light the grace of God that bringeth salvation hath appeared unto all men;
and there is your condemnation who abide in darkness,
that Light is come and grace has appeared, in which power against sin is freely tendered,
and yet darkness is rather loved and lived in, because your deeds are evil.
The free grace of God is turned into wantonness by all you
that live in ungodliness and follow after worldly lusts,
which the saints are taught to deny.
And you are the murmurers, complainers, and slothful servants,
who would foolishly charge the fault upon God, as though he did not draw to Christ,
nor give power against sin; whenas he has freely given him to the people for a witness,
in whom all power and fulness dwell;
and by his Spirit he hath striven with you ever since you began
to yield the members of your bodies servants to unrighteousness;
for which you have often been checked in secret,
and felt the Spirit moving you to purity contrary to your wills.
But how often ye have resisted the Holy Spirit, and quenched his motions,
let the Light in your consciences judge.

Ye stiff-necked and uncircumcised in hearts and ears! how will you be
able to stand when the Lord shall visit upon you the evil of your doings,
who have a form of godliness, but deny the power which overcomes sin?
How deeply are you fallen into the enemy`'s snare, who own his power to keep you in sin,
and cannot see nor own the Spirit and power of God that would lead you out from it,
though it be a reprover of you!
My very soul laments your captivity.
How is the whole head become sick, and the whole heart faint!
How are you scattered in your imaginations,
and driven from mountains to hills which are dry and barren!
How are your glory and beauty withered, and your wise men gone backward,
and their knowledge become foolishness, and their language confounded!
How do you reel to and fro and stagger like a drunken man!
How are you groping in the dark to find Him whom your souls long after!
How do your eyes fail, whilst your expectations are outward,
looking for glorious days and a power to come, but when you know not,
but as you imagine and conceive from the promises written in Scripture!
Which imaginations and conceivings blind the eye (which should apply the promises
to the right object) and lead the mind outward into groundless hopes,
Which are mixed with doubts and uncertainties.
Whilst you follow such blind guides as your own imaginations and conceivings,
which arise from the earthly wisdom which knows not the things of God,
you often fall into the ditch, and are defiled with the pollutions of the world;
and thus compassing yourselves about with the sparks you have kindled,
you are forced to lie down in sorrow.

And now a word to all amongst you who sit weeping by the rivers of Babylon,
and have honest desires after God and his righteousness.--Over you my bowels yearn,
that you may not any longer be tossed about by the sleights of men,
nor feed on airy notions, which give you not the least power against sin,
but draw your minds outward, to look at Christ at a distance from you,
and his appearance in power to come hereafter, though he be near to every one of you,
reproving in the gate or door of your hearts;
even as saith the righteousness which is of faith,
"`The Word is nigh you in your hearts and in your mouths,
that is the Word of faith which we preach.`"
This is the same Word which was from the beginning, preached by the Apostles,
and witnessed to be living and abiding forever, ingrafted and able to save the soul;
and this is it which discerns the thoughts and intents of your hearts,
and bears witness against every vain thought, idle word and froward, ungodly way,
which your own wills, which are bound to vanity, choose.

Therefore, cease from your own wisdom, labours and self-works, which are all wicked;
and stand still in the Light of that ingrafted Word,
(of which the Scriptures testify,) which is able to save your souls.
So may your blind eyes be opened, and you brought into a true sense of your conditions,
to see how you have walked in unpleasant places;
and that notwithstanding all your knowledge and profession,
all is not right in the inward, but corruption still lodgeth in the heart,
as a partition-wall, separating you from God;
and that you have no understanding nor ability to do good of yourselves,
but forever might have perished in this state, if God, in his everlasting love,
had not given his Son a Light into the world, to manifest and lead out of this darkness.
So, in the Light, which shows you sin and inability in self to come out of it, wait,
and you will feel in yourselves the sentence of death
and condemnation upon the first man,
which is of the earth, earthly; and by the operation of God`'s power,
which is manifest in the Light,
you will feel desires begotten and moving in your souls after righteousness.
This motion is the Father`'s drawing in his love that you may not perish,
but come unto Christ, who is the Light and Life; and this is the will of God,
who begets in you by the Word of Truth both to will
and to do according to his good pleasure.

Therefore, beware of continuing in stiff-neckedness,
lest you be found fighters against God and resisters of his will,
as they are who perish in sin; but whilst it is called today, hear "`Him,
who speaketh from Heaven,`" whose voice shakes the heavens and the earth,
who is the good Shepherd and calls unto you that have gone astray.
Therefore, harden not your hearts, but wait in spirit to hear and know his voice,
who testifies against all sin,
and calls you to come after Him out of the conformity and love of this world:
for whosoever will be his disciple, must sell all, deny himself,
and take up his cross daily, and in obedience follow Him.
This is that which you yet want; and +++[+++your want of it]
makes the difference between you and us,
and is the ground of the enmity`'s standing and sin prevailing over you.
Therefore let him who amongst you is weary and heavy laden therewith,
and would be Christ`'s disciple, consult not with flesh and blood,
nor give way to that nature which stumbles at the cross and seeks
to save its own life in the delights and pleasures of the flesh,
and to keep in the union, love and impure friendship of the world,
which is "`enmity against God;`" and whosoever will be its friend, is God`'s enemy.
Profess what you will, who love the world, the love of the Father is not in you.
Therefore, do not love it, nor the things that are in it,
neither fear any outward losses or sufferings that you shall
meet with in your separation from your former companions,
nor the frowns nor oppositions of men;
for if you count any thing too dear to part with that you may win Christ,
you are not worthy of him.

Let self, in which the inability to do good lodgeth, be wholly denied by you,
and take up the daily cross to your wills and lusts, that war against your souls;
which cross crucifies to the world and is the power of God in all that are saved.
And taking it up and enduring it,
you will come to witness the flesh crucified with its affections and lusts,
and the partition-wall broken down,
and that which lets taken out of the way by the Lamb of God,
in whom dwelleth the fulness both of wisdom and power.
These together with Himself are freely given to all that ask not amiss,
but wait in spirit to know Him revealed, and his life through death made manifest,
which opens the mystery that hath been hid from ages,
which is "`Christ in you the hope of glory,`" who
is greater than he that is in the world,
and gives victory and dominion over it, as it was in the beginning.

And this salvation is witnessed and freely tendered unto you, in the Light,
Life and Power;
in which waiting to learn of him who is "`meek and lowly of heart,`" you
will come to see that his holy arm is not shortened that it cannot save,
but stretched out to take you by the hand and lead you by a way you have not known;
in which you will come to see the wonders of the Lord, and the works of his hands;
+++[+++you will be]
brought forth out of bondage to corruption,
and will then possess the life of that which you now possess in words.

Now, being warned, take heed of hardening your hearts against the Lord,
by continuing in sin and resting in the outward knowledge
of these things from what you have read in the Scriptures;
for that is not as you ought to know them.
If you do so, your visitation will pass over,
and the Spirit of the Lord will cease striving,
by which he would sanctify and gather you into his fold.
Then will the things belonging to your peace be hid from your eyes,
and you shall desire to see one of the days of the Son of man and shall not see it;
and though you be not gathered, yet shall He be glorious;
and the Gentiles will hear his salvation, and many shall come from the east, west,
north and south, and sit down together in the kingdom of God, and you who will not hear,
shall be shut out.
So, he that hath an ear let him hear and come forth, for the time is now at hand;
and I shall be clear of your blood at that day,
who in love to your souls have sent you a warning,
commending it to your consciences in the sight of God,
where I look to be made manifest when the book is opened; and till then,
I am willing to bear your reproaches,
and to be accounted your enemy for declaring the Truth.

--
