== Chapter V.

Imprisoned at Boston--Abused at York--Imprisoned at Aylesbury--Letter
to Friends--Salutation to the Lord`'s people--A small Treatise,
(containing some account of his own experience, the character and calling of Friends,
etc.)--Address to the Judges and Justices at Aylesbury Assizes.

+++[+++In the year 1658,
John Whitehead was imprisoned by the mayor of Boston
for offering some christian exhortation to the people,
when assembled in their place of worship in that town.
No account has been found of the length of this imprisonment.
It appears, however, that his sufferings for conscience sake, were about this time,
if not of long duration, yet of frequent occurrence.
We find him in the following year, sharing therein with his friends in Yorkshire:
at a meeting in York, he and some others were much abused,
being sorely beaten and having their clothes torn.
On the First-day following, musketeers were set to keep them out of their meetinghouse,
who failed not to use great violence in executing their commission.

The following short extract, from The Christian Progress of George Whitehead,
under date of 1659, shows that John Whitehead was, in the course of that year,
engaged in promoting the cause of Truth in Cambridgeshire, etc.:--]

One James Bedford, priest of Bluntsham and Erith, in Huntingdonshire,
having made a great noise, boasting and clamour, against the people called Quakers,
to render them ridiculous and odious,
some of our friends had some public disputes or discourses with him,
in order to abate his clamour,
yet he persisted in his reviling and ostentation against us,
as if he could refute and run down the Quakers.
At a dispute which our dear friend John Whitehead had with the
said priest in the steeple-house at Haddenham in the Isle of Ely,
where I was present, (but did not much interpose,
the appointment being between the priest and John,)
I observed the priest to be a mere empty,
confident boaster and reviler, and made but poor work of it.

+++[+++In the Eleventh Month, 1660, John Whitehead was, with seven others,
committed to Aylesbury Jail for refusing to take the oath of allegiance;
three officious justices having come to a place where they were assembled,
for the purpose of thus making a prey of them.
It would seem by the date of the last of the three next following documents,
written during this imprisonment, that he was confined this time at least three months.]

John Whitehead to Friends

Dear Friends,

Both sons and daughters, amongst whom I have travailed,
that you might be gathered into the everlasting covenant of light and life,
to feed by the Shepherd`'s tents, among the sheep and lambs of his fold.
When I consider, that by departing from iniquity,
ye are become a prey to all the beasts of the field,
who gather themselves together to rend and devour
you;--how do my bowels yearn towards you,
and my heart doth melt into tenderness with the love
and life that is shed abroad in it unto you:
in which life my soul is often poured out in silence before the Lord,
(who knows how to deliver his little ones who have put their trust
in him,) that you may be kept together in one mind and spirit,
and have your hearts established with grace upon Him,
who is the only begotten of the Father.
Hold fast your confidence in the word of his patience,
and in the living hope stand fast and immoveable upon the spiritual Rock,
that you may not be shaken: for now the storms, tempests, and floods are come,
that the hearer may be known from the doer, and the false from the wise builders.
Therefore, let not the upright in heart be troubled, though some shake and fall,
and are by the floods swept away; but rather rejoice,
in that they which are approved shall be made manifest,
and their righteousness which God hath given them,
shine forth as the stars of the morning: yea, blessed shall they be that overcome;
for they shall be as pillars in God`'s house,
which he is building and will finish of tried and lively stones,
that he may dwell in it forever.

Be not discouraged at the raging of the sea,
neither dismayed at the tumult of the people:
for the Lord your God is with you to deliver you, whether in life or death.
O! then, stand wholly given up unto his will;
and wait upon him for strength and patience to lay down your own lives,
if nothing but that or the transgression of the law
of your God may satisfy them that persecute you;
for better is it to fall into the hands of men for transgressing their law,
than to fall into the hands of God for wilful transgression of his law,
For you know man can only kill the body and no more; but God,
after he hath killed the body, hath power to cast into hell.
These things I write to remind you of God`'s power: that you may both trust, fear,
and love him, whose glory is arising upon you, and shall more abundantly appear in you,
whose minds are stayed upon him, who in mercy hath called you,
and chosen you to follow the Lamb, who shall have the victory.

Therefore, fear not to go through any suffering for his name`'s sake;
because he hath the words of eternal life;
by him your souls may be everlastingly satisfied and refreshed.
And what if God suffer your bodies to be broken,
and turned to the ground whence they were taken,--that shall not
prevent us from partaking of the glory that shall be revealed.
And let not any look out with the wrong eye,
to search when shall be the end of these things;
for a thousand years with the Lord are but as one day, and his long-suffering is great.
Let all whose minds are turned towards God keep out
of the reasoning which draws back into self-safety;
lest thereby the nobility of your minds be clouded, and the plants choked,
whose growth is but little in the Truth: but stand in God`'s fear,
and mind his witness in your consciences, and join not to anything against that,
and it will preserve you, though your strength be small.

And, dear brethren, whose portion is larger, remember that more is required of you,
and according to your ability improve your talent
in strengthening the weak and considering the feeble-minded;
and though you cannot give the oil of your lamps unto the foolish,
having need for it all yourselves;
yet tell them in time where they may buy it without money or price,
that they may be prepared to meet the bridegroom, whose day is at hand.
And if there be any among you who do not wickedly depart from God, but,
through weakness or violent temptation, are ensnared by the enemy,
then you whom God doth preserve and strengthen,
reach forth your hands to help out of the jaws of the devourer:
then shall the soul that is saved from death bless you,
and the Lord will requite you in the day of your need.

And see that you be inwardly armed;--for he that goes to war against principalities,
powers, and the rulers of the darkness of this world, in another armour,
which he hath not proved to be spiritual,
nor hath inwardly received it from God in the light, he shall not overcome.
Now all lies at stake; and whosoever doth fly before the victory be obtained,
loseth what he hath wrought, and makes himself a scorn to fools.
Therefore, let neither death, banishment, peril, sword, hunger, or nakedness,
neither any other thing, whether present or to come, cause you to fly from the Truth;
but in all conditions cleave unto it, and it shall preserve you.

And ye that have of this world`'s goods,
let the bowels of your compassion be open to your poor brethren;
and order that which God hath made you stewards of in his wisdom,
for their and your own relief, before it become a prey to the spoilers:
and let tender love and mercy, as you have received it from the Lord,
abound in you one to another.
Live in the one Spirit of the Lord, that in it you may have unity and peace with God,
and one with another: and bear one another`'s burdens, and suffer one for another,
as Christ suffered for the body`'s sake, leaving to us an example;
which God hath counted me worthy to follow, who am, amongst many brethren,
a sufferer for the testimony of his Truth.
Let not your hearts be troubled, but rather encouraged by my bonds,
in which I have peace with God; and though I should see your faces no more,
I am joined with you in a perpetual covenant, and the remembrance of you is sweet to me.
My love saluteth you every one with true inward breathings;
that under the shadow of the Almighty ye may be preserved,
and by his right hand upheld until the tempest be over:--that thou,
O Zion! in thy beauty may arise; and the Lord, thy light and glory,
be in the midst of thee,
as the sun from under a thick cloud;--that men may see Him whom they have pierced,
and the desire of nations be towards Him;
and the people that dwell therein may walk with us in the light
of the Lord;--that blessing and peace may fill the whole earth,
and nation not lift up sword against nation, neither learn war or persecution any more.
Amen, Amen!

And you that be at liberty in the outward,
give up yourselves to serve the Lord in the morning of life;
and visit your brethren that be in bonds for the Lord`'s sake;
so will the Lord take it as done to himself,
and give you a reward in the resurrection of the just.
And keep your meetings as you see most expedient, in the light of the Lord,
and in his fear, out of the fear of man; and be fervent in waiting upon God,
that a double portion of his Spirit and power may be upon both sons and daughters,
old men and babes;--in whose mouths,
O Lord God Almighty! ordain them strength to bring to nought the wisdom of the wise,
and to drive backward the counsel of the ungodly;
that the fold of thy lambs may be preserved entire:
and let thy life and virtue be unto them a fresh pasture, and open thyself amongst them,
O thou fountain of living waters!--that the thirsty amongst thy people may be satisfied;
and fill their hearts with thy love,
that therewith they may love their enemies;--that thy witness may arise in them,
and clear the innocency of thy own people:--for we have fled unto thee for refuge,
and can use no other weapon to plead our cause but the words of thy mouth.

John Whitehead.

Written in the prison house in Aylesbury, the Second of Twelfth Month, 1660.

This to go amongst Friends, to be read when they are met together in the fear of God,
with understanding; and likewise to be sent to the prisons,
to be read amongst Friends who suffer for Truth`'s, sake.
Fail not to communicate it one to another.

A Salutation to the Lord`'s People, To be Read in their Meetings and Prisons,
for their Further Refreshing and Building up in That which is Holy.

Dear Brethren,

In the Seed immortal and incorruptible, in the dearest life and love of God,
I salute the whole flock of God everywhere, with whom I am united in the life of Christ;
who, after he had suffered for us, rose by the power of God,
and is ascended far above all principalities and powers, that he might fill all things;
as we know, who can witness that his presence hath been with us in the day of our trials,
to deliver us and to give us strength to bear what man can do unto us.
Oh! the riches of his glory and the depth of his
counsel are immeasurable and beyond all expression!
For he toucheth the mountains, and they smoke, and moveth the hills with his hand;
at the turning of his countenance the foundations of the earth shake,
and are out of course.
He walketh upon the sea; his hand moveth in the deep,
and causeth the waters thereof to dash one against another:
he hath caused his light to shine out of obscurity,
and hath put his fear into our hearts, that we may understand his goings.
He hath shed abroad his love to draw us after him,
and covereth us with the shadow of his wings, that our hearts may perfectly trust in him.
He hath opened the Fountain of Life, that the poor of the flock may drink,
and the feeble knees be made strong.
He defends us from the fiery darts of the devil,
and turns the wickedness of the wicked back upon them.
If he withdraw his hand we faint; but for his mercy`'s sake,
he will lift up the head of his anointed on the wings of the morning.
He hasteth to plead the cause of the afflicted and
to confound those that Would harm his prophets.
But the wicked have shut their eyes and see not his goings;
that their hearts may be hardened against the day of recompense.
But let us wait upon him, and give glory to his name in the midst of the fire,
for his mercy endureth forever.
Oh, that men would fear him, that they may feel that his mercy endureth forever!
Because we know him, let us rely upon him, for vain is the help of man.
He taketh the wise in their own craftiness;
and they that lie in wait for blood shall fall in their own snares.

Therefore, O Zion, who in the Light knowest thy Maker, thy Husband,
when it is night lie between his breasts, and in the day walk with him,
that the daughters may know that thou dependest upon him,
and see that he is the staff of thy hand: so shall his secrets remain with thee,
and his blessing in thy heritage.
Let thy children hang upon thy breasts and not let go thy skirts,
but endure the chastisement of a father,
that they all may live and be nourished with good;
for the pit and a snare are in the way of them that leave thee,
and darkness shall cover them.
Thou shalt not go after other lovers,
for the Lord hath betrothed thee to himself in righteousness;
so shall strength and honour be thy clothing;
thou being beloved of One and truly loving One; live in that only One,
who is the beginning and end, the eternal Father in the Son, with the Spirit,
delighting in the midst of thee, to whom belong the kingdom, glory, honour, and worship,
majesty and dominion over all forever.

O, Thou infinite, incomprehensible Being! let the Spirit, the water, and the blood,
which thou hast appointed to bear witness on earth, plentifully be poured forth,
that the nations may be sprinkled from an evil conscience,
and they who have mourned by the rivers of Babylon may drink of the waters of life;
and by thy Spirit lead the people from far unto thy Holy Hill,
that therein they may retain the adoption of children:
and cause the sons of men to dwell together in thy love,
who art the God of the spirits of all flesh.

Written in Aylesbury Prison, by

John Whitehead.

The Eighth day of the Second Month, 1661.

A Small Treatise,

Wherein is briefly declared some of those things which I have heard, and seen,
and learned of the Father.
With a Testimony against such as do or shall invent forms of doctrine or worship,
and by outward force compel people thereto.
Here is also the calling and work of that ministry
which is owned by the people of God called Quakers,
in short spoken of: and a true character given of their temper of spirit, manner of life,
and worship: wherein is briefly hinted, what God hath done, and will do for them.

Written for the satisfaction of such as desire to know them,
and the things that are most surely believed amongst them;
and for a testimony against such as have erred, or shall err, from the spirit and life,
wherein God doth seek people to worship him.

After God, in the riches of his goodness and patience, days without number,
had borne the injustice, oppression, pride, persecution, deceit, hypocrisy,
and other grievous abominations, wrought by the rulers and people of England,
he suffered the sword to go through it, by which much blood was shed:
and with a great shaking he overturned foundations,
at his rebuke they were out of course, and man`'s building laid waste,
that people could find no shelter.
For the mountains were removed out of their place,
and the little hills lifted up themselves, but were not fixed,
the green trees also became dry and withered,
so that many were ashamed of the oaks they had desired,
and wandered from mountain to hill, and walked amongst the groves of man`'s planting,
seeking a resting place, but could neither find pasture for their souls,
nor water answerable to their thirst,
nor the shadow of the Rock wherein to rest safely and be satisfied.

Then did God remember the desolate estate of his people,
and pitied the wanderings of his flock,
who were become a prey to the devourer and often taken in his snares,
because none sought after them; for the former bishops, overseers,
and teachers left them, partly because their great revenues and hire were taken away,
and partly because they were discountenanced by great men.
And many of those pastors who arose in their stead
became brutish and sought not the Lord,
neither looked after his flock, that they might bring again that which was driven away,
bind up that which was bruised, and strengthen that which was diseased;
but like briars and thorns they tore the wool from off them,
and like grievous wolves they devoured them;
and instead of carrying the lambs in their arms,
and gently leading those that were travailing with young,
they sought how with force and cruelty they might rule over them;
for which the Lord was against them, and brought night upon them,
that their vision ceased; and in darkness he left them until the day of recompense.

After these things, God, who had compassion on his people,
caused the Branch again to spring forth of the root of David, who was filled with virtue;
for the covenant of life and peace was in Him,
and He spread and shot forth many branches, which partook of the fatness of the Root;
and the weary came to rest under his branches;
in Him also was the word of reconciliation,
which turned the hearts of the fathers to the children,
and the disobedient to the wisdom of the just.

And in the year 1652, I being a branch of this Tree,
the life of its root caused me to blossom and bring forth fruit;
for the Spirit of the Lord came upon me,
and by it I was anointed for the work of the ministry,
and sent to divers places to preach repentance,
and testify that the kingdom of God was at hand.
And the power of the Highest was with me, leading me forth, and bringing me in,
and delivering me from the workings of Satan, who, as the mystery of godliness opened,
did subtlely lie in wait to deceive.
But the Anointing which I had received,
taught me to stand still in the hour of temptation;
and waiting upon God in the Spirit of Truth, I have received counsel,
and obtained help of him by which I have been delivered out of temptation unto this day.
And through the Spirit I grew in unity and favour with God, and his secrets were with me.
For the Spirit, as a key, opened his treasure,
and showed me that which was from the beginning,
and gave me to know and feel something which was before the world was;
and also to discern the state of man before the fall, when his soul was living in,
and nourished with the breath of life, which proceeded from God;
and in the fall how the Lamb was slain,
and how death came to have dominion over man who was made in God`'s image,
by the transgression of one who, hearkening to the woman, tempted by the serpent,
received his seed, and departed from the Life of God which did enlighten him,
to feed on that which was forbidden by him.
Thus into the root of evil he did degenerate,
and from that brought forth fruit unto death,
which passed over him and covered him with darkness;
so the wrath laid hold of him as its child.

I also beheld how the bowels of the God of mercy yearned towards the languishing
man upon whom death and darkness had passed and wrath come,
and how God drew near to him in the Light of Life, and did sow the Seed of promise,
and hid his kingdom within, and gave the Word for a Light to men,
that the degenerate might become regenerate, and the dead made alive.
I also saw in the Word of promise, power to bruise the serpent`'s head,
destroy his works, and save the soul from death, whereof he had power.
I also saw that in the Word was Life,
and that he hath power to quicken every one who cometh to him.

And I also beheld, that as judgment came upon all men to condemnation,
so the gift of God was tendered to all for the justification of life;
and that thereby man was put into a capacity for receiving it.
And here I understood the good will of God towards men,
and saw that as all were concluded under sin, even so he showed mercy to all;
in that the free gift of God, which is Eternal Life, came upon all.
And I saw that, by the Eternal Life, every man who comes into the world was lighted,
and warned to shun the evil ways of death to which
he is inclined by the corruption of nature.
And here I felt how God loved man first,
and called him who had departed from him back again;
by which love all are put into a capacity to return, though few have regarded,
so as to return and live.
So I beheld that God was the Author of eternal salvation,
and that man`'s salvation was wholly of God through Christ the Life and Light;
and that man`'s destruction was and is wholly of himself,
because he believeth not in the Light which God hath sent into the world;
but loveth darkness, death, and to follow him that hath the power of it,
which is the devil, rather than to follow the Light that lighteth the Gentiles.
This Light mine eye hath seen to be the salvation which
God hath prepared for all people to the ends of the earth,
and the ground and means of man`'s believing and returning to God;
and that no man could come to the Father but through the Light,
that being the only begotten Son of the Father,
and the firstborn of every creature before the world was,
in which Light the Father dwells and delights, and by him he declares himself to man.
I also beheld how the Light abideth forever, and is the Beginning and End of all things;
also the Foundation that is laid in Zion, and chief Corner-stone of the building;
and how he was, and is the Rock of ages, who followed the fathers in the wilderness,
and to whom all the shadows under the law pointed--the Foundation of many generations,
which the prophets said should be raised up, and whereupon the church was built.

I saw also how in his humiliation he was in fashion as a man, born of a virgin,
and touched with a feeling of our infirmities, yet without spot of sin,
perfect in holiness, having the Spirit without measure,
and the fulness of the Godhead in him; yet was he a man of sorrows, rejected of men,
judged a blasphemer and not worthy to live,
by the chief priests and pharisees who had the Scriptures; and Pilate,
who had natural learning--Hebrew, Greek, and Latin,--delivered him to be crucified.
And after he had witnessed a good confession before him, he tasted death for every man,
of which it was impossible for him to be held: therefore he rose by the power of God,
and in divers manners appeared to his disciples.
After which,
he that descended did ascend far above all heavens into the glory of the Father,
with whom he is glorified, as he was before the world began;
having that name which is before every name, which he had in the beginning,
which is the Word of God, the Eternal Life that was with the Father,
who doth enlighten men; that through him, who is the Way, Truth, and Life,
man may be reconciled and have access unto God, who only hath immortality,
dwelling in the Light to which no mortal eye can approach,
and without which no man hath seen or shall see God.
Therefore, O man! whose soul is immortal, wait to have its eye opened in the Light,
that thou mayst see God and walk with him in the garden, as in the beginning,
before the fall and separation was, or ever the evil eye was open,
or the immortal eye overshadowed by death.

Moreover, the inspiration of the Almighty gave me understanding,
and thereby is mine eye open to see the things I write; with which I have also beheld,
how all immortal creatures, as well angels as men, are the offspring of an eternal Root,
created in, and brought forth by the eternal Almightiness for his glory,
and man in his image.
Therefore in the beginning man`'s will and inward desires were free,
and not compellable to or from any thing;
till hearkening to the temptation of the serpent he lost his habitation in the Light,
and is entered into the darkness, and thereby captivated;
and has lost his freedom and changed his glory into shame, and the truth into a lie,
which he speaks and believes instead of the truth.
Having erred from the Light, he is out of the divine way and harmony,
shut up in darkness and anguish,
where only they have their power and the root of their life
who are degenerate from the pure principle of Light.
All who are gone out from it do live in the fall, error and enmity against it,
and naturally do seek to draw all that they can penetrate or enter,
from the Light into the same condemnation.
And in this state or ground I have seen that all men who
have gone from the Light have corrupted their way,
and are together become unprofitable.
And also that those called Christians are apostate who have not only erred from,
but are in enmity against the Light and Life,
which the Apostles showed and turned the Gentiles (who became true Christians) unto;
though they profess and build men up in an outward knowledge of their words.
I know and have seen them all to be foolish builders--such
as darken counsel by words without knowledge,
who reject the Life that lighteth every man that cometh into the world, as natural,
and insufficient for a foundation.
And also that their building is Babel, which shall fall with violence and great noise;
for it stands but upon that which is moveable, changeable,
and shall melt like wax in the fervent heat of the day.

But when the Sun of righteousness was risen upon me,
and the power of the Father revealed in me, by which I saw God`'s love to mankind,
and the way of his redemption,
and also beheld many other things which are not to be uttered,
then bowels of pity yearned in me towards the children
of men who are gone out of the way,
perishing for want of the true knowledge of the only Lord and Saviour Jesus Christ,
whose life enlightens the world.
And the Lord God who shewed these things unto me, (with many others,
whom he anointed by the pouring forth of his Spirit for the same work,) caused
us to run to and fro amongst the professors of the Christian`'s words,
to show them their error from the Spirit and Life,
and how their worship stood in their own wills; and that their works were dead works,
found out by invention, and not led into by the Spirit of Life,
and therefore not accepted of the living and only true God,
whose presence hath accompanied us in our travels,
and his power and Spirit wrought mightily with us,
to seek a people to worship him in spirit, and bring again that which was lost.

And by the Spirit of the Lord we have not been so much directed
to show unto people that which was written by the former prophets,
evangelists and apostles, for a foundation of faith,
(that being generally outwardly known and believed where we have travelled,)
but rather to show unto people the Eternal Life whereof they wrote,
(which we have seen, felt and handled as they did;) that doth enlighten all men,
to which we have principally laboured to turn people, that they might be quickened,
and led from Satan`'s power to God,
and receive remission of sins through the precious blood of Christ,
by which they that believe and walk in the Light are cleansed from all sin,
and justified in the sight of God.

Christ who is the Eternal Life and Light is the foundation to which
we have borne witness and in whose name we have gathered people,
who is the Word that lives and abides forever;
that being thereby quickened and prepared as lively stones,
they may be built a spiritual house or church for God to dwell and walk in;
and have approved ourselves as the ministers of Christ "`in much patience,
in afflictions, in necessities, in distresses, in stripes, in imprisonments, in tumults,
in labours, in watchings, in fastings, in pureness, in kindness, in the Holy Ghost,
in knowledge, in long-suffering and love unfeigned.`"

And we have laboured to preserve and present those that have believed our report,
and gathered together in the Light, pure and spotless unto God;
and he hath given witness to us in the consciences of people,
by pouring forth of his Spirit, and giving increase of life, strength, and virtue,
with many other spiritual blessings, as to eat of the hidden manna,
and sit together in heavenly places in the Light.
I say this hath he done,
and given to those whom in his power we have gathered out of the temples,
worships and nature of the world, to know the Eternal God their Father,
and worship him in Spirit and Truth,
and not to move or act but as the Spirit of Truth moves and leads them,
in which God doth accept them and receive them as his children.
+++[+++Yet]
he chasteneth them in his tender mercy, and tries in the furnace of affliction,
hiding their life in himself,
that through great tribulation and persecution he may cause
the Spirit of grace and glory to rest upon them,
in which they shall grow unto a holy temple, and be a glorious church,
in which he will make his abode forever.

Nevertheless it is signified unto me by the Spirit,
that some who have obtained part of this ministry,
and such as for corrupt ends shall transform themselves
as ministers of righteousness and children of Light,
may and shall err from the Spirit and Life,
whereinto the ministers are transformed by the Lord, that they which are approved,
(being tried by false spirits, covered with the form of true doctrine,) may be manifest,
that they know the Shepherd`'s voice, and love to follow him and not a stranger.
For I do certainly know that such as depart from the Light,
and are strangers to the Life, will get and treasure up the words,
and thereby through worldly wisdom lie in wait to deceive,
and draw from the innocency of the Gospel (which is the power of God,
a cross to the motions of the flesh,
and a chain to the unclean spirit) into fleshly liberty and admiration of their persons,
because of outward knowledge, parts and gifts,
in which they will seek to be exalted above the true Seed,
though thereby they cannot reach the things that are eternal;
and such serve not the Lord Jesus Christ, but themselves.
The Light having shined in their understanding,
and the glance thereof leaving some impression of heavenly things in their imaginations,
they may form likenesses of those things; but not knowing the heavenly nature and virtue,
they will be prejudiced and envy such as cannot have
unity with that which they bring forth,
nor bow to their likeness; and from that ground, bitterness and persecution grow.

Therefore let this be a witness, now and in ages to come, against such as murmur at,
hate and persecute those that cannot in conscience
join to their form of doctrine and worship,
though they should make it as like our doctrine and practice as they can possibly invent.
Nay, though it should be the very same in outward appearance
and in every circumstance provable by the Scriptures,
and the words which we have left upon record,
yet if men take upon them to preach such doctrine,
and imitate such practices by virtue of any outward ordination,
or approbation of people who have itching ears,
without a true leading of the Spirit of God;
though pretending to the anointing and leading thereof, shall do it for a name,
honour or lucre`'s sake; and shall persuade, advise,
or give consent that outward authority, or the civil magistrate,
shall compel men to a conformity thereunto, or else in person or estate, or otherwise,
shall outwardly punish such as refuse to conform, though upon never so false grounds;
or shall compel any man from that way of worship
which in his own mind he is persuaded is right,
or shall defend his own way of worship by carnal weapons;
behold I (who am a child of the virgin--the true church--that is espoused to the Lamb,
brought forth in the return from her captivity,
and have the mind of Christ herein) do testify in his name and by his spirit,
that such are adulterate children, not begotten of God, nor born of his royal Seed,
nor owned by Jerusalem which is free, and is the mother of us all.
Though they be outwardly decked never so like her children, yet they differ in nature,
spirit and mind, from the true children of Zion, as much as light doth from darkness,
bitter from sweet, hatred from love, pity from cruelty, or life from death;
having but at most the form, and wanting the power of godliness:
which power doth ever accompany those that God calls into his work, for the conversion,
preservation, and edification of all them that believe.
To him alone it belongs to revenge every contempt
and disobedience against his glorious Gospel,
as also to fit, send forth, vindicate, preserve, and provide for the ministers of it.

Therefore let men pray to the Lord of the harvest to send forth labourers into his harvest;
and let none run but such as know that the Lord God in the spirit calls and sends them.
And let all people take heed, lest they heap to themselves teachers,
after their own lusts to satisfy itching ears; and beware of despising God`'s messengers,
who are sent contrary to the will of man;
or of harming his prophets who prophesy right things,
lest it be to their own wounding and rain.

And that the temper of spirit, manner of life and worship,
that the people called Quakers are of, live in and practice, may appear, I,
having had a certain knowledge thereof from the day that God showed himself unto me,
for a testimony against false Christians, and such as shall hereafter live ungodly,
write this declaration:--

First,
generally they are a people that have been of a sorrowful
spirit and acquainted with grief;
having had a true sense of their lost estate and separation from God because of sin;
they have mourned after him and waited for a Deliverer;
they Have also been in heaviness because of the abominations of the times;
and passing through the fiery indignation of God because of their own transgressions,
trembling hath taken hold of their flesh, and made their bones to shake.
In the furnace of affliction, where judgment and mercy meet,
they are melted into tenderness;
and bowels of pity are opened in them towards all creatures, but especially mankind;
whose depraved estate they lament.
Against the evil that hath corrupted, they are zealous; in testifying against it plain;
and in reproving for it, sometimes sharp, yet with inward mercy,
in which they are moved earnestly to pray that men
may be set free from the bondage of corruption,
and restored to their primitive purity.
In spirit they are fervent, in mind stayed and fixed;
in their purpose to cleave unto the Lord, resolute; in sufferings for his name`'s sake,
joyful and patient; in trials, constant;
in the visitations of the Father`'s love and openings of his Life they fear,
and their hearts bow before him.
In discourse they are solid, in gesture grave; in speaking in the name of the Lord,
reverent; and knowing that faith is the gift of God, they cannot envy,
but do rather pity those that do not believe and obey the Truth,
though before them Christ Jesus hath been evidently set forth.
And being assured that "`it is not in man that walketh to direct
his steps,`" they have compassion on them that are out of the way,
and in love do labour both with long-suffering and doctrine, to instruct men in it,
though they oppose themselves.
And being sensible that none can be purged from their sin and sanctified,
but by the blood of Jesus through the Spirit,
they cannot seek the destruction of sinners, though they be obstinate,
but rather that they may have time and space to repent and turn to the Lord.

Being leavened throughout with love and mercy,
it is against their very nature to revenge themselves, or use carnal weapons to kill,
hurt, or destroy mankind.
And seeing that the powers that be are ordained of God,
and permitted to have their time of trial by Him that rules in the kingdoms of men,
and with his own hand turns the proud doers, (who regard not the work of their day,
neither prize his patience,) into confusion, making them their own executioners,
working all things for his own glory and the good of those that fear him; I say,
though he raise up and set over them the basest of men, they do not murmur,
but either actively or passively submit to their authority for conscience sake.
And having received a kingdom that cannot be shaken,
and looking for a crown that is incorruptible, they are not ambitious,
neither do they strive for the kingdoms of this world,
nor covet dignities which fade away;
but are content in the station in which God sets them,
waiting and longing that his righteousness may be revealed to reign in men,
till the knowledge and glory of God overspread the whole earth,
and his kingdom come over all.

Secondly, touching their manner of life,--though it be well known to many,
and needs not my recommendation; yet for a testimony against wickedness in ages to come,
let it stand upon record, that, as God is most just, merciful,
righteous and equal in all his ways, so they whom he hath created anew,
naturally desire to be like him; bearing the image of the heavenly.
They make justice, right reason and equity,
with the royal law which they have received in spirit,
and is engraven on the table of their hearts, which saith,
"`Whatsoever ye would that men should do unto you,
do ye even so to them,`" the rule of their walking toward all men.
So that their dealings are just, their behaviour good, and their conversation honest,
their life blameless, their yea, yea; and their nay, nay, in all things.

They cannot swear at all in any case whatsoever;
but by a perpetual covenant are bound to speak truth to their neighbour,
and keep their word though to their hurt.
Covetousness they deny as idolatry; cruelty, oppression and uncleanness, they abandon,
as destructive to the innocent life.
But having received forgiveness for their trespasses,
they are ready to forgive them that trespass against them; and do, with their hearts,
love their enemies, and are ready to spend and be spent for the good of their souls.

And being sensible that the earth is the Lord`'s and the fulness thereof,
and that they are but stewards of the portion he hath given them,
they do not use things superfluous, which are destructive to the creation,
and hurtful to their neighbours.
But in apparel they are modest, in meats and drinks temperate;
that they may have wherewith to give a portion to the afflicted, feed the hungry,
and cover the naked with a garment; accounting that religion pure,
which brings men to visit the fatherless and widows in their affliction,
that keeps them unspotted from the world, and bridles the tongue.
Lest with that they should offend, they set a watch before the door of their lips,
that no evil communication should proceed out of their mouths.
Unwholesome words they are not free to use; nor to men will they give flattering titles,
because the fear of God is in them; neither can they bow to the spirit of pride in men,
nor stand uncovered before them, as they do when they approach unto God in prayer,
because his honour ought not to be given to another.

The customs of the world which are foolish and vain,
wherein there is no true service to God nor man, they cannot countenance;
nor uphold its invented worships by a conformity thereto.
Neither dare they pay tithes to that priesthood or ministry,
which having hearts exercised with covetous practices, unduly claims them of Christians,
knowing that Christ is come in the flesh,
and hath changed the priesthood that took tithes,
and of necessity the law that gave them also; since which,
the forcing them from people is an unchristian oppression
that they cannot in any wise uphold.

In a word, every appearance of evil they seek to shun, and from all iniquity to depart;
though for so doing they are made a prey, a scorn, a reproach,
and the objects of men`'s fury; by whom they have suffered, some death,
some long imprisonments and grievous tortures; others beatings, whippings, stockings,
buffetings, stonings, with the spoiling of their goods,
to the outward ruin of themselves and distress of many of their families.
Notwithstanding that dearness of affection that is in the husband towards the wife,
parents to children, and children to parents,
yet they are willing to give up all that they may follow
the leadings of the Life of Christ Jesus their Lord,
who hath watched over them to deliver them out of temptations,
and preserve them through all their sufferings unto this day.
And they do all these things in the integrity and simplicity of their hearts towards God,
not thinking thereby to merit life, or engage his love and favour by what they can do.
But being beloved of the Father, and having received life freely,
by it they are bound faithfully to serve him; believing that in the resurrection,
both just and unjust shall give an account to him, who hath searched and known them,
and written their ways in a book,
which shall be opened in the day of righteous recompense,
when both the righteous and the wicked shall be rewarded
according to the deeds done in the body,
whether they be good or evil.

Thirdly, touching their worship--therein they are not bound up to any form,
esteeming only that worship pure, which is in Spirit and Truth;
and above all things judging it their duty to wait
in Spirit to be taught what God requires of them;
and thereby he doth move and require them to meet together in his name and fear,
sometimes upon a mountain, sometimes in a field, barn, house,
or upper chamber belonging to a believer,
or else at some certain place which they hire for that purpose,
as they see most expedient.
And when they are gathered together in the name of the Lord Jesus Christ,
they find it their strength there to be still,
and watch in their measure of his Light and Life, lest their minds should rove abroad,
and they be tempted to act something in their own wills, or to speak their own words,
which they are sensible do not profit;
therefore they rest in a silent dependence upon God,
to hear the words which proceed out of his mouth, by which their souls live.
In this dependence and waiting upon God, they have received many heavenly gifts,
as the discerning of spirits, prophecy, the Word of life, of wisdom and knowledge.

And the power of the world to come hath mightily wrought in them,
and manifested the treasures of that world unto them;
also visions and revelations they have had given them,
and the anointing of the Spirit abundantly poured forth upon them, which abideth in them,
and teacheth them all things pertaining to life and godliness,
and divers things not expedient to be uttered.
The Spirit is the sole judge of what things is expedient to be uttered and what not,
and the movings of its life is their rule; so that every one who prophesieth,
ministereth, exhorteth, or admonisheth, doth it of the ability which God hath given,
and by the moving of his Spirit; and if anything be revealed to one that sits by,
the first doth hold his peace, that all may speak one by one,
only what God giveth them and moveth them to speak by the Spirit,
that of it all may learn and be comforted.
But if any do ran out beyond their measure of the Spirit, to speak of themselves,
or to use their tongues to speak in the name of the Lord,
what they have gathered out of the Scriptures of the holy men of God into the comprehension,
when God hath not spoken to them, nor bid them speak,
then the sheep of Christ deny their voice, as not being seasoned with life and virtue,
and the witness of God riseth in them against it,
to judge and stop it by the power of God.

And those that are spiritual,
with the spirit of meekness labour to restore such as are overcome with evil,
considering that they also may be tempted, and though he hear not at first,
they suffer with long patience, admonishing again and again,
if peradventure God may give him repentance unto life.
For, as children of their heavenly Father, they are merciful,
and do not only suffer to come, but also call and invite to their assemblies the blind,
lame, and maimed, that the rain may fall on the just and on the unjust.

So that it may be noted,
that what is spoken of the people of God called Quakers in general,
will not hold true concerning every particular that cometh amongst them;
for they discern some to be false and treacherous-hearted,
and look upon them to be without the unity of the body,
whereinto the living members are baptised by the Eternal Spirit,
who are come into the fellowship of the mystery, and are made partakers of eternal Life.
Such as are deceitful and not truly of them,
cannot at all feed with them on the fatness of the Root of Life,
nor long endure amongst them, because the presence and power of God is with them;
which hath often caused the wicked to fall down flat, and tormented the unclean spirits,
and caused the earthly part to tremble very exceedingly;
in which power all souls which love righteousness rejoice and are refreshed,
because of the appearance of their Saviour and the presence of their Bridegroom,
unto whom is their fervent desire.

And as they are thus exercised in waiting upon God,
his power doth prepare them for the marriage supper of the Lamb;
and the spirit of prayer and supplication cometh upon them,
and maketh intercession for them, sometimes with sighs and groans that are unutterable,
and sometimes with sensible words,
which the Spirit gives them to utter with understanding
for the comfort and edification of others,
but not at any time of themselves;
for that by the flock is judged an unsavoury dead thing, unto which God hath no respect.
The law of the Spirit, and the movings of his life, is herein their rule;
and the fervent prayers of the faithful, which proceed from the Spirit of Life,
avail much, for they pierce through the clouds,
and enter into the ears of the God of Heaven, who answers by unstopping the deaf ear,
opening the blind eye, causing the lame to leap as a hart, the sick to recover strength,
the dead to live, and the tongue of the dumb to sing forth his praise;
so that their sighs have often been turned into the voice of the turtle,
their lamentations into the sound of praises,
and their prayers into hallelujahs of glory to the Highest,
who openeth his treasure unto them,
and causeth the waters of Shiloh to spring in the midst of their tents,
that every plant in his vineyard may be refreshed.
He also in the congregation of his saints spreadeth a table for his children,
and giveth them all to eat of that one Bread which came down from Heaven,
whereof the Christians did partake before the apostasy,
and doth make them all to drink into one Spirit.
And by that one Spirit whereinto they drink of the Life and Virtue,
they are united into one body; and as the several members receive thereof,
they are firmly knit together, and filled with pure love one to another;
by which I know they are disciples of Christ, and the church of the living God,
which is the pillar and ground of the truth.

I do further see, how the Lord is leading the church out of the wilderness,
and raising it from under the feet of the Gentiles,
which have long trodden upon the holy city,
and with blood and persecution have built an unholy one in her stead,
which God will lay waste and make desolate:
because he takes pleasure in the stones of Zion, and favours the dust thereof,
which hath been trampled: upon, and by few sought after for many generations.
And the Lord saw it, and hath heard her mourning,
which hath sat solitary as a widow of youth;
and he beheld that there was none upon the earth a help-meet for her,
which could heal her breaches, gather her stones, and build them upon her own foundation,
because it was hid from their eye.
Then did his bowels yearn towards her, and he could no longer refrain himself,
but in his power he arose, and his arm hath brought salvation unto her;
and by his bright appearing through the clouds,
his righteousness is revealed for an everlasting foundation.
And the inspiration of the Almighty hath given unto many skill
to seek out the stones of Zion from their rubbish and polish them;
for the set time to favour her is come, and the Lord will gather her dust together,
and his seed out of all countries, to the pasture and fold of one Shepherd.
He will also give unto her which hath sat solitary, as in widowhood,
increase of children, and she shall not any more be called desolate and forsaken.
Therefore be wise, O kings, and hearken ye rulers of the earth;
take not counsel together against the workings of God,
and be not altogether heedless of the operation of his hands;
neither seek to hinder the rebuilding of Zion, as those who have gone before you did,
whom God therefore broke in pieces.
For if you speak proudly against the Lord, it shall not stand;
and if you take counsel together against his husbandry and building,
it shall come to nought.

Therefore fear not, O children of Zion,
though in the return of your captivity from Sodom and Egypt you feel many obstacles,
and are, in yourselves, weak as worms which the ploughers turn their clods upon;
for the Lord your God is with you, and ye shall yet be aided with a little help.
Therefore be patient in your tribulations, and steadfast in your walking with God;
and because ye believe, make not haste;
for the work is the Lord`'s. And he hath raised up for thee, O daughter of Zion,
a sure foundation; therefore wait to feel the Life preparing thy stones,
and cementing them together; and in due time the top-stone shall be laid with grace,
that thou mayst be an everlasting habitation for the Highest;
whose light and glory shall shine in the midst of thee,
and cause the sons of thine afflicters to come bending to thee,
unto whom thy gates shall be open.
Then shall the skirt of him who is a Jew inward, be precious;
and many shall lay hold of it, and say,
Let us be called by thy name to take away our reproach.
Then shall the earth yield her increase, and God, even our God, who is Light,
will refresh the inhabitants thereof with mercy, and visit the nations with his blessing;
that their desire, with the restitution of all things, may be accomplished,
and God over all exalted with righteousness, to rule the whole earth.

Written in the Prison-house in Aylesbury, the Third Month, 1661.

+++[+++It is likely that the following impressive Christian remonstrance to the Judges, etc.,
was written a short time before John Whitehead`'s release from Aylesbury Jail:]

For the Judges of the Assize, and Justices of the Peace, Sitting at Aylesbury:
for them to Read and Consider these Particular Things Following,
in the Fear and Wisdom of God; and to Do Thereupon what unto Law,
Justice and Righteousness shall Appertain.

We who are called Quakers, have been for many years men of a sorrowful spirit,
and many of us well acquainted with grief,
having long lain under the terror of a troubled and wounded conscience,
by reason of our sins and iniquities.
And now, being come to peace and reconciliation with God, through Christ,
we are afraid to sin against him, by doing any thing, which, in our consciences,
we are persuaded is displeasing unto him:
and therefore have we suffered much spoil of our goods,
and cruel and hard usage upon our bodies, from the worst of men;
and our liberties have been taken from us,
and many of us have continued long in prisons and dungeons; our beds being straw,
and our company thieves and murderers, and our relations debarred from coming at us;
and many times our necessary food and relief hath
been kept from us;--and all this for no evil,
but because we durst not break our peace with God, in sinning against our consciences.

Of late, some of us have been taken out of our houses by force, and by armed men,
without any warrant, and contrary to all law; and have been cast into prison,
only because we could not swear; and others,
for no other cause but for meeting a few together in our own dwelling houses,
and that without any warrant when we have not been in number above three or four men.
And since the king`'s proclamation, which forbids all such apprehensions,
some have had the oath of allegiance tendered unto them;
and because they could not swear at all, have been committed;
others have been sent to prison,
because they could not find sureties for their good behaviour,
though they had done nothing at all,
but only met three or four neighbours together in
their own dwelling houses to wait upon God.
All which things, we hoped,
should not have been inflicted upon us by those who have lately been in sufferings themselves,
and therefore might the better pity others; and not deal with us like that evil steward,
mentioned in the Scriptures,
who though he had so many thousand talents forgiven him by his Lord,
yet would not himself forgive his fellow servant a small debt;
but fell upon him and took him by the throat, saying, I will have the uttermost farthing.
Especially considering the promises and declarations of the king,
concerning his indulgence to tender consciences,
which we expected would have been made good unto us;
we doing nothing on our part against him, or his government;
but we always have made it our greatest work and business to live a sober,
godly and quiet life under his authority and government; and shall continue,
(God assisting us) to keep our word and promise with him and all men,
however they break and deal with us; and our yea shall be yea, and our nay, nay,
while we have breath; though we dare not swear at all, because Christ Jesus,
our Lord and Master, hath said unto us, "`Swear not at all.`"
And the Apostle James, who abode in the same doctrine and practice, saith,
"`Above all things, my brethren, swear not; neither by Heaven, nor by Earth,
nor any other oath.`"
And the Apostle Paul, in his Epistles, both to the Romans and Philippians,
quoting the words of the Prophet Isaiah, Chap.
45., where it is written, that "`unto God, every knee shall bow,
and every tongue shall swear`"--I say the Apostle
repeating the same saying in both the Epistles aforesaid,
leaves out the word swear in them both, and puts in the word confess instead thereof,
saying, "`Every knee shall bow,
and every tongue shall confess to God;`" signifying to us thereby,
that the practice of swearing (amongst true Christians)
is to be laid aside in the days of the Gospel.

And further,
because we look upon obedience to the king`'s just
commands to be a duty incumbent upon us,
by virtue of God`'s precept; therefore we that fear God, dare not but honour the king,
because the Lord requires it at our hands, and woe unto us from him if we do it not;
but we see no reason,
neither can we with a good conscience swear to the observance of this
one duty and command of God more than unto any other of God`'s commands;
especially when we consider his absolute prohibition
of all swearing in the days of the Gospel.
And because we could not swear at all under the former powers,
we suffered both in our estates and liberties; whereby it may appear,
that our refusing to swear is not out of any prejudice either to the king or his government,
but from an obligation of conscience, because we dare not swear at all,
for the causes and reasons aforesaid.

These things duly considered in God`'s fear,
we doubt not but the justness of our cause will plead our innocency before you.
Therefore, consider,
if all your books will afford a precedent of the like case that ours is,
being truly stated.
Or doth any of your histories help you with a relation of
the like assizes which this present year and circuit affordeth,
wherein you meet with so many innocent persons in all your jails and counties,
whose sufferings have been so long and great and undeserved,
from so many changeable powers and governments, as these late years have produced?
Oh, examine thoroughly our cause, and search deep into our principles,
and inquire impartially of our accusers, what evil have we done,
and what have been our conversations,
that so many thousands of persons should be imprisoned together at one assize!
Can all your reading supply you with examples in the like case in any age,
since England was a nation?

Therefore you had need be wise, O ye judges! and stand in God`'s counsel,
that the right mother of the child may be discovered.
For it hath been said, that the opinions of judges are infectious,
and many are ready to be led thereby; and your judgments are like to become records,
in this case.
Oh, how cautious and circumspect ought you to be in making of new precedents;
especially in a case of so great importance,
and wherein so many thousands of families are concerned, and their little ones,
which know not their right hand from their left!
For your proceedings and examples are like to be observed,
when your persons are departed and gone: especially,
if you leave an example of severity and rigour against us; we being on every hand,
and from the worst of men, ready to become a prey, and to be swallowed up,
if the Lord our God did not restrain them:
the very name of a Quaker being crime enough with many,
to render a man guilty of whatever may be charged against him.
For so hath it come to pass in the years past,
that we have been a prey to every furious hand, and envious tongue;
who have esteemed themselves well employed,
if they were but accusing or offering violence to us.
Such hath been our portion, and to this day it is not abated,
but rather increased by many degrees beyond what hath yet appeared since we were a people:
and all this for no other reason but because we dare not violate oar consciences;
for our departing from iniquity hath made us become a prey.

Notwithstanding all this, herein was and is our rejoicing,
both in our former and present sufferings, in the testimony of a good conscience.
In your indulging and cherishing of which, you will both answer the end of magistracy,
and manifest your singular service to the king and kingdom.
For in that stands the safety and welfare of both;
because if the conscience be violated and seared, Oh, what cruel injustice, murder,
and all manner of wickedness, will the kingdom abound with!
And therefore they that now persecute us,
and cause us to suffer because we cannot sin against our consciences,
will be found in the cool of the day to be the greatest enemies to the king,
when we shall be justified therefrom in the sight of God and all good men;
and we shall appear to be faithful and loyal subjects, when they shall be condemned,
who have not been a terror to evil doers, nor a praise to them that do well.

And therefore to God`'s witness in all your consciences we commit our cause;
and however you deal with us, yet shall we pray for them that persecute us,
and do good to them that despitefully use us;
and remain true friends to the King and his just Government, in a meek and quiet spirit,
which is to us of great price: and we may not part with it,
whatever is suffered to be done unto us.

John Whitehead.

Written in Aylesbury Jail, in the Year 1661.
