== Chapter VI.

Apprehended at Binbrook,
and committed to Lincoln Castle--An Epistle of Counsel and Encouragement--Letter
to faithful Friends--Letter to Friends in Hull,
etc.--John Whitehead is taken to the Sessions at Castor--Unfair and abusive
conduct of the court--Address to the justices--Remanded to prison.

+++[+++Under the influence of that love which unites the flock of Christ, as sheep of one fold,
John Whitehead went on the 13th of the Ninth Month, 1661,
to pay a visit to his friend Humphrey Cod at Binbrook in Lincolnshire.
Whilst he was sitting quietly in the house,
with none present but the said H. C. and his wife, a constable,
accompanied by two other men, came in and apprehended him on a general warrant.
He was taken before Alexander Emmerson, a commissioner of the peace,
by whom he was required to give bond for his good behaviour.
This he refused to do,
considering himself already under a stronger obligation
than any outward form could impose,
viz., the law of God;
and that there was no just ground for requiring of him such an engagement.
The magistrate professed to suspect him of being a dangerous person,
merely because he was one called a Quaker,
and a few sober people had met with him the day before.
On this ground he was sent to Lincoln Castle, where he remained three months.

It will be seen by the Epistles, etc., which now follow, that he was,
during this imprisonment, assiduous in his endeavours to promote the cause of Truth.]

John Whitehead, a suffering servant of the Lord,
unto the sheep of his pasture +++[+++amongst whom he hath laboured]
wisheth stability in grace, increase of faith,
with all spiritual comforts and blessings needful for your strengthening and
preservation in the path of Life unto the end of the race set before you,
that ye may obtain that which your souls long after,
and not be beguiled of the recompence of reward,
prepared for you that endure faithful unto the end of time.

As I was waiting on God to fulfill his will,
I felt his love springing in me unto all souls; and,
in spirit beheld their bondage to corruption.
Also in the Light I plainly saw the manifold trials that
do attend the camp of the saints and the beloved city,
which they that dwell upon the earth are compassing about with the instruments of cruelty,
thinking to wear out the saints of the most High and to scatter the holy people,
who have been made instruments to reprove their ungodly deeds.
Having beheld these things and felt God`'s yearnings towards his creatures,
and his everlasting love to the house of Jacob, I have therefore,
since I saw you face to face,
laboured with good success to strengthen the plants of God`'s vineyard,
that they might live and grow in that ground where they have felt
the Root of Life to nourish and the dew of heaven to refresh,
and where they have received divers testimonies of God`'s
power in delivering them and of his love in preserving them;
that they might be encouraged to hold fast their confidence,
and to persevere until the righteousness of God be revealed
to render tribulation to them who trouble us,
and to you who are troubled, rest with us,
in the day that the Lord Jesus shall take vengeance in flames of fire on them
that know not God and are disobedient to his glorious gospel.

This I have also laboured to preach unto them that dwell upon the earth;
testifying that the "`common salvation`" of every soul is Christ, the Light,
which shineth in the heart, and shows the corruptions therein,
which have embondaged the soul;
that the Light might give unto it the knowledge of the glorious God,
and lead it into the possession of treasure in the earthen vessel,
which many are seeking without to find--And further,
I have in the Light manifested the confusion of Babel`'s builders,
and reproved the abominations of the times;
whereby Satan felt his kingdom weakened and hath stirred up wrath against me,
and by his instruments hath cast me into prison in the castle of Lincoln,
where I am now shut up for the testimony of Jesus, and because I love his lambs,
and have laboured to inform strangers in the right way.

And now, dear Friends, what can I do more to establish and confirm you in the faith,
than patiently suffer for the Lord and your sakes, until he break their bands asunder.
Be assured I am not straitened in spirit towards you, neither is the Word of God bound;
but therein do I breathe unto the God of all power, that your faith may not fail,
but be daily increased; and in the virtue of the Word,
my soul saith unto my heavenly Father,
who is the Husbandman and walketh in his vineyard--water thy plants every moment,
and cause them to grow in thy virtue; for without instruments thou canst reform thy work.
Therefore, let the light of thy countenance shine upon them,
that they may behold thy presence in their assemblies:
in their watchings let them feel thee near to deliver out of temptation,
and in their waiting upon thee let thy visitations renew their strength,
that they may walk together in thy love, and trust perfectly in thy name.
O Lord, pour forth of thy Spirit both in sons and daughters,
that in the leadings of it they may serve and worship thee,
and be a refreshing and a comfort one to another.
Let thy glorious power be revealed in us, and stretch forth thy hand for our help;
for thou alone dost know our innocency, and hast pitied us in our afflictions; therefore,
we hope in thy mercy, and commit ourselves to thee;
for in the day of thy power we were made willing to stay upon thee,
and are gathered in thy name for a refuge.

And now, O righteous Father, not only we whom thou hast recovered out of the apostasy,
who have received the first-fruits of the Spirit, but the creation which thou hast made,
groans to be delivered from the oppression of violence and bondage to corruption.
Therefore let thy bowels yearn towards thy suffering seed,
and thy mercy reach over all thy works;
and in righteousness cut short the day of Jacob`'s trouble,
and restore all things by thy power, that all thine enemies may dread thy name,
and see that thou knowest how to deliver them that put their trust in thee;
that they also may bow to thy sceptre, and that thy kingdom may come over all;
for unto thee alone, with thy Word and Spirit, belong glory, majesty, worship,
dominion and reverence forever and ever.

Thus, having poured out my supplication to the Lord, who himself loveth you,
in discharge of my duty to him, (unto whom I owe my whole life), as also to you,
I exhort you all to wait upon the Lord in the measure of Light which he hath given you.
Look not out at things which are seen, lest your faith fail;
neither be discouraged because you are sensible of your own weakness;
for ye are God`'s instruments by whom he will confound the strong and mighty.
Therefore, be not dismayed at the enemy`'s rage, whether inward or outward;
for though he sift you as wheat, yet not one corn shall be lost;
and though he tread over and crush some of your tender plants with his feet,
yet shall the Life of your Root cause such again to spring up.
Therefore, let not your hearts be troubled,
nor fear those sufferings or hardships which the
enemy sets before you to cause you to stumble,
or to turn aside out of the right way.
But look up unto the God of all mercy, by whom you enjoy all things that you have,
both pertaining to this life and to that which is to come.
He hath delivered you out of the jaws of the devourer unto this day,
and doth not intend your destruction;
though he suffer you to pass through many great tribulations for the trial of your faith,
and exercise of your patience; that all of you may be fully made manifest,
and such approved, as love God more than all things under the sun,
and in their hearts do perfectly trust in him,
and seek not out any invention to save themselves which may grieve his Spirit,
but delight in his love to do his will, and patiently wait to inherit the promise;
in the day of their distress, flying unto his name alone for refuge and protection.
I say, such shall never be put to confusion nor rooted up;
but be nourished as the lilies of the valley, and, in bringing forth fruits,
be blessed forever.

But they who with their hearts depart from the living God,
and bow down to an image invented by man, and trust in the arm of flesh, thinking,
by a corrupt compliance with the world, and their own care, wisdom and prudence,
to save themselves, shall certainly find destruction in their goings.
Therefore, let such consider whether they have an arm like the Highest;
or whether they can deliver themselves from the sword in the day of battle,
or from death in the time of plague, or from hunger in the time of famine;
or whether they can deliver their corn from blasting and mildew,
or the fruits of the ground from the palmer-worm and caterpillar.
Who can deliver from hailstones and shafts of lightnings, murrain,
consuming rot and other instruments of destruction which are at God`'s appointment?
and who can deliver their house and fields, their basket and store, from God`'s curse,
if rebelliously or treacherously they depart from him?
Or thinkest thou, O vain man, thereby to make thy offspring blessed,
or to lay up treasure for thy children?
Shall it not be a snare unto them, until the moth consume it?
Wherefore, I say, most blessed is the man whose help is in the name of the Lord,
and who puts his confidence in God, who casteth down and raiseth up,
killeth and maketh alive, as it pleaseth him.
On him all creatures wait; and he gives nourishment to everything that hath life,
whether vegetable or animal.
O! then, fear not, little flock, but cast your care upon him,
and walk before him with a perfect heart, and love him above all things;
in everything watching that your consciences may be kept clear, void of offence,
and nothing spoken nor acted against the Light of the Lord Jesus Christ;
so in him you shall have peace, though in the world ye have trouble;
yet shall your latter end be blessed, and your offspring inherit your substance.

And, dear Friends, meet often together in the name of the Lord, as he requireth,
notwithstanding the contradiction of sinners and the laws of mortal men;
so shall you feel the pure presence of God in the midst of you,
and in the day of your adversity he will be your hiding place,
and will not leave you destitute of help in the time of affliction.
Therefore, diligently wait on God in all your meetings,
that you may all inherit the promise of the Father, which the world cannot receive,
even the Holy Spirit, that in it you may worship God, and exhort,
comfort and pray for one another, and for your enemies, not quenching the Spirit;
and beware of bringing forth any thing, or running into any thing,
but as you are led by the Spirit and power of the Lord.

And if any have erred from the Truth,
let them return and patiently wait on God for mercy and forgiveness,
who pities the wanderings of his sheep,
and in dear compassion seeks after that which is lost,
though ninety and nine be left alone in the wilderness.
Therefore, as he is merciful, dear children, be ye merciful,
and ready to forgive one another and your enemies, as God, for Christ`'s sake,
hath forgiven you much: and have perfect love and peace amongst yourselves,
and in no wise jar one with another, lest you be guilty of weakening one another,
and so drive the halt out of the way.
But, in all lowliness of mind and tenderness of heart,
condescend one to another in the Truth, that you may not grieve one another.
And judge that eye which is more apt to look at another`'s weakness than at its own,
and that mind which hath a delight to spread it abroad,
for it is the transgression of the royal law; lest you be judged of God,
and the measure you have given to others be measured to you again.

And you whom God hath anointed with the oil of gladness,
take heed of being exalted above your fellows, which is the place of the Head.
Beware of doing any thing whereby they that are in heaviness may be grieved,
for God accepteth them: therefore let your melody unto the Lord, who seeth in secret,
be chiefly in the heart; and stoop low, that you may mourn with them that mourn; and,
if need be, enter into heaviness with them that are in heaviness.
So, in the pure love and sympathy one with another, you may edify one another,
and be comforted of God together, growing unto a habitation of his delight,
who by his Spirit hath signified "`how pleasant it
is for brethren to dwell together in unity.`"

And, dear lambs, let none of you be discouraged because of my bonds,
but in a pure conscience hold fast the mystery of faith without wavering.
For though the devil should cast many of God`'s servants into prison,
yet the victory is sure to the Lamb`'s followers, who through his precious blood,
and the Word of their testimony, shall come through the tribulation of these days,
which shall have an end;
when it shall be manifest that we as naturally serve God as Job did,
and not for any self-end, but are as willing to be stripped of all,
and embrace afflictions for his Name`'s sake, as to be compassed about with blessings.
And in the meantime, the sufferings of God`'s lambs, whether imprisonment,
spoiling of their goods or banishment,
are not only for the purifying and making them white,
but also for a trial and to leave all without excuse that make mention
of the name of the Lord Jesus Christ +++[+++and depart not from iniquity,]
whom he will judge in righteousness according to their works, in the day of separation,
when the sheep shall stand on the right hand and the goats on the left.
Then to them on the right hand, who have been as sheep given up to the slaughter,
he will say, "`Come, ye blessed of my Father,
inherit the kingdom prepared for you from the foundation of the world;
for I was naked and ye clothed me; I was a stranger and ye took me in;
hungry and ye fed me; thirsty and ye gave me drink; sick and in prison,
and ye ministered unto me; for inasmuch as ye did it to one of these that believe in me,
ye did it unto me.`"
But to them on '`his left hand the Lord will say, "`Go, ye cursed, into everlasting fire,
prepared for the devil and his angels; for I was naked and ye clothed me not;
a stranger and ye took me not in; hungry and ye fed me not;
thirsty and ye gave me no drink; sick and in prison and ye visited me not.`"
But inasmuch as their eyes are without,
and they will not see him afflicted in his people, they will say,
"`When saw we thee naked, or a stranger, or hungry, or thirsty, or sick, or in prison,
and did not minister unto thee?`"
Then shall our Lord and King say,
"`Inasmuch as ye did it not unto the least of these that believe in me,
ye did it not unto me.`"
And the righteous shall enter into everlasting life;
but the wicked into everlasting punishment.

John Whitehead.

The first copy of this was written in the Castle of Lincoln, the 22nd of the Ninth Month,
1661.

Let it be carefully copied, and sent to be read in the meetings of Friends,
amongst whom I have laboured while it was day, having peace,
(in this hour of the world`'s darkness) in which I rest
with all the brethren and Friends that are faithful.

To All Faithful and Upright-Hearted Friends, Both in Bonds and at Liberty;
but more Particularly Those in the Counties of Northampton, Buckingham, Bedford,
Leicester, Hertford and Thereaway.

Dear Brethren And Fellow-sufferers,

From the pure Fountain of Life, a living stream runs towards you all,
of that love which may be better felt in your tender
hearts than can be expressed by me unto you.
For you my soul is truly solicitous unto the living God and Father of all mercy,
who hath never left us in all our trials,
that you may in your sufferings be comforted with the glorious light of his countenance,
and have your souls refreshed by the springs of his life,
and your hearts filled with wisdom from above;
that in it you may stand before rulers and governors, and see over all their snares;
and in the innocency and simplicity of that glorious cause wherein we suffer,
stand clear and pure to the glory and praise of God.
He hath called us into his marvellous Light, that in it we may walk with him,
till we have finished the testimony he hath given us and doth give us;
for which my soul saith in the Spirit,--let not anything be dear unto us, whether life,
liberty or dearest relations.
Then will our God gird us with strength,
and we shall overcome through the blood of the Lamb, and possess the crown of Life,
prepared for us in that everlasting kingdom, which is not of this world;
to which we are born heirs, who are of the incorruptible Seed,
and have not made any corruptible thing the price of our calling.
So my dear brethren and fellow servants, both in bonds and at liberty,
feeling that your hearts and minds are as mine, given up unto God to fulfill his will,
I am refreshed in you, and do salute you every one in the love of our God,
as if I did name you one by one;
for when it was in my heart to write to some of you in particular,
I was prevented by a feeling of a fresh stream of love to you all, as one body,
knit together in the fellowship of the Spirit of God;
in the comfort of which I lie down with you all, who am

Your brother in the Truth,

John Whitehead.

I shall be glad to hear from any of you, as ye are moved and have opportunity;
being prisoner for the Truth`'s sake, in the Castle of Lincoln.

The 17th day of the Tenth Month, 1661.

To Friends in Hull, Holderness, etc.

Dear Friends,

In that ancient love wherein we have lived together many years,
I tenderly salute you all, being in a fresh sense of the Lord`'s power and presence,
which was with us whilst in humility we waited upon him.
Then great fear was upon us all,
lest we should grieve his Holy Spirit that was manifest in us to profit withal;
and also lest we should give any offence one to another, or to the church of God;
or lay any occasion of stumbling in the way of those whose eyes were upon us.
And I cannot forget how we increased in grace,
and our assemblies were blessed and virtuous,
and the love of God did spring and flow amongst us in that day,
whereby we were constrained to deny ourselves,
and in tenderness and lowliness condescend one to another,
that the peace of God might be multiplied amongst us,
by which we are known to be Christ`'s disciples.
Then did the heavenly Jesus descend upon us, and we became as a fruitful garden;
and your faith and love, and godly simplicity were spoken of,
in and amongst the people of God through many countries;
and you became exemplary to many that were round about you.

But I know that many of that generation are passed away, and their reward is with them,
and you are left behind to carry on the Lord`'s work, and to bear the burden of this day;
which in some respect is easy,
in comparison of that which they have borne who went before you.
Howbeit there is no time, state or place in this world, without trials,
temptations or troubles.
Therefore dear friends, brethren and sisters, I exhort and beseech you all--be watchful;
and keep low in humility, and in the fear of the Lord;
that his peaceable wisdom may guide you,
and his power preserve you out of all the snares of the enemy of your souls,
who lays wait against the dwellings of the righteous, that he may spoil their resting,
and make weak the hands of the Lord`'s workmen and servants.
Oh friends!
I am jealous over you with a godly jealousy, lest you suffer your minds to be drawn out,
and lose the first love and humility, faith and fear of God,
which is your armour against the enemy; for he would make a breach amongst you,
who have been gathered into the love of God, and the heavenly fellowship in his Spirit.
Therefore walk in the light and life of it, that you may both see when good comes,
and embrace it;
and then you will discern all the suggestions of the enemy
which would withdraw your love from God and from one another;
which love is the bond of perfection,
and that which draws from it will lead into self-love and partiality.
From thence spring evil surmisings and murmurings one against another,
which if given way to, beget strife and division, confusion and evil works.
These tend to hinder your growth and prosperity in the Truth,
and lay an occasion of stumbling in the way of the simple.

Therefore dear friends, I say unto you once more--keep love in your minds,
and be tender in the fear of the Lord; that his wisdom, which is pure, peaceable,
gentle and easy to be entreated, full of mercy and goodness,
may guide you in all your meetings: so that unity in the Spirit, and bonds of peace,
may be kept inviolable amongst you, and the wisdom which is from beneath judged down.
For where that rules, it is for itself, and there is striving for mastery,
handling one another with coarse rough hands, contrary to the Apostle`'s doctrine,
who said, "`Be not many masters, for in many things we offend all.`"
Therefore keep to the one thing most needful, the Light of Christ Jesus,
by whom greater truth doth come; and therein being exercised,
your hearts and work will be seasoned with love to God and one another;
so will his blessing and peace be among you forever:

Which is the true desire and prayer of your ancient and steadfast friend in the Truth,

John Whitehead.

The 25th day of the Tenth Month, 1661.

+++[+++About two months after John Whitehead`'s commitment to Lincoln Castle,
he was taken to the general Sessions held at Castor.
But, a little before his appearance there, Emmerson, the magistrate,
by whom he was committed, found occasion to relent;
and "`being not well able to come forth to sit on the bench,`"
desired John Whitehead to be brought to his house.
During their interview Emmerson behaved very civilly,
expressed some sorrow for what he had done,
and a desire that John might be set at liberty; but said,
it was not in his power to release him, yet he would do what he could for him.
When John appeared in the court, his hat was taken off by a bailiff;
and so defectively did the magistrates fulfill the duties of their vocation,
as ministers of justice, that some of them undertook, in a scurrilous manner,
to condemn him before he had been heard, or evidence had been given against him.
John Whitehead gives the following account of these proceedings:]

William Broxolm, +++[+++one of the magistrates on the bench,]
said he knew me; and I was one of the veriest rascals in England;
and asked me for sureties for my good behaviour,--to whom I replied,
"`I am not yet convinced of any ill-behaviour.`"
Then he said, that appearing in the court with my head covered was ill-behaviour.
I asked him, whether the law required me to be uncovered, or they only.
He answered, they required it.
Then I told him, as I did not appear covered in contempt of authority,
so I could not uncover in respect of their persons.
He then said, I wrote books against the king and his government:
which accusation I did then, and do now, utterly deny.

William Wray, +++[+++another of the magistrates,]
said, I was the most notorious rogue in all Yorkshire or Lincolnshire,
and had seduced the people; yet he confessed, he had never seen my face before,
but had heard of me.
Then I told them, I could not reasonably hope for justice from their hands,
if they who sat to judge me were my accusers: at which they were silent,
and caused the mittimus by which I was committed, to be read.
The clerk of the peace asked me what I had to say to it?
I told him I did deny the matter of fact, as it was there charged against me,
and desired that my accusers might appear face to face,
and that I might have liberty to answer for myself.
The clerk said, if I stayed till then, it might be as long as I lived, for aught he knew.

Then a lewd man of the country stood up, and said,
I was one of the chief deluders among the Quakers, and had been at Wintringham,
+++[+++a village in the north of Lincolnshire.]
To him I replied, "`Seeing thou accusest me in open court, speak truth;
didst thou ever see my face, or hear me speak one word, before now?`"
To which he answered, "`Nay;`" but +++[+++said]
I had been often at Wintringham.
I answered, "`If thou hast no more to say, I hope that is no crime,
to have been at Wintringham.`"
Then one of the justices asked me, what I did at Binbrook?
I answered, that I came in love to visit my friends.
Some other questions they asked, +++[+++seeking]
advantage against me, to which I answered nothing, after the good example of Christ.

Then William Broxolm asked me when I was at church?
I told him, that was not the business now in hand;
but I supposed there was but a small living,
as none of their priests would come and officiate
at the parish church (so called) to which I belonged,
what should I go for?
One of them said, I might go to some other; but I told them the law did not enjoin that,
that I knew of.
Then great fury was in the court against me; some said, "`Away with him!`"
But William Broxolm said,
"`Tender him the oaths of supremacy and allegiance;`" and Edward Aiscough,
+++[+++another of the justices]
asked if I would take them?
I desired liberty to speak, and said to them, "`I do not understand that you have power,
by law, to tender the oath of supremacy to me.`"
Then several of them spake together, and said, "`Away with him!
Away with him!`"
So I was forthwith taken away, and not suffered to give them any further answer.

Seeing I could not be heard, it came upon me to write these lines following to them,
which were delivered into Edward Aiscough`'s hand,
who said he would read them to the rest of his brethren.

For the King`'s Justices, now sitting at Castor, these.

Friends,--In tender love I send you these lines, that ye may consider,
that God beholds you in the seat of judgment.
Therefore be wise, and not rash and hasty in judgment, lest,
by untrue surmises and false reports, you condemn the innocent.
For I am one that fears the Lord, loves the king,
and seeks the peace of the land of my nativity,
and therefore ought to have the benefit of the wholesome laws to which I was horn,
that will no man to accuse himself; neither take any man`'s life, limb,
liberty or estate, but by judgment of his peers.
Therefore let me have a fair trial; and if I be found guilty of these things,
whereof in wrath I have been accused, or if any wicked lewdness, rebellion,
or treachery be found in me, let the law that is just, pass upon me:
but if I be innocent, why should snares be laid for my feet,
or I be crushed by a high hand, and denied my liberty, under specious pretences?

O remember! did not the heathen rage?
And was not Cain wroth with his brother, and slew him?
And did not the unbelieving Jews resist and evilly entreat God`'s servants,
under the name of ringleaders of a dangerous sect, that turned the world upside down?
etc. And will ye follow their steps?
Surely my soul laments to see Englishmen, that profess Christianity,
so fierce one against another; and my heart doth pray unto God,
that we may not be devoured one of another.
O! then let us follow that which makes for peace,
and not unrighteously judge one another;
for both you and I must appear before the judgment seat of Christ,
who will not respect persons, but will justify the innocent, and condemn the guilty.
Therefore be noble and righteous in judgment, and consider what evil I am guilty of;
except it be a crime to no one that fears God, and trembles at his Word,
whom men in scorn call a Quaker; and if that be the fact whereof I am accused,
then I do ingenuously confess, that in that way which evil men call heresy,
do I worship the God of my fathers,
believing those things that are written in the Scriptures of Truth.

So I rest in love, your friend, and shall have peace with God,
however you shall dispose of me; believing that the more we are afflicted,
the more we shall increase and grow.

John Whitehead.

The 15th day of the Eleventh Month, 1661.

Notwithstanding what I here proposed to them,
and although none appeared against me that did or could
justly charge me with the breach of any known law,
they passed an order, wherein they accused me of being a person of dangerous principles,
that in contempt of the king`'s laws drew persons together in unlawful conventicles;
that I refused to give an account of my abode and business in these parts,
and denied the oaths of supremacy and allegiance, tendered to me;
and withal refused to give security for my good behaviour;
and therefore they commanded the sheriff to convey me to the Castle of Lincoln,
there to be kept till I should willingly do the same.

All these accusations are false but the last;
and I could not give security for my good behaviour, for these reasons: First,
Because I was never legally convicted to be of evil behaviour.--Secondly,
Because I am inwardly bound, by the righteous law of God,
to behave myself well towards all men.--Thirdly,
Because I have given no just cause of suspicion, by threatening, or otherwise,
for which it may be required.--Fourthly, Because I have already subscribed, by promise,
with my hand, and in the presence of authority, engaged fidelity to the king,
and a peaceable deportment in the land of my nativity:
which word of promise doth more engage me than any bond can do:
for my word is as my life, and to break it would be a wounding to my very life and soul:
but the breach of a bond in a sum of money, would be but the loss of the sum,
which is of small value to me in comparison of my word:
therefore I cannot undervalue the greater, by giving the less.

So all these things considered, the judicious reader may observe,
whether they do not now, as in the days of the ancient prophets,
men of corrupt minds did, turn judgment backward into the gall of bitterness,
and cause justice to stand afar off; so that truth falleth in the streets,
and equity cannot enter; but he that departs from iniquity makes himself a prey.
But surely the Lord seeth it, and is displeased,
and will not always suffer the apple of his eye to be touched by the rough hands of Esau;
neither will he forever bear the bruises of his plants,
nor always suffer his children to be a prey and spoil to their enemies;
but his arm shall bring salvation, and his righteous hand sustain us,
till he clothe himself with the garment of vengeance, and put on zeal as a cloak,
wherein he will give to every one a recompence according to their works.
Therefore doth my heart submit to his will; for unto him I do commit my cause,
who will judge righteously.

Yet my soul is poured forth unto him, that he may pity those that afflict us,
and remember that they know not what they do.
For when they persecute thy servants, O Lord! they think they do thee good service;
therefore lay not their sin to their charge; but open their eyes,
and show them thy salvation.
And in mercy remember me with all thy suffering lambs; and uphold us by thy power,
till we have finished our testimony,
to the glory of thy name throughout all ages forever.
