== Chapter VII.

[.chapter-synopsis]
* Letter to Friends in Hull--Letter to such as have been convinced of sin
* [.book-title]#The Testimony of John Whitehead# written near the time of his release from Lincoln Castle
* A Manifestation of Truth.

+++[+++After having been, in this arbitrary manner, remanded to prison,
John Whitehead manifested his unabated concern for the spiritual welfare of his fellow-professors,
by the following weighty letters:]

[.embedded-content-document.letter]
--

[.letter-heading]
To Friends in Hull

[.salutation]
Dear Friends,

Both in bonds and out of bonds, I am in a sense of all your trials;
my very heart doth sympathize with you; and the Seed which you know is but one in us all,
bears a part with you; for I am persuaded that the Lord is with you,
and will not leave you comfortless in your tribulations,
that I also may be comforted by your faithful standing in this time of trial.
O, my dear hearts! look not out so as to be discouraged,
though other professors fall on your right hand and on your left;
but rather rejoice in the Lord, who upholds you by his power and makes you stand.
For are not you of that great people, whom God hath chosen to be his witnesses;
that in you he may show forth his power, patience,
and long-suffering unto a generation of evil-doers?
Therefore stand in his will, for he numbers the days of your trouble,
and will work deliverance for you in his appointed time:
and when your faith and patience have been fully tried, your innocency shall appear.
So, dear Lambs, wait for the counsel of God to guide you,
that you may be "`wise as serpents and harmless as doves;`"
and in perfect love bear one another`'s burdens,
that you may be comforted in one another.
And give no offence to them that are without; but, according to your ability,
do good to them that hate you and despitefully use you;
so will the Lord look upon your affliction,
and in righteousness plead your cause by his witness in all consciences.
In tender love to you all I rest,

[.signed-section-closing]
Your friend and companion in tribulation,

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 20th day of the Eleventh Month, 1661.

--

[.embedded-content-document.letter]
--

[.blurb]
=== To All Such as have been Convinced of Sin, and Enlivened by the Quickening Spirit of God. John Whitehead, Prisoner for the Testimony of Jesus in the Castle of Lincoln, with the Dearest Salutation of Love Sendeth these Lines.

[.salutation]
Dear Friends,

All wait in the Spirit, that your minds may be kept spiritual and stayed on the Lord;
for "`to be carnally-minded is death;`" and if any
of you let that come over you and reign,
as it did and doth over all men in the fall, whose minds are in the earth,
then will you be as "`trees twice dead,`" that can neither
bring forth fruit to God nor receive blessing from him,
but must be rooted up.
For when ye were once "`dead in trespasses and in sins,`" the Lord in
the riches of his goodness did manifest his Life to quicken you;
and his Light hath shined in your hearts to show you the way of peace.
Therefore, all continue in his goodness; and take heed of letting in earthly reasonings,
doubts, and slavish fears,
lest the old enemy enter and draw your minds back into the things that are earthly,
sensual, and perish with the using; and so cause you, Demas-like,
to cease to follow the Lord and to love this present world,
and thereby lose the power and endless riches of the world to come.
Through faith in this power alone, you can be kept in the midst of all your trials,
and be armed with courage and patience,
wherein to stand above the fear of what man can do unto you.
So, blessed are you that watch and wait to be kept by the power of God,
and have faith in the power; for you shall overcome the world,
and inherit the promises which are exceeding precious.
These, the ancient fathers, prophets, and righteous men seeing afar off,
were not mindful of their earthly country,
but pressed on to the purchased possession of an immortal crown,
which God will also certainly give to all who, in his love,
keep his commandments faithfully until death.

Therefore hold fast that which ye have received, and grow in life, grace and virtue,
that ye may be kept zealous,
lively and diligent in your meeting together to worship God in Spirit;
and wait upon him for renewing of strength,
so much the more as the day of trial approaches; that you may be counted worthy to stand,
though others, who for a time have flourished in profession,
do fall at your right hand and at your left;
so shall you be instruments of eternal praise unto God forever.

[.signed-section-context-close]
The 31st day of the Eleventh Month, 1661.

--

[.embedded-content-document.testimony]
--

[.blurb]
=== The Testimony of our Dear Friend John Whitehead, When he was Prisoner in the Castle of Lincoln, for the Truth`'s Sake, 1661.

The Word of Life doth open my heart, which is filled with love unto you all;
out of the abundance of which,
I say unto you,--above all things love God and one another, now in this trying day:
and take heed of burdening the Pure or grieving the
Spirit of God in yourselves or in one another,
either by words or works which are not savoury: but keep low, in the pure, savoury,
holy Life; and according to its law, judge your own selves with righteous judgment.
So shall not any thing take root in you that offends;
for through the Spirit of pure judgment,
a burning will kindle in that ground which receives
offence from another to your own hurt,
or brings forth that which offends or hurts another,
until the cause of offence be wholly taken away:
that as trees of righteousness you may grow together in peace;
not exalting yourselves one above another, seeing you all have nourishment,
and stand by the virtue of the Root, not bearing it, but it you.

Remember, the olive tree would not leave its fatness, whereby God and man were honoured,
to be promoted over the trees; neither would the fruitful fig-tree leave its sweetness,
to be set over the trees; neither would the vine leave its wine,
whereby God and man were cheered, to reign over the trees: but the rough,
renting bramble, being lifted up, said, "`Come under my shadow,
or else let fire come out of the bramble and devour the cedars.`"
O, you plants of the Lord`'s vineyard! feel what is in this,
that you may keep your habitations; for whoever seeks to be greatest,
justly deserves to be least; and he that speaks of himself, seeks his own honour;
but he whom God hath sent, speaketh the words of God,
and seeketh his honour that sent him.
Unbelievers seek honour one of another; but it shall not be so amongst you.
Therefore all keep low, in the place where God hath set you in his house,
with the loins of your minds girt up in the Spirit,
ready to serve one another in bonds or at liberty,
that ye may encourage and comfort one another, according to the ability given you of God.
These things I write unto you whom God in mercy hath given to know the Truth;
and blessed are you who for the love of it lay down all, and abide faithful,
till you have fought the good fight of faith through
afflictions and overcome the wicked one;
for then shall the Lord be your portion, and he will crown you with life everlasting.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
1661.

[.postscript]
====

At this time my testimony is near finished in this place;
for the Lord put it into my heart, to write to the judge;
and the witness of God pleading my cause, though I did not appear before him,
yet he hath set me at liberty, as one innocent,
and was displeased with the justices for their illegal proceeding against me.
And now I wait to be ordered by the Lord in his service: seeing nothing,
but after a very short space, I must pass into Yorkshire,
where I have a testimony to finish, either in bonds or at liberty, as the Lord will,
into whose power I commit myself and you my dear Friends; breathing,
that we may never be weary of well-doing till we have run the race set before us.

====

[.signed-section-signature]
John Whitehead.

--

+++[+++Soon after John Whitehead`'s release from Lincoln Castle, he proceeded,
according to his prospect, "`to finish his testimony in Yorkshire.`"
When in the course of this engagement he came to Hull,
he found the officers of the garrison united with the magistrates
of the town in the antichristian work of persecution.
Among various brutal outrages committed by Richard Bishop, one of the garrison,
he took John Whitehead and Philip Ford from a meeting
and beat them till his stick broke in pieces.
They were afterwards, by the Governor`'s order, turned out of the town;
and in this manner Friends who were not inhabitants, were usually served,
whatever business they had there.

The next following production of John Whitehead`'s pen appears to have
been written soon after his discharge from this last imprisonment.
It consists of a faithful remonstrance to an opposer,
and an instructive compendium of Christian faith and practice; it is entitled,]

[.embedded-content-document]
--

[.blurb]
A Manifestation Of Truth

[.salutation]
Friendly Reader,

I have lately received in manuscript a small book, which, in the fear of the Lord,
I have read over and seriously pondered.
This I was the more induced to do, because I had some ground to suspect,
if not to conclude,
that it was written by one who hath been famous for
the profession that he hath made of Christianity.^
footnote:[_The Lord Say._]
And therefore I should admire,
but that I know that the pleasure of the Lord is to "`destroy the wisdom of the wise,
and to bring to nothing the understanding of the prudent;`" (1
Cor. 1:19) from whom he hides that which he reveals to babes,
(Matt. 11:25) that no flesh might glory in his sight; I say,
but that I know and consider these things, I should admire, that he,
who hath read the Scriptures and so long professed Christ,
who said that men would say "`all manner of evil,`"
(Matt. 5:11) of his blessed and peculiar people,
should be so far degenerated both from Christian charity and true nobility,
as to harbour so many evil thoughts and groundless
jealousies against a harmless and innocent people:
and my soul mourns that he is so far given up to believe
and report such palpable untruths against us.
+++[+++Here several absurd calumnies are recited,
which had been inserted in the book alluded to.]
Divers other hard speeches and groundless suggestions I find,
which I shall not particularize,
being satisfied that they have not arisen from any just cause given by us,
either in doctrine or practice: also hoping that the author may be sensible by this time,
(wherein truth has risen above slanders,) that he hath overshot
himself in writing such grievous things against us,
whom I am persuaded, he doth not fully know.
Therefore I cannot wonder if he do persecute us, which however,
I will not positively affirm, though I certainly know that his principle leads to it,
which saith that a blasphemer may justly be put to death in Gospel times;
though Christ Jesus, who is far more excellent than Moses, gave no such command,
but rather held forth the contrary in the whole course of his doctrine and practice:
(read Matt. 18.)

But if he with whom I now deal, hath had his hand against any,
who for conscience-sake could not respect his person,
so as to imprison them or to spoil their goods for things done
in obedience to the Light of Christ in their consciences,
though contrary to his judgment;
that will be accounted in God`'s day as persecuting their persons,
under the pretence of persecuting the devil and their sin,
which narrow cover the most bloody persecutors have ever had.
However, this I say, and desire that he may know it, if he be yet alive,
that he is at least guilty of their sin who said, "`Come,
let us smite him with the tongue; report ye, and we will report it.`"
But surely the Lord sees how we are set as a mark for every one to shoot at;
and I am persuaded that when he hath fully tried us,
he will roll away the reproach from us forever: and their eyes,
who wait to see us stumble and fall into foul enormities, (as divers professors,
but not professors of the same Life, have done) shall certainly fail.
For hitherto hath the Lord helped us, and blessed us,
and made us stand in the sufficiency of his grace in the sight of our enemies;
and I know that his presence is yet with us and that "`we are of him,`" and not
of that spirit that they were of at Munster who followed John of Leyden,^
footnote:[John Bochold was a tailor of Leyden--hence called John of Leyden.
He was a leader of a seditious section of the _Anabaptists,_ who in 1533 seized on Munster,
the capital of Westphalia,
under the fanatical pretext of a divine commission
to establish the kingdom of Christ upon earth.
Munster was denominated "`the New Jerusalem,`" and Bochold created "`King of Zion.`"
His visionary followers were taught to think themselves the delegated heralds,
through whose instrumentality the will of Heaven
was to be conveyed to the ends of the world.
Their fallacious hopes were overthrown in 1536,
when Munster was retaken by Count Waldeck, and Bochold cruelly put to death.
The term "`Anabaptist`" appears to have been indiscriminately
applied to separatists from the Roman and Reformed Churches,
of very different character and merits.
That section of which Bochold was a leader,
appears to have been a wicked and deluded set of men, who,
whilst professing to be immediately inspired and
commissioned by God to establish a spiritual kingdom,
attempted by force of arms to overthrow all civil government and legal restraints,
and gave the rein to some of the most debasing passions of our nature.
The flagitious conduct of which these were guilty,
was made the ground of persecuting others, who abhorred their spirit,
and who had no connection with them beyond that,
which arose from separation from "`state religion,`"
and an accidental belief in some common truths.]
and thought to build up Zion with blood and to beat down her enemies with carnal weapons.
For though they might pretend to be led by the Spirit within them,
we know that that which led them into uproars, war and bloodshed,
was not the Spirit of Christ which leads us; for it teaches us to love our enemies,
to save men`'s lives and not to destroy.

And as to the corrupt principles and practices of those called Ranters,
we have given testimony against them:
and all that have heard and duly weighed in that Spirit which tries all things,
can witness that we are as far from them as light from darkness.
But whereunto shall I liken the men of this generation?
For when the Spirit of Christ doth so work in the hearts of any,
that they cannot run with the world into rioting and excess,
then presently they will call it Beelzebub,
or the devil transformed into an angel of Light;
as the Pharisees did to Christ in the days of his flesh;
and if they called the Master of the house Beelzebub,
no wonder if it be more done to them of his household.

But as for self-mortification, voluntary humility and will-worship,
we know they avail not; but those who by the Spirit mortify the deeds of the flesh,
shall find comfort in so doing; and God will delight to teach and dwell in him,
who has an humble heart, and a broken and contrite spirit,
which doth fear God and tremble at his Word, however that be reproached by wicked men,
as one of the devil`'s tricks; and we, with whom his tabernacle is,
do not worship in our wills, but in Spirit and in Truth.
Neither do we say that it is a perfect demonstration of humility to cast away band-strings,
lace and ribbons;
though we believe it a duty incumbent upon us to abstain
from wearing things superfluous and unserviceable,
and also from all excess in meats and drinks;
though we know that the kingdom of God stands not therein,
yet we desire to be found temperate and in modest apparel
according to the good example of the ancient Christians.

And further I observe that the author of that writing with which I now deal,
has often misrepresented our doctrines and practices;
as may appear by a serious view of his book,
whereby I perceive he does not rightly understand us,
and I am persuaded did never regularly try our spirits,
either by a sober hearing of our doctrines, declared by our own mouths and pens,
or by his own knowledge of our practices;
but has heard and believed what evil and prejudiced
men have maliciously printed and said against us,
on purpose to slander and render us odious.
Therefore, in answer to what is said against us, I shall labour rather,
(for the stopping of slanders and to prevent misconstructions,) to inform
the reader of the truth of those doctrines which we do believe and practise,
than particularly to traduce the author with whom I have to deal;
though in many things more I could show wherein he has wronged us,
and given unsound constructions both of Scripture and of our doctrines and practices.

[.blurb]
=== Concerning the Scriptures, and Concerning the Word, Spirit, and Light Within

Concerning the Scriptures, I say--we do not slight them,
nor cast them off as a dead letter, paper and ink;
but own them which Moses and the Prophets, the Evangelists and Apostles wrote or spoke,
as they were moved by the Spirit of God,
(so far as they are free from false transcription and corrupt
translation) to be the very words and true sayings of God,
and therefore not to be slighted, but read, believed,
and practised by every true Christian.
But they that are "`unlearned`" (2 Peter 3:16) of Christ,
whose hearts are not established by the grace of God,
pervert or wrest the Scriptures out of their right place to "`their own destruction;`"
not rightly distinguishing between the law and the gospel times,
nor between that which was abolished for the unprofitableness thereof,
and that which God hath established forever.

Therefore we direct all to that Word of God which was in
the beginning (John 1.) before the Scriptures were written,
of which the Scriptures testify, that it is Life, and is the Light of men;
which shines in darkness, even in men`'s dark hearts,
showing the grossness and corruption of their hearts; I say, we direct all to this Word,
which was and is God, the Saviour of all them that believe; who searcheth all hearts,
and incomprehensibly dwells in his kingdom, which is in man,
(Luke 17:20-21) and reproves man for his unbelief and evil deeds.
We direct all to wait to know this engrafted Word, (James 1:21) and to hearken to it,
that they may not be unlearned, but all taught of the Lord,
that Spirit which holy men of God knew, and in which they believed,
and by which they were moved and led, before the Scriptures were written;
that so by this "`Interpreter,
one of a thousand,`" people may have the Scriptures opened and feel the power of God,
and have faith in the power,
and live in the life in which the primitive Christians lived.

And thus to direct people to the Word, Spirit, or Light of God within,
is none of the devil`'s work, but the work of Christ`'s ancient ministers,
(Acts 26:17-18) neither doth it make void the Scriptures,
but establishes them in their right place as a true declaration;
and the Lord Jesus Christ, who is that quickening Spirit,
(1 Cor. 15:45) which doth enlighten every man that cometh
into the world (John 1:9) in his right place,
as the Foundation, which unto all generations standeth sure,
(2 Tim. 2:19) neither can our directing people to this Foundation, Christ,
the Light which enlightens their consciences, have such bad effects,
as to lay them open to all base lusts, error, and delusion;
for all these things are condemned by the Light;
and they that believe and do such things,
go from and against the Light in their own consciences.

[.blurb]
=== Concerning the Trial of Spirits

The Apostles gave forth no such command,
as that we should try the Spirit of God by the Scriptures;
for it is most absurd to try the superior by the inferior;
and no man can rightly understand the Scriptures,
nor discern spirits whether they be of God or not,
but by the Light of the Spirit of God within.
(1 Cor. 2:14) Therefore they are worthily reproved,
who presume by strength of wisdom, sharpness of wit and human learning,
to judge both of the Scriptures and of the Spirit of God and its movings in men,
as the Scribes, Pharisees, and Chief Priests did,
who in their pride and self-wit sat as judges of the Law in the letter,
and thereby condemned Christ, the Prince of life, and also his blessed martyr Stephen,
as blasphemers that were not worthy to live:
and this was the fruit of trying the Spirit by the Scriptures,
when man`'s wisdom sat as judge of both, which is rather to be judged by them both.^
footnote:[We own the Scriptures to be a rule, but not the only rule,
whereby to try spirits.]
And let such as know no other rule whereby to try spirits but the Scriptures,
confess that they are ignorant of the law written in the heart,
and of the testimony of Jesus,
which is the Spirit or Word of prophecy that is near in the heart,
even the more sure Word,
(2 Peter 1:19)--surer than the words of the Prophets and Apostles,
which may be wrested,--for it is a Light in a dark place, viz., in the heart,
to give man a true understanding of their words; and his law which is written there,
is perfect and unalterable.

And by this rule holy men of God tried spirits before the Scriptures were written,
and by this same rule all spirits which are gone forth into the world may still be tried;
and those which are contrary to it are also contrary to the Scriptures rightly understood,
and are therefore under the judgment of both the Spirit and the Scriptures.
The Spirit of God judgeth all things, but ought to be judged of no man; therefore,
sad will be their account who call it the devil, and its motions, his impulses:
for all sins and blasphemies against the Son of man may be forgiven,
but the blasphemy against the Holy Spirit shall not be forgiven,
neither in this world nor in that which is to come.
(Matt. 12:31-32)

[.blurb]
=== Concerning Perfection

We say first, that we have sinned and God hath let us see our sin,
and he hath forgiven it through the blood of Christ,
which doth wash and cleanse us from it,
(1 John 1:7) and by his power we are kept from sinning:
yet we do not boast of perfection in or of ourselves,
because by the grace of God we are what we are.
However, we know that it is the commandment of Christ that we should be perfect,
even as our Heavenly Father is perfect;
(Matt. 5:48) and therefore we are persuaded that
it is not impossible for us to be so,
even to be renewed into his image whilst here in this life;
for he is not such a hard master as to command impossibilities.
And moreover,
"`by one offering he hath perfected forever them that are sanctified;`"
and we are sanctified "`through the offering of the body of Jesus
Christ once for all,`" and therefore are "`perfected forever.`"
(Heb. 10:10-14) And this was and is the very end for which he sends forth his ministers,
even to gather the saints into the "`unity of the
faith and of the knowledge of the Son of God,
unto a perfect man,
unto the measure of the stature of Christ;`" (Eph.
4:11-13) who for this purpose was manifest,
even to take away sin, and to destroy the works of the devil.
(1 John 3:5-11)

But if any say, "`that cannot be whilst here in this life,
for some sin will remain in men whilst on this side
the grave,`" let them answer me these questions:
1st, Whether they believe that any shall enter into or inherit God`'s kingdom?
2nd, And if yea,
then whether they believe that they shall enter into it with some sin in them?
3rd, And if nay,
then in what time and place shall they be cleansed and their sin perfectly done away,
seeing they deny it is possible whilst in this life?
But we affirm it,
being persuaded that there is no purgatory wherein to be cleansed after death,
and knowing that Jesus Christ is able to save to
the uttermost all that come to God by him.
(Heb. 7:25) So that those who are born of God
and abide in Christ "`sin not,`" "`neither can,
because they are born of God and his seed remaineth
in them;`" (1 John 3:9) contrary to which text,
no argument can stand good;
but herein are the children of God and the children of the devil made manifest;
"`he that doeth righteousness is of God,
and he that sinneth is of the devil,`" who sinneth from the beginning.
And this doctrine doth not tend to ranting, (as they who understand it not,
say) but to encourage people to wait to be cleansed,
and kept by the mighty power of God from all unrighteousness,
(which is all sin) and to press on to perfection in the life of Christ.

[.blurb]
=== Concerning Salvation by Christ

We say and believe, that without the sufferings and death of Christ at Jerusalem,
no man can be saved, justified or sanctified; and therefore do they maliciously,
or at least ignorantly, slander us, who say,
we expect not to be saved by Christ`'s sufferings at Jerusalem,
but by Christ`'s sufferings in us; for such words did never proceed from us.
Though we say that it is not a historical knowledge and belief of what
Christ said and suffered at Jerusalem sixteen hundred years ago,
that can or does save any man without the feeling of his Spirit,
power and life made manifest within,
to make them "`conformable to his death,`" (Phil. 3:10) and
to raise them together with him to live in the virtue of his life,
by which life we are saved, as well as the ancient Christians.
(Rom. 5:10) And we are "`sanctified and justified in the name
of the Lord Jesus and by the Spirit of our God,`" (1 Cor:
vi.
11,) who mightily worketh in us; and all his works are perfect.
And therefore,
I do distinguish between "`the righteousness of faith,`" "`which the Spirit worketh,`"
and "`the righteousness which is of the law,`" performed by man`'s own strength;
for though the one be "`as filthy rags,`" yet so is not the other:
and he is an enemy of righteousness that mingles them both together,
and treads them under foot, as dung and dross.
Therefore let all who love their souls, love Christ, the righteousness of God,
and follow after him that they may be made righteous,
and have that boldness in the day of judgment, which the ancient Christians had,
"`because,`" said they, "`as He is, so are we in this world.`" 1 John 4:17.

[.blurb]
=== Concerning Swearing

To swear at all in Gospel times, is no part of God`'s worship;
therefore it is no delusion, but the Truth, that makes us refuse to swear in any case.
For though swearing was used in the time of death`'s reign, from Adam to Moses,
(Rom. 5:14) and that by some of God`'s people; and not only so,
but commanded in some particular cases by Moses and the prophets in the time of the law;
yet a greater Prophet being raised up, to whom they all gave witness,
and commanded that He should be heard in all things; with this severe penalty,
that every soul that would not hear Him, should be cut off from his people;
(Acts 3:22-23) and seeing Christ Jesus that Prophet,
whom it was said God would raise up,
hath found that covenant faulty in which oaths were used,
and by his own mouth expressly hath commanded us not to swear at all;
(Matt. 5:33-34) though in old time it was lawful,
and an honour to God to swear in some cases, yet now it is not lawful,
nor an honour to God to swear in any case, because Christ Jesus, the great Lawgiver,
in the New Testament hath by plain and express precept wholly forbidden it.

Against this precept, no argument, conclusion or interpretation, whether of council,
synod or private man, is good--though grounded upon the law of Moses,
the words of the prophets, or practice of God`'s servants, saints or angels;
for their words and practices are to be reduced to a harmony with his,
and not his to theirs.
He is given to be Head over all things to his church, which is his body,
the fulness of Him that filleth all in all;
and therefore cannot the example of saints or angels,
and much less the practice of men in strife, justify us in the breach of his command,
had we no other ground for our denial to swear.

But to swear at all is against the law of the Spirit of Truth that dwelleth in us,
and derogates from the glory of His verity, who hath made our yea, yea, and our nay, nay,
in all things.
The apostle James,
(who wrote to the twelve tribes scattered abroad,) as if he had foreseen that,
because of former precepts and customs,
they would justify some swearing contrary to Christ`'s command, was very positive,
and did expressly forbid it: "`above or before all things,`" saith he, "`my brethren,
swear not; neither by heaven, nor by earth, (mark) nor any other oath;
but let your yea be yea, and your nay, nay, lest ye fall into condemnation.`"
(James 5:12) Therefore we cannot swear by heaven nor the things therein,
nor by earth nor the things therein, nor by any other oath, though by such Christians,
as are in the apostasy from the Spirit and Life of Christ, it be accounted, lawful;
for if we did swear at all, we should justly fell with them into the same condemnation.

[.blurb]
=== Concerning the Worship of God, and Why we Separate from them that Worship in "`Temples Made with Hands`"

Because we thus believe and declare,
that "`God is a Spirit,`" (John 4:24) and "`dwelleth not in temples
made with hands,`" neither is rightly worshipped there;
(Acts 7:48; xvii.
24, 25;) and therefore we cannot join in worship with them,
who are erred from the Spirit and from the Truth, and in their own wills worship in vain,
having their fear towards God taught by men`'s precepts,
(Matt. 15:8-9) and whose worship consists, not of God`'s ordinance,
but in divers observations, inventions, and traditions,
which are not the commandments of the Lord from Heaven,
but rather a loathing to his soul and a grief to his Spirit,
because in matter and manner they are contrary to the primitive Christians`' worship.
For they did not sprinkle infants, and call that baptism into the church,
that we can find in the Scripture, or in history for near the first three hundred years:
neither was it a part of their worship to sing David`'s psalms in rhyme or metre,
as men do in these days who are far enough from the condition
in which David was when he gave forth the psalms.
And besides, the ministers that were allowed among the primitive Christians,
did not read prayers for money, nor study sermons to last an hour,
and preach them for money; neither did the primitive Christians love to have it so,
as the titular Christians now do; who by their divisions, envying,
and persecuting about worship, make it manifest,
that they are neither in the same spirit nor worship in
the same manner as the primitive Christians did.

And therefore we separate from them; for which we have sufficient ground,
even though they had the very form of godliness,
(which they have not,) seeing they are out of the power, (2 Cor. 6:17-18;
2 Tim. 3:5) which should crucify them to the world, and the world to them;
and are conformed to the world: for the generality of them live in sensual lusts,
if not in open profaneness.
But although we cannot for conscience sake join with them in their worship,
because we do in heart believe it is not right;
yet do we not (as he saith) cast off all worship and ordinances of God;
for we are sought out by the Father to worship Him in Spirit and in Truth,
(John 4:21-24) where we have found acceptance with God at what time soever,
and wheresoever we have been gathered together to wait upon him,
whether by day or in the evening, as the true Christians were,
when Paul continued his speech till midnight;
and sometimes we meet in a believer`'s house, upper chamber, field or barn,
as the ancient Christians did, who were gathered out of the world,
and separated from the Jews`' worldly sanctuary, and heathen`'s temples,
and yet were not of those that did "`creep into houses, and separate themselves, sensual,
not having the spirit,`" no more than we are,
though by such as accused them and persecuted them,
we have all manner of evil said against us falsely; and are persecuted as they were,
because for conscience-sake we cannot forsake the assembling of ourselves together,
as the manner of some is, but must meet together in the name of the Lord Jesus Christ,
(Heb. 10:25; Matt. 18:20) that we may enjoy his presence,
and comfort and edify one another in love.

[.blurb]
=== Concerning Ministers and their Maintenance

We say--how shall they preach and declare unto us the mind of God,
except they be chosen and sent of God?
(Rom. 10:14-15) And therefore we refuse to hear such as run and are not sent of God;
but for lucre and honour`'s sake,
(1 Pet. 5:2-3) take upon themselves to preach and speak of those things,
which by wisdom, human learning, and natural parts, they can never understand,
but "`darken counsel by words without knowledge;`" for the generality of them say,
that revelation is ceased, and that they have no vision in these days;
therefore we wonder not, that they and their people are so ignorant of God;
"`For no man knoweth the Father but the Son,
and he to whomsoever the Son will reveal him.`"
(Matt. 11:27)

Neither do we wonder why so many perish for want of true knowledge,
(though we greatly mourn to see it so;) for we know,
that when the teachers have no vision,
(as by their own confession they have not) the people perish.
Therefore, we dare not trust our souls with them,
though people that have itching ears do choose them for their pastors;
or though such bishops as exercise lordship and dominion over people`'s consciences,
impose them upon us.
For the Lord Jesus Christ is the Bishop of our souls,
(1 Peter 2:25) and he hath given us pastors according to his own heart,
who feed us with knowledge and understanding,
(Jeremiah 3:15) and lead us to living springs, and a fold of rest.
These we do dearly own and esteem for their work`'s sake;
they are Christ`'s true ministers, whom he hath sent,
and furnisheth and qualifieth by the gift of his Spirit, for the work of the ministry;
who without money or price, have freely received the word of reconciliation,
and freely preach it; coveting no man`'s silver, nor his gold, nor his corn, nor his hay,
nor his wool, nor his lambs; but cast their whole care upon the Lord who hath sent them;
and plough in hope, plant in hope, and thresh in hope,
that the ground may be broken up that hath brought forth briars and thorns,
and the true seed grow to a blade, an ear, and corn in the ear,
and then be separated from the chaff.
Such as these shall never be frustrate of their hope,
nor want necessary things pertaining to this life,
though they know not today what they shall have tomorrow.
(Matt. 6:25,27) I know that they who preach the Gospel shall never want a livelihood:
but He that hath sent them will take care to provide them a morsel in due season:
and such as these (though some of them have no more certain dwelling-place than
the ancient ministers of Christ had) are made manifest in our consciences,
and so far approved and owned as the ministers of Christ.

But the company of priests who are made by man`'s will,
have the law of a carnal commandment to uphold their ministry and maintenance,
and claim tithes of men`'s increase,--a thing not mentioned by the ancient christians.
And when for pure conscience-sake (and not for any corrupt ends,
as our manifold sufferings may evince) we cannot
uphold that Jewish custom and antichristian practice,
which hath been introduced in the dark night of popery, then do they sue us at law,
cast us into prison, and make spoil of our goods,
ordinarily the treble value of what they demand,
but sometimes amounting to the treble treble value of what they said was due;
which hath brought such a blot on them as shall never be wiped off;
and manifests them to be such as Peter said,
had "`hearts exercised with covetous practices;`" and such
"`grievous wolves`" as Paul said should come,
"`not sparing the flock;`" therefore we turn from them to the Chief Shepherd,
who hath redeemed us from being a prey to them.

[.blurb]
=== Concerning Women`'s Speaking

That daughters did prophesy in the congregation of God`'s ancient people, is evident;
for to Israel God spoke by Miriam, in the days of Moses; and again,
he spoke by Deborah to Israel, and judged them by the words of her mouth,
who sat under the palm-tree for many years, in the days of Barak.
And Joel said that, when God poured forth his Spirit, daughters should prophesy,
as well as sons;
(Joel 2:28-29) and one man had four daughters that
were prophetesses in the apostle`'s days;
(Acts 21:9) and divers women were helpers of the apostles in the work of the ministry,
as is both evident in the Acts of the Apostles, and in the Epistles,
where Paul also gave rules how they should prophesy, saying,
that "`every woman praying or prophesying, with her head uncovered,
dishonoureth her head: (1 Cor. 11:5) and where should the woman prophesy,
if not in the church?
Seeing the same apostle commendeth that gift above many for edification of the Church,
and saith, that "`Prophecy serveth not for them that believe not,
but for them that believe,`" it is evident,
that although he did not permit a woman to speak in the church,
nor usurp authority over the man, yet he did permit the Spirit of God to speak in women,
as we do; for we dare not forbid it, lest in so doing we should quench the Spirit,
which they have the promise of, as well as men.

[.blurb]
=== Concerning Superiors and Inferiors, and the Honour that is Due from the One to the Other: also Concerning Titles, Courtesy, and Salutation by the Way

In the beginning God "`created all nations of one blood to dwell upon
the face of the whole earth,`" that they might glorify his name,
and live innocently in love one to another;
but afterwards the seed of the serpent was received into man`'s heart,
that naturally inclines him to pride, violence, and all other foul enormities.
We are persuaded that by God`'s ordinance some have a superiority given
them for the punishment of evil doers and a praise to them that do well:
as,
the husband over the wife--the parents over the children,--the king over his subjects,
and the rulers over the people, in their several countries and liberties;
also masters over their servants, and mistresses over their handmaids:
and to these superiors we are persuaded by the Lord,
that there is an honour due from inferiors.

And in his Light we see and know that it consists not in vain ceremonies,
wherein there is no service to God or man; such as uncovering the head,
and bowing the knee: and therefore the example of such good men as Jacob,
who bowed to Esau, and Abraham, who bowed to the Hivites, a heathen nation,
will not warrant us to bow down and worship creatures against our consciences,
any more than other of their practices, now generally allowed to be erroneous,
will warrant us to do the like.
Neither doth due honour consist in vain compliments,
which for the most part are frivolous, feigned and hypocritical,
but in diligent and speedy obedience to all the just commands of superiors,
and in patient suffering under those that are unjust;
for those children do most honour their parents, and those subjects their prince,
who are of good behaviour, temperate, sober, wise, and humble,
who readily obey all their just commands,
and patiently suffer chastisement for refusing to obey that which is unjust.
This honour which is due from all inferiors to superiors,
we do not at all teach any to withhold;
and therefore we can with confidence appeal to the
consciences of our very enemies and accusers,
that we design to level nothing but sin, wherein we are justified by the Lord,
who will bring down the loftiness of man, and bow the haughtiness of his spirit,
and exalt himself alone, as in the beginning; for he is worthy.

Because he alone is the Lord, therefore we cannot call any man the Lord besides him;
though we know in the world there are lords many, and one of them we can call a lord,
but not the lord, nor my lord, because God is the Lord,
and there is none our Lord besides him.
In like manner, we can call some ladies, as the ancient Christians did;
yet not any Elect lady, but such whose election we know:
and why should we call any my lady, unless by marriage-union we have interest in them?
And for such as do any way demonstrate to us,
that they are of a noble and honourable spirit,
we shall not hesitate to call them noble or honourable, as Paul did Festus and others;
but we see they are most degenerate from true nobility and christian faith
(and so least deserve it) who do so eagerly seek honour one of another;
for to such Christ said, "`How can ye believe?`"
(John 5:44) rendering that as the reason of their unbelief.

And further, a king we can call by that title, and a father by that title,
and those that are our masters according to the flesh, by that title,
and every one in their place, by such titles as are neither false, flattering,
nor blasphemous; but such titles as are so, we cannot give to any,
for in so doing God would soon take us away.
(Job 32:21-22)

And for courteousness to all, both to superiors and to equals--where is the man or woman,
among all our neighbours, that hath been conversant with us, that can justly accuse us,
and show wherein we have not been courteous and amiable to them?
unless they count it discourteous to reprove for evil,
or not to worship and adore their persons as God, by uncovering the head,
and bowing the knee, which is usual when we approach to him in prayer:
and if withholding that from men be esteemed discourtesy,
let them show where God commanded it, or the ancient christians gave it,
seeing Mordecai (Esther 3:5) refused to give it, when required by a king, to Hainan,
a person of great place, though thereby he not only endangered his own life,
but the life of all the Jews throughout the provinces of Babylon.

And further,
if any judge us not courteous for speaking to them
in that language which God and nature hath appointed,
for distinction betwixt singular and plural numbers, viz., thou to a single person,
whether superior or inferior, and you to many,
then let them come and show the contrary to be a courtesy
commanded or commended by God or any of his saints.
And for not using divers other vain customs and manners of the nation in which we live,
I know we are accused of discourtesy and unmannerliness;
as--for not using the drunkard`'s custom and manner, in drinking one to another,
and pledging those that drink to us--for not using
the ignorant peoples`' customs and manners,
in saying, God-even and God-morrow, when we meet them;
and other things wherein people will not be held
guiltless for taking God`'s name in vain,
and using such words as corrupt good manners;
and therefore we cannot be conformable to them, though for it we suffer reproach.

But in all things wherein we may do any service to God or our neighbours,
where is the man that can say we refuse, or are discourteous, or unneighbourly?
And from whom have we withholden either rents, debts, or other customs,
which in righteous reason and conscience are due?
But surely our blameless conversation in these things,
may by this time have stopped the evil surmisings and gainsayings of our adversaries;
and therefore I shall commit our cause to the Lord, who, I am persuaded,
will yet more and more plead it,
and clear the innocency of those that love him by the rising of his Light,
which is a faithful witness in all consciences,
and by which we desire more and more to be made manifest.

And therefore we desire that all sober people may take heed
of receiving false informations against us,
whereby both they and we may be wronged;
but rather first hear what we declare and hold forth, and then judge of it and us,
according to the Light of the Spirit which God gives them,
and according to the Scriptures of Truth.
And if by true trial they find we hold forth or practise that which is contrary to either,
let them avoid it;
for on no man`'s conscience would we impose anything which he cannot freely receive,
no more than we would be imposed upon; for it is our principle, "`to do unto all men,
even as we would be done unto.`"

[.signed-section-context-close]
Written the 24th day of the Second Month, 1662.

--
