== Chapter VIII.

John Whitehead`'s second imprisonment at Lincoln--Letter to Judge Windham--Epistle "`for
the Vineyard of the Lord`"--Address to professors of the Truth who are turned aside.

+++[+++About five months after John Whitehead`'s release from this last imprisonment,
he became again exposed to the persecuting spirit of the age.
For refusing to swear,
he was a second time committed to Lincoln Castle:--so fruitful
a source of injustice and oppression was the law respecting oaths,
as then administered.
His narrative of the transactions relative to this
portion of his sufferings for conscience sake,
is as follows:]

Upon the 8th of the Fifth Month, 1662,
upon suspicion that I had met together with some sober people for the worship of God,
I was apprehended by John Clarke, constable of Hannah-cum-Hagnaby,
in the parts of Lindsey and county of Lincoln;
and by virtue of a warrant subscribed by Martin Litster,
carried to the next justice of the peace, called William Woolley,
to answer to such things as should be objected against me;
who after having heard me and my accusers face to face,
confessed that he heard nothing charged against me worthy of bonds,
and therefore refused to commit me.
But either fearing the displeasure of Martin Litster, or willing to do him a pleasure,
he advised the constable to carry me before him, which accordingly he did the next day.
Being come before him, he examined my accusers, one of whom was a priest;
but finding that nothing could be laid to my charge
which might give sufficient ground to commit me,
he sought to ensnare me in my words,
and to find occasion against me concerning the worship of my God;
but the innocency and wisdom wherewith I was clothed, prevented him,
so that be could find none.

Yet being resolved I should either go to prison or bow to his will,
he took pains to go to another justice, called John Boswell,
and caused me to be brought after him before those two,
who joined together and examined me.
I freely confessed to them that I came into these parts in love to visit my friends,
and did sometimes speak unto them words of truth according to the Scriptures of Truth:
whereat they conceived so great offence, that they thought me worthy of bonds.
I bade them consider that persecutors were ever blind,
and thought they did God good service when they killed his children;
and I told them that I did believe the more we were persecuted,
and suffered for righteousness sake, the more we should increase and grow:
whereat Martin Litster was much offended.
That they might be sure to have matter enough against me,
they asked me if I would take the oath of allegiance.
But they had neither the oath, statute-book, nor Bible that I saw:
so that they did not at all tender it to me; yet I told them,
that for conscience sake toward God,
(and not in any contempt or disaffection to the king
or his authority,) I could not take any oath;
whereupon I was sent to prison, and kept there till the general jail delivery,
by virtue of a mittimus, whereof this is a true copy:

To the Keeper of His Majesty`'s Jail at the Castle of Lincoln,
or to his Deputy or Deputies There.

Lincoln Lindsey.

Foreasmuch as John Whitehead of Owstwick, in the county of York,
was upon complaint brought before us this day, by warrant,
for upholding private meetings contrary to an act of Parliament, made and provided;
and being tendered the Oath of Allegiance by us,
being two of his Majesty`'s justices of the peace for the said parts and county,
according to the statute in that case made and provided,
did refuse to take the said oath.
These are therefore in the King`'s Majesty`'s name to charge and command you,
immediately upon the receipt hereof, to receive him, the said John Whitehead,
into your said jail; and him there safely keep without bail or mainprize,
until the next general jail delivery to be holden at the said Castle of Lincoln,
for the said county: and hereof you are not to fail,
as you will answer the contrary at your perils.

Given under our hands and seals, this ninth day of July,
in the fourteenth year of his Majesty`'s reign, Anno Bom.
1662.

Martin Litster.

John Boswell.

At the Assizes, or general jail delivery,
begun at Lincoln the 19th day of the month called July, Woodham Windham sat as judge;
and in his charge uttered many hard sayings,
which reflected on those whom I knew to be innocent and harmless men, with threatenings,
that we who refused to swear should be fined and banished.
Whereupon I knowing that myself with William Morris, William Bancoft, and John Cleasby,
who were fetched out of their own houses and committed
to prison because they could not swear,
were all in his calendar,
expected that we should have been called and proceeded against as the law directs;
but justice was both deferred and delayed contrary to Magna Charta, cap.
i.; for we were not called at all, nor brought to answer,
neither did any accusers come in to charge us with the breach of any law of God or man:
yet did the above-named judge order us (whom he neither saw nor heard
speak for ourselves) to lie in prison till the next Quarter Sessions,
contrary to justice and equity, and contrary to the express statute of the 28th Edw.
III. cap.
3, where it is enacted, "`That no man is to be imprisoned, disinherited, or put to death,
without being heard what he can say for himself.`"
But surely he was afraid that the truth of our cause should appear before the country,
in whose presence he had sought to render us odious;
whereat I gave him a hint in a letter, a true copy of which follows:--

Friend,--

I write unto thee in the name of the God of Heaven,
who created thee and all mankind of one blood to dwell upon the face of the whole earth,
that thou mayst understand he hath not given power to one Christian man,
of what estate or degree soever, to be lord over the faith and conscience of another;
and much less to destroy one another about faith and worship.
Surely thou wast raised up into the seat of judgment for a praise to them that do well,
and not to asperse the innocent,
nor to render harmless people odious in the face of their country;
to whose consciences we can appeal, that our conversations have been,
and still are blameless amongst them;
and that they have not any thing justly to charge us with,
but that which concerns the law and worship of our God.
For when do any of us come into your courts for witchcraft, murder, theft, perjury,
or other matter of wrong and wicked lewdness, as do +++[+++many of]
the reputed members of the Church of England; which, thou saidst,
is now pestered with heretics, that must be put forth,
as were the lepers out of the camp of Israel.

But before thou, and those that be in authority with thee, proceed to that work,
consider,--have you received an infallible spirit
to judge what is truth and what is heresy?
And have you an angelical understanding to discern between the tares and wheat?
If not, then may you pluck up the one instead of the other;
and how easily may you call evil good and good evil,
as the Jews did in the days of the ancient prophets and apostles, who judged Elias,
the man of God, to be a troubler of Israel; and Paul,
the minister of the gospel of peace, a mover of sedition throughout the world;
and Christ Jesus, the prince of life, they said was a blasphemer,
and by their law ought to die;
and so may you render yourselves liable to God`'s just hand of vengeance, as they did;
for as David said in a certain psalm,
"`He ordaineth his arrows against the persecutors.`"

Therefore in tender love I say again, consider,
all you that would compel us to a conformity in worship,--Is
your worship in the infallible spirit of truth;
not differing in matter or manner from the primitive Christian`'s worship?
If this you cannot affirm, and reasonably demonstrate to every man`'s conscience,
then why will you seek to force the conscience to conform to that
which you cannot demonstrate is altogether right and infallible.
But if you say, that you have received an infallible spirit, and in that do worship,
not differing in whole or in part from the primitive Christians;
then do not so uncharitably judge, as to say,
our consciences are not tender but obstinate, if we cannot believe your assertions:
but allow us that liberty which the apostle did not only allow,
but also commend the Bereans for, to search the Scriptures,
whether those things you hold forth be so or no;
because we must give an account for ourselves, and if we do not serve God aright,
it will not excuse us to say, "`our teachers did lead us wrong;
"`for if we follow blind guides, we may justly fall with them into the ditch.

Thou didst further say, that if we be let grow, who deny swearing in any case,
though before a lawful magistrate, human society cannot be continued;
and therefore our principle was exceedingly dangerous.
To which I say,--we are of no other principle,
neither do we hold forth any other thing in that case,
but what our dear Lord and Saviour Jesus Christ, and his Apostle James, did hold forth,
(notwithstanding of old time men might swear by the Lord,
and perform their oaths to him.) But Christ said, "`I say unto you,
swear not at all;`" and the Apostle James, writing to the twelve tribes scattered abroad,
as if he had foreseen that they would stand to justify some swearing,
contrary to the aforesaid precept, (because Moses allowed swearing,
and their forefathers practised it) said, "`Above all things my brethren, swear not;
neither by heaven, nor by earth, nor by any other oath: but let your yea be yea,
and your nay, nay; lest you fall into condemnation.`"
This commandment of the Lord is so plain, that no argument is good against it,
nor yet any law, statute or custom of men;
for they should be consonant to the words of Christ,
seeing he is given to be the Head of all things to his church.

And though he forbad all swearing,
yet did not he subvert all human society any more than we do,
but taught to speak truth every man to his neighbour, and do justly,
as we ever desire to do.
We are willing to suffer the like punishments if
we do bear false witness without an oath,
as if we did forswear ourselves.
And upon these terms might our testimonies be taken without an oath;
and neither the truth suppressed, nor justice obstructed, nor human society destroyed,
which we have and shall in our places ever labour to preserve.
For the Lord God of heaven and earth knows that we are lovers of truth and justice,
and all mankind; and more especially those that inhabit the land of our nativity;
the peace and tranquillity of which we shall ever seek,
though in it we be reproached as factious, and have suffered hard things.
We desire that the Lord may forgive those who wrongfully afflict us,
not knowing what they do.

Even so, O Lord God Almighty,
turn the hearts of all men into the everlasting way of thy Truth,
and heal the breaches of this nation; that in justice, equity, righteousness,
mercy and love one to another, we may become the glory of all nations.
And till the innocency of our hearts appear to them that yet know us not,
strengthen our faith and patience,
that we may meekly suffer what for our trial thou permittest man to do unto us.

Thus have I cleared my conscience in witnessing the truth,
and opening our case in some measure unto thee,
who am a lover of justice and thy soul`'s friend.

J+++.+++ Whitehead.

Lincoln Castle, the 20th day of the Fifth Month, 1662.

This letter was given into the judge`'s hand, and read by him;
yet he would not hear our case, but ordered us to lie in prison till the Sessions,
without rendering any reason for so doing.

+++[+++In the interval between the Assizes and the next following Quarter Sessions,
John Whitehead manifested his love to his fellow-professors,
and his concern for the promotion of the cause of Truth,
by giving forth the two following impressive Epistles.]

For the Vineyard of the Lord of Hosts; to be Read in Their Meetings

The breathings of a prisoner for the Testimony of Jesus,
who in the deep hath seen the afflictions of his people,
and cannot hide His praise who supports them, nor withhold his complaint,
because of the hardness of men`'s hearts;
but cries unto the Lord God of righteous judgment for the deliverance of his own people.

With a few words of exhortation and advice,
given forth as a testimony of my dearest love to the whole seed of God.
Because I cannot otherwise communicate it in this time of my restraint,
I have been the more large, that I may be refreshed with you, and you with me,
in the overflowing Fountain of our Life.

O Vineyard of the Most High,
wherein I have laboured according to the ability which God hath given me,
since the appearing of "`the bright and morning star,`" who hath enlightened the world,
in whose joy I am now at rest.
My peace is as a river, because I hid not my talent in the earth,
nor stood idle in the market-place; but have improved what was given me,
for my Master`'s use, and for the increase and watering of thee his vineyard.
I cannot in any wise forget thee now when trouble is near,
and all the beasts of the field compass thee about,
and with their whole power seek to break down thy hedge, crop off thy leaves,
devour thy fruit, tread under thy tender plants, cut off the flourishing branches,
and make thee as a wilderness.

In the everlasting love of our God I think upon thee,
remembering the kindness of thy youth, and the love of thine espousals,
wherein thou wast betrothed to the Lord with judgment and mercy,
in the day in which thou satest solitary in the wilderness, and hadst none to help.
My heart is broken within me, and doth with thy breathing babes and tender mourners,
whose cry hath reached unto heaven, send forth these breathings;
that in the spirit of supplication we may have fellowship together,
whilst my soul saith unto God, "`Surely thou hast not cast off the beloved of thy soul,
nor sold thy heritage, to be trodden down, for a thing of nought;
neither hast thou given the plants of thine own right hand for a spoil to their enemies.
Shall they then prevail, who come gnashing with their teeth to devour us?
And wilt thou let thy name be blasphemed, wherein thou hast gathered us,
in which we do trust?
For thy presence is yet amongst us,
and thou withholdest not the riches of thy mercy from us, but openest thy treasure to us;
and of thy fulness we have received strength,
else we could not have escaped in the hour of temptation,
nor stood upright in the time of our deep trials.
When thou sawest us weak, thou turnedst not away thy face from us,
but ever hast stretched out thy right hand to uphold us,
and hast helped us with a little help: when we call upon thee,
thou bowest down thine ear to hear,
and givest us also to understand the words of thy mouth.
Why dost thou not as well show thyself unto the world, as to us;
for they understand not thy way,
but because (though thou hast given thy light into the world) they love darkness rather,
and that blinds their eyes, that they know not thee, nor us whom thou hast sent,
and therefore do persecute and seek to root up,
not believing that we are thy pleasant plants.

Although thou hast created us anew in thine own image, and shewed thy light, life, love,
virtue, power, patience, and goodwill towards men, through us, yet do they not consider,
but think they do thee good service when they kill us all the day long.
And when we speak to them in thy name, and would turn them from their envy, anger, pride,
covetousness, murders, thefts, lies, adulteries, fornications, oppressions, injustice,
and the evil of their inventions, unto the Light, wherein thy fulness dwells,
that therein they might walk with thee in newness of life,
they reject our testimony and say we would delude them.

And when we declare thy righteousness and show thy judgments at hand,
because transgressions are multiplied and iniquity drunk up as water,
they harden their hearts against us and mock at fear,
neither do they prepare to turn unto thee; but for our love in warning them,
they give us the water of affliction to drink.
And when we call them who are yet wandering with a heart panting
for living water (but being gone astray from thy ways,
do drink of the whore`'s cup, or, at best,
of that water which men have fouled with their feet,) and say,
"`Turn ye again to the Lord, and defile not yourselves with the inventions of men,
neither touch any unclean thing; but come forth and be ye separate,
and our God will be a Father unto you,
and you shall be his children,`" then they reproach us as factious,
and as sowers of sedition.
But if any do lay it to heart, and believe our testimony and return,
they meet them first with flatteries, then with threats and cruelties, which they spread,
as the snares on Mizpah, for their feet; like the chief Priests,
Pharisees and Lawyers of old, who would neither enter into the kingdom themselves,
nor suffer those that were entering to go in.

And when we are gathered in thy name, and do silently wait to feel thy power,
that in it we may edify one another,
and drink at the Fountain of Life which thou hast opened unto us,
without reverence to thy name they come upon us with open violence to devour thy lambs,
merely for drinking at the Fountain: yea, their stroke upon us is very cruel,
because we love thy precepts and cannot derogate from the glory of thy verity,
who hast made our yea, yea, and our nay, nay; and said unto us by thy Son since the law,
"`Swear not at all.`"
And though we have given our cheeks to the smiter, our bodies to prison,
and exposed our goods to the spoiler,
and patiently borne many other grievous sufferings for the Truth`'s sake,
whereof thou hast made us witnesses,
yet will they not believe those things which thou hast spoken by us:
and what have we more with which to seal the testimony that thou hast given us?
unless thou wilt suffer the whore to drink more of the blood of thy saints
before thou bring thy long and often-threatened judgments upon her,
who yet fears them not, but saith, "`I sit a queen, and am no widow,
neither shall I see any sorrow.`"
And by what means wilt thou plead with Babylon, who saith she is the lady of kingdoms?
Or who shall persuade men to fly out from her, that they perish not in their plagues?
for they are mad upon her idols, mock thy messengers,
and shamefully entreat and stone those whom thou hast sent to forewarn them,
that they may escape the wrath to come.

Yet with thee is mercy and forgiveness; and I know thou wouldst not their destruction,
but rather that they may turn and live.
Therefore hear my complaint, and bow thine ear to my request; for I groan within myself,
and my spirit breathes that thou mayst arise in thy mighty power,
and speak by thy righteous judgments, that men may fear before thee,
and the nations be persuaded to come to thy light,
and kings to the brightness of thy rising.
Let thy right hand rend the veil from off all hearts,
that thy salvation may be showed openly, and Satan trodden under foot;
for who else is sufficient for these things?
But in the day of indignation, O Lord, remember thine heritage,
and let not thy Vineyard be rooted up, but spare thy people,
and cause thy tender plants to grow: chain the dragon,
and let the earth drink up the floods that would hinder
thy spouse from returning out of the wilderness,
where her place hath been in the long, dark night of apostasy.
But since the dawning of the day, thou hast said unto her that sat solitary,
"`I am the husband of thy youth, therefore walk with me;
and I will not leave thee nor forsake thee, but lead thee unto the mountain of my house;
and my banner over thee shall be love;`" and herewith thou hast allured her,
and she followeth hard after thee.

But now, O Lord, our Shepherd, we are compassed about with adversaries,
and grievous wolves are gathered to prey upon thy lambs; therefore abide thou with us,
and break their teeth, O God, that thy flock may not be meat for them.
For our expectation is from thee alone, and we have not made flesh our arm,
because our hope is in thee:
neither tribulations nor afflictions can separate us from thee,
for we have appealed unto thy righteousness,
who searchest the hearts and triest the reins of all men,
that thou mayst give judgment between us and them who afflict us.

And if thou hast not sent us and commanded us to speak,
or if in heart we be not innocent towards men,
and no way guilty of doing or intending those evils wherewith they charge us,
then let our hearts fail, and confusion cover us before them in the day of our trial.
But, and if thou hast sent us, and commanded us to speak,
and by thy own power begotten us into an innocent life, then open thou our lips,
and let the words of thy mouth break forth through
us and stick in the hearts of our enemies;
that they may be pricked, like the persecutors of old,
and not have ability to resist the spirit and wisdom by which thou leadest us.
For though we ourselves know that we are of thee,
yet do we patiently wait till thou decide the controversy,
and in the sight of all men show who are thy people.
Yet can I not cease to breathe,
that thou mayst shorten these days of trouble for thy elect`'s sake,
in whom thy soul delighteth;
that no more may be laid upon thy little ones than they can bear, lest they faint,
and their adversaries triumph, and say, "`Where is now the God in whom they trusted?`"
O let them know that thou art near,
and dost hear the cry of the oppressed! and upon
the glory of thy Name let there be a defence;
and so keep us in it, to the end that it may never be dishonoured.

Now having refreshed my full heart,
in spreading our cause before the Lord--O ye his people! bear with me a little,
and let your ears be inclined to hear a few things which concern your peace.
For, because I love you, I cannot withhold from you that it is signified unto me,
that whilst you are beset with adversaries on every side,
the enemy will bestir himself with all subtlety and
violence to make a breach amongst you,
and also will tempt you to everything whereby he may weaken you,
and let your adversaries in upon you.
But he shall not be able to effect his purpose whilst you all,
in that faith which worketh by love, meekness, and gentleness, do hold the one Head,
which is Christ the Light, and not the planters nor the waterers.
For him we preached, and in him we have believed,
who is the author of eternal salvation from sin,
and the perfecter of man`'s redemption up to God.
And you are witnesses that we have not preached up ourselves,
neither laboured to set up him that planteth, nor him that watereth,
as any thing in comparison of the precious Truth of God, for which we now suffer.
But in plainness and sincerity, not with wisdom of words,
but in the demonstration of the Spirit, we have manifested the life and power of God;
that ye may know, believe, and be guided by it in yourselves,
and so inherit rest and peace with God, and not always stand afar off,
in the expectation of somewhat to come.
This is an unsettled state,
wherein they that stand may easily be deceived with swelling words, or good pretences,
wherewith the strange woman^
footnote:[The false church.]
(whose ways are moveable,) decketh herself,
lest those whom she seeks to catch in her snare, should ponder the path of life,
and see that her ways lead to the chambers of death,
and that her steps take hold on hell.

But dearly beloved friends and brethren, seeing we know that the Son of God is come,
by an inward feeling of his presence in spirit,
which hath given us an understanding that is true, and we look not for another,
but are rooted and grounded in him, let us hold fast our confidence,
and faithfully follow him, and patiently endure the cross,
that we may ever be his disciples, who is a quickening Spirit, and doth dwell in us.
Then shall we no more wander amongst briars and thorns,
but feed amongst the lilies of the valley, and drink of the water of life.

But, Friends,
because all of you that are convinced are not yet come into the savoury life,
to discern of things that differ,
you must take heed of presuming to judge of things that are beyond your measure.
For your principal strength and safety is to be still,
and to wait in the light of the Spirit within,
that both your faith and wisdom from above may be increased;
and that will open you more and more to receive instruction,
but will never let you slight nor reject the Spirit`'s testimony in the elders and brethren,
whom God did use as instruments to turn you unto himself,
and who still in the same love watch over your souls--neither shall you despise prophesying,
nor quench the Spirit that speaks in the mouth of babes, who are of stammering lips;
but as friends of the Bridegroom, you will rejoice to hear his voice in any instrument,
by whom, or to whomsoever he speaks.
But take diligent heed, lest you set up any instrument above its place,
or give unto it any part of the glory which is due unto Him that useth it,
lest thereby ye kindle his wrath, and cause jealousy to burn like a fire.
For if his glory be given to, and received by, the most precious instrument in his hand,
He will cast it away from him;
and suffer it to be trodden under foot as the mire of the streets.
Therefore be tender of one another`'s preservation;
and let all your affections be guided with justice, equity, and moderation,
so shall you never puff up any above, nor cast down any below their measure,
which doth much tend to preserve the body in the unity of the Spirit, and bonds of peace.

And you that are as children in simplicity, wait,
that also in understanding ye may become men.
Take heed of being so affected with simplicity, as to despise or hate knowledge;
like those to whom wisdom cried and understanding uttered her voice,
and they would not hear; who stood conceited in ignorance,
till calamity came upon them like an armed man.
But always bow down your ears to the instruction of life, and do the will of God;
that ye may understand doctrine, and be of a sound judgment to try spirits and doctrines,
whether they be of God or not.
And in so doing, be sure to keep your own habitations in a measure of Light;
see that neither prejudice nor immoderate affections bear sway in you;
so will you see what stands in unity with the first
principle by which you were turned towards God,
and what is approved in his Light,
and tends to establish you in righteousness--and that you may safely embrace.
But whatsoever jars with the first principle,
and would dissettle and remove you from the Light within,
(wherein that which may be known of God is made manifest,) either
by drawing into uncouth and singular outward observations,^
footnote:[This was probably intended as a warning
against the extravagancies of John Perrot.
He was a man of great natural parts, but not continuing in true humility,
ran out into exorbitant imaginations.
Whilst travelling on a religious visit to several parts of the continent,
he was arrested and examined before the Inquisition at Leghorn, but was set at liberty.
Soon after this,
he was imprisoned at Rome for a considerable time for publicly testifying against idolatry.
Whilst there, he manifested a tendency to fanaticism,
and on his return to England in 1660, caused a schism among Friends,
the effects of which were felt for several years after.
He lapsed into self-exaltation,
and thought himself farther enlightened than his brethren,
maintaining that it was an improper and worldly formality to remove the hat,
when another was engaged in prayer.
Soon after this, he allowed his beard to grow.
He had some followers, but they do not appear to have been numerous.
His conduct subsequently manifested more fully that
he was actuated by the spirit of error;
for he not only assumed gaudy apparel, but gave himself up to sensuality,
and took up the sword; and having obtained a place under government in America,
became a severe exacter of oaths,
and seemed to be principally influenced by mercenary
motives in the exercise of the functions of his office.]
or by promising liberty,
or a greater glory than that which the Light of the
Spirit within hath given us to behold with open face,
as in a glass, and is translating you into; I say,
that which by these things would work discontent in your present measures,
and let you loose from waiting in God`'s fear,
into the comprehension of things above your measures, is dangerous, and to be eschewed:
and if any hold forth such things, they,
as well as such as would draw you back into the rudiments of the world,
speak of themselves, and seek their own glory; but he whom God hath sent,
speaketh the words of God, and seeketh his glory that sent him.

And if contention, strife, wars, or commotions arise in the earth, betwixt man and man,
or people and people where you inhabit,
dwell you in that power which hath redeemed you out of the earth from amongst men,
and that will keep you sensible that you are not your own, but bought with a price,
that you may be unto God a peculiar people:
and therefore you shall not defile yourselves with their contentions,
nor strive nor side with parties who fly to that
sword for refuge by which they may perish.
But we having received and trusted in the sword of the Spirit,
by which we can never perish, let us sit down in that which keeps holy and harmless,
and separate from sinners; so shall his wonderful counsel, who is Prince of peace,
be with us, wherein we may be peace-makers,
and obtain the blessing to be called children of God.

And you who are as yet not much exercised with sufferings,
but are at peace in your dwellings,
none making you afraid--take heed lest at any time you be secure:
for then may the enemy entice you from a sense of God`'s mercy,
to look out at creatures and to set your heart on earthly things;
and then if a trial come suddenly and unexpected, it will be the heavier upon you;
and if, through want of preparation, ye fall under it,
then it will be hard for you to be raised up again to stand faithful unto the end,
wherein your safety and the possession of the crown of life depend.
If you be not constant and faithful in these last trials,
you lose your reward for all that ye have gone through: for,
"`if any do put his hand to the plough, and look back,
my soul hath no pleasure in him,`" saith the Lord.
Therefore, as I would that you should not be dismayed, nor fear the threatenings,
excommunications, fines, and imprisonments,
or any other thing which you may suffer by the wicked hands of mortal men,
so would I that you may both inwardly and outwardly
be prepared to suffer what man can do unto you.
And whilst ye behold the Lord restraining their wrath from breaking out against you,
bear a part with your brethren who are suffering under it;
and God shall reckon it to you in the day of your need.

Finally, dear friends and brethren, be of one mind, and live in peace;
and in the name of the Lord keep your meetings,
that love and life may abound amongst you; and therein faithfully instruct, admonish,
and (if need be) reprove one another.
But let the Spirit judge all things; and with an open,
tender heart receive instruction and reproof one from another;
pondering it in deep silence, and not measuring it in the reasoning part,
for that will grow high and work prejudice against the admonisher and reprover,
if you see not a present cause, or need of such a thing;
and thereby you may both hurt yourselves,
and discourage those that in sincerity sought your good,
whereby they may be caused to lament in silence when
they see you in the like danger again,
and say, "`We called, but they would not hear.`"
Therefore measure and bear all things in the meek, lowly spirit.
And you that are strong and spiritually minded, being come over all these things,
labour to restore and raise up them that fall; comfort the feeble-minded,
and say to him that stands afar off, "`Draw near and walk with us in the light,
and the Lord will also give thee rest.`"

And wait on your ministry,
that ye may preserve that which is gathered in the savoury life,
to shine as lights before men.
For there is a seed sown in this nation and elsewhere,
which begins to bud forth in thousands, who having not seen, yet love;
which gives me sufficient ground to believe that when the winter is past,
and the latter rain comes upon the earth, there shall be a plentiful harvest;
wherein every one that hath been faithful in a little shall reap much,
and give thanks unto God who hath blessed the seed sown;
who will send forth such as in the furnace of affliction he hath fitted for his use,
faithfully to labour:
that every eye may be opened to see that the common salvation which God
hath prepared for all people is the Light that doth enlighten the Gentiles,
and the glory of Israel.

John Whitehead.

Written in Lincoln Castle, the 24th day of the Sixth Month, 1662.

The Case of such Professors as Have Known the Way of Truth,
and are Turned Aside from its Holy Testimony, to Save Themselves, Opened and Lamented:
With some Wholesome Warnings and Admonitions,
Tending to Restore and Turn them Again to the Lord, That They may be Saved by Him,
Both from the Evil and Punishment of Sin.

Dear Hearts,--

What lamentation shall I take up for you,--wherewith shall I sufficiently
bemoan you who were visited in the springing forth of God`'s day,
and have thereby seen the way of Truth,
and felt somewhat of that power of God which once made your hearts tender,
and caused the strong man to bow himself;
so that you began to be pliable unto God`'s will, and to love his precepts!
But now you are turned from the Light,
and wandered out of that way which you know to be true,
and have lost the feeling of the power of God and have your
hearts hardened by the deceitfulness of sin,
and overcharged with the cares of this life, and your wills at liberty,
as a bullock unaccustomed to the yoke, and running on contrary to that of God in you.
I say again, what lamentation shall I take up for you!
Surely if my head were waters and my eyes a fountain of tears,
I could not sufficiently bemoan you; for I plainly see,
that destruction and misery are in your ways,
because the Lord`'s good Spirit is daily grieved with you,
and his soul takes no pleasure in you that draw back from the paths of Life and Truth.

And they to whom you fly, and under whose shadow you seek to shelter yourselves,
cannot at all deliver themselves nor you from the wrath to come
upon all that are not obedient to the Gospel of Christ:
neither do they at all care for you.
Though they flatter with their lips, yet have they an eye to see,
that you who are treacherous to your own principles,
will easily become treacherous to them--so that your condition is exceedingly sad:
for in your present state you are an abomination to God, to his saints and angels,
a scorn to fools,
and a hissing and derision to the subtle adversary who hath caught you in his snare.

Therefore consider your estate;
and let me a little expostulate with you in the name of
the God of Heaven--What can be done more for a people,
that he hath not done, and been ready to do for you?
Hath not line been upon line, and precept upon precept, here a little and there a little,
that ye might understand and lay it to heart?
Have not God`'s servants and prophets been frequently sent amongst you,
to whom God hath given witness by his own Light in your consciences?
Moreover, hath he not smitten you with the word of his own mouth,
and caused you to feel and dread his power?
Hath he not also come in the spirit of meekness,
and with yearning bowels of love besought you to return,
when you began to stray from him?
Hath he not also been ready to forgive your trespasses, and heal your backslidings;
and can you justly charge him and his servants with blame if you perish?
Did not he once appear unto you altogether lovely?
And with him there is no alteration nor shadow of changing.
Oh then, consider what hath blinded your eyes, and why you turn aside from following him!
Do you not therein despise your birthright, as Esau, and betray the Just as Judas did?

Oh! woe is me for you that have let go eternal life,
and laid hold on this present world! for you have made a miserable exchange;
and the earth which you think to save you, is reserved unto fire;
and that which pertaineth thereunto and can delight in it, shall be burnt up.
When the terrors of death everlasting compass you about, where will you hide yourselves,
who, as Cain, have murdered the Just,
and must be banished from the presence of God forever?
And what good will all the earthly treasures wherein you have delighted,
do you in that day?
Shall not all the world`'s friendship then have an end?
And one tempter to wickedness shall curse another,
because they have been the occasion of each other`'s
misery--out of which gold cannot redeem;
nor can all the world`'s riches, glory and power, save one soul.

Therefore be ye awakened, all ye who have not yet sinned unto death;
but through distrust, slavish fear, or the lusts of your own flesh, are veiled,
and either stand still, or are turned away backward.
For you may be renewed to repentance,
who have any sense of your out-running or grievous sin in backsliding;
if you be at all smitten, and grieve for the same, there is hope concerning you.
Therefore fear the rod, and Him who hath appointed it:
and if there remain any bowels of tenderness or any spark of love to God,
if it be but so much as makes you sigh in secret for want of him,
then arise and come away, and linger no longer in darkness where Satan hath dominion,
lest you murder the Just, and so join to idols.
For why should you wander in the blackness of the night,
till in the end your steps take hold on hell, out of which there is no redemption!
Therefore I say again--be ye awakened, and do not trifle away the precious time,
lest the door of mercy be quite shut against you;
and take heed of giving any more way to an evil heart of unbelief, which saith,
"`The Lord delays his coming,`" and thinks him slack in fulfilling his promises.
For that, with the worldly wisdom wherewith the serpent mixes,
may be the ground of your apostasy from the Life,
and the principal chain wherewith man is held from returning to God.

Because unbelief binders you from beholding his most glorious power,
and from enjoying the most precious treasures of his kingdom:
and then the worldly wisdom not being capable of discerning the invisible things of God,
which he hath ordained to our glory, draws down the mind to save self,
and to lay hold on this present world; which ye can in no wise please,
and have its love and friendship, but you displease God,
and lose his love and friendship.
Therefore seeing ye cannot serve God and Mammon,
come forth and be ye separate from all idolatry, profaneness, and will-worship.
And if you are pursued with persecutions and reproaches, look not at them;
for such light afflictions are but for a moment,
and do work for us a far more weighty crown of glory;
which God will certainly give unto all that be faithful unto the end.
But it is a fearful thing to fall into the hands of the living and long-provoked God,
if you willfully disobey his Light in your own consciences, and rebelliously forsake him;
because he hath power to cast into hell, where the wicked and all they that forget God,
shall be tormented perpetually.

What can I say more unto you!
But with yearning bowels of love, exhort you to search and try your ways,
and turn again to the Lord, who wills not your destruction;
but delights rather to pardon than punish you, because he loves you as his creatures.
And as you return to the Lord, when you see briars and thorns, grievous wolves,
and hungry eagles in your way to devour you, be not dismayed at all;
but with purpose of heart cleave unto the Lord, who is a consuming fire,
and he will make your way through them,
and you shall see all that stands in opposition to you, vanish as a shadow,
in God`'s work and way.
For the end of all things is at hand,
and the kingdoms of this world shall become the kingdoms of our God, and of his Christ;
and they who have suffered with him, shall reign with him,
saith the Spirit of the prophets; but they that have denied him before men,
shall be denied by him at his appearing in the glory of his Father,
and the holy angels with him,
to give a reward to every man according as their works shall be.
Therefore consider, that if you for earthly things deny the Truth of God,
how will it grieve you in that day,
to stand afar off and see the Lord`'s innocent people
(who have not loved their lives unto death,
but freely given up all, that they might overcome,
through the blood of the Lamb and the word of their testimony)
receive a kingdom and a crown which fades not away,
whilst you are bereaved of all that wherein, you delighted,
and are compassed about with terror and covered with shame and contempt,
which is the just reward of all who deny the Lord that bought them;
who have put him to open shame by distrusting his power,
and turning from him in the sight of his enemies.

These things bearing a weight upon my spirit,
and because I do both desire to be clear of the blood of all men,
and do entirely love their souls, I have in this manner communicated them,
because I am a sufferer in outward bonds,
amongst the Lord`'s valiant and faithful people, called Quakers;
who though we have been despised and reproached by the wise professors of this generation,
yet are not of them that draw back to perdition, but press on to the end of our race:
wherein I say, Follow us, as we follow Christ.

John Whitehead.

Lincoln Castle, the 16th day of the Seventh Month 1662.

=== Chapter IX.

Proceedings at the Quarter Sessions at Louth,--John Whitehead and
other Friends remanded to prison--Epistle to Friends at Whitby,
etc.--Two Letters to the Justices--Two Letters to Judge Wyndham--Sufferings of many
Friends in Lincolnshire--Letter from Twelve Friends to the Justices at Spital--Letter
from John Whitehead to the Justices at Louth--Discharged from Prison.

Before the Quarter Session following, William Bancoft was released;
some of the justices being moved hereunto by the imbecility and weakness of his old age;
and at the Petty Sessions for the parts of Kesteven, William Morris was released:
but John Cleasby and myself were carried to the General Sessions held at Louth,
the 7th of Eighth Month.

+++[+++Previous to their appearing before the court,
John Whitehead and John Cleasby addressed a letter to the justices,
remonstrating against the injustice of continuing
them in prison without allowing them a fair hearing;
and in the character of "`peaceable men, who fear the Lord and love justice,
truth and righteousness,`" pleaded for moderation and equity.
John Whitehead then proceeds:]

When we were brought before their judgment seat,
no one appeared to accuse us of the breach of any law of God or man;
but they sought how they might ensnare us concerning the law of our God.
We had already endured a long and illegal imprisonment, as we manifested in open court;
yet they made one injury done unto us the foundation of another,
and tendered to us the oath of allegiance, which we could not in conscience take.
We alleged, that that oath was principally, if not wholly, intended for popish recusants,
as was manifest by the reason of the law,
which chiefly was this:--The natural born subjects of this
realm did withdraw their due allegiance from the king,
and did yield obedience to a foreign power;
and upon that transgression was the law added.
But we give no such occasion for that law to be executed against us;
for we yield all due obedience to our temporal prince,
and utterly deny all foreign power;
therefore according to a rule of their own in the construction of laws,
the reason of the law ceasing, the law ought also to cease,
and not to be executed upon us.

But notwithstanding this, and many other reasons which we gave,
why they should not tender that oath to us, they urged us to answer,
whether we would take it or no: to which we replied,
(there being many present that professed to be ministers
of the Gospel,) "`if you or they can convince us,
that it is lawful for us to swear at all,
we shall not refuse to take the oath of allegiance.`"
But they wholly refused to dispute the matter with us,
and persisted in urging us to take the oath.
Whereupon we replied, "`That we were Christians,
and made conscience of the commands of Christ,
(Matt. 5:34) and therefore in obedience to him, could not swear at all.`"

Then they recorded our denial,
and fined each of us five pounds for refusing to
take an oath contrary to the late Act of Parliament;
which fine they then demanded us to pay in open court.
But we refused to pay it,
because in conscience we knew ourselves to be innocent
from committing any offence against God;
neither against the law of man did we any injury, but what they occasioned.
Whereupon we were withdrawn;
and they expressed that they would levy the said fine upon our goods,
according to the tenor of the said act,
or else that they would after a week`'s time commit us to prison for three months,
according to the express words of the said statute,
which runs thus--"`And for want of such distresses,
or non-payment of the said penalty within one week after such conviction,
that then the said parties so convicted,
shall for the first offence be committed to the common jail
or house of correction for the space of three months.`"

But they then forthwith sent us back to prison by the following
order,--how contrary to law let the wise in heart judge:--

Lincoln Lindsey.

Whereas John Whitehead and John Cleasby were by the Judge`'s order of the last Assize,
sent to this Session; where appearing in open court,
the Oath of Allegiance was severally tendered unto them,
according to an act of this present Parliament, which they obstinately refused to take;
and thereupon a fine of five pounds was imposed upon each of them,
in farther pursuance of the said act, which they also refused to pay,
in great contempt of authority, and of the laws and statutes of this kingdom.
It is therefore ordered by this court,
that the Sheriff of this county shall convey the said John Whitehead
and John Cleasby to his Majesty`'s jail at the Castle of Lincoln,
there to abide until they pay their respective fines, or take the Oath of Allegiance,
according to the said act in that case made and provided.^
footnote:[Here the court ordered contrary to the law,
which directs but to imprison for three months.]

Per curia`'

Ex`' per Johannem Thornton,

Cleric`' Pac`'.

Dated 7th of October, 1662.

+++[+++Soon after this arbitrary re-commitment, John Whitehead wrote the following Epistle:]

To Friends at Whitby, Osmotherley, and in Blackamores, Cleveland, Bishopric, and That Way.

Feeling in my heart that love springing afresh, wherein I was first moved to visit you,
and freely to administer unto you what the Lord freely gave unto me,
I cannot at all be unmindful of you.
Though confined at a great distance from you, yet do I, in that love,
most dearly salute you all,
longing greatly to hear of your welfare and prosperity in the Truth.
And these things do I fervently desire of the Lord for you,
even that the eye of your understanding may be kept clear and open in the Light of God,
to see that exceeding great reward which is before you,
that doth far surmount all that man can do unto you;
and also that both your faith and patience may be daily increased,
that therein you may be steadfast and constant in whatever
God calls you to do or suffer for the precious Truth,
which in much power hath been made known unto you;
and I hope hath had that operation in you,
that you are even prepared for this day of trial; and are so engaged to God,
through that pure fear and love, which he hath put into your hearts,
that ye cannot depart from him.

Therefore to the teachings of that holy anointing, that abideth within you,
I do wholly commit you; exhorting you to take diligent heed thereunto,
because the times are perilous,
and there are now many false spirits gone out into the world,
some of which are transformed as the ministers of righteousness,
which by good words and fair speeches, out of the true power,
deceive the hearts of the simple, and draw them from the true feeling of God,
and of their own states, into airy notions and knowledge,
which doth but puff up and not edify in godliness.
Therefore keep ye low to the pure, weighty seed of God in you,
which cannot bow to any image, nor join to any evil;
that you may with sound judgment measure and weigh all spirits:
and beware of that which is found too light, though excellent in speech,
for it will corrupt and gender to more ungodliness.
But wait you to feel the power of God working in you: and grow in grace,
and in the sense of God`'s love unto you,
wherein he called you out of darkness into his marvellous Light;
that ye may be a holy and peculiar people,
showing forth the virtue of the invisible God who dwelleth in you,
unto all people who have their eyes upon you.
Then shall he be in truth glorified and admired in you,
whose love constrains you to give up to do his will;
and not to love your liberty nor your lives more than Him who hath loved you,
and washed you from your sins with his own precious blood;
whereby He doth also nourish and strengthen you to overcome the wicked one.

Therefore, dear children, abide with Him; and as He hath loved you, so love one another,
and that will draw you to meet often together.
And in the Word and breathings of life, comfort one another, as ye are comforted of God;
so shall I also be comforted and refreshed by you in my bonds,
which I patiently endure for the Truth`'s sake.
For though I was called at the last General Sessions, held for this county,
and gave a good testimony for the Lord,
together with many sound reasons against my unjust imprisonment,
and their unjust proceedings against me, yet equity could not enter;
but contrary to right, I was fined five pounds for refusing to swear, and by their order,
am to lie in prison till payment.
But my time is in the hand of the Lord, who knows how to deliver me when he pleaseth;
to whom I have given up myself, and do rest in his will.

Your friend and brother,

John Whitehead.

I shall be glad to see or hear from any of you as you have freedom,
that I may perfectly know your state, and bear a part with you,
both in sufferings and spiritual rejoicing.

Lincoln Castle, the 25th of the Ninth Month, 1662.

After we had been kept prisoners by the foregoing order,
(which exceeds the rigour of the law,) at the next General Sessions, held at Louth,
the 13th of the Eleventh Month,
(not being permitted to appear in court,) we represented our case to the justices,
by this following writing, which was delivered into their hands:--

For the King`'s Justices of Peace, at the General Sessions, held at Louth: these.

Friends,--You may remember, that we whose names are subscribed,
after we had endured imprisonment a quarter of a year,
did appear at the General Sessions,
held at Louth the 7th day of the month called October,
where we expected to have been discharged, as in equity we ought;
seeing that no accuser appeared to charge us with the breach of any law of God or man;
but instead of that, an oath was tendered to us,
(although there was no occasion for it that we know
of;) for the not taking of which in open court,
although for conscience sake we refused it, we were fined each of us five pounds,
which you know was the rigour of the late Act of Parliament,
by which you proceeded against us;
whereupon we were withdrawn and heard no farther sentence,
expecting that we should at least in a week`'s time have been discharged,
and the fine levied upon our goods, according to the tenor of the said act:
but contrariwise, we were by your order remanded back to prison,
where we have patiently suffered fourteen weeks,
which is more by fourteen days that the law requires, in case the said fine be not paid.
Therefore we having suffered the utmost penalty that the law, upon which you proceeded,
requires for such an offence, we do appeal to your own consciences,
(who are sworn as well not to exceed the law as to execute it,) whether we ought not,
both by law, reason and justice, to be discharged.
But we have by virtue of the said act, demanded our liberty of the jailer, who saith,
he cannot grant it without an order from you.
Therefore we write these things unto you,
that you may review the act and your former order, duly consider our case,
and do thereupon what to law, justice and equity shall appertain,
even as you would be done unto, if our case were your own.
However we remain lovers of justice peace and truth,
and shall ever desire your eternal good.

John Whitehead.

J+++.+++ Cleasby.

Lincoln Castle, the 12th day of the Eleventh Month 1662.

After the receipt of this, some of them acknowledged,
that we having suffered more than the penalty of the law,
ought in all reason to he discharged.
But instead of discharging us they made a new order,
(else their clerk hath grossly abused them and done it upon his own head;) wherein they
have quite mistaken the matter of fact for which they fined us the Sessions before,
and feigned new matter, which was not mentioned in their former order.
It will be seen how their second order, here inserted, clashes with the other;
and shows that they who have no justice nor truth on their side,
have need of good memories, lest they confound themselves in their own doings,
as these have done, who only accord in this,--unjustly to detain us in prison.

Lincoln Lindsey

Whereas at the General Quarter Sessions of the peace, held at Louth,
in the said parts and county, at Michaelmas last,
John Whitehead and John Cleasby appearing at Court,
were then and there by their own confessions convicted
for assembling themselves with others,^
footnote:[Here this order clashes with the other, and falsely accuses us;
for we were neither convicted nor questioned for
meeting together then and there as they say;
for proof whereof, let the reader view their former order.]
under pretence of joining in a religious worship, contrary to an Act of Parliament,
made in the thirteenth and fourteenth years of our sovereign lord the King, that now is;
whereupon a fine of Five Pounds was imposed upon each of them,
which they then refused to pay, or to take the Oath of Allegiance,
severally tendered to them in open court, in great contempt of the laws of this kingdom:
whereupon they were committed to safe custody.
It is therefore ordered this day by the Court,
that the said fine of Five Pounds so set and imposed
upon the said J. Whitehead and J. Cleasby,
shall be remitted,^
footnote:[We having suffered already more than the penalty of the said act,
need not have it remitted, but ought to be discharged without these conditions,
which now they unjustly impose:
seeing that if hereafter we do any thing that the law forbids, it is at our own peril.]
and they released from their imprisonment and all
the penalties mentioned in the said Act,
if they upon sight hereof do repair to some of his Majesty`'s
Justices of the Peace for those parts and county,
and there take the Oath of Allegiance; and also give security for the time to come,
that they and either of them will forbear to meet in any such assembly.
Anything in the former recited Order contained to the contrary notwithstanding.
Dated 13th of January, 1662.

Per`' Cur`'

Thornton.

To the Keeper of his Majesty`'s Jail, of the Castle of Lincoln.

Notwithstanding this pretended discharge,
and that we had suffered more than the law in that case requires,
we could not have our liberty: whereupon we wrote to the justices as follows:--

To William Wray, Robert Christopher, William Fitz Williams, William Woolley,
Isaac Knight, John Bosswell, and to every of them.

Friends,--A copy of your order given forth at your Sessions, held at Louth,
the 13th of this month, we have obtained; whereby it appears, that you,
(or at least some of you,) neither take notice of your own actions,
neither of our afflictions, nor of the law itself,
which you are sworn equally to administer; for in this order you say,
That "`at the Sessions going before, we were convicted by our own confessions,
for assembling ourselves together with others, under pretence of religious worship,
contrary to the late Act of Parliament, etc.`" which is utterly false;
for no such thing was then objected against us,
neither were we at all questioned for meeting together at that Sessions;
neither was there any fine laid upon us upon that account, as this your order affirmeth:
but an oath was tendered unto us;
for the not taking of which we were fined each of us five pounds,
which you ought by law to have levied upon our goods and set us at liberty,
as the judges and other justices of peace have done to others in the like case.
For the very words of the Act run thus.--"`The said respective penalties
to be levied by distress and sale of the parties`' goods so convicted;
and for want of such distress and non-payment of
the said penalty within one week after such conviction,
that then the said parties so convicted, shall, for the first offence,
be committed to the common jail, or house of correction, for the space of three months.`"
But for non-payment of the fine above-said, we have been imprisoned near four months,
though it was the first offence,
and also occasioned by them before whom it was committed.

Therefore your remitting the penalty of the law is needless,
because we have already suffered it, and more;
and therefore ought to be discharged without either of the
conditions that you in this order impose upon us;
whereby you show your tender mercy to be cruelty,
and not only below the mercy of the law, but above the rigour of the law.
For the mercy of the law would have discharged us
upon one of the conditions which you proposed,
as soon as ever we were convicted, before we had suffered any thing;
and the rigour of the law would have discharged us
without either of the conditions that you impose,
seeing we have fulfilled it in suffering.
Therefore consider, how you do by your orders wrong and oppress us,
contrary to all law and reason.
So that we now suffer merely for not obeying your
wills in going to swear and giving bonds,
when there is no occasion for either.
If we should so depart from our principles, as to swear,
and deny our most Christian meetings as you would have us,
then could we also sue such as unjustly detain us;
and take a severe revenge for the false imprisonment,
wherein you have combined to keep us;
for there is nothing keeps us from revenging ourselves,
but that which brings us from swearing,
and to meet together in the name of the Lord Jesus Christ.

Therefore take heed of opposing that principle which
brings us to love and forgive our enemies,
lest you kindle wrath against yourselves, which you have justly deserved.
But the long-suffering of God waits for your repentance,
which we desire may be given you; who do not ask any mercy from you,
but rather justice which hitherto you have denied us;--the Lord lay it not to your charge.

And because we know some of you are learned in the law,
it makes us the more wonder that you should pass such an insignificant, unlawful order,
under the seal of your court, under pretence of a discharge,
which rather tends to straiten than discharge us.
Therefore if you intend to discharge us,
and the clerk you employ doth of his own head detain us, through envy against us,
it becomes you to correct him, and amend the faults whereby your power is abused,
in sending us a free discharge according to law.

John Whitehead.

J+++.+++ Cleasby.

Notwithstanding this letter was received by some of them, they did not lay it to heart,
neither did they consider our affliction so as to let us go free;
though we had more than suffered the law,
yet were we detained by their orders until the Assizes began at Lincoln,
the 19th day of the First Month, called March, 1663, wherein Wadham Windham sat judge,
to whom we with others were returned by the calendar;
and we presented our case to him as followeth.

Friend,--Since we understand that thou hast been for some years a judge in this nation,
and art well acquainted with the good laws and customs of England,
which abhor all arbitrary and illegal proceedings,
we are bold in this manner to represent our case, truly stated, unto thee;
desiring that thou mayst duly consider how we have been dealt with,
and do thereupon what to equity and justice doth appertain.

First,
We do here truly declare that John Whitehead and John Cleasby were
sent to prison before the last Assizes that were holden at Lincoln,
at which we expected to have had a legal trial,
and either to have been discharged or proceeded against as the law directs.
But we were, by order from thee, committed till the next General Sessions,
without trial or hearing; and to Sessions we were carried:
and there appearing on the 7th day of the Month called October,
no accuser appeared face to face to accuse us of any thing.
But the court was pleased to tender us an oath,
although there was no occasion for it that we know of; for the refusing of which,
(although we did it for conscience sake) we were by virtue of the
late Act of Parliament made against us who are called Quakers,
fined each of us five pounds:
and though by law we should have had a week`'s time to have either paid the fine,
or have had the same taken from us by distress,
yet we were forthwith sent to prison by orders from the said Sessions.
After we had suffered the penalty of the law, viz. three months in prison,
we made our address to the said justices for our liberty;
but it hath hitherto been denied us,
though we have lain in prison above five months for that very thing,
for which the law imposes but three months; as by a due examination of our case,
and viewing of their orders, thou mayst perceive.
Therefore we desire that one injury done unto us,
may not be made the foundation of another;
but since we have suffered more than the law requires in that case,
let us either have a free discharge or a fair hearing;
that the cause of our long suffering may be made manifest,
which in justice we are persuaded ought not to be denied us.

Secondly,
That Samuel Davy was taken from a peaceable meeting
by soldiers without any warrant for that place,
and committed to Spalding Bridewell till Sessions,
where he conceives he ought to have been tried for what he was imprisoned.
But contrariwise they tendered him an oath, which he gave no answer to,
because he conceives he ought first to have been cleared of his imprisonment.
Then they ordered him to this prison, as a ringleader;
yet the clerk made his mittimus for refusing an oath,
which was tendered upon the new Act made against Quakers and others,
which for the first time he conceives to be but three months imprisonment,
or five pounds fine, according to the statute;
but he hath been detained a prisoner more than three months.

Thirdly,
That Edward Parish was sent for by a party of soldiers from
his own house without any warrant from any justice of peace,
and commanded to appear before the deputy-lieutenants,
to answer such things as should be objected against him; which accordingly he did;
and although no accuser appeared to charge him with any thing done contrary to law,
yet they committed him to prison,
because he (knowing himself innocent,) could not give bonds for good behaviour,
and have ordered him to lie in prison till he either do the same,
or be discharged by some of the deputy-lieutenants,
or some of the justices of the peace for the parts of Lindsey.

And we do farther declare, That it is for our conscience sake that we cannot swear;
and because we know nothing by ourselves worthy of bonds, we cannot give bonds;
and do not refuse in contempt of the king or his laws,
or any that are set in authority under him.
For though our sufferings are, and have been very great, yet we are peaceable men,
and neither do at present, nor ever shall seek the hurt or destruction of any man or men,
either in their persons or estates.
What others have done should not be imputed to us, who are of another spirit and mind,
which leads us not only to love our neighbour as ourselves, but also our enemies.
Therefore we do once more, as our birthright, desire that we may partake of that justice,
which (thou saidst) "`flows from the throne like a pure
stream,`" but which hath savoured like wormwood,
as it hath been handed unto us by inferior magistrates.
So expecting that thou wilt not deny those fair proceedings to us,
which thou so freely allows to others, whose cases are criminal, we subscribe ourselves,

Sufferers for conscience-sake,

John Whitehead, John Cleasby, Samuel Davy, Edward Parish.

Lincoln Castle, the 12th of the First Month, 1663.

But the Judge did not call us at all, yet did he discharge Samuel Davy and Edward Parish,
also John Cleasby whose case was the very same with mine, as may be perceived;
but he ordered me to lie in prison till the next Sessions, and abide their order,
although he afforded me neither trial nor hearing,
neither did any accuser openly appear to charge me
with the breach of any law of God or man.
Wherefore after I understood what was done, I wrote to him as follows.--

Friend,--If I be an offender, why is justice delayed, and not speedily executed upon me?
But if I be innocent, why dost thou deny me my liberty which of right is due?
Why dost thou asperse us openly, and refuse to hear us openly before the country?
Wert thou afraid that our innocency should appear,
or wouldst thou have covered their shame, who have done violence unto us?
Is it not both against the law of God and man,
to imprison me without hearing what I can say for myself?
For doth not your law presume every man innocent till the contrary appear?
And how can the contrary appear without trial?
Though Felix was willing to do the Jews a pleasure,
he left not Paul bound without hearing, though he was counted the ringleader of a sect;
and hast thou acted like a Christian magistrate, in leaving me bound now the second time,
whom thou hast never heard speak for myself;
or rather like a man blinded with prejudice against me?
Since thou hast released others, whose cause was the same,
art not thou a respecter of persons?
Let God judge between thee and me in this matter: to whom I appeal, being assured,
that he will hear me and look upon my afflictions,
and in due time execute judgment for me.
And in that day shalt thou be inexcusable O man! forasmuch as thou knowst,
that they who justify the wicked, or condemn the innocent,
are both an abomination to the Lord.
Therefore consider, that thy breath is in thy nostrils, and repent,
if peradventure thou mayst be forgiven for all thy hard thoughts and hard speeches;
which is the desire of my soul, who am

Thy friend in truth, and therefore cannot flatter,
but am obliged thus faithfully to warn thee.

John Whitehead, Prisoner.

Lincoln Castle, the 14th day of the First Month, 1663.

+++[+++As John Whitehead was conspicuous in his religious service,
and in his zeal for the cause of Truth,
he was doubtless regarded by his persecutors as one
on whom it was especially desirable to impose restraint;
and scarcely any pretext seems to have been too trivial
or unreasonable to serve their purpose.
No other reason was given for this further detention in prison, than,
that the Judge`'s will was to have it so, which one of the justices said was a law.

Six other Friends were now in prison with him, for non-payment of tithes.
Two of them, viz. Vincent Frotheringham and Robert Whiteman,
were kept in prison three years, and another, viz. Thomas Richardson, more than a year.]

Besides what is above spoken of, +++[+++John Whitehead continues,]
there have been many more in prison for the Truth`'s sake, in this county.

In the parts of Holland (one of the three divisions of Lincolnshire) Samuel Davy,
Henry Wilson, Gregory Sherwin, William Carnall, John Thompson, Stephen Willoughby,
George Reeve, John May, Susan Thomas, Margaret Smith, Rebecca Preston, and Ellen Wilson,
were apprehended on the 5th of the Eighth Month,
without any lawful warrant to that place where they
were met together in the peace of God.
The man who apprehended them was no civil officer, but a sword-man;
wherefore they objected against him, and would not have gone with him; but he said,
"`he would make them go, or trail them at a horse`'s tail.`"
They were taken to Justice Jay, and by him committed to Spalding prison,
for meeting together in the fear of God; where they remained but five days,
and were then all released but Samuel Davy, whom the justices had formerly threatened;
because he did, before a judge of Assize,
witness against some of their former illegal proceedings against him.
Having now got an opportunity to do somewhat against him,
one of them called him the grand rogue;
and waiving the matter for which he was brought thither,
they determined to send him to prison as a ringleader,
and therefore tendered him an oath;
and for not giving answer whether he would take it or not,
they sent him to the Castle of Lincoln, where he remained twenty-two weeks,
till he was delivered as before signified.

At the same Sessions, John Titman, Edward Tisdale and George Billers, were committed,
for not submitting to the court, being indicted for not going to the steeple-house.
For that very thing,
those three innocent men were kept prisoners about a quarter of a year.

Upon the 12th day of the Eighth Month, Thomas Summers, Christopher Clark, John Scotney,
Edward Fisher, John Sandby and Thomas Mathers,
were also apprehended at a peaceable meeting,
and carried before Justice Burrel and Justice Oldfield, of Pinchbeck, who therefore,
though with some reluctance, committed them to Spalding prison.
Justice Burrel said, he had rather have been at plough; and Justice Oldfield,
that he had rather have been at plough ten times.
Notwithstanding,
these six innocent men were kept prisoners at Spalding about a quarter of a year.

At the Sessions held at Spalding, in the Eleventh Month, they appeared, and were,
together with John Avy and six more, indicted,
"`for meeting together under pretence of religious worship.`"
To this indictment they pleaded not guilty, and desired a present trial;
but the court put them off, and upon their promise to appear at the next Sessions,
dismissed them.

Upon the 14th day of the Tenth Month, Vincent Barrow, John Thetting, Thomas Yorksey,
Robert Kelsey, Peter Moody, Thomas Barrow, Charles Tate, John Clark, William Clark,
Richard Parnell, John Spicer and Thomas Halifax, being met together in the fear of God,
to wait upon him for the guidance of his Spirit, that therein they might worship him,
were apprehended and brought before John Moonson senior and John Moonson junior,
without any lawful warrant; who therefore, and because they could not swear,
committed them to prison on the 17th day of the Tenth Month,
where they were detained until the 15th day of the Eleventh Month.
On that day they appeared at the General Sessions held at Spital,
and delivered this following paper to the justices, subscribed with their hands:--

Friends,

We are a people that do fear the Lord, and follow after truth and righteousness;
for which we have been exposed, and still are, to very grievous sufferings,
wherein the God of Heaven and earth hath hitherto upholden us; to whom we do appeal,
that we are innocent towards you, and all that be in authority over us.
We are not of them that are profound to make slaughter,
neither can we plot or contrive to shed the blood of our enemies; but do love them,
according to Christ`'s doctrine,
and desire to live peaceably in all godliness and honesty;
for which cause we have hitherto paid taxes, custom, and all other just dues,
as they have been lawfully demanded of us.

When we meet together, it is in the fear of the Lord,
for no other end but to worship him in Spirit and in truth.
And we hope you will not deny that that worship is authorised by the laws of the land.
If so, then our meeting together for that very end,
is no transgression within the compass of the late act,
and consequently we ought to be indemnified.

Therefore, in equity and moderation consider our case,
and measure no other measure unto us than you would have measured to you again.
For why should we suffer merely for seeking to keep
our consciences void of offence towards God,
when we do no manner of wrong towards men?
And we do further appeal to your very consciences, whether it be not against common good,
to take us from our husbandry and other honest diligent labour,
and thrust us up in jails and correction-houses,
where we cannot be so serviceable in our generation,
nor labour for the maintenance of our wives and children; whenas,
we have committed no offence nor wicked lewdness,
that in justice deserves such punishment?
And if you fine us for worshipping God according to our consciences,
and set hard-hearted men to take spoil of our goods, then consider,
how can we pay rents and taxes, and maintain our families?
Will you not be guilty of bringing ruin and destruction on us in this world,
who have not deserved such hard measure from you, as our consciences bear us witness?

Therefore have we confidence to commit our cause to the Lord,
and in his strength can cheerfully suffer what you can do unto us,
and praise Him that hath counted us worthy to suffer for meeting in his name,
and obeying his doctrine.
Nevertheless, we desire that you take heed of shortening your own tranquillity,
and provoking the Lord to take vengeance upon you:
for we cry unto him when we are oppressed, and he doth certainly hear us,
and will right our wrongs, when he hath suffered you fully to try our faith and patience.
So into his will we are given up, and remain,

Lovers of your souls, and desire your eternal good.

Notwithstanding this paper, and although no one appeared to prosecute them,
yet were they examined by interrogatories, concerning their meetings;
and because they would not deny,
but confessed that their meeting was for the worship of God,
they were fined each of them thirty shillings.
But the justices of that Sessions were more noble than they of Louth,
for they forthwith discharged them of their imprisonment.

Likewise Thomas Markham, Robert Rockhill, William Williamson, John Rockhill,
and Thomas Benson, for meeting together in the peace and love of God,
were apprehended by Daniel Whitekombe, who said, his sword was his order:
and he took them before Edward Roseter, who committed them as prisoners.
But they remained in the constable`'s custody till the Sessions at Castor,
the 14th of the Eleventh Month, 1662, where they appeared,
and were indicted by the same party that apprehended them,
who gave this evidence against them,
That he found them together in Elizabeth Lellingrave`'s house; and on asking them,
Wherefore they were met together?
They told him they were met in peace and love; and that was all that he could say.
Whereupon an indictment was found against them by the grand jury; some of whom confessed,
that they heard not the evidence;
and the accused were not permitted to speak for themselves.
But without any legal trial, was each of them fined twenty shillings;
one of the justices saying, "`It was a breach of the law,
if they were found above five together, whatever the occasion was.`"
If it be so, we are not only deprived of liberty to worship God,
but also of human society:--how hard measure that is, every sober man may judge.

Also three poor labouring men, James Taylor, Thomas Norton, and Robert Walker, were,
about the 5th day of the Twelfth Month, 1662,
taken from their distressed wives and children,
and all by one cruel priest sent to prison,
because they could not with a good conscience give him tithes of their hemp,
their roots and milk,
which with great industry they provided for their poor wives and families.

Surely the +++[+++early]
ministers of Christ would have been ashamed of these practices; who declared,
that after their departure, "`grievous wolves should enter,
not sparing the flock,`" which we daily experience to be true.
But in all these things our eyes are unto the Lord,
of whom we have obtained help unto this day;
and through his mercy we choose rather to die in prison,
than to violate our consciences for our outward liberty; being assured,
that God will reward us according to our doings, and them also who afflict us,
according to theirs; for such as every one soweth he shall reap; and look,
with what measure any one measures it shall be measured to him again.
And if any be offended or ashamed that their deeds are brought to light,
let them be much more ashamed to do such things as cannot
be reported without being a stain to their honour and reputation,
or an ill savour in the country;
for there is nothing secret that shall not be made manifest.

After having been thus the second time recommitted by Judge Windham`'s order,
without trial or hearing, I was kept prisoner till the General Sessions, held at Louth,
the 28th of the Second Month, 1663, where there sat Robert Christopher, William Woolly,
Isaac Knight, and William Fitzwilliams, to whom this following letter was delivered:--

For the King`'s Justices, at the General Sessions in Louth,
to read and consider with a meek spirit.

When will you hearken to the cry of the oppressed, and execute justice for the stranger?
Surely you cannot be so ignorant of the law,
but must know that the wrong which I have already suffered is exceedingly great,
since you may understand that I have now been a prisoner about ten months,
seven of which I have suffered in that very case where the
law saith the offender shall suffer but three;
and surely you cannot reasonably judge, whilst by your order I have been kept in prison,
that I have done anything worthy of bonds,
for which I should be detained four months longer than the law requires.
Therefore how can you in honesty tax me for not conforming to the law,
since I have more than fulfilled it through sufferings?
I can do no less than appeal once more to your very consciences for justice and right;
and the rather,
because the judge of Assize hath now the second time
denied to take cognizance of my case,
save that at the Assize he ordered me (whom he never saw,
nor heard speak for myself) to lie in prison, and abide your order at this Sessions,
which I expect may be to enlarge me,
because I am persuaded no man can justly charge me with anything worthy of bonds.
Therefore do not seek occasion any longer to detain me in your county;
which I the rather desire,
because I understand that I am already presented
in the Ecclesiastical Court in the county of York,
where I cannot make my appearance, to answer such things as may be objected against me,
if you detain me a prisoner here.
Wherefore, if you judge me to be a troubler of your country,
and would have me out of your coasts, then let me go free;
that as I have confessed Christ Jesus and his heavenly doctrine, in your courts temporal,
so I may confess him and the right way of God`'s worship,
in theirs that are deemed spiritual.
But if this just and reasonable desire may have no place in you,
so as to procure my liberty, which hath of right been long due, then know,
that since the Scripture cannot be broken,
but they that will live godly in Christ Jesus must suffer persecution,
it is all one to me where I suffer;
being through God`'s power made as willing and content
to suffer whatsoever you can inflict upon me,
if it be to the loss of my life, for the truth I profess,
as I was the first day you caused me to be shut up in prison;
being assured that my reward is with the Lord,
who will also recompense you according to your doings.

John Whitehead.

Lincoln Castle, the 25th of the Second Month, 1663.

After the reading of this letter, one Captain Foster, who is a tender man,
and hath some authority under the Earl of Lindsey, did also speak somewhat on my behalf;
which, together with the innocency of my cause, did so work upon the justices,
that as soon as I came to the bar,
I was by the above-named justices discharged from my long imprisonment.
