== Chapter X.

[.chapter-synopsis]
* John Whitehead imprisoned at Hull
* And at Spalding
* Epistle, "`A tender visitation of heavenly love`"
* Procures George Fox`'s release from Scarborough Castle
* Imprisoned at Stamford
* Attends the Sessions at Spital, and writes a remonstrance to the justices
* John Whitehead`'s third imprisonment in Lincoln Castle
* Petition to the Judge at the Assizes
* Copy of Mittimus and exculpatory Certificates
* Trial at the Assizes
* Remanded to prison under sentence of premunire
* Letter to the Judge

+++[+++After having been at liberty but little more than three months,
John Whitehead was committed to prison at Hull, under the circumstances which,
with much simplicity,
he describes in the following letter found among the Records at York:]

[.embedded-content-document.letter]
--

[.salutation]
Dear Friends,

Last Seventh day I took my journey from Lincoln; and being wholly clear of that county,
as I signified in my last, I did intend to pass to my outward being;
and in order thereto, a boat being ready, I entered it to cross the River Humber,
at a town called Paul, below Hull;
and there was a priest drinking in the ferryman`'s house, who was bound for Yorkshire.
Other rude company were drinking with him,
and would hardly be gotten to forsake their strong drink till the tide was almost spent.
When they came forth to the boat in which I was, they took occasion to quarrel with me,
examined what I carried,
and said I might have seditious letters and books for anything they knew;
and I told them they might examine me for an evil end and to do me mischief on the highway,
for anything I knew;
and therefore I desired to know by what authority they questioned me.
One of them said, I should see his authority,
(meaning his sword,) and he would nail me to the
door-cheek if I offered to stir,--or to that purpose.
But after I had a little season reasoned with them, they let the boat go off,
nobody being in it but the priest, myself, and the ferryman.
But they having trifled away the time, the ebb bent against us,
and we could not reach over the river, but were driven back again.
As soon as I was landed, I got upon my horse and passed on easily,
not intending to lodge at the ferry-house,
where those rude men who had threatened me were drinking; but they stood in my way,
caught hold of my horse, and violently pulled me down; then they locked up my horse,
and by force kept me there that night.
They were no civil officers, nor had any warrant for what they did.

Yesterday morning they brought me to Hull, before William Broxholme,
who was the deputy governor; and he having no other occasion against me,
caused a little packet of books (which G. G., servant to R. W., sent to me,
I having them about me) to be rifled; and also he searched my portmanteau and pockets,
took all my letters and parcels and the books from me,
and had me and them to the Mayor and Aldermen of the town of Hull,
urging them to tender me the oaths of supremacy and allegiance.
So after they had examined me, and we had reasoned together for a good season,
they waived the tendering the oath,
and insisted on it that I should give bond for my appearance at the Sessions,
and in the meantime to be of good behaviour;
for not doing of which they did in the conclusion commit me to prison;
though with as much reluctance as ever I knew any do,
often expressing their unwillingness thereunto.
Divers Friends and professors came to visit me; and that the issue of it will be good,
I doubt not.
They keep all the books and my letters in their custody,
and the military officers do intend,
(seeing that they are most of them printed for R. W.,
and were sent down by G. G.) to write up to London:
and no question but they will procure what hurt they can unto them.
Therefore I would have thee as speedily as may be after this comes to thy hand,
to advertise them that they may secure themselves and their books as well as they can.
I have given order to M. M. to return R. W. the price for the books,
which I doubt not he will shortly do.
I suppose they have not any other matter against me but what they
can pick out of the books or papers which they took from me,
unless they can create an offence at the Sessions
which are to be holden this week on the Fifth-day;
only they look upon me as the grand ringleader of a very dangerous sect;
but the Lord in whom we trust,
will not fail to clear our innocency after he hath fully tried us.
This, with my endeared love unto thee, is all at present,
but that my desire is to hear from thee as often as thou hast freedom,
who am thy friend in truth,

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Writ in the common jail at Hull,
where I am kept a close prisoner for truth and righteousness`' sake.
The 13th day of the Fifth Month, 1663.

--

+++[+++We are not informed how long John Whitehead was kept in prison this time;
probably not more than a few days--considering the
reluctance of the magistrates to commit him,
it is likely that he was discharged at the Sessions, about to be held when he wrote.

[quote]
____
Upon the 6th of Ninth Month, 1664,
John Whitehead was apprehended at a meeting of the Lord`'s people,
and committed to Spalding prison, for waiting on God amongst his people,
where he remained until the 5th of Tenth Month in
the same year.--__Ancient Minutes of Lincolnshire.__
____

During this imprisonment, he wrote the following address to his fellow professors:--.

The impressive manner in which he commemorates the Divine compassion extended to them
"`in the day of their wearisome wanderings,`" and his affectionate exhortation to faithfulness,
will, doubtless, commend it to the cordial acceptance of the serious reader.]

[.embedded-content-document.address]
--

[.blurb]
=== A Tender Visitation of Heavenly Love. Streaming from the Fountain of endless life, unto the Tribulated Flock of Christ, Whom the World in Derision calls Quakers; Being an Epistle Given Forth by the One Spirit of Truth, Through a Servant of the Living God, who is called Among Men, John Whitehead.

[.salutation]
Dear Friends And Brethren,

Called by God, and gathered in the name of the Lord Jesus Christ, who is the Word,
the Light and the Life, whereby we and all men have been enlightened,
that we might see our deformity, and be made sensible what glory,
dignity and felicity we lost by degenerating from the law of the life of the Creator:
and not only so,
but in the same Light God hath given us again the knowledge of his glory, virtue,
and power; that by the operation thereof through faith, we might be reformed,
created anew, regenerated, restored, and established in the image and glory of God,
wherein man was formed at first by the Word of God.
This hath been the principal thing pressed unto by all the prophets, apostles,
and righteous men, who have served God in their generation,
and been witnesses of his good will towards men; who gave his Son a ransom for all,
and to enlighten all, as the Spirit of God now in due time hath testified unto us:
which is an evident token that God hath not appointed us to wrath,
but to obtain salvation,
and through regeneration to become heirs of a kingdom that cannot be shaken,
which stands in righteousness, peace, and joy in the Holy Spirit.

Herein ye that are faithful have access to God,
and enjoy sweet inward communion with him, whose tabernacle is with us,
and whose bounty towards us hath been exceedingly great, and his goodness infinite.
Of this I cannot but declare a little,
that posterity may know there is mercy with him that he may be feared;
for in long-suffering he bore the infirmities of our youth,
and in mercy passed by the sins of former ignorance; he also quickened us who were dead,
and opened our eyes that we might see, and our ears that we might hear.
When compassion moved him to pity us in the day of our wearisome wanderings,
he restored us a path to dwell in,
wherein he hath guided us by the skillfulness of his hands,
and chastised us when we have turned aside.
His lovingkindness and mercy he hath not taken away from us,
but hath opened his ear unto our cry.
When we were little, he carried us in his arms;
and in our travails and trials he hath supported us.
When temptations have overtaken us, and the enemy compassed us about on every side,
he hath pitied our weakness, and stretched out his hand to deliver us;
by his power we have been plucked out of the mire and clay,
and our feet have been set upon a Rock, out of which clean water hath flowed,
both to wash and refresh us.

Therefore I will praise the Lord with my whole heart,
and ascribe glory and honour unto the Most High; for his work is perfect,
and his love immeasurable to his children.
He hath given people for their life, and will not spare nations for their ransom;
they who have digged a pit, have fallen therein;
and they who lay snares for the innocent, shall be taken therein; as our eyes have seen,
and our fathers have told us.
Wherefore let us hope in the Lord as long as we live; for though he doth now,
and hath often suffered us to be distressed, yet have we not been destroyed;
because under us hath been the everlasting arm of our God,
who every way hath dealt with us as a father with his children in whom he delighteth.

Therefore dear friends, as we have tasted that God is gracious,
let us take heed unto the grace which he hath given us,
and not decline from the way that he chose for us in the day of our simplicity;
but bow our ears to the instruction of life, that we may be kept tender towards God,
out of the corruptions of this world and defilements of sin,
which in ancient time grieved God`'s good Spirit,
and provoked him to be wroth with his inheritance.

Wherefore let us hold fast the mystery of faith in a pure conscience,
and pass the time of our sojourning here in God`'s fear;
waiting for the fulfilling of these very precious promises which we have received,
that we may be partakers of the divine nature,
and thereby do the things contained in the royal law of our Lord.
So shall we stand justified when the secrets of men
shall be manifest and judged by his Light,
and every man shall feel in himself the reward of his works,
whether they be good or evil.
For in them that have done evil, shall the wrath of God burn like devouring fire;
but in them that have done good,
shall divine joy and consolation arise from the wellspring of God`'s everlasting love.

So these things bearing a weight upon my heart,
I judged it my duty to stir you up by way of remembrance;
for the joy that is set before you, to endure the cross and despise the shame;
committing yourselves wholly to the Lord in well-doing,
that he may keep your minds stable in the love of the Truth,
till ye come to receive a full reward for every labour of love,
and for all sufferings that ye have undergone for the Lord`'s sake.
And dear hearts, though I am persuaded that divers of you know these things,
and are established in the present truth,
yet seeing we dwell in tabernacles of clay and are subject to be tempted,
the love of God constrains me to communicate that
which I have received for your good and preservation;
desiring that ye also, in the same love, may seek to preserve one another, and admonish,
exhort and stir up that which is good in one another;
so much the more as we know the true Light shineth,
and hath manifested the things belonging to our peace;
considering that ye must give an account to God, how you improve your talents.

Be not discouraged at the untowardness of such as have given way to the enemy,
and are driven aside by his subtlety and violence;
for they most need help who are the least sensible of it,
and who presumptuously kick against the admonitions
and exhortations of faithful friends and brethren;
being hardened in themselves, that they feel not God`'s witness: wherein persisting,
they are not only beguiled of their reward, but lose all tenderness to the Truth,
and are covered with thick darkness, and drowned in destruction and perdition.
Therefore, as soon as ye are sensible the enemy hath got advantage of any particular,
be ready to give and receive warning and exhortation to and from one another,
lest any be hardened through the deceitfulness of sin.

And dear friends, in the name of the Lord Jesus Christ diligently meet together,
and suffer not yourselves to be drawn out from a watchful, waiting state;
lest slumbering, ye trifle away your precious time and grow weak,
and the enemy enter at unawares.
For they that wait on God, shall renew their strength;
and the watchful eye shall see his Saviour and Deliverer near,
to the refreshing of his soul, which shall be clothed with righteousness,
and filled with the glory and virtue of an immortal life;
whilst the soul of the sluggard is clothed with rags,
and such as are careless are entangled with many hurtful lusts.

Wherefore, dear and tender plants, I say again,
be watchful and obedient to God in things that are clear and manifest;
so will hidden things be revealed,
and ye be taught to avoid everything that tends to beget doubts,
disputings or contention about persons or things,
which are below that divine Life whereby you are enlightened.
And wait for the latter rain where ye have received the former rain;
so shall ye take deep root in a fruitful ground and be no more subject to tossing.
"`Whilst your hearts are tender in the Light,
sound judgment shall shut out deceit and false spirits,
and keep you tender and open to the instruction of life,
both in yourselves and in whomsoever it shall breathe forth exhortation or doctrine,
that ye may be edified or built upon that foundation which is sure;
whereby ye may be strengthened against every appearance of evil,
and stand pure in a righteous, holy, blameless life, which may silence all gainsayers,
and be to the praise and glory of God,
who hath called you out of darkness into his marvellous light; wherein,
that ye may abide forever,
is the earnest desire of your brother and companion in tribulation,
who under his own hand hath sent you this salutation.

[.signed-section-context-close]
From Spalding prison this 19th day of the Ninth Month, 1664.

--

+++[+++In the year 1666, John Whitehead was in London,
with several other Friends in the ministry, viz., Alexander Parker, George Whitehead,
Thomas Loe, Josiah Cole, and Thomas Rolfe.
At this time George Fox was a prisoner in Scarborough Castle.
He had been apprehended at Swarthmore, in the year 1663,
on suspicion of being concerned in a plot.
At the Lancaster Sessions, after refusing to take the oaths of allegiance and supremacy,
he was committed to prison in that place,
where he continued till some time in the year 1665, and was then removed to Scarborough.
Here he had been a prisoner more than a year,
and had been informed that none but the king could release him.
John Whitehead, having some acquaintance with Esquire Marsh,
(so called) one of the king`'s bedchamber,
visited him on the subject of George Fox`'s unjust imprisonment.

Marsh engaged,
that if John Whitehead would get his case drawn up he would deliver it to Sir John Birkenhead,
the Master of Requests, and endeavour to procure his release.
A statement of the case was accordingly prepared,
and the Master of Requests obtained an order from the king for George Fox`'s discharge.
As soon as this was effected,
John Whitehead took the order down to Scarborough
and delivered it to the Governor of the castle,
who, upon receipt of it, discharged George Fox forthwith.

[.embedded-content-document.legal]
--

Upon the 6th of the Fourth Month, 1668,
John Whitehead was taken out of a meeting at Stamford,
committed to prison by the mayor for twenty-four hours, and then sent away by pass.

--

In the Sixth Month, 1670, eleven Friends who resided at Gainsborough and places adjacent,
were summoned to appear at the Sessions at Spital,
for meeting together at one of their houses.
For this alleged offence eight of them were fined,
and had property taken from them to the amount of £64.16s. 4d.

John Whitehead, prompted by christian sympathy towards these, his suffering brethren,
and also by "`tender love`" towards their persecutors, attended the said Sessions;
and after having witnessed the proceedings of the court,
he wrote a remonstrance to the magistrates on account of their unchristian conduct,
which he concludes thus:--

[.embedded-content-document]
--

Therefore as a stranger and pilgrim,
that passed through the country and stepped in to hear your proceedings,
in tender love I exhort you to proceed no further against God`'s people,
nor punish men for meeting in reality to worship him,
lest ye perish in the day of his wrath--which that ye may escape,
shall be the earnest desire of your real friend (who loves to tell men the truth,
though for that he be counted your enemy.)

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Ancient Records of Lincolnshire.

--

No record respecting John Whitehead, of sufficient interest for insertion,
has been found between the last date and the year 1682,
when his allegiance to his Divine Master was again
put to the test by the ordeal of suffering:
the ruthless hand of persecution was once more permitted
to be stretched forth against him.
But his conduct under all these trials of his faith,
spoke the language of the apostle in no indistinct manner:
"`None of these things move me, neither count I my life dear unto myself,
so that I might finish my course with joy,
and the ministry which I have received of the Lord Jesus,
to testify the gospel of the grace of God.`"
(Acts 20:24)

On the 22nd day of the Third Month he was again committed to prison at Lincoln
for preaching in a meeting held at the house of Thomas Sowtors in Sutton.
He was apprehended under the conventicle act, and also charged with being a Jesuit.
After having lain in prison ten weeks,
he was brought to the bar at the Assizes at Lincoln,
which began on the 31st of the Fifth Month, before Baron Street.
But the judge, instead of proceeding to try him on the charges contained in his mittimus,
resorted to the customary snare of tendering the oath of allegiance;
and for his refusal to take it he was indicted.

It will be seen in the following account of his trial,
that he pleaded ably against the unfairness and illegality of committing him
on one charge and then indicting him for another:--a course of proceeding which,
it seems, Friends had often occasion to complain of, in those times of persecution.
And inasmuch as the sentence of premunire^
footnote:[The penalties of which were--to be put out of the king`'s protection,
to forfeit lands and goods to the king,
and to remain in prison during the king`'s pleasure, or for life.]
was to be the consequence of conviction in the present case,
the earnestness which John Whitehead manifested in his defence is well accounted for.

Previous to his being brought into court,
he submitted his case to the consideration of the judges, by way of petition,
to the following effect:]

[.embedded-content-document]
--

Upon the 21st of +++[+++the month called]
May last past, I was by Michael York,
chief constable for the parts of Holland in this county, seized as a Jesuit,
and kept in custody until the next day.
I was then carried before Justice Burrel,
who proceeded to convict me upon the statute made
in the 22nd year of King Charles the Second,
for preaching at a conventicle or meeting.
From this conviction liberty to appeal is allowed, as appears by the said act:
and I doubt not but to clear myself from the breach of that act,
which lays a fine of twenty pounds, and not imprisonment, after conviction,
upon the preacher; and provides, that such as are convicted and fined by that act,
shall not suffer by any other law or statute whatsoever, for the same offence.
Notwithstanding, I have been kept close prisoner these ten weeks,
to my great loss and damage, and the great hurt of my poor distressed wife and family:
+++[+++for on a journey]
occasioned through my imprisonment, my wife hath broken one of her legs,
and lies in great distress.^
footnote:[+++[+++The following is extracted from an original Letter,
written in consequence of this grievous accident, and dated Lincoln Castle,
the 16th of the Fifth Month,
1682.+++]+++
{footnote-paragraph-split}
My Dear Wife,
{footnote-paragraph-split}
How is my heart
afflicted for thee in this day of our great distress.
The Lord be merciful unto thee, support and comfort thee in thy great need,
and give thee patience to bear thy grief and misery, wherein I cannot help thee;
for the jailer will not suffer me to come and see thee, though I desired it fervently.
I beseech thee, for the Lord`'s sake, be circumspect and careful of thyself,
and spare not for cost; get whatsoever is necessary for thee; and requite,
according to our power, those that have been kind to thee in thy great distress;
and the Lord give them a reward wherein we cannot.
I sent thee a letter yesterday, before I knew anything of thy hurt.
I desire thee, if thou be able, to read it to John,
and commit outward things to his care:
I hope the Lord will give him a heart to be faithful in this day of our great need.
I warn both the lads to be good, as ever they intend to look me in the face.
And Mary, be sure let the family have what is necessary:
when provision is wanting let John buy;
and I desire him to be faithful and diligent with what force
can be gotten to carry on the business without doors.
And, dear wife, by some means let me know how it is with thee,
that I may mourn when thou mourns, and be in heaviness when thou art in heaviness.
It may be the Lord will look upon our affliction and deliver me; but if he will not,
his will be done; I will both hope and patiently wait for his help;
and in due time he will deliver us out of all distress.
So the Lord be with thee and refresh thy spirit,
that in all thy infirmities thou mayst be sustained.
{footnote-paragraph-split}
I ever
remain thy dear husband,
{footnote-paragraph-split}
John Whitehead.
{footnote-paragraph-split}
To
my dear wife Elizabeth Whitehead,
this deliver, at Swine Grange, with care.]
For my imprisonment there is no cause,
or but a malicious accusation from the said Michael York, who swore,
"`he suspected me to be a Jesuit;
and that I seduced the king`'s subjects from their obedience;`" which accusation I did,
and do utterly deny as false and slanderous,
being well assured that no man can prove such things against me.

I can also manifest the contrary, under the hands of my neighbours,
attested by the hands and seals of several justices of the peace,
whose loyalty and credit I hope will not be questioned.
Therefore my request is, that one injury may not be made the foundation of another,
but that I may have a fair hearing, and legal trial;
and that if I be not found such as I am suspected and accused to be, but an innocent man,
that fears God, honours the king, and desires to live a peaceable life,
in godliness and honesty, I may be discharged, as to right and justice doth appertain;
and I shall be obliged ever to pray for your welfare and prosperity,
who am a friend to justice, and desire the peace of this kingdom.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 30th day of the Month, called July, 1682.

--

This was delivered to the judge by his marshal,
with a copy of the mittimus by which I was committed, as here inserted.

[.embedded-content-document.legal]
--

[.letter-heading]
To the Keeper of His Majesty`'s Jail at Lincoln

[.signed-section-context-open]
Linc.
Holl.

I send you herewithal the body of John Whitehead, late of Swine,
in the East Riding of Yorkshire; for that he is this day brought before me,
accused and suspected to be a Jesuit,
and hath made no satisfactory answer in his own defence;
and is also now convicted before me, by the oaths of several persons,
for preaching at an unlawful assembly or conventicle, at the house of Thomas Sowtors,
in Sutton St. Mary`'s, upon Sunday the twenty-first day of this instant May,
where there were about forty assembled, besides those of the family of the said Sowtors;
at which time and place, as at several other times and places,
the said John Whitehead did endeavour to seduce several of his Majesty`'s
liege people from the doctrine and discipline of the Church of England,
as by law settled amongst us: These are therefore, in his Majesty`'s name,
straitly to charge and command you,
to receive the said John Whitehead into your said jail, and there him safely to keep,
until he shall from you be delivered by due course of law.
Hereof you are not to fail at your peril.

Given under my hand and seal at Wikam, the 22nd day of May,
in the thirty-fourth year of our sovereign lord, King Charles II.,
and in the year of our Lord 1682.

[.signed-section-closing]
This is a true copy of his mittimus.

[.signed-section-signature]
Clifford Barnard, Under-Jailer.

--

The justice who committed me,
being in the chamber with the judge when these were delivered,
as the marshal informed me, denied the copy of the mittimus to be a true one:
whereupon the judge sent his marshal to compare it with the original,
which was in the jailer`'s custody, and he found it exactly to agree therewith, and said,
he would affirm it to the judge.
In the afternoon of the same day, the judge came into the court, and I was called,
and when I appeared before him, he said: "`I hear you are a great preacher,
and are suspected to be a Jesuit; and I think the justice here did wisely,
in suspecting and securing you;
for it was made appear before the Lords and Commons in Parliament,
that there was scarcely any considerable conventicle in England but had a Jesuit in it;
and therefore, to try how you stand affected to the Government,
I will tender you the oath of allegiance.`"

[.discourse-part]
_John Whitehead._--The court may take notice,
that I have been kept close prisoner ten weeks,
and I desire the cause thereof may be inquired into;
and if I be found guilty of those things which are charged against me,
let me suffer according to law.
But if it appear that I am clear from the matter of charge,
and slanderous accusations laid against me, then I desire to be discharged,
and that there may not be an occasion sought against me.
For I am not a man of those dangerous principles,
neither doth any Jesuit belong to our meetings.

[.discourse-part]
_Judge._--Do not you go up and down preaching?
And did not you preach in that meeting?

[.discourse-part]
_John Whitehead._--I hope I was not brought hither to answer
to questions whereby I may inform against myself.
I desire my accusers may appear face to face, that I may know what they charge me with,
that I may have a fair trial thereupon;
for I have been much grieved and damnified by my imprisonment,
and my poor wife and family much distressed thereby;
for on a journey occasioned by my imprisonment, she got a fall from a horse,
and broke one of her legs, and is now deprived of my help and assistance.
Therefore I desire a fair trial, and if I be found innocent, let me be discharged.

[.discourse-part]
_Judge._--I am sorry for the mishap and hurt your wife hath had.

[.small-break]
'''

And the justice who was by, that committed me, being asked, what witness he had?
pointed to Michael York, who was sworn, and gave this evidence in open court:
"`Upon the 21st of May, being Sunday,
there came a man to church and told the constables and churchwardens
that there was a conventicle at Thomas Sowtors`' house;
and thereupon they went to the said house, and as they said to me and others,
they found this man preaching at a meeting in the said house,
where there was above forty people assembled, and warned them to depart,
and took the names of some of them that were met; who said,
what they did was not contrary to law.
After the return of the officers, I inquired what they had done,
and what manner of man he was that spoke?
And they told me, a low, broad man;
and I remembered I saw him the day before at a neighbour`'s house, where I was:
and I went and took the officers with me; and there, after some discourse,
the man came forth of the room; and I asked, if that was the man that spoke?
And the officers said, it was he; then I apprehended him,
and suspected him to be a Jesuit; and as I have heard,
he is one that makes it his practice to seduce the King`'s subjects,
and is a ringleader of the Quakers, and is one of the greatest and most eminent,
at least that ever I heard of, in these parts.`"

[.discourse-part]
_John Whitehead._--The evidence he has given is not from his own knowledge of me,
or of the things that he hath affirmed, as the court may observe;
and that he hath not assigned any cause for his suspicion that I am a Jesuit;
and what he hath against me, as to seducing the King`'s subjects, was in general terms,
which signify a design to slander; and that what he hath said,
was not upon his own knowledge, but by report from others.

[.small-break]
'''

It was desired and pressed,
that he might answer this question--whether he ever
had heard me speak in any meeting in all his life?

But no answer was given to this question, though much desired by me;
for I knew he could not affirm he had either seen
or heard me speak in a meeting in all his life,
unless he would willfully perjure himself.

[.discourse-part]
_Judge._--You cannot deny but that you are a preacher, and travel up and down the country,
else how came you thither?

[.discourse-part]
_John Whitehead._--I had business: being concerned as a trustee for some charitable uses,
I had occasion to speak with several persons about it; and I intended to go for London,
there being a suit depending in Chancery, for a legacy of two hundred pounds,
wherein I with others am concerned.

[.discourse-part]
_Judge._--Forasmuch as you travel up and down, and are publicly known to be a preacher,
I have reason to suspect your allegiance, and therefore must tender you the oath;
if you will take it, you shall have your liberty.

[.discourse-part]
_John Whitehead._--I have given no occasion for my allegiance to be suspected,
but have lived peaceably, and therein performed my allegiance,
and do truly intend to perform it as long as I live,
and therefore ought not to be run upon with an oath to ensnare me;
but to have a fair trial for what is already charged upon me,
that I may be acquitted or condemned according to law.
And I have certificates to manifest I am no such dangerous person,
but a man that hath lived peaceable for these thirty years, with my wife and family,
as those that have been, and are my neighbours, can testify;
and such as have been conversant with me have given it under their hands:
I desire their certificates may be read in court.

[.discourse-part]
_Judge._--That will be to little purpose for you;
you must take the oath or you cannot be discharged.

[.discourse-part]
_John Whitehead._--I desire thee to look upon the certificates,
they being attested to be from credible persons,
by justices of the peace and other officers,
and maybe will give the court satisfaction without an oath,
that I am not such a person as I was accused to be;
and therefore I desire they may be read.

[.small-break]
'''

This was not granted: but being pressed thereunto,
the judge and some of the justices looked on them one by one, read some part of them,
and then returned them to me again.

[.offset]
The certificates offered to the court were,--

[.embedded-content-document]
--

[.numbered-group]
====

[.numbered]
I+++.+++ _A Certificate from the Parish of Swine._

[.small-break]
'''

These are to certify all persons whom it may concern, that John Whitehead,
of Stinks House, in the parish of Swine, in the middle bailiwick in Holderness,
in the East Biding of Yorkshire, hath lived in good credit amongst his neighbours,
in the same parish, for about thirteen years last past,
having a wife and family amongst us;
and hath ever demeaned himself peaceably amongst us his neighbours;
and was never suspected to be a Jesuit or Papist, nor any way popishly affected:
all which we certify under our hands 1628.

[.signed-section-signature]
Jos.
Micklethwait, Jos.
Godall, Vicar, Rob.
Finton, Church-warden, Jo. Carrick, Church-warden, Rob.
Carrick, Chief Constable, Ralph Rand, Will.
Carrick, Will.
White, George Carrick, John Linsley, John Dunn, Tho.
Vollies, Rich.
Hinds, Robert Wood, Ed. Linsley, Clerk, Stephen Barron, Luke Fiddell, Ezekiel Carrick,
Thomas Atkisson, John Presly, Rob.
Buttey, Ed. Fennecke, Tho.
Carrick, Const.

[.numbered]
II. _A Certificate from some of the Inhabitants of the Constable of Oustwick and Hilston._

[.small-break]
'''

We, the inhabitants of the constable of Oustwick and Hilston, do certify and declare,
that John Whitehead was an inhabiter, with his wife and family, amongst us,
for the space of about sixteen years, beginning in the year 1653,
and ending in the year 1669, during which time he lived peaceably,
and in good credit amongst us that were his neighbours;
and was neither suspected to be a Jesuit, nor popish recusant,
nor any ways popishly affected.
Witness our hands the 23rd of June, in the year of our Lord 1682.

[.signed-section-signature]
John Linwood, Mar.
Blonnt, John Blonnt, Robert Thorpe, Will.
Thew, Rob.
Bluntt, Rob.
Sheils, Walter Johnson, Isaac Stoe, Josh.
Stoe, inhabitants of Oustwick and Hilston, J. Snaith, Constable, F. Jackson, Constable,
Tho.
Raven and John Cannam, Overseers from the Poor for Oustwick and Hilston.

[.signed-section-context-close]
Hull, the 23rd of July, 1682.

Memorandum, that the day and year abovesaid, Thomas Horneby, of Hilston, came before me,
Christopher Richardson, deputy-mayor of Kingston-upon-Hull, and gave oath before me,
that he saw all the men, whose names are above-written, by them subscribed,
or set their marks, to this present certificate; and this I do attest for truth,
witness my hand, and seal of my office of mayor, on the day abovesaid.

[.signed-section-signature]
Christopher Richardson.

[.numbered]
III+++.+++
_A Certificate similar to the foregoing, as to John Whitehead`'s character, from Kelk._

[.numbered]
IV+++.+++ Ditto from Scarborough.

[.numbered]
V+++.+++ Ditto from Whitby.

[.numbered]
VI+++.+++ Ditto from York.

====

--

After these certificates were viewed by the Court they were returned to me.

[.discourse-part]
_Judge._--They do not clear you from being a Quaker and a preacher;
therefore I cannot take them for satisfaction, but must tender you the oath:
and if you refuse to take it then you incur the danger of premunire,
and must be put out of the king`'s protection and lose all your goods and chattels forever;
and live in prison all your days, unless the king be graciously pleased to pardon you.

[.small-break]
'''

He then read this part of a clause of the statute made in the 3rd of King James, cap.
4.: "`And if the said person or persons, or any other person whatsoever,
other than noblemen or noblewomen of the age of eighteen years or above,
shall refuse to take the said oath,
being tendered unto him or her by the Justices of Assize and Jail Delivery in open Assizes,
or the Justices of Peace,
or the quarter part of them in their said General Quarter Sessions;
every person so refusing shall incur the danger and penalty of premunire,
mentioned in the Statute of Premunire,
made the 16th year of King Richard the Second,`" etc.

[.discourse-part]
_John Whitehead._--That was not the matter I was imprisoned for to answer unto,
but to the thing charged against me in my mittimus.
Refusing of the oath was no part of the charge in my mittimus:
and it those things cannot be proved against me, I ought to be acquitted,
and no new matter insisted upon until I be tried, and either acquitted or condemned.

[.discourse-part]
_Judge._--You shall be acquitted from all that was charged against you;
and if you will take the oath of allegiance you shall be cleared,
and set out of the gates.

[.discourse-part]
_John Whitehead._--I understand not that a first tender of the oath should be in court,
for this reason:
because it is against the form of the statute and order of law prescribed and limited,
both in the 3rd of King James, cap. 4. even in relation to popish recusants,
and in the 7th of King James, cap. 6, more general,
whereby the first tender of the said oath is not
directed to be made in open Assizes or Sessions,
but contrariwise, the first tender out of court;
and commitment of the party or persons refusing until the next Assizes,
or General Quarter Sessions, where the said oath shall be again required;
which "`again`" relates to the second tender in open Assizes
or Sessions after the first tender out of Sessions.
See the first part of that clause read in court in the 3rd of King James, cap. 4.
to which agrees the Statute of the 7th of King James, cap. 6.
In relation to the first tender being made out of Sessions in these words, viz.:
"`Where the said oath shall be again,
in the said open Assizes or Sessions required;`" which "`again`" likewise follows the
commitment of the party for refusing on the first tender made out of Assizes or Sessions,
as the law directs:
and that clause "`any person whatsoever`" is left out in the 7th of King James,
and therefore ought not to be so severely urged.

[.small-break]
'''

Here Henry Burrel, the justice who committed me to prison,
being upon the bench at the judge`'s right hand, said,
"`Did not I tender you the oath when I committed you?`"

[.discourse-part]
_John Whitehead._--I hope thou wilt not say thou didst.

[.discourse-part]
_Justice._--But I am sure I did tender it to you.

[.discourse-part]
_John Whitehead._--That is not true--interrupted by some under clerks,
when I would have said,--as thou knowest in thy conscience;
thou neither readest it to me, nor gavest me the book.
And all that were present may be witnesses against thee;
and likewise the mittimus by which thou committedst me is a witness against thee,
under thy hand and seal;
wherein is neither mentioned the tender of the oath nor yet my denial.

[.discourse-part]
_Judge._--It was no matter whether it was tendered before or not;
(and overruling the reasons before-mentioned,
said) I can tender it to any person in court; and therefore I will tender it to you.

[.small-break]
'''

So he bade the clerk read the oath, and it was read accordingly,
and the judge pressed me to answer directly, whether I would take it or no.

[.discourse-part]
_John Whitehead._--I do not dislike the allegiance due to the king, but have practised it,
and do ever intend to perform my allegiance as becomes a true Christian and good subject.
But I do really scruple to swear in any case in obedience to Christ,
yet am willing to give what satisfaction I can;
and for that cause have drawn up a paper which I desire to read,
and am willing to subscribe,
by which I acknowledge and declare what is required
by the oath to be acknowledged and declared,
only leaving out the words, "`I swear,`" and such words as are in the nature of an oath.

[.discourse-part]
_Judge._--Read your paper.

[.small-break]
'''

I then read to the court my Declaration of Allegiance, and offered to subscribe it.

[.discourse-part]
_Judge._--I cannot accept of it, I have no warrant by law to do it:
and both I and you must be bound by the law; but I see you have a copy of the oath,
consider of it till the morning,
and then give your answer whether you will take it or not.

[.small-break]
'''

I acknowledged that a civility to me, and so was dismissed for that time.
Next morning I was not called into the court,
for the judge proceeded to the trial of traitors, murderers,
felons and other malefactors.
And after they were tried and sentenced,
upon the 2nd day of the Sixth Month the grand jury were called and placed in court;
and I was again brought before the judge.

The judge asked me again if I would take the oath of allegiance?

A counsellor being in the court,
who had been spoken to by some of my friends to move the judge in private, did,
beyond their expectation and without my knowledge,
plead with the judge on my behalf in court.
But he stood so near him and spoke so low,
that his reasons and allegations were not heard by us,
and therefore an account of them cannot be given; but whatever they were,
it seems the judge would not admit them,
appearing determined beforehand what to do against me;--which,
how contrary that is to law and right, let the wise in heart consider.

[.offset]
Then I said, I desire to be heard.

[.discourse-part]
_Judge._--I will hear you if you will come to the point.
Here is an indictment drawn, and if you will not take the oath,
the grand jury will find it against you,
and then you incur the danger and penalty of premunire.

[.discourse-part]
_John Whitehead._--I hope the court hath considered what I have offered before,
when I was in court the other day,
for the clearing of my innocency from those aspersions
that have been cast upon me when I was committed,
by which I have been much wronged already, and have suffered close imprisonment:
therefore I desire I may have right and justice done me according to law,
since my accusers prove not the matter wherewith they have charged me.
But my innocency is cleared from that foul aspersion which hath been cast upon me,
in saying, I was a Jesuit and a seducer of the king`'s subjects.
No witness hath appeared in court that durst affirm
they ever saw or heard me speak in a meeting;
and the certificates I produced the other day in the court,
which were under the hand of those who have been and are substantial neighbours,
whose credit is attested by justices of the peace under their hands and seals,
do sufficiently clear me, both as to my principles, that they are not popish,
and my practice, that it hath been peaceable.
So that there is no reason why I should have an oath tendered me,
seeing I have done nothing that may give just occasion
why my allegiance should be called in question:
for I appeal to the court and whole country,
where is there any person that hath any matter of sedition or false doctrine,
or any other thing unbecoming a Christian and true protestant subject,
to lay to my charge.

No man appeared upon this my solemn appeal to the court and country,
that did or could justly charge me either with sedition, false doctrine,
or the breach of my allegiance.
Let sober-minded unbiased men judge,
whether by due course of law I ought not to have been cleared, as the common usage is,
to clear others, when no man can have aught to say against them.

[.offset]
Here the judge began to accuse me.

[.discourse-part]
_Judge._--You are a man that travels up and down preaching, and goes to London and about,
to gain proselytes and mislead people;
therefore the king had need to have some special security for your allegiance;
and the law hath provided that security, and I can accept of no other.
Therefore if you will take it you may have your liberty;
otherwise the grand jury are there to take notice,
and will indict you for refusing of the oath, and then you must lie in prison.
Clerk, read the Oath of Allegiance.

[.small-break]
'''

The which the clerk did then audibly read,
and the marshal offered the book for me to swear upon, which was not offered before.

[.discourse-part]
_John Whitehead._--He that is my judge ought not to be my accuser,
for I am a freeman of England, and have right to travel in any part of this nation,
behaving myself peaceably.
And our law saith, "`No freeman shall be taken nor imprisoned,
or be disseized of his freehold or liberties, or free customs, or be outlawed or exiled,
or any otherwise destroyed; we will not pass upon him nor condemn him,
but by lawful judgment of his peers, or by the law of the land.
We will sell to no man, we will not deny or defer to any man, either justice or right.`"
Therefore I desire that I may have due process of law,
and that right may be done me--that the matter for
which I was accused and imprisoned may be tried,
and the wrong I have already sustained may be redressed--and that
one injury done unto me may not be made the foundation of another,
by tendering an oath to ensnare me, who do not dislike the allegiance,
but have already offered to declare and subscribe the substance of that oath,
which I am now ready to do again;
and if any of you can convince me that it is lawful for me to swear any oath,
I will not refuse the oath of allegiance.

[.discourse-part]
_Judge._--I tell you that an oath is for deciding of controversies, and ending of strife:
the law saith, you shall swear, and I must require it of you;
give a positive answer whether you will take it or no.

[.discourse-part]
_John Whitehead._--Though in the time of the law, men might swear,
and an oath for confirmation was to them an end of strife: yet now since the law,
all oaths are forbidden, as appears by the words of Christ Jesus,
whom we ought to hear in all things; for he prohibited not only profane, vain oaths,
which do now abound in the nation, but also solemn oaths; for he saith,
"`It hath been said by them of old time, Thou shalt not forswear thyself,
but shalt perform to the Lord thine oath;`" which
you may observe was not a vain oath in communication,
but for such as were of weight to be performed to the Lord.
"`But I say unto you, swear not at all:`" which, doubtless, the Apostle James,
as well as we, did understand to be an absolute prohibition,
and therefore he seconds it on this wise, "`Above all things, my brethren, swear not;
neither by heaven, nor by earth, nor by any other oath;
lest you fall into condemnation.`"

[.discourse-part]
_Judge._--Do you think that you are wiser than all
that have been before you since that time,
that you undertake to stand against that which hath been
the practice of all nations for these sixteen hundred years,
and before?
For my part I should be loth to condemn that which hath
been the practice of the christian world so many years;
for without an oath justice will be obscured, and cannot proceed.

[.discourse-part]
_John Whitehead._--An oath doth not always oblige men to speak truth;
and justice may proceed if truth appear, with or without oaths.
Nor are we alone in our refusing to swear; for many ancient Christians,
and some Protestant martyrs, as William Thorpe, the Waldenses, Albigenses, and others,
were of the same mind with us, if history may be credited.
In the first ages of the church it was enough to say, I am a Christian.

[.discourse-part]
_Judge._--I will not stand to dispute it farther with you.
If you will not take the oath which hath been tendered to you,
the grand jury shall go forth,
and then they will subscribe the bill of indictment that is drawn against you,
and you must lie in prison.

[.discourse-part]
_John Whitehead._--I desire to know whether it be a first
or a second tender of the oath that I am to answer to,
that things may be cleared as we go;
that the grand jury may understand in what condition I stand,
and I may not be ensnared to give an answer before that be cleared.

[.discourse-part]
_Judge._--I tendered it before unto you in court on Monday you know,
and it is now tendered to you again.

[.discourse-part]
_John Whitehead._--I know it was read in court then,
and I had time given till my appearing again to give my answer,
whether I would take it or no.
And I hope the court will take notice I have offered
several reasons why it should not be tendered,
and have several reasons to offer, why I should not be proceeded with upon that statute,
that makes the refusal of the oath in court a premunire;
because that punishment is too severe and great for such as refuse
not that oath for any disloyalty or dislike of government,
but for conscience-sake; as appears by the preamble of the statute,
made in the third year of King James, cap.
4, which was made against papists upon occasion of the powder plot,
by which the nation was grieved and exasperated;
and therefore they provided that severe penalty of premunire
against popish recusants who refused the oath of allegiance;
which is indeed fit for none but rebels and plotters against the government,
or such who are at least treacherous in their principles,
and ready to entertain any treasonable design or practises against the government,
and to purchase bulls from Rome against the king`'s regality and dignity.
And therefore the parliaments holden the 13th and 14th year of this king,
made another law against refusing to swear, and maintaining that an oath is unlawful;
which, as appears by the said Act,
is a fine not exceeding five pounds for the first offence;
and a fine not exceeding ten pounds for the second offence; and banishment,
if the king be pleased to give order, for the third offence.
I think the judge is as much obliged to execute this law, as the other;
and ought rather to proceed by this latter statute than the other,
which was not made against us;
because the penalty in this is more suited to the quality of the offence, so called;
as all punishments ought to be according to the nature and practice of the offence.

[.discourse-part]
_Judge._--The indictment is drawn for refusing the oath of allegiance,
and shall not be altered;
for I will proceed upon that statute which hath been read to you,
wherein the oath is contained.

[.discourse-part]
_John Whitehead._--I understand not why an indictment
should be drawn for refusing the oath,
when I had not time given me till now, to answer, whether I would take it or no.

[.discourse-part]
_Judge._--Do not trifle with the court: but if you will take it, take it;
otherwise the jury must go forth and file the bill against you.

[.discourse-part]
_John Whitehead._--The will of God be done.
I have served Christ Jesus my Lord and Master these thirty years,
and I see no cause why I should depart from his precepts.

[.small-break]
'''

The grand jury withdrew;
and in about half an hour`'s time returned and delivered a bill against me.
Then by order from the judge I was taken away; and did neither hear my indictment read,
nor was asked any farther question; but expected to have been called again,
that I might have heard my indictment, and have had liberty to plead to it;
but nothing farther was done concerning me in court.
Notwithstanding, in the calendar this return was made:
"`John Whitehead to lie in jail being convicted of
a premunire for refusing the Oath of Allegiance.`"

Upon the whole matter, which is here impartially communicated,
according to the best notice which was taken of the
proceedings of the court in this case,
the reader may observe,

[.numbered-group]
====

[.numbered]
_First,_--That I was taken and imprisoned upon a groundless
suspicion and suggestion that I was a Jesuit;
and that, seeing no man could of his own knowledge say any thing against me,
according to due process of law I ought to have been cleared by proclamation,
as is usual in all criminal cases.

[.numbered]
_Secondly,_--That the judge seemed determined against me beforehand,
and resolved to tender me the oath of allegiance;
for so his marshal informed me before I was called into court;
and from that determination the judge would not be driven by either law, reason,
or the testimony of my neighbours,--men of good estates and credit;
but would either force me to violate my conscience,
or ruin me and my distressed wife and family.

[.numbered]
_Thirdly,_--Whether I be not more to be credited upon my promise of allegiance,
which I offered to subscribe, according to my principles and conscience,
than if contrary to both, I had sworn thereunto?
and whether the judge would have made an oath the condition of my liberty,
but that he was persuaded it was a snare that would hold me in prison?

[.numbered]
_Fourthly,_--Whether I be legally imprisoned;
seeing there was no manifest and positive denial to take the oath of allegiance;
though many reasons why it should not be required of me,
and why I could not swear at all in any case;
since the statute of the 13th and 14th of Charles the Second doth not say a man shall
be imprisoned for refusing of an oath and maintaining that it is unlawful to swear,
till he be fined, not exceeding five pounds,
and that fine not paid in a week`'s time--then the
law directs that the party so refusing or maintaining,
shall be imprisoned, not exceeding three months?

[.numbered]
_Fifthly,_--Whether it did not show a great deal of cruelty
and severity in the judge to decline this statute,
made on purpose against the people called Quakers,
and proceed by a statute made against Papists,
a people that were then reckoned to be false in their hearts to the king and government,
and had provoked the three states of the realm by the powder plot?
and whether there ought not to be a difference put between those
who refuse to take an oath in obedience to Christ`'s command,
and those who refuse the oath of allegiance from a dislike of the government,
that they may favour and set up a foreign power?

[.numbered]
_Sixthly,_--Let it be considered,
whether these severities against persons who are real Protestants,
be not a wide door opened to let in popery?
and whether, whilst ignorant people are told from the seat of justice,
that Jesuits are amongst the Dissenters,
hereby Dissenters may not be exposed to the fury of the nation,
which hath so lately been incensed by the machinations of Jesuits?
And whether, whilst innocent men are prosecuted and imprisoned as Jesuits,
without remedy or redress, those that are really such,
have not a brave opportunity to carry on their design,
and bring the nation to popery and slavery or ever they are aware?
Consider this,
all ye that seem so zealous for the Church of England--how
safely they may work amongst you,
and wrest your power from you, whilst you are looking for them where they have no place,
and daily disobliging your friends.

[.numbered]
_Seventhly,_--Let it be observed and advised upon,
whether a man can be legally returned in the calendar by the judge,
convicted of a premunire (though indicted or presented by the grand
jury) when the prisoner hath never heard his indictment read,
nor been called to answer, whether guilty or not guilty;
and whether that issue ought not to be tried by another jury,
before there can be a lawful conviction or attainder of premunire?
And whether without such judgment and sentence pronounced thereupon in open court,
he can be put out of the king`'s protection,
his goods confiscated and his body imprisoned, during the king`'s pleasure?
So where lies the remedy for the prisoner, on earth or in heaven?
He hath promise from God Almighty--"`Because thou hast kept the word of my patience,
I will keep thee, from the hour of temptation, which will come upon all the world,
to try them that dwell upon the earth.`"--Rev. 3:10.

====

[.embedded-content-document.letter]
--

[.blurb]
=== Here Follows the Copy of a Letter, Sent to the Judge After He had Returned the Calendar, which was Delivered into His Own Hand.

Consider in the fear of God,
in whose hand is thy life and breath,--whether that which thou hast measured unto me,
thou wouldst have measured unto thee again.
Wouldst thou not think it very hard measure, if one injury were done unto thee,
not only to be denied a redress, but to have that injury made the foundation of another?
And yet so hast thou done unto me,
and denied me that right which thou hast granted to the worst of malefactors.
For if the matter charged against them was not proved, then didst thou acquit them;
and in so doing thou didst well: but although nothing was proved against me,
and the direct contrary to what I was charged with was proved by me,
and my innocency manifested by good and sufficient testimonies,
yet wouldst not thou acquit me;
but on purpose because thou understoodst I could not swear,
thou tenderedst unto me an oath,
that thou mightst either force me to violate my conscience,
or else ruin and destroy me and mine, as to the comfort of this life.

Well, the Lord, whom I serve, will judge between thee and me;
and where thinkest thou to stand and appear at that day,
when those that have not visited his servants in prison, etc.,
shall have this dreadful sentence, "`Depart from me into everlasting fire,
prepared for the devil and his angels;`" since thou art one that, contrary to all right,
hast imprisoned me, and that for keeping the commands of Christ?
If they shall have judgment without mercy, that have showed no mercy,
then how great shall thy judgment be, who hast showed no mercy at all,
but turned the poor from his right?
Consider these things whilst thou hast time,
and repent of all thy false suggestions and hard speeches against the people of God;
if peradventure thou mayst find mercy,
and have thy heart purged from that uncharitableness,
hatred and prejudice that lodgeth in thee against
those that dissent from thy manner of worship.
And think not by force and cruelty to win them unto thy way;
but remember that in all ages, persecution, which was ever blind,
hath increased the number of the persecuted:
and those that have been as fierce as thou in their day,
have wearied themselves and repented.
I desire thou mayst not do it too late, but whilst mercy may be obtained;
for I do really desire thy salvation, though thou hast sought to ensnare and ruin me.
And think not to cover thyself with saying,
"`It is the law that doth it;`" for by the due process of law I should have been quit,
and yet of right ought to be so; which if thou refusest to do, yet I shall rest in peace,
and commit my case to the just Judge of heaven and earth, who will reward thee,
and all that had a hand in my imprisonment, according to their works.

[.signed-section-signature]
J+++.+++ Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 3rd day of the Sixth Month, 1682.

--

+++[+++Thus without regard to law, justice, reason, or humanity,
was this innocent man condemned to endure the grievous
privations consequent on a sentence of premunire.]
