== Chapter XII.

John Whitehead and others fined at Fulbeck--The case of Mary Waterman--John
Whitehead`'s Letter to her persecutor--Taken from Devonshire House Meeting,
London,
fined and imprisoned--An Epistle to Friends--Minutes
and Testimonies concerning John Whitehead--Conclusion.

+++[+++Of how long duration this last imprisonment at Lincoln proved to be from its commencement,
has not been clearly ascertained.
Gough, in his History of the People called Quakers,
after stating that John Whitehead "`was convicted and premunired,
and in consequence cast into prison,`" adds,
"`where it is supposed he was detained until the general release in 1686.`"

At whatever time he was fully released,
it appears that he was out of prison in the Fifth Month, 1684.
For on the 3rd of that month he attended a meeting for church
affairs at the house of the widow Joan Wray,
of Fulbeck,
"`not pretending nor intending public worship,`" (according to
the Monthly Meeting Record,) "`but to consider wisely of the poor,
fatherless, and widows amongst us, and to supply their wants,
as every one stands in need; and this is a blessed work,
and thus we have done every month in the year for many years,
that the several parishes where they dwell may not be chargeable with them.`"

Information of this meeting was given to Justice Thorold, of Grantham,
by a woman who used to travel about the country begging and blowing a horn.
Upon the report of this vagrant, the said Thorold and Justice Berisford of Lednam,
came to the meeting,
and found John Whitehead exhorting his friends to charity and liberality,
suitably to the occasion of their meeting.
The justices took the names of most that were present,
and fined them in all to the amount of £72 13s. 2d.

The widow at whose house the meeting was held,
had taken from her ten beasts and thirty-eight sheep,
worth £41. These were driven from market to market, but nobody would buy them.
At length one Edward Wright redeemed them, by paying the fine of £20,
without her knowledge.

Two Friends were fined £5 each, "`for the pretended poverty of John Whitehead.`"

It also appears that John Whitehead was at liberty towards the end of the year 1685; as,
according to Besse`'s account of the Sufferings of Friends in London, he was,
on the 11th of the Twelfth Month in that year, with nine other persons,
taken from Devonshire House Meeting, and carried before the Lord Mayor,
under whose cognizance some of them were bailed, and others sent to prison.
At the next Sessions they were indicted for a riot, and fined 13s. 4d. each.
It would appear that John Whitehead was one of those who were bailed,
and that he was committed to Newgate at the Sessions, for nonpayment of the fine;
as he was, with some others who were apprehended with him,
discharged from that prison on the 2nd of the Fourth Month, 1686;
and he had then been in prison only about seven weeks.

It may be concluded that John Whitehead was not, when at Fulbeck, as above related,
fully discharged from prison, but only at liberty for a short time on sufferance,
from the circumstance that he was for some time a
fellow-prisoner with the widow Mary Waterman,
of Skegness, who, after having been in prison about three months at Orby and Alford,
was removed to Lincoln Castle in the Eighth Month, 1684.
This faithful woman was taken prisoner by an attachment for tithes,
at the suit of Thomas Tomson, priest of Skegness;
and died a prisoner for her testimony on the 19th of the Second Month, 1687.
Near her departure, she told John Whitehead, she was glad she came thither to die.

After her decease, a short account of her hard usage and peaceful close was drawn up,
to the following purport:--]

A True Relation of the Sufferings and Death of Mary Waterman, of Skegness,
in the County of Lincoln, Widow, Who Died in Prison at Lincoln,
the 9th Day of the Second Month, called April, 1687, for Her Testimony Against Tithes.

After some vexatious proceedings had been taken in the county court, by Thomas Tomson,
priest of Skegness, against the said Mary Waterman and Peter Waterman, her eldest son,
(who was joint executor of her husband`'s will,) because
for conscience-sake they could not give him tithes,
the said priest caused to be taken away from them goods to the value of about £20,
by a distringas.
But this proceeding being contrary to law, they recovered those goods,
although with much charge.
After this, and whilst the priest was prosecuting them in the Exchequer,
Peter Waterman died.
Subsequent to his death, the widow, his mother, by an attachment,
was taken prisoner at the said priest`'s suit on the 19th of the Fifth Month, 1684,
kept in prison at Orby and at Alford till the 17th of the Eighth Month in the same year,
and then by the procurement of the priest, brought to Lincoln Castle.
Whilst a prisoner there, the jailer, encouraged by the king`'s proclamation,
gave her some liberty; but the priest, through his attorney,
threatening the sheriff and jailer for granting this indulgence,
she was remanded to prison.

The attachment upon which she was in custody,
being weakened in consequence of a pardon having been granted to contempts,
a second attachment, bearing date the 19th of the Fifth Month, 1686,
was delivered to the jailer.

The priest, who appeared intent upon the total ruin of Mary Waterman and her family,
proceeded to prosecute Robert Waterman, her second son,
who was with her as a servant and managed her business;
and by another attachment out of the Exchequer, on the 16th of the Sixth Month, 1686,
the said Robert was arrested,
and the day following became a fellow-prisoner with his mother in Lincoln Castle,
although he was not a joint executor with her,
and therefore not liable to the claim of the priest for tithes.
He was, however, through the kindness of the sheriff and jailer,
allowed some liberty to go home and attend to his business.

During the latter part of Mary Waterman`'s imprisonment, she was,
through the procurement of the priest, kept more close, and in a smoky room.
There she grew weaker and weaker, till she died on the 19th of the Second Month, 1687.

In her sickness she often thanked God,
that he had strengthened her to give up her life for her testimony against tithes.

+++[+++This severely suffering case of Mary Waterman,
called forth John Whitehead`'s strong and tender sympathy;
also the expression of sharp rebuke and solemn warning to her persecutor,
as appears by the following letter addressed to him a few days after her decease:--]

Friend Thomas Tomson,

I thought good hereby to let thee know, that Mary Waterman, that desolate widow,
whom thou hast been long pursuing with one vexatious suit after another,
died the 19th day of this month, being kept close at thy suit.
Therefore search and see, whether in thy skirts will not be found her blood,
when the Lord shall make inquisition,
and give that heavy doom pronounced in Matt. 25:41, to the end of the chapter,
on those who have not visited his servants in prison.
O! where wilt thou appear in that day,
who didst keep that innocent woman in prison for tithes;
or to which of the saints wilt thou turn, to find an example for thy horrid actions!
None of the priests under the law, except those two wicked sons of Eli,
Hophni and Phinehas, who both fell in one day, did ever force their maintenance.
And among the ministers of the Gospel whom Christ sent forth, and directed,
"`Freely ye have received,
freely give,`" neither tithes nor forced maintenance was
so much as mentioned to be received for several ages.
Therefore be ashamed of thy wickedness and hardness of heart,
and repent whilst the Lord gives thee time and space,
that this thine iniquity may be blotted out, which is the desire of

Thy soul`'s friend,

John Whitehead.

Written the 26th of the Second Month, 1687.

P+++.+++ S. And let thy repentance be manifest by discharging her son Robert,
who hath been wrongfully detained by thee, though not joint executor with his mother.

+++[+++As far as appears from any record, John Whitehead`'s imprisonment in Newgate,
as before related,
is the last portion of the sufferings he had to endure for conscience-sake;
neither has any thing been found written by him later
than the foregoing letter to the priest of Skegness,
unless the following lively Epistle, without date, be an exception.]

An Epistle Given Forth by John Whitehead

Dearly Beloved Children, And Plants Of The Lord,

My life and dear love is shed abroad amongst you, and doth salute you,
and reach you all in the spirit;
breathing that you may be kept in the fear and council of God,
to grow up in the pure life, wisdom, and power of Christ Jesus,
in whom "`all fulness dwells.`"
All of you abide and wait in your measure of his Light,
that you may receive of his fulness, and be fed with the living food,
and watered with the tender mercies of the Lord; that so you may grow,
having branches to bring forth much fruit, and be kept green and tender,
in the pure and unfeigned love, to have unity one with another;
being kept together in the Spirit, as members of the same body,
of which Christ is the Head.

And as every one of you in particular comes to abide and dwell in the Light and love,
you will grow daily into a pure care and dearness towards one another,
and into a pure sense and feeling of one another`'s burdens and infirmities:
so that if one member suffer, you will all come into the suffering with it;
and if one be had in honour, all to rejoice with it;
and if any be in danger to be corrupted or ensnared through the deceitfulness of sin,
and the rage of your soul`'s enemy,
who continually seeks to devour,--then you that are
preserved in the life and power of the Spirit,
are to watch over the other, and in all tenderness and long-suffering,
seek to preserve and restore them;
that so the enemy may not get advantage of any one member to separate it from the body;
but that all of you in the virtue, power, and life of Christ,
may grow in the pure union and love,
really to do to each other as you would be done unto.

Let nothing rule amongst you but the Spirit of the Lord Jesus,
which throws down all high thoughts and conceitedness;
which Spirit (you all submitting to be guided by it,) will lead you to the rock,
whence you were hewn, and will establish you on the sure foundation,
that the gates of hell shall not prevail against you;
but in the power of Christ Jesus abiding,
you will witness the victory over hell and death,
and trample them under foot in the life and love of God;
and therein shine forth a glorious church,
to the praise of Him who hath called you out of darkness into his marvellous Light.

And all amongst you, whose minds are turned towards God,
and are seeking his kingdom and the righteousness of it,
and have breathings and thirstings begotten in you
to be taught and refreshed by the Lord;
take heed of looking out from the Light of Christ,
which is the Light of the kingdom given to guide you into it, lest your hearts be veiled,
and your minds blinded by the god of this world,
who would draw your minds out to delight in earthly, perishing objects,
and thereby bring you into carelessness and a carnal security;
then iniquity will come to abound, and the love and the desires which breathe after God,
will grow cold and be choked with the cares of this life,
and your souls will grow barren and dry for want of refreshment.
If you mind not your watch, to dwell in the light,
the devil will lead you to and fro in earthly thoughts and imaginations,
which will fill you with unbelief and hardness of heart,
and cause you to faint and grow weary of seeking after God.
But dear hearts, all to the measure of Light keep,
and be faithful to that of which you are convinced, and obey it;
so will your desires towards God be strengthened, and your souls daily refreshed,
and pure teaching you will come to find, and know the wiles of the enemy;
and the working of the mystery of iniquity will be made manifest.
The Light which reproves you for sin and calls for purity and holiness,
which Light is a perfect guide, is ever present with you, lying down and uprising;
it shows you the thoughts and intents of your hearts,
that so you may flee from that which is evil and cleave to that which is good.
Therefore to it be faithful; and take heed of halting between God and the world,
lest you turn from serving Christ, and become men-pleasers, and so get into formality,
and there rest in a conforming to the Truth in outward appearance and profession,
but not in heart, and thereby lose the Guide;
and then in feignedness and deceit walk by imitation,
that you may appear to be something before men, which is the hypocrite`'s state.

Therefore let all that be judged and denied by the Light which enables to walk single,
true and upright; then will you become lively,
bold and undaunted in the power of the Lord;
not hasty nor forward to act any thing in your wills;
but in meekness and patience you will wait on the Lord for
his pure wisdom to guide you in all your ways.
And patiently waiting on him, you will come liberally to receive of his fulness,
both of the wisdom, knowledge and love of God, which will refresh your souls,
and keep you from weariness and fainting in the way.

Therefore lift up your heads in the power of the Lord,
and be faithful in meeting together in his fear, to wait upon him;
watch one over another in his Light and love,
and build up one another in your most holy faith: that so in the faith you may be kept,
and the weak hands strengthened, the feeble knees confirmed,
and that which is lame be helped and kept in the way;
so will you grow up together in the power and love of God, whose presence is amongst you.
His everlasting power keep and preserve you faithful to the measure of his Light,
that therein you may be kept in the unity of the Spirit and bonds of peace,
where I am present with you in spirit,

Who am your dear brother in the unchangeable Truth,

John Whitehead.

+++[+++We now approach to the period when this faithful labourer
in the Lord`'s vineyard was called to his rest.

Had he kept a continuous journal of his life,
doubtless much more than has now been related of
his travels and services as a gospel minister,
might have been presented to the reader:
and it is probable that the blank intervals which occur in this compilation,
would have been occupied by narrations and remarks fraught with interest and instruction.

That John Whitehead was preserved alive and vigorous in the Truth,
and fervent in concern for the welfare of the church to the end of his days,
appears by the testimonials of some of his contemporary friends which follow:--

The Records of the Monthly and Quarterly Meetings in Lincolnshire,
of which John Whitehead was a member,
bear copious evidence of his usefulness and zeal in promoting
the faithful maintenance of our Christian discipline.
During the last ten years of his life he filled the
office of clerk to the Quarterly Meeting.
After his decease,
his surviving friends recorded the following short
notice of his valuable services in the church:--]

At a Quarterly Meeting, held at our Meetinghouse in Lincoln,
the 30th day of the Seventh Month, 1696, It +++[+++hath]
pleased the Lord, a day or two ago, to take from amongst us by death, his servant,
our elder brother, dear John Whitehead; who, in his day and time,
was raised up of the Lord in the work of the ministry
of the Gospel of our Lord Jesus Christ,
and therein was serviceable in the Lord`'s hand,
to turn many to the truth and right way of the Lord:
and many that are yet alive can bear testimony hereunto,
and can praise the Lord our God on his behalf: so he now rests from his labours,
and his works follow him; blessed be the holy name of the Lord our righteousness forever.
Amen.`"

+++[+++The Minutes of York Quarterly Meeting show,
that the sum of £5 was three times presented by that meeting to John Whitehead--once
to defray his expences in attending the Yearly Meeting in London,
and twice "`as a token of Friends`' love.`"

His frequent imprisonments and sufferings of other kinds,
render it not unlikely that he sometimes needed such "`tokens.`"
The following extract may be regarded as a posthumous acknowledgment
of his "`Friends`' love,`" offered in the way of sympathy
towards those who should follow him in Gospel service.]

York Quarterly Meeting, 15th of Seventh Month, 1700.

At this our Meeting, Thomas Aldam brought £15,
being the gift of our friend John Whitehead to our Quarterly Meeting,
and ordered by his last will to be disposed of as a refreshment to poor travelling
Friends who labour in the word and doctrine of our Lord Jesus Christ.]
