== Testimonies Concerning John Whitehead

[.centered]
=== From T. Thompson`'s Testimony

[.embedded-content-document.testimony]
--

John Whitehead, in his latter years, was not able to travel much,
yet he went forth many journeys to visit Friends,
labouring to establish them in the Truth.
For two or three years before his death he was often exercised in weakness,
eating very little; yet the winter before he died he travelled on Truth`'s account.
I met with him at Boston in the Tenth Month, 1695,
and again in London in the Twelfth Month of the same year.
There I was with him in some meetings, also divers times elsewhere;
and I understood he was satisfied, and in unity with Friends,
and manifested his willingness to assist them in the service
and exercise they were concerned in with the parliament,
for the relief of Friends in the case of oaths.
On his return home I met him again at Huntingdon, where we had a blessed meeting;
praises be unto the Lord.
There I parted with him, and saw him no more;
but the remembrance of him is precious to me.

--

[.centered]
=== David Crosby`'s Testimony Concerning John Whitehead

[.embedded-content-document.testimony]
--

This testimony I have in my heart to bear, for our dear,
ancient and worthy friend J. Whitehead.
He was one whom the Lord had fitted,
qualified and enabled to bear part of the burden in the heat of the day,
when many unruly and wicked men did what they could
to stop or hinder that work from being carried on,
that the Lord God of life and power had called him unto.
Yet for all the wicked could do, he,
by the Lord`'s power that he had abilitated him with,
was willing to labour in the work and service that God hath concerned him in;
and the Lord made him very instrumental to turn many from darkness to light,
and from Satan`'s power to God.
For he was a man of such a meek and quiet spirit,
that his life and conversation preached daily to those amongst whom he came.
His words were few, but very savoury, seasoned with the grace that makes not ashamed,
and brought honour to God, and comfort to his people.

I can truly say, that he was very helpful to me and my family.
The first time that I saw him after I was convinced, was at a meeting near us.
Hearing that he was to be there, I went; and that meeting was a good meeting to me,
blessed be the Lord, for he reached my state and condition;
so that from that time to his dying day, I had a great love for him,
and he for me and my family; for he would come and see them in my absence,
and give my dear wife and children a word of counsel and advice,
which was very acceptable to them.
For in that day, I and my poor family met with many trials, and deep exercises;
but when he came to see us, he would tell us, that those things which we met withal,
were but what he, and many more had met withal: and thus encouraged us,
and did us good many a time.
So that I have great cause to bless and praise the Lord upon his account.

A little time before he departed this life I went to visit him,
and right glad we were to see one another.
I told him that I hoped the Lord would enable him
to go abroad and visit Friends once more;
and he answered, If the Lord saw it meet, he could be glad to visit a few meetings;
and then he had nothing to do but to die.
It did me good to hear him say so,
after all the hard usage that he had gone through by wicked men.
He finished his course well: so blessed are they that die in the Lord,
for they cease from their labours, and their works follow them.
This dear servant of the Lord is now out of the reach of all his enemies,
and is at rest and peace with the Lord,
where all the faithful labourers in the Lord`'s word and service desire to be.

[.signed-section-signature]
David Crosby.

[.signed-section-context-close]
Gun-house, the 16th day of the Tenth Month, 1696.

--

[.centered]
=== Stephen Willoby`'s Testimony Concerning John Whitehead

[.embedded-content-document.testimony]
--

When it pleased God in his great love and mercy to visit this nation,
after the dark night of apostasy, with the fresh breaking forth of his everlasting Truth,
in order to make known the way of salvation to the sons of men,
and to reveal the mystery that hath been hid from many generations;
then he was pleased in his heavenly wisdom to choose for his work and service,
to minister to the people, in the breaking forth of the day of his power,
such messengers as were acceptable to himself;
of whom our well-beloved friend John Whitehead was one.
In that day he took his life in his hand--went forth as a lamb amongst wolves,
and travelled on foot through many counties in this nation,
to declare the day of salvation, to bring glad tidings to the poor in spirit,
and to make known, both to the rulers and people of this kingdom,
that God would gather a people to wait upon himself,
and that God himself would be their teacher.
Yea, he to my knowledge did labour and travail both by day and night,
that he might make the gospel without charge; and his care was very great in that day,
to settle meetings for worship in such places as were most
convenient for Friends and others who were of good report.
He visited the poor as well as the rich,
and would sometimes go many miles to visit a poor family that was of good report;
and many were convinced by his ministry,
who with him became great sufferers for the precious Truth`'s sake,
in Oliver Cromwell`'s time, and afterwards, when small meetings were gathered.

His care was very great to preserve peace and unity amongst Friends.
With tender love, and fatherly care he did often visit us;
and he thought no pains too great to gain a soul to God.

In those days he had many disputes, both with priests, professors, and profane;
but the Lord gave him great dominion over them all:
many times some have been convinced at those disputes, turned their back on the priests,
and joined with Truth and Friends; to the praise of God I speak it,
who did appear in this his instrument that he had chosen for his work and service.
So the work of the Lord prospered in his hand, and he was made able,
by the power of the Lord,
to plead the cause of God and his people before rulers and magistrates,
and often was he called thereto.
This service he performed with great courage and boldness,
though with danger of his life or liberty.
I never saw him shrink at any trouble or persecution;
but he stood faithful to God and his people in time of trouble, as in time of peace,
and kept on his way in all seasons, states and conditions.
He often hazarded his life for the Truth`'s sake,--many times in my sight and company.

Thus with hard labour and strong travail he performed his duty to God and his people.
Even as a father taketh care of his children,
so did this elder take care over the flock of God: and as Friends increased,
so his care increased also.
It was not his way to usurp authority over the heritage of God, nor to use any power,
but the power of the Spirit, in the church of God.
His words were always savoury, administering grace to the hearers.
He was slow to anger--a man endued with much patience.
He suffered many long imprisonments without murmuring or repining;
cheerful in sufferings, and often said, "`Through sufferings we must be made perfect;
and in the Lord`'s time sufferings would come to an end.`"
His care was very great in his old age to preserve peace and concord amongst Friends;
and if any difference happened amongst them, he was a man of sorrow for it,
and did take care both day and night, until it was ended: his prayer to God often was,
that the bond of peace might be kept amongst the brethren.
I cannot speak so much of his care for the church as it deserves.

I knew his love to true-hearted Friends; his patience, his innocent life, his meekness,
his humble and lowly carriage cannot be forgotten,
but his good example will be kept in remembrance, and his works will praise him;
according to that saying of the Prophet,
"`The righteous shall be had in everlasting remembrance;
but the name of the wicked shall rot.`"
This in short I have written concerning my deceased friend;
but I know there are some yet living who have a larger
testimony in their hearts concerning him;
and some that were labourers with him in the word
and doctrine--morning stars in the break of the day.
As any of them find freedom to give their testimony, with others in the love of Truth,
concerning this faithful labourer, it may do its service, and be a remembrance,
or show to generations to come,
of the great love and care that constrained Friends
to go through many hardships in the beginning.

[.signed-section-signature]
Stephen Willoby.

[.signed-section-context-close]
Tydd, the 24th day of the Third Month, 1697.

--

[.centered]
=== George Whitehead`'s Account of John Whitehead

[.embedded-content-document.testimony]
--

From a certain knowledge and lively remembrance of the living testimony
he did early and publicly bear for the blessed Truth,
as it is in Christ Jesus; and of the Christian frame and temper of his spirit,
and the comfortable society we have often had together,
I have this account to give:--He knew the Lord`'s power,
and the work thereof in early days,
near the beginning of the breaking forth of the Light
and day of Christ in our age and times.
His labour and travail was to turn and gather people thereunto;
and the Lord blessed his labours of love to the good of many poor souls.
He was also a great sufferer for his Christian testimony by divers imprisonments,
especially his latter imprisonment in Lincoln Castle,
to the impairing the health and strength of his outward man.
And although by that occasion, and the infirmities of age growing upon him,
he became disabled from travelling abroad in Truth`'s service, as he had done,
yet he was enabled to come sundry times to London
when in old age and drawing towards his conclusion;
where he bore living and clear testimonies for the blessed Truth,
to the comfort of Friends at divers meetings, both the yearly and others.

And being a tender and loving man to Friends and brethren,
he manifested his unfeigned love to them;
desiring the peace and prosperity of the whole church of Christ in true unity and concord,
bearing a zealous and faithful testimony against the spirit of enmity and division.
And he being a man of a solid and sound judgment, his ministry was such,
and so both convincing and converting to many.
And as he kept the faith,
I do not question but he attained the end that will
crown all the faithful in Christ Jesus.

[.signed-section-context-close]
London, the 15th of the Fifth Month, 1703.

--

[.centered]
=== The Testimony of Friends, at Thealby, in Lincolnshire, Concerning John Whitehead

[.embedded-content-document.testimony]
--

[.salutation]
Dear Friends,

It is in our hearts, and rests with weight upon our spirits,
to give in our testimony on the behalf of our dearly beloved, ancient and worthy friend,
John Whitehead,
who was one of the first that the Lord raised up and sent
into these parts with the message of life and salvation.
In his first coming forth it was his lot, with many other dear servants of the Lord,
to tread untrodden paths, wherein he met with many hardships and sufferings;
being mocked, stoned,
beaten and imprisoned in divers places for his testimony to the Truth,
enduring with much patience, which crowned him with victory in the end.

He was drawn forth to direct people to the Light within,
and to turn them from Satan`'s power to the power of the living God,
and to preach repentance to all, testifying that the kingdom of God was at hand.
And he declared in order the blessed day of the Lord`'s spiritual appearance,
and the breakings forth of his mighty power in the
hearts of the sons and daughters of men;
and many were reached and some of us convinced through his living and powerful testimony;
though we be but a few of the many that were convinced,
and received the benefit of his spiritual labours.
For the Lord God almighty having endued him with "`power
from on high,`" he became an able minister of the Spirit,
and through the revelation of the mind and will of God to him,
he opened many excellent things to the satisfaction of our long panting and travailing,
weary souls.

His travail also was for Truth`'s prosperity,
and to preserve Friends in love and unity one with another,
in which the Lord blessed his endeavours wonderfully.
His care was great over those that were brought to
the knowledge of the Truth through his testimony;
as also over all those that had received the Truth in the love of it,
for he was instrumental in the hand of the Lord, in turning many to righteousness;
and therefore he does and shall shine as a star in
the firmament of God`'s power forever and ever.
He was a nursing father, tender and affectionate, apt to teach,
ready to inform in all things relating unto the Truth; being grave in counsel,
and sound in judgment;
labouring much in the latter part of his time to settle Friends upon the sure Foundation,
and to establish them in the "`present Truth.`"
He was endued with excellent gifts,
and qualified to speak a word in season to every state and condition.
We that remain are witnesses of the blessed effects of his labour and travail,
both in particular, and in general; for when our exercises were great and heavy,
and we stood in need of his assistance, Oh! how ready,
how willing and able was he to serve us, and to answer all our requests,
and give satisfaction in the thing that we wanted!
We may truly say, our hearts are filled with sorrow to be deprived of so dear a friend,
tender a father and furnished a minister,
as could apply what was suitable to every condition;
which made him truly beloved and honoured in the church of Christ in this county,
and other places where he had travelled: for he was love-worthy,
because the love of God dwelt in him wonderfully, and flowed from him many a time,
whereby he was manifest to be meek, patient, and of the Lamb`'s nature,
not easily provoked, but bearing and forbearing, pitiful and tender,
sympathising with us, and strengthening us under many weary exercises.
The eye that truly saw him blessed him, and the ear that heard him gave witness for him,
that he was an honourable elder, spiritual father, and pillar in the church of Christ,
and kept his station there till his course was finished.

Some of us, the last time we were with him, a little before he departed this life,
heard him say, that he had laboured whilst his strength lasted,
and that now he had nothing to do but to die; and kneeling down,
supplicated the Lord for the preservation of all his people,
committing us with himself into his hand and arm of protection.
The sense of that life, power and presence of the Lord that was then felt,
remains as a testimony upon our spirits, of his well-being with the Lord.
He departed this life, the Twenty-ninth day of the Seventh Month, 1696,
at his dwelling-house in Fiskerton;
and after a large and good meeting with the most considerable Friends in this county,
was buried the first day of the Eighth Month, 1696, in Friends`' burying-place, Lincoln.

Given forth and subscribed by several of us, in behalf of ourselves and others concerned,
at our Monthly Meeting, held at Thealby, in the north parts of the county of Lincoln,
the fourteenth day of the Third Month, 1697.

[.signed-section-signature]
Henry Symson, Robert Wilkinson, William Smith, Francis Dent, Anthony Westoby,
Michael Atkinson, John Nainby, Joseph Wresle, Peter Nayler, Richard Wresle, John Wresle,
James Coakes, Thomas Wresle, Robert Colier, Joseph Richardson, Edward Gilliat,
George Frow, William Williamson.

--

+++[+++In bringing this volume to a close, it may be briefly remarked,
that the serious perusal of it is well calculated to prepare the reader feelingly to
respond to the paragraph appended by T. Thompson to his account of his honoured friend;
which is as follows:--

[quote]
____
O! that the consideration of the dealings of the
Lord may move all that make mention of his name,
to walk faithfully in the Truth; that seeing many of the ancients,
worthies and valiants in Israel are removed and taken from us,
and we are left to finish the work of our day, we may truly lay it to heart,
and labour in the vineyard of the Lord according to the gift received:
that in the ancient power all may be preserved, to grow up a holy people unto God:
that as this honourable servant of the Lord,
(with many others who now rest in the Lord,) in the morning of the day,
did for the Seed`'s sake, pass through and patiently endure many buffetings, beatings,
cruel mockings and scornings, so we also who yet remain, may walk as good examples,
in all faithfulness, patience, meekness and temperance;
that the Lord alone may be honoured, who is, over all, worthy of praise, honour, glory,
and renown, both now, forever and forevermore.]
____
