[quote.epigraph, , Dan. 11:3]
____
And they that be wise shall shine as the brightness of the firmament;
and they that turn many to righteousness,
as the stars forever and ever.
____

== Advertisement

The volume from which the present work is compiled was printed in the year 1704,
under the title of [.book-title]#The Written Gospel Labours of
that Ancient and Faithful Servant of Jesus Christ,
John Whitehead.#
It consists of his Auto-biography, Epistles, and other Writings,
together with several Testimonies concerning him, written by his contemporary Friends.
Some of these documents had been printed prior to the above date, in separate tracts.
When the whole of them were bound together,
but little attention appears to have been paid to chronological order;
and some portions of the biographical matter were detached from the general narrative.

With a view to render the work more perspicuous,
and the perusal of it more agreeable and interesting,
the various parts (excepting a few short pieces and paragraphs,
for the omission of which there has appeared sufficient
reasons) are now disposed in order of time,
so as to form a regularly connected Memoir--some Letters and Minutes,
copied from [.book-title]#The Ancient Records of the Society of Friends in Lincolnshire and Yorkshire,#
are added--and the volume is divided into chapters.

We are informed by William Penn (see the _Preface_) that "`John Whitehead was among
the most eminent of the early Friends for his sound mind and capacity,
great zeal and boldness, and as great humility, patience and labour, in word, doctrine,
and charity.`"
Such a testimony to his Christian character appears fully
to justify the attempt to preserve and to bring into view,
in the most acceptable manner,
these instructive proofs of his love for the cause of Truth,
and of his stedfast desire to promote it.

The title-page of the former edition states that these writings were "`collected
and published for the information of the present and succeeding ages.`"
It was a sentiment very prevalent with the early Friends,
that their "`written Gospel labours`" were designed by "`Him
who is given to be the Head over all things to the Church,`"
to convey edification and encouragement in the way of Truth,
to distant posterity.
It may be acknowledged with thankfulness that abundant evidence
has already been afforded of the soundness of this persuasion;
and we may trust that this evidence will not be permitted to fail,
while these weighty records continue to be duly estimated: for,
as the author of [.book-title]#An Essay on the Christian Doctrine
and Practices of the Early Friends# has well observed,
"`If the things which belong to our peace have due place in our affections,
we shall meditate with pleasure on the experience of those
who have trodden the path of virtue before us.
The fervour of our piety,
the strength of our attachment to religious truth will be
promoted by frequently perusing their excellent writings,
and dwelling in serious contemplation on the bright example they have left us,
adorned with the Christian graces, and inviting us to follow in their footsteps.`"

[.signed-section-signature]
Thomas Chalk.

[.signed-section-context-close]
Kingston-on-Thames, 1852.
