== Preface

It has been the practice of God`'s people in all ages,
to commemorate his goodness to them,
by transmitting to succeeding times a faithful record thereof,
that the unborn generations may be informed of the
foregoing dispensations of God to mankind,
and excited to believe, fear, love, worship and obey him,
who is the great and everlasting God, the Father of Lights,
and the God of the spirits of all flesh.
And since it has pleased him, in the riches of his love, through Christ Jesus,
his glorious Light to the world, to visit our present age, with a blessed, near,
and sensible manifestation of himself,
for the better accomplishing of that evangelical promise,
referring to the glory of the latter days, namely,
that God would write his law in the hearts,
and put his fear and Spirit in the inward parts of the sons and daughters of men;
that he himself would become their teacher, from the least to the greatest,
and that in righteousness he would establish them; yes, he would come so very near them,
as to walk in them, and dwell in them, and they should be his people and temple,
and Christ his beloved Son should be their light,
and he himself their God and glory forever.

And forasmuch as thousands within this northern island,
have been experiential witnesses of his spiritual appearance and work in them,
towards the completing of the aforesaid blessed promises;
and because our dear and beloved ancient brother in Christ, John Whitehead,
some of whose labours follow, was of the first in time, and among the most eminent too,
for his sound mind and capacity, his great zeal and boldness, and as great humility,
patience and labour, in word, doctrine and charity,
we think ourselves engaged to allow nothing to be lost of so valuable a nature.
That is the true and prevailing motive with us,
for publishing the written labours of our departed faithful friends and brethren,
that have run well, been good examples, held out to the end, and at last overcome,
through Jesus Christ, our holy Light and Life, our heavenly Shepherd and Bishop,
the great Captain of our salvation.

In this preface I would caution and inform the reader of some things,
that he may not ignorantly be displeased, or under any reasonable disappointment.

[.numbered-group]
====

[.numbered]
_First,_ then, he is not to expect the learning of the schools,
unless that of the prophets, and of the enlightened and spiritual generations of men,
and of a plain, sound and practical knowledge,
to be felt as evidently by those that are in any measure
restored to the exercise of their spiritual senses,
as darkness was said to be felt in the land of Egypt, may merit the name of learning,
(as to be sure it does in the school of the cross of Christ,) and then
he will not be disappointed in the perusal of the following book.

[.numbered]
Neither, _secondly,_ has this godly author laboured a nice or polished style,
which men usually do, to give a lustre to, or varnish their matter with,
but he writes as an enlightened and experienced man.
It is the way of God to reveal and recommend his dispensations to the world,
by men so qualified, that they know what they teach, and whereof they affirm:
not witnesses by report only, or at second-hand, but such as have seen, tasted,
felt and handled the same powerful Word of God which they declare unto others.
And indeed, who among men would choose a guide, to show him the way to any place,
at which the pretended guide had never been?
Therefore the sons of this morning,
and children of the Light of this day-spring from on high,
spoke and wrote according to the enlightenings thereof,
and the operation of Christ`'s power in themselves, the great Light of the world,
for their conversion, as well as conviction,
according to the saying of the beloved disciple and evangelist John,
"`That to as many as received him he gave power to become the sons of God.`"
So that their religion was from the knowledge and work of God in the soul;
and the Divine agent, by which it was wrought, was Christ by his Spirit revealed in man.
And these are true gospel-ministers; not after the oldness of the letter,
but according to the newness of the Spirit,
where all glorying and boasting (save in the Spirit and the work of it) is excluded;
for by grace are we saved, through faith (which is the gift of God,
and that not of ourselves,) in his beloved Son, in whom he is well pleased;
and whom all in these last days are commanded to hear,
at the peril of being cut off from the presence of his glory forever.

The primitive believers were reached by the power that attended Christ`'s ministry--by
that light and authority from above that were the perpetual companions of his doctrine:
for, "`he taught,`" say the blessed witnesses of that time, "`as one having authority,
and not as the scribes.`"
But why not as the scribes,
when they were the standing ministry of the church in those times?
Because they were but dry preachers,
as men without life and power--ministers but of the letter,
and not of the Spirit--they reached not the conscience, nor preached experience.
The case is the same at this day--many preachers, but few ministers of Christ`'s making,
who taught as he had learned of his Father;
and his ministers teach as they have learned of him; as he has enlightened, quickened,
and redeemed them from sin and Satan:
so that they are witnesses of the work of his Spirit and power to salvation upon themselves;
and by that experience they become knowing and able ministers of Christ,
who can speak a word in season for the salvation of souls.
Such had, and now have, a reaching and an effectual ministry;
and if all that hear them are not turned to God by them,
yet they are left without excuse,
their consciences being convinced of the truth of what they say,
though their lusts render the way too strait for them to be willing to walk in,
which proves the perdition of those to whom the gospel-call or light comes,
and who refuse to be reformed.

[.numbered]
_Thirdly,_ let him read therefore with an inward as well as with an outward eye,
and read no faster than he feels and understands in himself,
and bring things to the inward test and touchstone.
And if he has not attained to the experience of these truths,
he may by the Spirit`'s mirror in himself, or glass of righteousness,
see so far as to give an assent to the truths therein discovered;
and as he submits himself to the convictions and manifestations of it within him,
he will find, that as face answers face in a glass,
so will his conscience answer to the truths occasionally delivered by this good man,
in his following labours,
which were written by him in the openings of the same Light and Spirit of Truth.
And truly, as of the outward light and day we have all of us the same knowledge,
and that by the same way, though we live not under the same latitude;
so inwardly we see Truth, and therefore we all give one and the same testimony,
as well positively as negatively: not only avoiding and reproving the same things,
but obeying and recommending the same things in faith and practice.
And unity and charity are no mean arguments of the revival of primitive Christianity,
which could not be,
were we not a people in some measure baptized by the one good Spirit into the one body,
and made to drink into the same Spirit: a people at unity within ourselves;
and that not merely of affection, and much less upon trust, or implicitly,
but of a sensible and sound experience;
as the believing Samaritans told the woman at Jacob`'s well, who called them to Christ;
"`Now,`" said they, "`we believe not because of your saying,
for we have heard him ourselves, and know that this is indeed the Saviour of the world.`"
For this advantage singularly accrues to this profession,
that it does not only refer everyone to employ the best of their understanding,
and to examine nicely all pretensions to religion,
that they may hold fast that which is good, according to the apostle`'s advice;
but to a principle in man, that is better and greater than man,
which God by Christ has given unto him, for a light and leader.
This is the seed and little leaven of the kingdom, the convincer,
sanctifier and converter of the soul of man; that which gives him sight, hearing,
feeling and tasting of heavenly things;
without which man is as unable to see and search the deep things of God,
as his outward eyes are to see any outward object in the dark.

====

Therefore to this Divine agent, that works the works of God within us and for us,
and that reveals to us the mysteries of Christ`'s kingdom,
we would have all turn their minds.
And when we speak of the Light of Christ within us--a measure of the Spirit--the ingrafted
Word--the Grace and Truth that the beloved disciple testified Christ was full of,
and of whom we receive grace for grace,
we mean this Divine principle that is variously denominated
from the diversity of its operations in man.
By this it is that Christ repairs the breaches, builds up the waste places,
which the enemy of our souls has made in us, and restores paths to walk in,
that are paths of righteousness and peace.
So that Christ is not only our blessed propitiation,
but our spiritual physician and operator, in whose hands we come to be purified,
translated, renewed, or born again, and thereby qualified to be his true disciples,
his friends, and (with all reverence be it spoken) his brethren too.
O reader! short of this there is no way for salvation known to me!
Therefore I recommend it to you, and you to it: hear it and obey it,
and your soul shall live forever.

I shall now only add my own knowledge of the person whose
labours have given occasion for what I have written.
I have known him above thirty years; and I must say,
my acquaintance with him was to my edification and comfort.
He was bred a soldier in our late civil wars, but changed his weapons,
warfare and captain, about 1654, when he listed himself under the banner of Christ,
for the promotion of his peaceable kingdom among men,
where he was not less diligent and valiant--a grounded man in the
knowledge and work of Christ our Divine agent--of a solid judgment,
and yet of a lively spirit--fervent in ministry and prayer.
He was also among men a good scribe,
and an able and just arbiter or judge in business referred to him--in
friendship sweet and firm--a faithful and kind husband,
and a good neighbour--one who had a general tenderness for the afflicted.
His life was precious with Good`'s people, his death doubtless so to himself,
though to the church a loss;
for we are assured that they that turn many to righteousness (as he has done,
as well as confirmed the churches) shall shine as the stars forever and ever.

[.signed-section-signature]
William Penn
