== Chapter I.

[.chapter-synopsis]
* His early convictions and religious experience
* When a soldier at Scarborough, powerfully awakened by the ministry of William Dewsbury
* Engaged as a minister previous to quitting the army
* An Epistle of caution and counsel

+++[+++Of the place or exact period of John Whitehead`'s birth, no account has been found;
but it seems probable from some circumstances mentioned in this compilation,
that he was born in Yorkshire about the year 1630.
The certificates in Chapter x. show that he resided
nearly thirty years from the year 1653,
in Holderness, a district in the eastern part of that county;
and we learn from the ancient records of the meetings for discipline in Lincolnshire,
that his residence during the remainder of his life, from 1683 to 1696,
was in the neighbourhood of Lincoln.
His own account of his life commences as follows:]

[.small-break]
'''

In the days of my youth I lived without the fear of God;
though he was a reprover of me from my childhood: yet I hearkened not to his reproof,
but lived in pride and pleasure, sporting and playing, and in vain, idle communications,
as all do who mind not the counsel of God.
Yet, by the education received from my parents who feared God,
I was restrained from grosser evils, as swearing, lying, cursing, and the like;
into which many children are permitted to run,
whose parents live without the fear of God.
By my parents I was instructed in the strictest profession of religion,
which then was called by the world, Puritanism.
Yet I lived without any true sense of my fallen and
lost state until I was about fifteen years of age,
about which time I had a day of visitation; and God,
who is rich in mercy and delights not in the death of a sinner,
caused light to shine out of darkness, and discovered to me my condition,
not by man nor by outward means, but by the Word, which is power and life,
which then stirred in me; from which Word light did spring in me,
and let me see the iniquity in which I lived,
and that my heart was full of corruptions and filthiness,
and lusted to all manner of evil and unrighteousness,
though I was outwardly restrained from acting gross evils.
Thus I became sensible of my wretchedness and separation from God; and desires,
by the power of the living Word, were begotten in me towards God, which wrought me,
in some measure, into his fear: and those things which were evil,
in which I had formerly delighted, began to be embittered to me,
and the fear of God caused me to depart from them,
whereby my conduct became blameless as to the world.
But I was ignorant of the true knowledge,
where to wait upon God for redemption from the evil that lodged in my heart,
and separated me from him.

I was instructed by my parents in the use of means, as hearing sermons,
reading the Scriptures, and the like, to which I paid much attention,
and so grew in knowledge beyond many of my equals: but as knowledge grew,
a secret pride grew; my sin still remained in my heart,
and the wrath of God abode upon me; under the sense of which I groaned,
but found no way to escape it.
For though I had an outward knowledge of God and Christ and the promises,
yet my will and affections and lusts were not crucified.
In this state I continued until I was about eighteen years of age,
about which time I went into the army.

I had often secret breathings and longings after God,
but zealously followed men whom the world called godly ministers,
who spoke much of faith in Christ, and of God`'s free grace, and of free justification;
which things I apprehended in my understanding; and believed,
as the world`'s professors do, that the grace of God was free,
and that Christ died for my sins, and rose again for my justification;
and that justification was free by his blood.
Here I got some ease, and my outward conduct was blameless among men.
But this faith was outward: and I stood not in the living faith and the living hope,
which removes mountains, purifies the heart, and is an anchor to the soul;
for the root of evil still remained, and my heart was unclean, and condemned me.

So there were in me many doubts and questionings of my state;
and I found no true rest to my soul, but was tossed from mountain to hill,
while I sought it without, in outward observations, as hearing sermons,
reading the Scriptures, and the like.
In this unsettled condition I continued until I was about nineteen years of age;
and then the Lord appeared in love to my soul, which lay in the pit crying unto him,
and more enlightened my understanding, and by his Spirit convinced me of righteousness.
He let me see that the kingdom of God is not in outward observations;
but that it is within, and is righteousness, peace and joy;
that all the children of the Lord are taught of the Lord, Christ;
that he is the way to the Father,
and that he is given of God to lead his people into the kingdom of God.

And then, by the power of God, desires after righteousness were enlivened in me,
and I was brought to wait, in the fear of God, on the Lord alone,
from whom my soul found some refreshment; and his secrets were with me.
And by his Spirit he showed me barrenness, dryness,
hypocrisy and confusion in the most eminent teachers of the world,
and in all the formal professors with whom I was then acquainted: and the Light of God,
which discovered their emptiness, led me from following them.
My understanding began to be more opened in the true knowledge of Jesus Christ;
I saw that he alone had the words of eternal life,
and I was weaned to him alone for teaching.
I had many openings in the living Truth;
and the eternal love of God in Christ Jesus was witnessed
to my soul by the Holy Spirit of promise,
in which I exceedingly rejoiced: when in this state I was about twenty years of age.
But I being ignorant of the daily cross of Christ,
in which to wait upon God for the possession of what I saw, and which was promised to me,
the serpent beguiled me under fair pretences, and said unto me,
that I was now made partaker of the love of God,--that there was
perfect reconciliation to God brought forth in the blood of Jesus,--and
that whom he loved once he loved unto the end.
And when the pure Light which witnessed for God, called for purity and holiness,
the serpent laid before me the failings of the saints, and said,
the best of saints committed sin--that I could not be set free from it,
while I was here on earth, for in the flesh dwells no good thing: but, said he,
that is no matter, for all is reconciled in Christ,
and none can pluck you out of his hand.
And I, lending an ear to him in these plausible temptations,
was drawn from the counsel of Christ into carelessness,
and forgot the lovingkindness of God: and then my will got strength,
and ran again into pleasures and carelessness.

So I was carried captive into spiritual Egypt,
where our Lord was crucified and the witnesses slain, Rev. 11:8:
and then that nature which was of the world, rejoiced and made merry over the Witness.
Yet a Seed did still remain, which secretly reproved me for my wicked thoughts,
idle words and unsavoury actions (though the world could not reprove me):
and then the "`Mother of Harlots`" with the wisdom of the serpent, made covers,
and told me that that was but the spirit of bondage which reproved
me--that it would lead me again into bondage--that the saints had
liberty to take pleasure and delight in the world,
and that they had the most right to its treasures--that though I did commit sin,
yet God did not impute it to me; for he sees no sin in Jacob,
nor transgression in Israel--that it was not outward works that
could alter the purpose of God or separate me from him.
But I had turned from that which he loved, and I was in the house of bondage;
and "`the Mother of Harlots`" sat decked in me, and said, she should sit a queen forever,
and see no sorrow.
I gloried in my knowledge, and could talk of experiences through which I had passed:
but "`the prince of the power of the air`" was head in me,
and my soul was brought into bondage to corruption.

In this state I lay nearly two years:
and the Lord by his Seed,--his Word,--sometimes disquieted my earthly spirit, brought me,
in some measure, into a sense of my condition,
and let me see that I was separate from Christ,
and had lost the Divine love and virtue which I had once enjoyed.
Sometimes there was a secret longing in me to see from where I had turned;
but the serpent told me, that I could not do, because of myself I could do nothing,
and that the Lord`'s time was not yet come; for when he would have me otherwise,
he would make me as he would have me to be,
and I could not resist him in the day of his power.
And thus he drew me from hearing the counsel of Christ,
who called for self-denial and holiness,
to live at ease in the flesh and to put the day of the Lord afar off;
in which state I had perished in my gainsaying,
but that the long-suffering and riches of God`'s love to me were inexpressible.

And as I here lay in the house of bondage,
the Lord in his love sent his faithful messenger, William Dewsbury,
into the place where I resided.^
footnote:[Scarborough--John Whitehead was at this time, in the army,
and was probably about twenty-two years of age.
{footnote-paragraph-split}
William
Dewsbury commenced his Gospel labours in the Eighth Month,
1652, at which time, according to his own account (see [.book-title]#Life of W. D.#),
he was engaged "`in obedience to the command of the Lord, to run to and fro,
to declare to souls where their Teacher is--the Light in their consciences.`"
His visit to Scarborough, as above alluded to,
was most likely even prior to John Whitehead`'s meeting with him at Malton,
in the Tenth Month of the same year, (see pp.
9, 10,) so that John Whitehead must have been among the first who were convinced,
or rather confirmed and established in the truth,
through the instrumentality of that eminent minister.
{footnote-paragraph-split}
The
reader will please to observe,
that the dates in this volume are according to the Old Style
so that every month is to be reckoned as two months later,
to agree with our present mode of computing.
Thus, the Eighth Month (as above) corresponds with the Tenth Month as now computed.]

In him God had raised the Witness to declare his powerful Word:
and when I heard it declared, and the cross of Christ preached,
the Witness of God arose in my conscience and witnessed to the Truth:
my understanding again was opened by the power of
the same Spirit that first convinced me of sin;
and I saw that I was in the prodigal state,
above the cross of Christ--that I was the servant
who had known his Master`'s will and not done it;
and the judgment of God took hold of me.
Yet a secret hope was raised in me that mercy would be shown me upon my return:
and in this day of my visitation I sunk down into the power
of the Spirit that convinced me of sin and of judgment,
and resolved, in the power of it, to return unto Him against whom I had sinned.
And no sooner did I return, but in his love He received me, and put his fear in my heart,
which caused me again to depart from all manner of evil;
and set up his righteous judgment in my heart, which took hold of the man of sin:
and a day of trouble and great fear fell upon the earthly man.
And as I here waited, the Word of the Lord came unto me and said,
if I would be his disciple I must deny myself and take up his cross daily and follow him:
and by the power of his Word my will was brought into the cross,
and I was separated from my former companions and from conformities to the world,
to wait upon God in the way of his judgments.

+++[+++In contemplating the Christian experience of individual
members of our Society at its origin,
we cannot fail to be much struck with the great similarity of their
spiritual exercises and the way by which they were convinced of
the inefficacy of the mere profession of religious doctrines,
however accordant they might be with a correct interpretation of Holy Writ.
John Whitehead, as appears from the above deeply instructive account,
was one among the many,
who in that day experienced the light of divine Truth
in a preeminent degree to arise in their hearts,
showing them the hollowness of the high profession of the times,
and inducing them to turn from dependence on man for spiritual instruction,
and to believe in, and come to, Jesus Christ,
not only as to the "`Lamb slain`" through whose blood
they were to receive remission of sins,
but also as the "`Head over all things to his Church,`"--the present Teacher,
Governor and Guide of his people.
John Whitehead, we have seen, was instructed in the strict profession of Puritanism,
which had the effect of leading to an exterior propriety of conduct,
without making known to him the deep depravity of the heart,
and the consequent necessity of experiencing the regenerating power of Divine grace:
we have also seen that in the gradual enlightening
of his mind he became possessed of a correct knowledge,
as far as the intellect was concerned, of some important evangelical doctrines;
but his faith being outward, though he obtained some ease to his troubled spirit thereby,
he was still tossed and tried,
and sought rest in outward things,--in the use of means alone;
not as yet fully understanding that the means were given for an end,
and were useless unless that end were attained.
But that same Spirit which visited him at an early age and convinced him of sin,
in the further unfolding of light and in the extension of heavenly love,
at length convinced him also of righteousness,
showed him the nature of the kingdom of God,
and weaned him from the teaching of men to wait on the Lord alone.

Thus, although as yet not fully enlightened,
nor practically acquainted with the necessity of
a daily abiding under the cross of Christ,
and therefore remaining weak and in bondage,
and subject to the subtle temptations of the enemy,
his mind was prepared by the Spirit of Truth,
to unite at once with the evangelical and living testimony of William Dewsbury,
and to become himself also, in a short time,
a minister and witness of the same precious principles,--the same practical,
inward and efficacious religion of the Gospel.

T+++.+++ Thompson, in his Testimony Concerning John Whitehead,^
footnote:[In the work from which the present volume is compiled,
this Testimony is signed, _Theo.
Thomson,_ Skipsea;
but there appears good reason to conclude that the writer`'s name should have stood Tho.
Thompson.
A careful examination of the Registers of York Quarterly Meeting, etc.,
has failed to discover the name as it stands in the
Edition of 1704.--Thomas Thompson lived at Skipsea,
was a minister of note, and died in 1704, aged 73 years.
In a Memoir of his life, written by himself,
after giving an account of his convincement in 1652, he says,
"`In those days I often accompanied William Dewsbury, John Whitehead,
and sometimes James Nayler, and other early ministers,
to and fro in the East Hiding of Yorkshire.`"--These circumstances seem
to justify the conclusion that this Friend was the writer of the testimony.]
relates, that on the 27th of the Tenth Month, 1652,
he first saw him at Malton in Yorkshire, to which place he, T. T.,
had accompanied William Dewsbury, where, in an assembly of brethren and friends,
John Whitehead`'s "`mouth was opened in prayer to the Lord.`"
In the First or Second Month of the year following,
"`at a meeting of the Lord`'s people at Butterwick,`" he again met with him;
and he was then "`preciously opened in testimony for the Lord.`"
Thus rapidly did the seed sown in the good soil, spring up and bring forth fruit.
After this meeting at Butterwick, he again returned to Scarborough,
for he did not leave the army till the following summer.
"`He then (T. T. continues) came into Holderness,
there labouring with his hands in the harvest time;
after which it was with him to go into the Moors, to preach the Gospel of Jesus Christ:
in part of which journey I accompanied him;
and truly it was a very comfortable time to me.
Oh! the living power and wisdom of God with which he was then attended:
I am greatly affected with the remembrance of it.
Oh! the precious meetings; and the heart-breaking power of the love of God,
which then was manifested in our assemblies.`"

The following Letter, without date, was probably written about this time:]

[.embedded-content-document.letter]
--

[.salutation]
Dear Brethren and Sisters,

You who are begotten again of the Word of Truth,
my love in the Lord Jesus extends to you all.
Every one of you beware of lusting after the flesh-pots
of Egypt,--earth and earthly things,
or after the merchandize of Babylon, and enticing words of man`'s wisdom,
which the Lord in his eternal love has called you from, by revealing his Son in you,
who is the living bread that came down from heaven.

Dear brethren, forsake not this living mercy for outward things,
though never so seemingly glorious, for they all perish in the using;
but "`the Word of the Lord endures forever:`" when it goes forth,
it gives understanding to the simple, and the soul of the needy is refreshed by it.
Therefore wait every one within yourselves to hear the joyful sound;
and every one of you dwell in obedience to that which is made manifest,
and so more will be communicated.

You must all give an account of your stewardship.
Oh! therefore, be faithful, that you may do it with joy, and not with grief;
and trifle not away this day of the Lord`'s love and mercy;
for now there is balm in Gilead, and a Physician near your souls.
See therefore that your health be recovered by Him,
and that you neglect not so great salvation.
For notwithstanding the vain imaginations of any, and their hard thoughts of the Lord,
yet his arms of love are stretched out still; but how long you know not.

Therefore let none be careless, but singly strive to enter in at the strait gate;
for many strive and are not able,
because they would have their own wills and wisdom kept alive,
with the profit and vain delights of this world,
which keep them captive in the broad way that leads to destruction.
But my brethren, not as unbelieving or disobedient,
put on strength in the power of the Lord, who has called you,
and press on by the strait gate, where the earthly will and wisdom are kept in death,
and so receive the kingdom of heaven,
as those who forsake their own wills and reasonings,
and yield themselves up into the love and mercy of the Lord;
and as you mind to be guided by his pure counsel, though your strength seem weakness,
yet nothing shall be able to separate you from his love;
but as conquerors you must pass out of death into life.

Therefore be strong in the Lord every one of you,
and give up what you have and are into his will: let not carnal pleasures allure you,
nor carnal fears cause you to distrust; but "`run with patience,
that race which is set before you.`"
Be not slothful but diligent, for to this end has he chosen you,
that you might manifest the riches of his love, and bring forth fruit to his praise.
And faint not in your way, for the time of refreshment comes on quickly,
when the redeemed of the Lord shall walk in Zion,
with songs and everlasting joy upon their heads,
singing the songs of their deliverance,--hallelujahs
and praises to Him who sits on the throne,
and judges the earth in righteousness.

Therefore fear and tremble, you careless ones, who have lost your first love;
strengthen that which remains lest you walk in darkness.
And you that halt between God and the world,
that which you lust after and account so profitable and delightful,
shall depart from you: for this world passes away, and all the comforts which it affords,
and it will leave you naked and bare before Him, whose love you have rejected,
and whose counsel you have despised.
Oh! therefore, lay it to heart, and consider how you will be able to stand before Him,
when He arises to plead with you in his fiery indignation?
Now you have time prize it; forsake that which is earthly,
and chose that which is eternal--you cannot have both.
Be not sayers only, but doers, lest you cause the worthy name of God to be blasphemed,
and so bring upon yourselves swift destruction.

Dear children, you that are called and chosen, my desire is,
that you may be kept stedfast unto the end.
So I commit you all to the tender mercies of our God,
who never leaves nor forsakes those who trust in him.
Let this be read among you when you are met together.

Written from the spirit of the Lord, by your brother in the truth of the gospel.

[.signed-section-signature]
John Whitehead.

[.postscript]
====

I am now about to go into the Moors,
where I hear there is much hungering after the Truth;
when I shall return I know nothing of.
Therefore pray for me,
that I may be kept faithful to declare the Truth as it is revealed in me.

====

--
