== Chapter VIII.

[.chapter-synopsis]
* John Whitehead`'s second imprisonment at Lincoln
* Letter to Judge Windham
* Epistle "`for the Vineyard of the Lord`"
* Address to professors of the Truth who are turned aside

+++[+++About five months after John Whitehead`'s release from this last imprisonment,
he became again exposed to the persecuting spirit of the age.
For refusing to swear,
he was a second time committed to Lincoln Castle:--so fruitful
a source of injustice and oppression was the law respecting oaths,
as then administered.
His narrative of the transactions relative to this
portion of his sufferings for conscience sake,
is as follows:]

[.small-break]
'''

Upon the 8th of the Fifth Month, 1662,
_upon suspicion_ that I had met together with some sober people for the worship of God,
I was apprehended by John Clarke, constable of Hannah-cum-Hagnaby,
in the parts of Lindsey and county of Lincoln;
and by virtue of a warrant subscribed by Martin Litster,
carried to the next justice of the peace, called William Woolley,
to answer to such things as should be objected against me;
who after having heard me and my accusers face to face,
confessed that he heard nothing charged against me worthy of bonds,
and therefore refused to commit me.
But either fearing the displeasure of Martin Litster, or willing to do him a pleasure,
he advised the constable to carry me before him, which accordingly he did the next day.
Being come before him, he examined my accusers, one of whom was a priest;
but finding that nothing could be laid to my charge
which might give sufficient ground to commit me,
he sought to ensnare me in my words,
and to find occasion against me concerning the worship of my God;
but the innocency and wisdom with which I was clothed, prevented him,
so that be could find none.

Yet being resolved I should either go to prison or bow to his will,
he took pains to go to another justice, called John Boswell,
and caused me to be brought after him before those two,
who joined together and examined me.
I freely confessed to them that I came into these parts in love to visit my friends,
and did sometimes speak unto them words of truth according to the Scriptures of Truth:
whereat they conceived so great offence, that they thought me worthy of bonds.
I bade them consider that persecutors were ever blind,
and thought they did God good service when they killed his children;
and I told them that I did believe the more we were persecuted,
and suffered for righteousness sake, the more we should increase and grow:
whereat Martin Litster was much offended.
That they might be sure to have matter enough against me,
they asked me if I would take the oath of allegiance.
But they had neither the oath, statute-book, nor Bible that I saw:
so that they did not at all tender it to me; yet I told them,
that for conscience sake toward God,
(and not in any contempt or disaffection to the king
or his authority,) I could not take any oath;
whereupon I was sent to prison, and kept there till the general jail delivery,
by virtue of a court order, whereof this is a true copy:

[.embedded-content-document.legal]
--

[.blurb]
=== To the Keeper of His Majesty`'s Jail at the Castle of Lincoln, or to his Deputy or Deputies There.

[.offset]
Lincoln Lindsey.

Foreasmuch as John Whitehead of Owstwick, in the county of York,
was upon complaint brought before us this day, by warrant,
for upholding private meetings contrary to an act of Parliament, made and provided;
and being tendered the Oath of Allegiance by us,
being two of his Majesty`'s justices of the peace for the said parts and county,
according to the statute in that case made and provided,
did refuse to take the said oath.
These are therefore in the King`'s Majesty`'s name to charge and command you,
immediately upon the receipt hereof, to receive him, the said John Whitehead,
into your said jail; and him there safely keep without bail or mainprize,
until the next general jail delivery to be held at the said Castle of Lincoln,
for the said county: and hereof you are not to fail,
as you will answer the contrary at your perils.

Given under our hands and seals, this ninth day of July,
in the fourteenth year of his Majesty`'s reign, _Anno Bom._
1662.

[.signed-section-signature]
Martin Litster.

[.signed-section-signature]
John Boswell.

--

At the court sessions, or general jail delivery,
begun at Lincoln the 19th day of the month called July, Woodham Windham sat as judge;
and in his charge uttered many hard sayings,
which reflected on those whom I knew to be innocent and harmless men, with threatenings,
that we who refused to swear should be fined and banished.
Whereupon I knowing that myself with William Morris, William Bancoft, and John Cleasby,
who were fetched out of their own houses and committed
to prison because they could not swear,
were all in his calendar,
expected that we should have been called and proceeded against as the law directs;
but justice was both deferred and delayed contrary to Magna Charta, cap.
i.; for we were not called at all, nor brought to answer,
neither did any accusers come in to charge us with the breach of any law of God or man:
yet did the above-named judge order us (whom he neither saw nor heard
speak for ourselves) to lie in prison till the next Quarter Sessions,
contrary to justice and equity, and contrary to the express statute of the 28th Edw.
III. cap.
3, where it is enacted, "`That no man is to be imprisoned, disinherited, or put to death,
without being heard what he can say for himself.`"
But surely he was afraid that the truth of our cause should appear before the country,
in whose presence he had sought to render us odious;
whereat I gave him a hint in a letter, a true copy of which follows:--

[.embedded-content-document.letter]
--

[.salutation]
Friend,--

I write unto you in the name of the God of Heaven,
who created you and all mankind of one blood to dwell upon the face of the whole earth,
that you may understand he has not given power to one Christian man,
of whatever state or degree, to be lord over the faith and conscience of another;
and much less to destroy one another about faith and worship.
Surely you were raised up into the seat of judgment for a praise to them that do well,
and not to asperse the innocent,
nor to render harmless people odious in the face of their country;
to whose consciences we can appeal, that our conducts have been,
and still are blameless among them;
and that they have not anything justly to charge us with,
but that which concerns the law and worship of our God.
For when do any of us come into your courts for witchcraft, murder, theft, perjury,
or other matter of wrong and wicked lewdness,
as do many of the reputed members of the Church of England; which, you said,
is now pestered with heretics, that must be put forth,
as were the lepers out of the camp of Israel.

But before you, and those that be in authority with you, proceed to that work,
consider,--have you received an infallible spirit
to judge what is truth and what is heresy?
And have you an angelical understanding to discern between the tares and wheat?
If not, then may you pluck up the one instead of the other;
and how easily may you call evil good and good evil,
as the Jews did in the days of the ancient prophets and apostles, who judged Elias,
the man of God, to be a troubler of Israel; and Paul,
the minister of the gospel of peace, a mover of sedition throughout the world;
and Christ Jesus, the prince of life, they said was a blasphemer,
and by their law ought to die;
and so may you render yourselves liable to God`'s just hand of vengeance, as they did;
for as David said in a certain psalm, "`He ordains his arrows against the persecutors.`"

Therefore in tender love I say again, consider,
all you that would compel us to a conformity in worship,--Is
your worship in the infallible spirit of truth;
not differing in matter or manner from the primitive Christian`'s worship?
If this you cannot affirm, and reasonably demonstrate to every man`'s conscience,
then why will you seek to force the conscience to conform to that
which you cannot demonstrate is altogether right and infallible.
But if you say, that you have received an infallible spirit, and in that do worship,
not differing in whole or in part from the primitive Christians;
then do not so uncharitably judge, as to say,
our consciences are not tender but obstinate, if we cannot believe your assertions:
but allow us that liberty which the apostle did not only allow,
but also commend the Bereans for, to search the Scriptures,
whether those things you hold forth be so or no;
because we must give an account for ourselves, and if we do not serve God aright,
it will not excuse us to say, "`our teachers did lead us wrong;
"`for if we follow blind guides, we may justly fall with them into the ditch.

You did further say, that if we be let grow, who deny swearing in any case,
though before a lawful magistrate, human society cannot be continued;
and therefore our principle was exceedingly dangerous.
To which I say,--we are of no other principle,
neither do we hold forth any other thing in that case,
but what our dear Lord and Saviour Jesus Christ, and his Apostle James, did hold forth,
(notwithstanding of old time men might swear by the Lord,
and perform their oaths to him.) But Christ said, "`I say unto you,
swear not at all;`" and the Apostle James, writing to the twelve tribes scattered abroad,
as if he had foreseen that they would stand to justify some swearing,
contrary to the aforesaid precept, (because Moses allowed swearing,
and their forefathers practised it) said, "`Above all things my brethren, swear not;
neither by heaven, nor by earth, nor by any other oath: but let your yes be yes,
and your no, no; lest you fall into condemnation.`"
This commandment of the Lord is so plain, that no argument is good against it,
nor yet any law, statute or custom of men;
for they should be consonant to the words of Christ,
seeing he is given to be the Head of all things to his church.

And though he forbad all swearing,
yet did not he subvert all human society any more than we do,
but taught to speak truth every man to his neighbour, and do justly,
as we ever desire to do.
We are willing to suffer the like punishments if
we do bear false witness without an oath,
as if we did forswear ourselves.
And upon these terms might our testimonies be taken without an oath;
and neither the truth suppressed, nor justice obstructed, nor human society destroyed,
which we have and shall in our places ever labour to preserve.
For the Lord God of heaven and earth knows that we are lovers of truth and justice,
and all mankind; and more especially those that inhabit the land of our nativity;
the peace and tranquillity of which we shall ever seek,
though in it we be reproached as factious, and have suffered hard things.
We desire that the Lord may forgive those who wrongfully afflict us,
not knowing what they do.

Even so, O Lord God Almighty,
turn the hearts of all men into the everlasting way of your Truth,
and heal the breaches of this nation; that in justice, equity, righteousness,
mercy and love one to another, we may become the glory of all nations.
And till the innocency of our hearts appear to them that yet know us not,
strengthen our faith and patience,
that we may meekly suffer what for our trial you permit man to do unto us.

Thus have I cleared my conscience in witnessing the truth,
and opening our case in some measure unto you,
who am a lover of justice and your soul`'s friend.

[.signed-section-signature]
J+++.+++ Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 20th day of the Fifth Month, 1662.

--

This letter was given into the judge`'s hand, and read by him;
yet he would not hear our case, but ordered us to lie in prison till the Sessions,
without rendering any reason for so doing.

[.small-break]
'''

+++[+++In the interval between the court sessions and the next following Quarter Sessions,
John Whitehead manifested his love to his fellow-professors,
and his concern for the promotion of the cause of Truth,
by giving forth the two following impressive Epistles.]

[.embedded-content-document.epistle]
--

[.blurb]
=== For the Vineyard of the Lord of Hosts; to be Read in Their Meetings

The breathings of a prisoner for the Testimony of Jesus,
who in the deep has seen the afflictions of his people,
and cannot hide His praise who supports them, nor withhold his complaint,
because of the hardness of men`'s hearts;
but cries unto the Lord God of righteous judgment for the deliverance of his own people.

With a few words of exhortation and advice,
given forth as a testimony of my dearest love to the whole seed of God.
Because I cannot otherwise communicate it in this time of my restraint,
I have been the more large, that I may be refreshed with you, and you with me,
in the overflowing Fountain of our Life.

O Vineyard of the Most High,
wherein I have laboured according to the ability which God has given me,
since the appearing of "`the bright and morning star,`" who has enlightened the world,
in whose joy I am now at rest.
My peace is as a river, because I hid not my talent in the earth,
nor stood idle in the market-place; but have improved what was given me,
for my Master`'s use, and for the increase and watering of you his vineyard.
I cannot in any way forget you now when trouble is near,
and all the beasts of the field compass you about,
and with their whole power seek to break down your hedge, crop off your leaves,
devour your fruit, tread under your tender plants, cut off the flourishing branches,
and make you as a wilderness.

In the everlasting love of our God I think upon you,
remembering the kindness of your youth, and the love of your espousals,
wherein you were betrothed to the Lord with judgment and mercy,
in the day in which you sat solitary in the wilderness, and had none to help.
My heart is broken within me, and does with your breathing babes and tender mourners,
whose cry has reached unto heaven, send forth these breathings;
that in the spirit of supplication we may have fellowship together,
while my soul says unto God, "`Surely you have not cast off the beloved of your soul,
nor sold your heritage, to be trodden down, for a thing of nought;
neither have you given the plants of your own right hand for a spoil to their enemies.
Shall they then prevail, who come gnashing with their teeth to devour us?
And will you let your name be blasphemed, wherein you have gathered us,
in which we do trust?
For your presence is yet among us, and you withhold not the riches of your mercy from us,
but open your treasure to us; and of your fulness we have received strength,
else we could not have escaped in the hour of temptation,
nor stood upright in the time of our deep trials.
When you saw us weak, you turned not away your face from us,
but ever have stretched out your right hand to uphold us,
and have helped us with a little help: when we call upon you,
you bow down your ear to hear, and give us also to understand the words of your mouth.
Why do you not as well show yourself unto the world, as to us;
for they understand not your way,
but because (though you have given your light into the world) they love darkness rather,
and _that_ blinds their eyes, that they know not you, nor us whom you have sent,
and therefore do persecute and seek to root up,
not believing that we are your pleasant plants.

Although you have created us anew in your own image, and showed your light, life, love,
virtue, power, patience, and goodwill towards men, through us, yet do they not consider,
but think they do you good service when they kill us all the day long.
And when we speak to them in your name, and would turn them from their envy, anger,
pride, covetousness, murders, thefts, lies, adulteries, fornications, oppressions,
injustice, and the evil of their inventions, unto the Light, wherein your fulness dwells,
that therein they might walk with you in newness of life,
they reject our testimony and say we would delude them.

And when we declare your righteousness and show your judgments at hand,
because transgressions are multiplied and iniquity drunk up as water,
they harden their hearts against us and mock at fear,
neither do they prepare to turn unto you; but for our love in warning them,
they give us the water of affliction to drink.
And when we call them who are yet wandering with a heart panting
for living water (but being gone astray from your ways,
do drink of the harlot`'s cup, or, at best,
of that water which men have fouled with their feet,) and say, "`Turn again to the Lord,
and defile not yourselves with the inventions of men, neither touch any unclean thing;
but come forth and be separate, and our God will be a Father unto you,
and you shall be his children,`" then they reproach us as factious,
and as sowers of sedition.
But if any do lay it to heart, and believe our testimony and return,
they meet them first with flatteries, then with threats and cruelties, which they spread,
as the snares on Mizpah, for their feet; like the chief Priests,
Pharisees and Lawyers of old, who would neither enter into the kingdom themselves,
nor permit those that were entering to go in.

And when we are gathered in your name, and do silently wait to feel your power,
that in it we may edify one another,
and drink at the Fountain of Life which you have opened unto us,
without reverence to your name they come upon us with open violence to devour your lambs,
merely for drinking at the Fountain: yes, their stroke upon us is very cruel,
because we love your precepts and cannot derogate from the glory of your verity,
who have made our yes, yes, and our no, no; and said unto us by your Son since the law,
"`Swear not at all.`"
And though we have given our cheeks to the smiter, our bodies to prison,
and exposed our goods to the spoiler,
and patiently borne many other grievous sufferings for the Truth`'s sake,
whereof you have made us witnesses,
yet will they not believe those things which you have spoken by us:
and what have we more with which to seal the testimony that you have given us?
unless you will allow the harlot to drink more of the blood of your saints
before you bring your long and often-threatened judgments upon her,
who yet fears them not, but says, "`I sit a queen, and am no widow,
neither shall I see any sorrow.`"
And by what means will you plead with Babylon, who says she is the lady of kingdoms?
Or who shall persuade men to fly out from her, that they perish not in their plagues?
for they are mad upon her idols, mock your messengers,
and shamefully entreat and stone those whom you have sent to forewarn them,
that they may escape the wrath to come.

Yet with you is mercy and forgiveness; and I know you would not their destruction,
but rather that they may turn and live.
Therefore hear my complaint, and bow your ear to my request; for I groan within myself,
and my spirit breathes that you may arise in your mighty power,
and speak by your righteous judgments, that men may fear before you,
and the nations be persuaded to come to your light,
and kings to the brightness of your rising.
Let your right hand rend the veil from off all hearts,
that your salvation may be showed openly, and Satan trodden under foot;
for who else is sufficient for these things?
But in the day of indignation, O Lord, remember your heritage,
and let not your Vineyard be rooted up, but spare your people,
and cause your tender plants to grow: chain the dragon,
and let the earth drink up the floods that would hinder
your spouse from returning out of the wilderness,
where her place has been in the long, dark night of apostasy.
But since the dawning of the day, you have said unto her that sat solitary,
"`I am the husband of your youth, therefore walk with me;
and I will not leave you nor forsake you, but lead you unto the mountain of my house;
and my banner over you shall be love;`" and herewith you have allured her,
and she follows hard after you.

But now, O Lord, our Shepherd, we are compassed about with adversaries,
and grievous wolves are gathered to prey upon your lambs; therefore abide with us,
and break their teeth, O God, that your flock may not be food for them.
For our expectation is from you alone, and we have not made flesh our arm,
because our hope is in you:
neither tribulations nor afflictions can separate us from you,
for we have appealed unto your righteousness,
who search the hearts and try the reins of all men,
that you may give judgment between us and them who afflict us.

And if you have not sent us and commanded us to speak,
or if in heart we be not innocent towards men,
and no way guilty of doing or intending those evils with which they charge us,
then let our hearts fail, and confusion cover us before them in the day of our trial.
But, and if you have sent us, and commanded us to speak,
and by your own power begotten us into an innocent life, then open our lips,
and let the words of your mouth break forth through
us and stick in the hearts of our enemies;
that they may be pricked, like the persecutors of old,
and not have ability to resist the spirit and wisdom by which you lead us.
For though we ourselves know that we are of you,
yet do we patiently wait till you decide the controversy,
and in the sight of all men show who are your people.
Yet can I not cease to breathe,
that you may shorten these days of trouble for your elect`'s sake,
in whom your soul delights;
that no more may be laid upon your little ones than they can bear, lest they faint,
and their adversaries triumph, and say, "`Where is now the God in whom they trusted?`"
O let them know that you are near,
and do hear the cry of the oppressed! and upon the
glory of your Name let there be a defence;
and so keep us in it, to the end that it may never be dishonoured.

Now having refreshed my full heart,
in spreading our cause before the Lord--O you his people! bear with me a little,
and let your ears be inclined to hear a few things which concern your peace.
For, because I love you, I cannot withhold from you that it is signified unto me,
that while you are beset with adversaries on every side,
the enemy will bestir himself with all subtlety and violence to make a breach among you,
and also will tempt you to everything whereby he may weaken you,
and let your adversaries in upon you.
But he shall not be able to effect his purpose while you all,
in that faith which works by love, meekness, and gentleness, do hold the one Head,
which is Christ the Light, and not the planters nor the waterers.
For him we preached, and in him we have believed,
who is the author of eternal salvation from sin,
and the perfecter of man`'s redemption up to God.
And you are witnesses that we have not preached up ourselves,
neither laboured to set up him that plants, nor him that waters,
as anything in comparison of the precious Truth of God, for which we now suffer.
But in plainness and sincerity, not with wisdom of words,
but in the demonstration of the Spirit, we have manifested the life and power of God;
that you may know, believe, and be guided by it in yourselves,
and so inherit rest and peace with God, and not always stand afar off,
in the expectation of something to come.
This is an unsettled state,
wherein they that stand may easily be deceived with swelling words, or good pretences,
with which the strange woman^
footnote:[The false church.]
(whose ways are moveable,) decks herself,
lest those whom she seeks to catch in her snare, should ponder the path of life,
and see that her ways lead to the chambers of death,
and that her steps take hold on hell.

But dearly beloved friends and brethren, seeing we know that the Son of God is come,
by an inward feeling of his presence in spirit,
which has given us an understanding that is true, and we look not for another,
but are rooted and grounded in him, let us hold fast our confidence,
and faithfully follow him, and patiently endure the cross,
that we may ever be his disciples, who is a quickening Spirit, and does dwell in us.
Then shall we no more wander among briars and thorns,
but feed among the lilies of the valley, and drink of the water of life.

But, Friends,
because all of you that are convinced are not yet come into the savoury life,
to discern of things that differ,
you must take heed of presuming to judge of things that are beyond your measure.
For your principal strength and safety is to be still,
and to wait in the light of the Spirit within,
that both your faith and wisdom from above may be increased;
and that will open you more and more to receive instruction,
but will never let you slight nor reject the Spirit`'s testimony in the elders and brethren,
whom God did use as instruments to turn you unto himself,
and who still in the same love watch over your souls--neither shall you despise prophesying,
nor quench the Spirit that speaks in the mouth of babes, who are of stammering lips;
but as friends of the Bridegroom, you will rejoice to hear his voice in any instrument,
by whom, or to whomever he speaks.
But take diligent heed, lest you set up any instrument above its place,
or give unto it any part of the glory which is due unto Him that uses it,
lest thereby you kindle his wrath, and cause jealousy to burn like a fire.
For if his glory be given to, and received by, the most precious instrument in his hand,
He will cast it away from him;
and allow it to be trodden under foot as the mire of the streets.
Therefore be tender of one another`'s preservation;
and let all your affections be guided with justice, equity, and moderation,
so shall you never puff up any above, nor cast down any below their measure,
which does much tend to preserve the body in the unity of the Spirit, and bonds of peace.

And you that are as children in simplicity, wait,
that also in understanding you may become men.
Take heed of being so affected with simplicity, as to despise or hate knowledge;
like those to whom wisdom cried and understanding uttered her voice,
and they would not hear; who stood conceited in ignorance,
till calamity came upon them like an armed man.
But always bow down your ears to the instruction of life, and do the will of God;
that you may understand doctrine,
and be of a sound judgment to try spirits and doctrines, whether they be of God or not.
And in so doing, be sure to keep your own habitations in a measure of Light;
see that neither prejudice nor immoderate affections bear sway in you;
so will you see what stands in unity with the first
principle by which you were turned towards God,
and what is approved in his Light,
and tends to establish you in righteousness--and that you may safely embrace.
But whatever jars with the first principle,
and would dissettle and remove you from the Light within,
(wherein that which may be known of God is made manifest,) either
by drawing into uncouth and singular outward observations,^
footnote:[This was probably intended as a warning
against the extravagancies of John Perrot.
He was a man of great natural parts, but not continuing in true humility,
ran out into exorbitant imaginations.
While travelling on a religious visit to several parts of the continent,
he was arrested and examined before the Inquisition at Leghorn, but was set at liberty.
Soon after this,
he was imprisoned at Rome for a considerable time for publicly testifying against idolatry.
While there, he manifested a tendency to fanaticism,
and on his return to England in 1660, caused a schism among Friends,
the effects of which were felt for several years after.
He lapsed into self-exaltation,
and thought himself farther enlightened than his brethren,
maintaining that it was an improper and worldly formality to remove the hat,
when another was engaged in prayer.
Soon after this, he allowed his beard to grow.
He had some followers, but they do not appear to have been numerous.
His conduct subsequently manifested more fully that
he was actuated by the spirit of error;
for he not only assumed gaudy apparel, but gave himself up to sensuality,
and took up the sword; and having obtained a place under government in America,
became a severe exacter of oaths,
and seemed to be principally influenced by mercenary
motives in the exercise of the functions of his office.]
or by promising liberty,
or a greater glory than that which the Light of the
Spirit within has given us to behold with open face,
as in a glass, and is translating you into; I say,
that which by these things would work discontent in your present measures,
and let you loose from waiting in God`'s fear,
into the comprehension of things above your measures, is dangerous, and to be eschewed:
and if any hold forth such things, they,
as well as such as would draw you back into the rudiments of the world,
speak of themselves, and seek their own glory; but he whom God has sent,
speaks the words of God, and seeks his glory that sent him.

And if contention, strife, wars, or commotions arise in the earth, between man and man,
or people and people where you inhabit,
dwell you in that power which has redeemed you out of the earth from among men,
and that will keep you sensible that you are not your own, but bought with a price,
that you may be unto God a peculiar people:
and therefore you shall not defile yourselves with their contentions,
nor strive nor side with parties who fly to that
sword for refuge by which they may perish.
But we having received and trusted in the sword of the Spirit,
by which we can never perish, let us sit down in that which keeps holy and harmless,
and separate from sinners; so shall his wonderful counsel, who is Prince of peace,
be with us, wherein we may be peace-makers,
and obtain the blessing to be called children of God.

And you who are as yet not much exercised with sufferings,
but are at peace in your dwellings,
none making you afraid--take heed lest at any time you be secure:
for then may the enemy entice you from a sense of God`'s mercy,
to look out at creatures and to set your heart on earthly things;
and then if a trial come suddenly and unexpected, it will be the heavier upon you;
and if, through lack of preparation, you fall under it,
then it will be hard for you to be raised up again to stand faithful unto the end,
wherein your safety and the possession of the crown of life depend.
If you be not constant and faithful in these last trials,
you lose your reward for all that you have gone through: for,
"`if any do put his hand to the plough, and look back,
my soul has no pleasure in him,`" says the Lord.
Therefore, as I would that you should not be dismayed, nor fear the threatenings,
excommunications, fines, and imprisonments,
or any other thing which you may suffer by the wicked hands of mortal men,
so would I that you may both inwardly and outwardly
be prepared to suffer what man can do unto you.
And while you behold the Lord restraining their wrath from breaking out against you,
bear a part with your brethren who are suffering under it;
and God shall reckon it to you in the day of your need.

Finally, dear friends and brethren, be of one mind, and live in peace;
and in the name of the Lord keep your meetings, that love and life may abound among you;
and therein faithfully instruct, admonish, and (if need be) reprove one another.
But let the Spirit judge all things; and with an open,
tender heart receive instruction and reproof one from another;
pondering it in deep silence, and not measuring it in the reasoning part,
for that will grow high and work prejudice against the admonisher and reprover,
if you see not a present cause, or need of such a thing;
and thereby you may both hurt yourselves,
and discourage those that in sincerity sought your good,
whereby they may be caused to lament in silence when
they see you in the like danger again,
and say, "`We called, but they would not hear.`"
Therefore measure and bear all things in the meek, lowly spirit.
And you that are strong and spiritually minded, being come over all these things,
labour to restore and raise up them that fall; comfort the feeble-minded,
and say to him that stands afar off, "`Draw near and walk with us in the light,
and the Lord will also give you rest.`"

And wait on your ministry,
that you may preserve that which is gathered in the savoury life,
to shine as lights before men.
For there is a seed sown in this nation and elsewhere,
which begins to bud forth in thousands, who having not seen, yet love;
which gives me sufficient ground to believe that when the winter is past,
and the latter rain comes upon the earth, there shall be a plentiful harvest;
wherein everyone that has been faithful in a little shall reap much,
and give thanks unto God who has blessed the seed sown;
who will send forth such as in the furnace of affliction he has fitted for his use,
faithfully to labour:
that every eye may be opened to see that the common salvation which God
has prepared for all people is the Light that does enlighten the Gentiles,
and the glory of Israel.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Written in Lincoln Castle, the 24th day of the Sixth Month, 1662.

--

[.embedded-content-document.epistle]
--

[.blurb]
=== The Case of such Professors as Have Known the Way of Truth, and are Turned Aside from its Holy Testimony, to Save Themselves, Opened and Lamented: With some Wholesome Warnings and Admonitions, Tending to Restore and Turn them Again to the Lord, That They may be Saved by Him, Both from the Evil and Punishment of Sin.

[.salutation]
Dear Hearts,--

What lamentation shall I take up for you,--how shall I sufficiently
bemoan you who were visited in the springing forth of God`'s day,
and have thereby seen the way of Truth,
and felt something of that power of God which once made your hearts tender,
and caused the strong man to bow himself;
so that you began to be pliable unto God`'s will, and to love his precepts!
But now you are turned from the Light,
and wandered out of that way which you know to be true,
and have lost the feeling of the power of God and have your
hearts hardened by the deceitfulness of sin,
and overcharged with the cares of this life, and your wills at liberty,
as a bullock unaccustomed to the yoke, and running on contrary to that of God in you.
I say again, what lamentation shall I take up for you!
Surely if my head were waters and my eyes a fountain of tears,
I could not sufficiently bemoan you; for I plainly see,
that destruction and misery are in your ways,
because the Lord`'s good Spirit is daily grieved with you,
and his soul takes no pleasure in you that draw back from the paths of Life and Truth.

And they to whom you fly, and under whose shadow you seek to shelter yourselves,
cannot at all deliver themselves nor you from the wrath to come
upon all that are not obedient to the Gospel of Christ:
neither do they at all care for you.
Though they flatter with their lips, yet have they an eye to see,
that you who are treacherous to your own principles,
will easily become treacherous to them--so that your condition is exceedingly sad:
for in your present state you are an abomination to God, to his saints and angels,
a scorn to fools,
and a hissing and derision to the subtle adversary who has caught you in his snare.

Therefore consider your state;
and let me a little expostulate with you in the name of
the God of Heaven--What can be done more for a people,
that he has not done, and been ready to do for you?
Has not line been upon line, and precept upon precept, here a little and there a little,
that you might understand and lay it to heart?
Have not God`'s servants and prophets been frequently sent among you,
to whom God has given witness by his own Light in your consciences?
Moreover, has he not smitten you with the word of his own mouth,
and caused you to feel and dread his power?
Has he not also come in the spirit of meekness,
and with yearning feelings of love besought you to return,
when you began to stray from him?
Has he not also been ready to forgive your trespasses, and heal your backslidings;
and can you justly charge him and his servants with blame if you perish?
Did not he once appear unto you altogether lovely?
And with him there is no alteration nor shadow of changing.
Oh then, consider what has blinded your eyes, and why you turn aside from following him!
Do you not therein despise your birthright, as Esau, and betray the Just as Judas did?

Oh! woe is me for you that have let go eternal life,
and laid hold on this present world! for you have made a miserable exchange;
and the earth which you think to save you, is reserved unto fire;
and that which pertains thereunto and can delight in it, shall be burnt up.
When the terrors of death everlasting compass you about, where will you hide yourselves,
who, as Cain, have murdered the Just,
and must be banished from the presence of God forever?
And what good will all the earthly treasures wherein you have delighted,
do you in that day?
Shall not all the world`'s friendship then have an end?
And one tempter to wickedness shall curse another,
because they have been the occasion of each other`'s
misery--out of which gold cannot redeem;
nor can all the world`'s riches, glory and power, save one soul.

Therefore be awakened, all you who have not yet sinned unto death; but through distrust,
slavish fear, or the lusts of your own flesh, are veiled, and either stand still,
or are turned away backward.
For you may be renewed to repentance,
who have any sense of your out-running or grievous sin in backsliding;
if you be at all smitten, and grieve for the same, there is hope concerning you.
Therefore fear the rod, and Him who has appointed it:
and if there remain any feelings of tenderness or any spark of love to God,
if it be but so much as makes you sigh in secret for lack of him,
then arise and come away, and linger no longer in darkness where Satan has dominion,
lest you murder the Just, and so join to idols.
For why should you wander in the blackness of the night,
till in the end your steps take hold on hell, out of which there is no redemption!
Therefore I say again--be awakened, and do not trifle away the precious time,
lest the door of mercy be quite shut against you;
and take heed of giving any more way to an evil heart of unbelief, which says,
"`The Lord delays his coming,`" and thinks him slack in fulfilling his promises.
For that, with the worldly wisdom with which the serpent mixes,
may be the ground of your apostasy from the Life,
and the principal chain by which man is held from returning to God.

Because unbelief binders you from beholding his most glorious power,
and from enjoying the most precious treasures of his kingdom:
and then the worldly wisdom not being capable of discerning the invisible things of God,
which he has ordained to our glory, draws down the mind to save self,
and to lay hold on this present world; which you can in no way please,
and have its love and friendship, but as you displease God,
and lose his love and friendship.
Therefore seeing you cannot serve God and Mammon,
come forth and be separate from all idolatry, profaneness, and will-worship.
And if you are pursued with persecutions and reproaches, look not at them;
for such light afflictions are but for a moment,
and do work for us a far more weighty crown of glory;
which God will certainly give unto all that be faithful unto the end.
But it is a fearful thing to fall into the hands of the living and long-provoked God,
if you willfully disobey his Light in your own consciences, and rebelliously forsake him;
because he has power to cast into hell, where the wicked and all they that forget God,
shall be tormented perpetually.

What can I say more unto you!
But with yearning feelings of love, exhort you to search and try your ways,
and turn again to the Lord, who wills not your destruction;
but delights rather to pardon than punish you, because he loves you as his creatures.
And as you return to the Lord, when you see briars and thorns, grievous wolves,
and hungry eagles in your way to devour you, be not dismayed at all;
but with purpose of heart cleave unto the Lord, who is a consuming fire,
and he will make your way through them,
and you shall see all that stands in opposition to you, vanish as a shadow,
in God`'s work and way.
For the end of all things is at hand,
and the kingdoms of this world shall become the kingdoms of our God, and of his Christ;
and they who have suffered with him, shall reign with him,
says the Spirit of the prophets; but they that have denied him before men,
shall be denied by him at his appearing in the glory of his Father,
and the holy angels with him,
to give a reward to every man according as their works shall be.
Therefore consider, that if you for earthly things deny the Truth of God,
how will it grieve you in that day,
to stand afar off and see the Lord`'s innocent people
(who have not loved their lives unto death,
but freely given up all, that they might overcome,
through the blood of the Lamb and the word of their testimony)
receive a kingdom and a crown which fades not away,
while you are bereaved of all that wherein, you delighted,
and are compassed about with terror and covered with shame and contempt,
which is the just reward of all who deny the Lord that bought them;
who have put him to open shame by distrusting his power,
and turning from him in the sight of his enemies.

These things bearing a weight upon my spirit,
and because I do both desire to be clear of the blood of all men,
and do entirely love their souls, I have in this manner communicated them,
because I am a sufferer in outward bonds, among the Lord`'s valiant and faithful people,
called Quakers;
who though we have been despised and reproached by the wise professors of this generation,
yet are not of them that draw back to perdition, but press on to the end of our race:
wherein I say, Follow us, as we follow Christ.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 16th day of the Seventh Month 1662.

--
