== Chapter IX.

[.chapter-synopsis]
* Proceedings at the Quarter Sessions at Louth
* John Whitehead and other Friends remanded to prison
* Epistle to Friends at Whitby, etc.
* Two Letters to the Justices
* Two Letters to Judge Wyndham
* Sufferings of many Friends in Lincolnshire
* Letter from Twelve Friends to the Justices at Spital
* Letter from John Whitehead to the Justices at Louth
* Discharged from Prison

Before the Quarter Session following, William Bancoft was released;
some of the justices being moved hereunto by the imbecility and weakness of his old age;
and at the Petty Sessions for the parts of Kesteven, William Morris was released:
but John Cleasby and myself were carried to the General Sessions held at Louth,
the 7th of Eighth Month.

[.small-break]
'''

+++[+++Previous to their appearing before the court,
John Whitehead and John Cleasby addressed a letter to the justices,
remonstrating against the injustice of continuing
them in prison without allowing them a fair hearing;
and in the character of "`peaceable men, who fear the Lord and love justice,
truth and righteousness,`" pleaded for moderation and equity.
John Whitehead then proceeds:]

[.small-break]
'''

When we were brought before their judgment seat,
no one appeared to accuse us of the breach of any law of God or man;
but they sought how they might ensnare us concerning the law of our God.
We had already endured a long and illegal imprisonment, as we manifested in open court;
yet they made one injury done unto us the foundation of another,
and tendered to us the oath of allegiance, which we could not in conscience take.
We alleged, that that oath was principally, if not wholly, intended for popish recusants,
as was manifest by the reason of the law,
which chiefly was this:--The natural born subjects of this
realm did withdraw their due allegiance from the king,
and did yield obedience to a foreign power;
and upon that transgression was the law added.
But we give no such occasion for that law to be executed against us;
for we yield all due obedience to our temporal prince,
and utterly deny all foreign power;
therefore according to a rule of their own in the construction of laws,
the reason of the law ceasing, the law ought also to cease,
and not to be executed upon us.

But notwithstanding this, and many other reasons which we gave,
why they should not tender that oath to us, they urged us to answer,
whether we would take it or no: to which we replied,
(there being many present that professed to be ministers
of the Gospel,) "`if you or they can convince us,
that it is lawful for us to swear at all,
we shall not refuse to take the oath of allegiance.`"
But they wholly refused to dispute the matter with us,
and persisted in urging us to take the oath.
Whereupon we replied, "`That we were Christians,
and made conscience of the commands of Christ,
(Matt. 5:34) and therefore in obedience to him, could not swear at all.`"

Then they recorded our denial,
and fined each of us five pounds for refusing to
take an oath contrary to the late Act of Parliament;
which fine they then demanded us to pay in open court.
But we refused to pay it,
because in conscience we knew ourselves to be innocent
from committing any offence against God;
neither against the law of man did we any injury, but what they occasioned.
Whereupon we were withdrawn;
and they expressed that they would levy the said fine upon our goods,
according to the tenor of the said act,
or else that they would after a week`'s time commit us to prison for three months,
according to the express words of the said statute,
which runs thus--"`And for lack of such distresses,
or non-payment of the said penalty within one week after such conviction,
that then the said parties so convicted,
shall for the first offence be committed to the common jail
or house of correction for the space of three months.`"

But they then forthwith sent us back to prison by the following
order,--how contrary to law let the wise in heart judge:--

[.embedded-content-document.legal]
--

[.offset]
Lincoln Lindsey.

Whereas John Whitehead and John Cleasby were by the
Judge`'s order of the last court session,
sent to this session; where appearing in open court,
the Oath of Allegiance was severally tendered unto them,
according to an act of this present Parliament, which they obstinately refused to take;
and thereupon a fine of five pounds was imposed upon each of them,
in farther pursuance of the said act, which they also refused to pay,
in great contempt of authority, and of the laws and statutes of this kingdom.
It is therefore ordered by this court,
that the Sheriff of this county shall convey the said John Whitehead
and John Cleasby to his Majesty`'s jail at the Castle of Lincoln,
there to abide until they pay their respective fines, or take the Oath of Allegiance,
according to the said act in that case made and provided.^
footnote:[Here the court ordered contrary to the law,
which directs but to imprison for three months.]

[.signed-section-context-close]
Per curia`'

[.signed-section-signature]
Ex`' per Johannem Thornton,

[.signed-section-context-close]
Cleric`' Pac`'.

[.signed-section-context-close]
Dated 7th of October, 1662.

--

+++[+++Soon after this arbitrary re-commitment, John Whitehead wrote the following Epistle:]

[.embedded-content-document.epistle]
--

[.blurb]
=== To Friends at Whitby, Osmotherley, and in Blackamores, Cleveland, Bishopric, and That Way.

Feeling in my heart that love springing afresh, wherein I was first moved to visit you,
and freely to administer unto you what the Lord freely gave unto me,
I cannot at all be unmindful of you.
Though confined at a great distance from you, yet do I, in that love,
most dearly salute you all,
longing greatly to hear of your welfare and prosperity in the Truth.
And these things do I fervently desire of the Lord for you,
even that the eye of your understanding may be kept clear and open in the Light of God,
to see that exceeding great reward which is before you,
that does far surmount all that man can do unto you;
and also that both your faith and patience may be daily increased,
that therein you may be steadfast and constant in whatever
God calls you to do or suffer for the precious Truth,
which in much power has been made known unto you;
and I hope has had that operation in you,
that you are even prepared for this day of trial; and are so engaged to God,
through that pure fear and love, which he has put into your hearts,
that you cannot depart from him.

Therefore to the teachings of that holy anointing, that abides within you,
I do wholly commit you; exhorting you to take diligent heed thereunto,
because the times are perilous,
and there are now many false spirits gone out into the world,
some of which are transformed as the ministers of righteousness,
which by good words and fair speeches, out of the true power,
deceive the hearts of the simple, and draw them from the true feeling of God,
and of their own states, into airy notions and knowledge,
which does but puff up and not edify in godliness.
Therefore keep low to the pure, weighty seed of God in you,
which cannot bow to any image, nor join to any evil;
that you may with sound judgment measure and weigh all spirits:
and beware of that which is found too light, though excellent in speech,
for it will corrupt and gender to more ungodliness.
But wait to feel the power of God working in you: and grow in grace,
and in the sense of God`'s love unto you,
wherein he called you out of darkness into his marvellous Light;
that you may be a holy and peculiar people,
showing forth the virtue of the invisible God who dwells in you,
unto all people who have their eyes upon you.
Then shall he be in truth glorified and admired in you,
whose love constrains you to give up to do his will;
and not to love your liberty nor your lives more than Him who has loved you,
and washed you from your sins with his own precious blood;
whereby He does also nourish and strengthen you to overcome the wicked one.

Therefore, dear children, abide with Him; and as He has loved you, so love one another,
and that will draw you to meet often together.
And in the Word and breathings of life, comfort one another, as you are comforted of God;
so shall I also be comforted and refreshed by you in my bonds,
which I patiently endure for the Truth`'s sake.
For though I was called at the last General Sessions, held for this county,
and gave a good testimony for the Lord,
together with many sound reasons against my unjust imprisonment,
and their unjust proceedings against me, yet equity could not enter;
but contrary to right, I was fined five pounds for refusing to swear, and by their order,
am to lie in prison till payment.
But my time is in the hand of the Lord, who knows how to deliver me when he pleases;
to whom I have given up myself, and do rest in his will.

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
John Whitehead.

[.postscript]
====

I shall be glad to see or hear from any of you as you have freedom,
that I may perfectly know your state, and bear a part with you,
both in sufferings and spiritual rejoicing.

[.signed-section-context-close]
Lincoln Castle, the 25th of the Ninth Month, 1662.

====

--

After we had been kept prisoners by the foregoing order,
(which exceeds the rigour of the law,) at the next General Sessions, held at Louth,
the 13th of the Eleventh Month,
(not being permitted to appear in court,) we represented our case to the justices,
by this following writing, which was delivered into their hands:--

[.embedded-content-document]
--

[.blurb]
=== For the King`'s Justices of Peace, at the General Sessions, held at Louth: these.

Friends,--You may remember, that we whose names are subscribed,
after we had endured imprisonment a quarter of a year,
did appear at the General Sessions,
held at Louth the 7th day of the month called October,
where we expected to have been discharged, as in equity we ought;
seeing that no accuser appeared to charge us with the breach of any law of God or man;
but instead of that, an oath was tendered to us,
(although there was no occasion for it that we know
of;) for the not taking of which in open court,
although for conscience sake we refused it, we were fined each of us five pounds,
which you know was the rigour of the late Act of Parliament,
by which you proceeded against us;
whereupon we were withdrawn and heard no farther sentence,
expecting that we should at least in a week`'s time have been discharged,
and the fine levied upon our goods, according to the tenor of the said act:
but contrariwise, we were by your order remanded back to prison,
where we have patiently suffered fourteen weeks,
which is more by fourteen days that the law requires, in case the said fine be not paid.
Therefore we having suffered the utmost penalty that the law, upon which you proceeded,
requires for such an offence, we do appeal to your own consciences,
(who are sworn as well not to exceed the law as to execute it,) whether we ought not,
both by law, reason and justice, to be discharged.
But we have by virtue of the said act, demanded our liberty of the jailer, who says,
he cannot grant it without an order from you.
Therefore we write these things unto you,
that you may review the act and your former order, duly consider our case,
and do thereupon what to law, justice and equity shall appertain,
even as you would be done unto, if our case were your own.
However we remain lovers of justice peace and truth,
and shall ever desire your eternal good.

[.signed-section-signature]
John Whitehead.

[.signed-section-signature]
J+++.+++ Cleasby.

[.signed-section-context-close]
Lincoln Castle, the 12th day of the Eleventh Month 1662.

--

After the receipt of this, some of them acknowledged,
that we having suffered more than the penalty of the law,
ought in all reason to he discharged.
But instead of discharging us they made a new order,
(else their clerk has grossly abused them and done it upon his own head;) wherein they
have quite mistaken the matter of fact for which they fined us the Sessions before,
and feigned new matter, which was not mentioned in their former order.
It will be seen how their second order, here inserted, clashes with the other;
and shows that they who have no justice nor truth on their side,
have need of good memories, lest they confound themselves in their own doings,
as these have done, who only accord in this,--unjustly to detain us in prison.

[.embedded-content-document.legal]
--

[.offset]
Lincoln Lindsey

Whereas at the General Quarter Sessions of the peace, held at Louth,
in the said parts and county, at Michaelmas last,
John Whitehead and John Cleasby appearing at Court,
were then and there by their own confessions convicted
for assembling themselves with others,^
footnote:[Here this order clashes with the other, and falsely accuses us;
for we were neither convicted nor questioned for
meeting together then and there as they say;
for proof whereof, let the reader view their former order.]
under pretence of joining in a religious worship, contrary to an Act of Parliament,
made in the thirteenth and fourteenth years of our sovereign lord the King, that now is;
whereupon a fine of Five Pounds was imposed upon each of them,
which they then refused to pay, or to take the Oath of Allegiance,
severally tendered to them in open court, in great contempt of the laws of this kingdom:
whereupon they were committed to safe custody.
It is therefore ordered this day by the Court,
that the said fine of Five Pounds so set and imposed
upon the said J. Whitehead and J. Cleasby,
shall be remitted,^
footnote:[We having suffered already more than the penalty of the said act,
need not have it remitted, but ought to be discharged without these conditions,
which now they unjustly impose:
seeing that if hereafter we do anything that the law forbids, it is at our own peril.]
and they released from their imprisonment and all
the penalties mentioned in the said Act,
if they upon sight hereof do repair to some of his Majesty`'s
Justices of the Peace for those parts and county,
and there take the Oath of Allegiance; and also give security for the time to come,
that they and either of them will forbear to meet in any such assembly.
Anything in the former recited Order contained to the contrary notwithstanding.
Dated 13th of January, 1662.

[.signed-section-context-close]
Per`' Cur`'

[.signed-section-signature]
Thornton.

[.signed-section-context-close]
To the Keeper of his Majesty`'s Jail, of the Castle of Lincoln.

--

Notwithstanding this pretended discharge,
and that we had suffered more than the law in that case requires,
we could not have our liberty: whereupon we wrote to the justices as follows:--

[.embedded-content-document.letter]
--

[.blurb]
=== To William Wray, Robert Christopher, William Fitz Williams, William Woolley, Isaac Knight, John Bosswell, and to every of them.

Friends,--A copy of your order given forth at your Sessions, held at Louth,
the 13th of this month, we have obtained; whereby it appears, that you,
(or at least some of you,) neither take notice of your own actions,
neither of our afflictions, nor of the law itself,
which you are sworn equally to administer; for in this order you say,
That "`at the Sessions going before, we were convicted by our own confessions,
for assembling ourselves together with others, under pretence of religious worship,
contrary to the late Act of Parliament, etc.`" which is utterly false;
for no such thing was then objected against us,
neither were we at all questioned for meeting together at that Sessions;
neither was there any fine laid upon us upon that account, as this your order affirms:
but an oath was tendered unto us;
for the not taking of which we were fined each of us five pounds,
which you ought by law to have levied upon our goods and set us at liberty,
as the judges and other justices of peace have done to others in the like case.
For the very words of the Act run thus.--"`The said respective penalties
to be levied by distress and sale of the parties`' goods so convicted;
and for lack of such distress and non-payment of
the said penalty within one week after such conviction,
that then the said parties so convicted, shall, for the first offence,
be committed to the common jail, or house of correction, for the space of three months.`"
But for non-payment of the fine above-said, we have been imprisoned near four months,
though it was the first offence,
and also occasioned by them before whom it was committed.

Therefore your remitting the penalty of the law is needless,
because we have already suffered it, and more;
and therefore ought to be discharged without either of the
conditions that you in this order impose upon us;
whereby you show your tender mercy to be cruelty,
and not only below the mercy of the law, but above the rigour of the law.
For the mercy of the law would have discharged us
upon one of the conditions which you proposed,
as soon as ever we were convicted, before we had suffered anything;
and the rigour of the law would have discharged us
without either of the conditions that you impose,
seeing we have fulfilled it in suffering.
Therefore consider, how you do by your orders wrong and oppress us,
contrary to all law and reason.
So that we now suffer merely for not obeying your
wills in going to swear and giving bonds,
when there is no occasion for either.
If we should so depart from our principles, as to swear,
and deny our most Christian meetings as you would have us,
then could we also sue such as unjustly detain us;
and take a severe revenge for the false imprisonment,
wherein you have combined to keep us;
for there is nothing keeps us from revenging ourselves,
but that which brings us from swearing,
and to meet together in the name of the Lord Jesus Christ.

Therefore take heed of opposing that principle which
brings us to love and forgive our enemies,
lest you kindle wrath against yourselves, which you have justly deserved.
But the long-suffering of God waits for your repentance,
which we desire may be given you; who do not ask any mercy from you,
but rather justice which hitherto you have denied us;--the Lord lay it not to your charge.

And because we know some of you are learned in the law,
it makes us the more wonder that you should pass such an insignificant, unlawful order,
under the seal of your court, under pretence of a discharge,
which rather tends to straiten than discharge us.
Therefore if you intend to discharge us,
and the clerk you employ does of his own head detain us, through envy against us,
it becomes you to correct him, and amend the faults whereby your power is abused,
in sending us a free discharge according to law.

[.signed-section-signature]
John Whitehead.

[.signed-section-signature]
J+++.+++ Cleasby.

--

Notwithstanding this letter was received by some of them, they did not lay it to heart,
neither did they consider our affliction so as to let us go free;
though we had more than suffered the law,
yet were we detained by their orders until the court sessions began at Lincoln,
the 19th day of the First Month, called March, 1663, wherein Wadham Windham sat judge,
to whom we with others were returned by the calendar;
and we presented our case to him as follows.

[.embedded-content-document.letter]
--

Friend,--Since we understand that you have been for some years a judge in this nation,
and are well acquainted with the good laws and customs of England,
which abhor all arbitrary and illegal proceedings,
we are bold in this manner to represent our case, truly stated, unto you;
desiring that you may duly consider how we have been dealt with,
and do thereupon what to equity and justice does appertain.

[.numbered-group]
====

[.numbered]
_First,_
We do here truly declare that John Whitehead and John Cleasby were sent
to prison before the last court sessions that were held at Lincoln,
at which we expected to have had a legal trial,
and either to have been discharged or proceeded against as the law directs.
But we were, by order from you, committed till the next General Sessions,
without trial or hearing; and to Sessions we were carried:
and there appearing on the 7th day of the Month called October,
no accuser appeared face to face to accuse us of anything.
But the court was pleased to tender us an oath,
although there was no occasion for it that we know of; for the refusing of which,
(although we did it for conscience sake) we were by virtue of the
late Act of Parliament made against us who are called Quakers,
fined each of us five pounds:
and though by law we should have had a week`'s time to have either paid the fine,
or have had the same taken from us by distress,
yet we were forthwith sent to prison by orders from the said Sessions.
After we had suffered the penalty of the law, namely, three months in prison,
we made our address to the said justices for our liberty;
but it has hitherto been denied us,
though we have lain in prison above five months for that very thing,
for which the law imposes but three months; as by a due examination of our case,
and viewing of their orders, you may perceive.
Therefore we desire that one injury done unto us,
may not be made the foundation of another;
but since we have suffered more than the law requires in that case,
let us either have a free discharge or a fair hearing;
that the cause of our long suffering may be made manifest,
which in justice we are persuaded ought not to be denied us.

[.numbered]
_Secondly,_
That Samuel Davy was taken from a peaceable meeting
by soldiers without any warrant for that place,
and committed to Spalding Bridewell till Sessions,
where he conceives he ought to have been tried for what he was imprisoned.
But contrariwise they tendered him an oath, which he gave no answer to,
because he conceives he ought first to have been cleared of his imprisonment.
Then they ordered him to this prison, as a ringleader;
yet the clerk made his court order for refusing an oath,
which was tendered upon the new Act made against Quakers and others,
which for the first time he conceives to be but three months imprisonment,
or five pounds fine, according to the statute;
but he has been detained a prisoner more than three months.

[.numbered]
_Thirdly,_
That Edward Parish was sent for by a party of soldiers from
his own house without any warrant from any justice of peace,
and commanded to appear before the deputy-lieutenants,
to answer such things as should be objected against him; which accordingly he did;
and although no accuser appeared to charge him with anything done contrary to law,
yet they committed him to prison,
because he (knowing himself innocent,) could not give bonds for good behaviour,
and have ordered him to lie in prison till he either do the same,
or be discharged by some of the deputy-lieutenants,
or some of the justices of the peace for the parts of Lindsey.

====

And we do farther declare, That it is for our conscience sake that we cannot swear;
and because we know nothing by ourselves worthy of bonds, we cannot give bonds;
and do not refuse in contempt of the king or his laws,
or any that are set in authority under him.
For though our sufferings are, and have been very great, yet we are peaceable men,
and neither do at present, nor ever shall seek the hurt or destruction of any man or men,
either in their persons or estates.
What others have done should not be imputed to us, who are of another spirit and mind,
which leads us not only to love our neighbour as ourselves, but also our enemies.
Therefore we do once more, as our birthright, desire that we may partake of that justice,
which (you said) "`flows from the throne like a pure
stream,`" but which has savoured like wormwood,
as it has been handed unto us by inferior magistrates.
So expecting that you will not deny those fair proceedings to us,
which you so freely allow to others, whose cases are criminal, we subscribe ourselves,

[.signed-section-closing]
Sufferers for conscience-sake,

[.signed-section-signature]
John Whitehead, John Cleasby, Samuel Davy, Edward Parish.

[.signed-section-context-close]
Lincoln Castle, the 12th of the First Month, 1663.

--

But the Judge did not call us at all, yet did he discharge Samuel Davy and Edward Parish,
also John Cleasby whose case was the very same with mine, as may be perceived;
but he ordered me to lie in prison till the next Sessions, and abide their order,
although he afforded me neither trial nor hearing,
neither did any accuser openly appear to charge me
with the breach of any law of God or man.
Therefore after I understood what was done, I wrote to him as follows.--

[.embedded-content-document.letter]
--

Friend,--If I be an offender, why is justice delayed, and not speedily executed upon me?
But if I be innocent, why do you deny me my liberty which of right is due?
Why do you asperse us openly, and refuse to hear us openly before the country?
Were you afraid that our innocency should appear, or would you have covered their shame,
who have done violence unto us?
Is it not both against the law of God and man,
to imprison me without hearing what I can say for myself?
For does not your law presume every man innocent till the contrary appear?
And how can the contrary appear without trial?
Though Felix was willing to do the Jews a pleasure,
he left not Paul bound without hearing, though he was counted the ringleader of a sect;
and have you acted like a Christian magistrate, in leaving me bound now the second time,
whom you have never heard speak for myself;
or rather like a man blinded with prejudice against me?
Since you have released others, whose cause was the same,
are not you a respecter of persons?
Let God judge between you and me in this matter: to whom I appeal, being assured,
that he will hear me and look upon my afflictions,
and in due time execute judgment for me.
And in that day shall you be inexcusable O man! forasmuch as you know,
that they who justify the wicked, or condemn the innocent,
are both an abomination to the Lord.
Therefore consider, that your breath is in your nostrils, and repent,
if peradventure you may be forgiven for all your hard thoughts and hard speeches;
which is the desire of my soul, who am

Your friend in truth, and therefore cannot flatter,
but am obliged thus faithfully to warn you.

[.signed-section-signature]
John Whitehead, Prisoner.

[.signed-section-context-close]
Lincoln Castle, the 14th day of the First Month, 1663.

--

+++[+++As John Whitehead was conspicuous in his religious service,
and in his zeal for the cause of Truth,
he was doubtless regarded by his persecutors as one
on whom it was especially desirable to impose restraint;
and scarcely any pretext seems to have been too trivial
or unreasonable to serve their purpose.
No other reason was given for this further detention in prison, than,
that the Judge`'s will was to have it so, which one of the justices said was a law.

Six other Friends were now in prison with him, for non-payment of tithes.
Two of them, Vincent Frotheringham and Robert Whiteman, were kept in prison three years,
and another, Thomas Richardson, more than a year.]

[.small-break]
'''

Besides what is above spoken of, +++[+++John Whitehead continues,]
there have been many more in prison for the Truth`'s sake, in this county.

In the parts of Holland (one of the three divisions of Lincolnshire) Samuel Davy,
Henry Wilson, Gregory Sherwin, William Carnall, John Thompson, Stephen Willoughby,
George Reeve, John May, Susan Thomas, Margaret Smith, Rebecca Preston, and Ellen Wilson,
were apprehended on the 5th of the Eighth Month,
without any lawful warrant to that place where they
were met together in the peace of God.
The man who apprehended them was no civil officer, but a sword-man;
therefore they objected against him, and would not have gone with him; but he said,
"`he would make them go, or trail them at a horse`'s tail.`"
They were taken to Justice Jay, and by him committed to Spalding prison,
for meeting together in the fear of God; where they remained but five days,
and were then all released but Samuel Davy, whom the justices had formerly threatened;
because he did, before a judge of the court session,
witness against some of their former illegal proceedings against him.
Having now got an opportunity to do something against him,
one of them called him the grand rogue;
and waiving the matter for which he was brought there,
they determined to send him to prison as a ringleader,
and therefore tendered him an oath;
and for not giving answer whether he would take it or not,
they sent him to the Castle of Lincoln, where he remained twenty-two weeks,
till he was delivered as before signified.

At the same Sessions, John Titman, Edward Tisdale and George Billers, were committed,
for not submitting to the court, being indicted for not going to the steeple-house.
For that very thing,
those three innocent men were kept prisoners about a quarter of a year.

Upon the 12th day of the Eighth Month, Thomas Summers, Christopher Clark, John Scotney,
Edward Fisher, John Sandby and Thomas Mathers,
were also apprehended at a peaceable meeting,
and carried before Justice Burrel and Justice Oldfield, of Pinchbeck, who therefore,
though with some reluctance, committed them to Spalding prison.
Justice Burrel said, he had rather have been at plough; and Justice Oldfield,
that he had rather have been at plough ten times.
Notwithstanding,
these six innocent men were kept prisoners at Spalding about a quarter of a year.

At the Sessions held at Spalding, in the Eleventh Month, they appeared, and were,
together with John Avy and six more, indicted,
"`for meeting together under pretence of religious worship.`"
To this indictment they pleaded not guilty, and desired a present trial;
but the court put them off, and upon their promise to appear at the next Sessions,
dismissed them.

Upon the 14th day of the Tenth Month, Vincent Barrow, John Thetting, Thomas Yorksey,
Robert Kelsey, Peter Moody, Thomas Barrow, Charles Tate, John Clark, William Clark,
Richard Parnell, John Spicer and Thomas Halifax, being met together in the fear of God,
to wait upon him for the guidance of his Spirit, that therein they might worship him,
were apprehended and brought before John Moonson senior and John Moonson junior,
without any lawful warrant; who therefore, and because they could not swear,
committed them to prison on the 17th day of the Tenth Month,
where they were detained until the 15th day of the Eleventh Month.
On that day they appeared at the General Sessions held at Spital,
and delivered this following paper to the justices, subscribed with their hands:--

[.embedded-content-document.paper]
--

[.salutation]
Friends,

We are a people that do fear the Lord, and follow after truth and righteousness;
for which we have been exposed, and still are, to very grievous sufferings,
wherein the God of Heaven and earth has hitherto upheld us; to whom we do appeal,
that we are innocent towards you, and all that be in authority over us.
We are not of them that are profound to make slaughter,
neither can we plot or contrive to shed the blood of our enemies; but do love them,
according to Christ`'s doctrine,
and desire to live peaceably in all godliness and honesty;
for which cause we have hitherto paid taxes, custom, and all other just dues,
as they have been lawfully demanded of us.

When we meet together, it is in the fear of the Lord,
for no other end but to worship him in Spirit and in truth.
And we hope you will not deny that that worship is authorised by the laws of the land.
If so, then our meeting together for that very end,
is no transgression within the compass of the late act,
and consequently we ought to be indemnified.

Therefore, in equity and moderation consider our case,
and measure no other measure unto us than you would have measured to you again.
For why should we suffer merely for seeking to keep
our consciences void of offence towards God,
when we do no manner of wrong towards men?
And we do further appeal to your very consciences, whether it be not against common good,
to take us from our husbandry and other honest diligent labour,
and thrust us up in jails and correction-houses,
where we cannot be so serviceable in our generation,
nor labour for the maintenance of our wives and children;
when we have committed no offence nor wicked lewdness,
that in justice deserves such punishment?
And if you fine us for worshipping God according to our consciences,
and set hard-hearted men to take spoil of our goods, then consider,
how can we pay rents and taxes, and maintain our families?
Will you not be guilty of bringing ruin and destruction on us in this world,
who have not deserved such hard measure from you, as our consciences bear us witness?

Therefore have we confidence to commit our cause to the Lord,
and in his strength can cheerfully suffer what you can do unto us,
and praise Him that has counted us worthy to suffer for meeting in his name,
and obeying his doctrine.
Nevertheless, we desire that you take heed of shortening your own tranquillity,
and provoking the Lord to take vengeance upon you:
for we cry unto him when we are oppressed, and he does certainly hear us,
and will right our wrongs, when he has allowed you fully to try our faith and patience.
So into his will we are given up, and remain,

[.signed-section-closing]
Lovers of your souls, and desire your eternal good.

--

Notwithstanding this paper, and although no one appeared to prosecute them,
yet were they examined by interrogatories, concerning their meetings;
and because they would not deny,
but confessed that their meeting was for the worship of God,
they were fined each of them thirty shillings.
But the justices of that Sessions were more noble than they of Louth,
for they forthwith discharged them of their imprisonment.

Likewise Thomas Markham, Robert Rockhill, William Williamson, John Rockhill,
and Thomas Benson, for meeting together in the peace and love of God,
were apprehended by Daniel Whitekombe, who said, his sword was his order:
and he took them before Edward Roseter, who committed them as prisoners.
But they remained in the constable`'s custody till the Sessions at Castor,
the 14th of the Eleventh Month, 1662, where they appeared,
and were indicted by the same party that apprehended them,
who gave this evidence against them,
That he found them together in Elizabeth Lellingrave`'s house; and on asking them,
Why they were met together?
They told him they were met in peace and love; and that was all that he could say.
Whereupon an indictment was found against them by the grand jury; some of whom confessed,
that they heard not the evidence;
and the accused were not permitted to speak for themselves.
But without any legal trial, was each of them fined twenty shillings;
one of the justices saying, "`It was a breach of the law,
if they were found above five together, whatever the occasion was.`"
If it be so, we are not only deprived of liberty to worship God,
but also of human society:--how hard measure that is, every sober man may judge.

Also three poor labouring men, James Taylor, Thomas Norton, and Robert Walker, were,
about the 5th day of the Twelfth Month, 1662,
taken from their distressed wives and children,
and all by one cruel priest sent to prison,
because they could not with a good conscience give him tithes of their hemp,
their roots and milk,
which with great industry they provided for their poor wives and families.

Surely the early ministers of Christ would have been ashamed of these practices;
who declared, that after their departure, "`grievous wolves should enter,
not sparing the flock,`" which we daily experience to be true.
But in all these things our eyes are unto the Lord,
of whom we have obtained help unto this day;
and through his mercy we choose rather to die in prison,
than to violate our consciences for our outward liberty; being assured,
that God will reward us according to our doings, and them also who afflict us,
according to theirs; for such as everyone sows he shall reap; and look,
with what measure anyone measures it shall be measured to him again.
And if any be offended or ashamed that their deeds are brought to light,
let them be much more ashamed to do such things as cannot
be reported without being a stain to their honour and reputation,
or an ill savour in the country;
for there is nothing secret that shall not be made manifest.

After having been thus the second time recommitted by Judge Windham`'s order,
without trial or hearing, I was kept prisoner till the General Sessions, held at Louth,
the 28th of the Second Month, 1663, where there sat Robert Christopher, William Woolly,
Isaac Knight, and William Fitzwilliams, to whom this following letter was delivered:--

[.embedded-content-document.letter]
--

[.blurb]
=== For the King`'s Justices, at the General Sessions in Louth, to read and consider with a meek spirit.

When will you hearken to the cry of the oppressed, and execute justice for the stranger?
Surely you cannot be so ignorant of the law,
but must know that the wrong which I have already suffered is exceedingly great,
since you may understand that I have now been a prisoner about ten months,
seven of which I have suffered in that very case where the
law says the offender shall suffer but three;
and surely you cannot reasonably judge, while by your order I have been kept in prison,
that I have done anything worthy of bonds,
for which I should be detained four months longer than the law requires.
Therefore how can you in honesty tax me for not conforming to the law,
since I have more than fulfilled it through sufferings?
I can do no less than appeal once more to your very consciences for justice and right;
and the rather,
because the judge of the court session has now the
second time denied to take cognizance of my case,
save that at the court session he ordered me (whom he never saw,
nor heard speak for myself) to lie in prison, and abide your order at this Sessions,
which I expect may be to enlarge me,
because I am persuaded no man can justly charge me with anything worthy of bonds.
Therefore do not seek occasion any longer to detain me in your county;
which I the rather desire,
because I understand that I am already presented
in the Ecclesiastical Court in the county of York,
where I cannot make my appearance, to answer such things as may be objected against me,
if you detain me a prisoner here.
Therefore, if you judge me to be a troubler of your country,
and would have me out of your coasts, then let me go free;
that as I have confessed Christ Jesus and his heavenly doctrine, in your courts temporal,
so I may confess him and the right way of God`'s worship,
in theirs that are deemed spiritual.
But if this just and reasonable desire may have no place in you,
so as to procure my liberty, which has of right been long due, then know,
that since the Scripture cannot be broken,
but they that will live godly in Christ Jesus must suffer persecution,
it is all one to me where I suffer;
being through God`'s power made as willing and content
to suffer whatever you can inflict upon me,
if it be to the loss of my life, for the truth I profess,
as I was the first day you caused me to be shut up in prison;
being assured that my reward is with the Lord,
who will also recompense you according to your doings.

[.signed-section-signature]
John Whitehead.

[.signed-section-context-close]
Lincoln Castle, the 25th of the Second Month, 1663.

--

After the reading of this letter, one Captain Foster, who is a tender man,
and has some authority under the Earl of Lindsey, did also speak something on my behalf;
which, together with the innocency of my cause, did so work upon the justices,
that as soon as I came to the bar,
I was by the above-named justices discharged from my long imprisonment.
