== Chapter XI.

[.chapter-synopsis]
* A General Epistle to Friends
* Address to Judge Gregory
* Second trial at the Lincoln Court Sessions
* Again remanded to prison
* Apology to the Judges, Justices, etc.

+++[+++A few months after this unjust sentence was passed,
John Whitehead became concerned to impart from his prison-house, encouragement,
caution and counsel to his fellow-professors;
and accordingly addressed to them the following weighty Epistle.]

[.embedded-content-document.epistle]
--

[.letter-heading]
A General Epistle to Friends

[.salutation]
Dearly Beloved Friends, Brethren, and Sisters,

I being a prisoner for the Word of God and the testimony of Christ Jesus,
having no other way to manifest that care and love
which are in my heart for you and to you,
it is come upon me to write this Epistle, to stir you up by way of remembrance,
to call to mind the days that are past, wherein the Lord in great mercy did visit us,
when we walked as other Gentiles, in the vanity of our minds.
And being alienated from the life of God, we had no ability to overcome those lusts,
whereby we were enticed into evil, to the wounding of our own souls,
and the darkening of our understandings;
until it pleased the Lord to visit us with the springing
forth of the blessed day of the Sun of righteousness,
whose holy Light shined in our hearts and consciences,
which discovered unto us our lost state and undone condition,
while we lived without God in the world.

In this Light the quickening power of Jesus Christ was manifest in us,
which brought us to an inward sense of our own weakness and corruption;
under which we were truly bowed down, and broken by the righteous judgments of God;
which wrought great humility and tenderness of heart and conscience in us,
through the appearance of his grace, by which we were exercised in his holy law,
which he wrote in our hearts.
He put his fear in our inward parts,
whereby we departed from evil and received ability to do good,
through the obedience of the Spirit of Christ Jesus;
who washed and sanctified us with his precious blood,
that we might be fitted for his use and service, after he had so mercifully visited,
illuminated and accepted us.

Oh! the love which God shed abroad in our hearts,
when he had enlarged us to run the way of his precepts, is more than can be expressed;
which love constrained us to seek his glory, and the good of his scattered people,
with the hazard of our lives, liberties,
and whatever else was near and dear unto us in this world.
We gave it all up through that love which was the
bond of our friendship with God and one with another,
wherein also we were edified and became a habitation of God,
whose tabernacle is with us.

And however he has permitted us to be smitten with the rod of men,
he has not taken his lovingkindness and mercy from us,
though our exercises have been many,
and the perils and tribulations which we have gone through, have been of various kinds,
and those with false brethren none of the least.
For no sooner did we begin to appear in that testimony which we had received from God,
but we had many adversaries, besides the imitators that from among ourselves arose,
uttering perverse things;
which gave occasion to professors and people to bend their tongues like bows against us,
in reproach, cruel mocking, reviling, slanders, stoning and buffeting;
all which the meek spirit and life of Christ Jesus manifested in us,
shone through and overcame; even as the wind blows where it wishes,
and disperses fogs and mists of darkness, that arise out of the earth.

Insomuch that the priests, who were ringleaders in those things,
were eager to call to the magistrates for help, who employed their power to crush us,
by imprisonment, whipping, and other wrongful vexations, as finings,
spoiling us of our goods, and the like.
And when that generation of professing priests saw they prevailed nothing,
they struck hands with the Church of England, which they had exploded, to suppress us.
Yet through all these things Truth has prevailed, and God has glorified his own Name,
in which he gathered us, and has blessed and prospered us into a people.
And now let the watchmen of the Church of England
beware of striking hands with the papists,
to help to root us up from being a posterity in the earth,
lest they also be swallowed up of their helpers; for again God will glorify his own Name,
and preserve his people in the sight of his enemies,
that he may be admired in them that fear him and trust in his Name.

And now, being sensible that that generation which saw the wonders of the Lord,
and were upheld by his mighty power, is passing away,
and that many of them have gone before us to their everlasting
inheritance with Christ Jesus in his kingdom;
and that another generation which has heard more, but seen and experienced less,
both of the wiles of Satan,
and of the operation of God`'s power which discovers and breaks his snares,
is entering into the vineyard,
even the offspring of the elders who through faith
and patience have obtained a good report,
besides many others who have come in at other hours of the day,
who must all be tried and proved, as virtuous men have been in all ages,
who have obtained like precious faith; it is my heart`'s desire and prayer unto God,
that we may all be found unto the praise and glory of God,
who has called us out of darkness into his marvellous Light;
that everyone may be counted worthy of eternal life,
and be made up among the Lord`'s jewels, and gathered into his treasury.
And for this cause bear with me in a word of exhortation, warning and advice,
which in the love of God I send among you,
from the movings of the Spirit of Christ Jesus,
that quickens us and knits us together as members of his body,
in which we both suffer and rejoice one with another,
having a sense and feeling of one another`'s conditions.

And first, I write unto you fathers and ancients among the flock and family of God,
who have known the Lord`'s great work in the beginning,
and the manner of his carrying it on, both in yourselves and others.
Blessed are you of the Lord who keep your habitation in him, and humbly walk with him,
daily enduring the cross of Christ Jesus,
and the contradictions of sinners against yourselves;
knowing that the servant is not greater than his Lord; and that we only can be preserved,
increase and grow, as trees that bear good fruit and wither not,
by the same principle of life which first quickened us unto God;
and therein let us abide forevermore.
And be exercised towards God in all your assemblies,
wherein the oversight and care of the flock of God come upon you,
who mark the end of our conduct.
And therefore that we may be kept holy and blameless in the love of God,
and in the meekness, patience and humility of Christ Jesus,
to be good examples to them that follow after us,
is the earnest desire and travail of my soul.

And you that are young men,
in the flower of your strength because the Word of God abides in you,
whereby you have in a good measure overcome the wicked one: Oh! my dear brethren,
watch and be sober, be modest and lowly-minded, fearing the Lord always,
lest you be again entangled with any yoke of bondage,
or with the pollutions of the world,
which you have escaped through the power of Christ Jesus;
and also lest you be ensnared by the wicked one, whom you have many times overcome;
for by faith we stand, not bearing the root, but the root bears us.
It behooves us to keep on our armour of Light, in which walking,
we have our feet shod with the preparation of the gospel of peace,
and wear the helmet of salvation, and the breastplate of righteousness,
the shield of faith, and sword of the Spirit which is the Word of God,
by which we are enlightened to see the devices of Satan, and his wiles and temptations.
His deadly malice is against us, and therefore he seeks to devour us,
or to bring us into danger, either by inward temptations or outward violence,
which he stirs up in this time of our trial and adversity,
making use of those for instruments who have dealt
treacherously in the land of uprightness.

Therefore let us be circumspect in word and conduct; committing our way unto the Lord,
who weighs the mountains in scales, and the spirits of men as in a balance;
who with the breath of his mouth will scatter the chaff,
and disperse the clouds of darkness,
which would obscure the glory of his heavenly appearance, as he has done in ages past,
and likewise in our days, of which many of you are witnesses.

So having this hope, we faint not;
but believe the God of peace will tread Satan under our feet,
and that through Christ`'s power, (without whom we can do nothing),
we shall triumph over the wicked one.
And as you have obtained the love, goodness and mercy of the Lord,
let the same freely run through you, that by patience, meekness,
long-suffering and seasoned doctrine, you may gather in the scattered;
and that those who have halted through feebleness of mind,
may have stumbling-blocks removed out of their way, and be confirmed;
and all the upright in heart be preserved in the unity of the Spirit and bonds of peace,
by your diligent labour in your monthly and quarterly meetings, and elsewhere.
And let love abound in your hearts one to another,
according to that old commandment which Christ gave his disciples;
for in that you may edify one another;
but "`the wrath of man works not the righteousness of God.`"

And you children who have known the Father,
through the Light of his beloved Son Christ Jesus who has shined in your hearts,
in whom you have believed, that you might receive remission of sins for his Name`'s sake;
take diligent heed unto yourselves, lest you grieve the Spirit of God,
through which you have received the adoption and are sealed unto the day of redemption.
But watch and be sober-minded,
lest the adversary who presents himself among the sons of God,
when he comes from walking to and fro in the earth, get advantage against you,
and draw your minds out from the pure holy Seed whereby
you are begotten into the love of God;
from which fervent breathings, and holy desires and godly zeal, spring up in broken,
tender and humble hearts.
Thereby nourishment is drawn in daily, which keeps you growing, fresh and fruitful,
while you abide in a holy reverence,
and devoutly given up to walk in the true Light and Life of Jesus Christ,
who is both our Saviour and Preserver,
without whom we can do nothing well pleasing unto God.

And therefore, little children that abide in him, grow more fresh,
lively and fruitful than aspiring spirits,
or lofty branches that run out till they have lost their hold in the root,
which should nourish them.
Oh! how soon do they become like corn on the house-top, decay and wither,
when their expectations are frustrated, their faith, by which they should stand, fails,
and their desires grow weak and feeble, their love and zeal cold!
For where humility is lacking, there is not a capacity for receiving more grace:
for such as are lifted up, are wise in their own eyes,
and conceited that they lack nothing, but abound in their own sense,
and are full of words,
and have not a place in them to receive that virtue
which the Lord is ready and willing to communicate.

Therefore, dear children, be not high-minded, but wait upon God in silence, humility,
and pure fear;
that of his fulness you may receive grace sufficient for you in all your exercises,
and a spring of holy understanding, to deliver you from the snare of death.
For the Lord has a regard unto you that fear him and think upon his name,
in these trying days, wherein the proud are counted happy,
and those that work wickedness are lifted up.
Therefore look not out, nor be dismayed at what man can do unto you,
whose breath is in his nostrils, for wherein is he to be accounted of?
But be faithful and valiant in keeping your meetings to wait upon God,
and worship and serve Him that made heaven and earth,
who knows how to glorify his own name, and reward all his faithful servants and prophets,
and them that fear his name, small and great.
So when you see the wicked flourish like a green bay tree,
and live in wealth and pleasure, prosperity and dominion,
let not your hearts be troubled,
though with rigour they rule over you and oppress you on every side.
For the Most High beholds it, and has an ear open to the cry of the poor,
and will deliver his children out of the jaws of the devourers,
and give them a sure reward and everlasting inheritance in the sight of their enemies,
who thought their life bitter, and their end without honour;
for the righteous enter into everlasting life,
and the wicked go into everlasting punishment,
and the gulf is fixed that they cannot change their minds nor their state,
for their torment endures forever:
but the meek and patient sufferers and faithful followers of Christ Jesus,
shall enter into their Master`'s joy, which is unspeakable and full of glory.

And you that are convinced,
and have a profession of Truth from the knowledge of things comprehended in the understanding,
from what you have heard and read,
and the advantages you have had by your education,--it lies upon me to
exhort and warn you to wait to possess the true Christian Life,
and to take heed of resting satisfied with that which you have taken to yourselves;
for it is the gift of God that is eternal life, which is to be waited for in the cross.
And also take heed that you confide not in your ability to do anything of yourselves,
for that will be rejected, till you know and inwardly feel the Seed of God,
and his work in your hearts: and this is the work of God,
that you believe in the Light of Christ Jesus, and be planted into his death;
that dying together with him, his Life may be made manifest in your mortal bodies;
that both your souls and bodies may be capable of glorifying God,
in bringing forth the fruits of his Spirit, wherein he can delight:
for now is the axe laid to the root of the tree,
and every tree that brings not forth good fruits,
must be hewn down and cast into the fire.
But the long-suffering and patience of God lead to repentance;
and have been great towards many of you, who have stood in a convinced state,
but have been negligent and careless; not walking worthy of the mercy of this day,
wherein the Lord has not been lacking to you, but has visited you time after time,
looking that you should bring forth good fruit.
And through the intercession that has been made for you,
he has let you alone year after year,
and his servants have laboured among you in the Lord`'s vineyard,
that you might be fruitful, while the rain has descended upon you.

But Oh! how many are yet barren,
or like that ground which does not bring forth herbs fit for the dresser,
but briars and thorns, and other unsavoury weeds, in which the Lord takes no pleasure!
And therefore I am sensible that wrath is kindled against that ground,
and those unnatural branches which bring forth evil fruits,
who sit and speak against their brethren, and slander their mothers`' children;
who because of his long-suffering have thought the Lord delayed his coming,
and therefore have joined with his enemies, and smitten their fellow servants,
labouring as much as in them lies, to expose them and all their faithful testimonies,
to the scorn and fury of this profane and desperate age.
For this cause a day of trial is come,
and the Lord will manifest whom he has chosen to
feed his lambs and to watch over his flock;
and they shall come near unto him, and have the Light of his countenance,
and in all their troubles be comforted with the presence of the Lord:
while his indignation smokes against all that are treacherous and false-hearted,
who have not regarded the glory of the Lord,
nor sought the prosperity of Zion in what they have brought forth;
but have seen false burdens, and caused the unwary to stumble,
and turned the simple from the right way:
and their reward shall be according to their works.

Therefore all dear Friends, keep your habitation in the Light,
and be followers of that which is good;
that in you may arise and increase the first love and faith
by which you believed the record that God gave of his Son,
in the unity of whose Life and Light we were blessed and prospered into a people.
And the Lord has delight in us, and will preserve us as a nursery of tender plants,
from which shall spring a mighty people; though the nations are angry,
and may seek to hinder the work of the Lord, who will distress them, as in ancient time,
that they may be tried that dwell upon the earth.
Therefore all tender-hearted Friends, take heed of looking out,
but abide in the Light where there is no occasion of stumbling;
for it judges down all evil thoughts and surmising one of another,
which gender to strife,
and tend to break the bonds of love and friendship one to another, which are,
and of right ought to be kept inviolable among the disciples of
Christ--that being the great commandment he has given to them,
and the principal mark he has set upon them through all generations.

Therefore dear brethren and Friends, love the Lord with all your hearts;
for that is a perfect bond to keep you in obedience to him:
and love one another as your own souls;
that you may sympathise one with another in afflictions, and help,
comfort and support one another, as the Lord has helped and comforted you;
that it may be manifested by your works,
that you have obtained like precious faith with the holy ancients,
who said not to those that were destitute and afflicted,
"`Be warmed and filled,`" but did minister unto them
of the ability that God had given them;
that by works of charity and mercy their faith might shine forth,
having virtue added unto it,
which makes the true faith to differ from the opinions and made-faiths,
which will all fail and come to an end; but the true faith, which stands in God`'s power,
shall have the victory, and those that possess it shall overcome the world: even so,
Amen.

[.signed-section-context-close]
From Lincoln Castle, this 21st of the Tenth Month, 1682.

[.signed-section-signature]
John Whitehead.

--

+++[+++At the time of the next court sessions at Lincoln,
which began on the 5th of the First Month, 1683, some of John Whitehead`'s friends,
having conferred with the clerk of the court sessions on his case,
informed him that he would "`be called to answer;`" he therefore
addressed a short statement of his case to Baron Gregory,
who sat as judge on the crown side, as follows:]

[.embedded-content-document.address]
--

[.letter-heading]
To the Judge of Life and Death.

This true state of my case, shows,--That I was taken and imprisoned,
being without ground or reason suspected to be a Jesuit,
and sent to prison by a court order, under the hand and seal of Justice Burrel,
bearing date the 22nd of May last past;
and at the last court sessions held for this county, I expected a fair trial,
that so I might have suffered, or been discharged, according to law.
But no man appearing that could prove me such a person,
nor manifest any true cause of suspicion, I expected to have been released,
as other men that were imprisoned upon suspicion and had nothing proved against them,
were; and the rather, because my innocency was cleared by authentic certificates,
which I produced in court.

But contrary to my reasonable expectation,
(which arose from the satisfaction I offered in court,)
one injury was made the foundation of another,
and I was surprised with the tender of an oath, which, I believe,
this court knew I could not take for conscience-sake.
Not that I disliked the allegiance therein required,
for I offered in court to subscribe the substance of it,
declaring my testimony against any oath whatsoever; and showing,
how that oath ought not to be tendered then and there to me: notwithstanding which,
I was judged to remain in jail, as a prisoner convicted of premunire,
for refusing the oath of allegiance, to the utter ruin and breaking up of my family,
so that I am reduced to that misery which accompanies imprisonment,
without means of getting a livelihood.
Therefore my request is, that I may be discharged from this my imprisonment,
that I may labour in the thing that is good, to relieve myself and distressed family.
So, in doing to me as you would be done unto if you were in my condition,
you will have peace, and I shall ever desire your health and prosperity,
who am a prisoner in the castle of Lincoln.

[.signed-section-signature]
John Whitehead.

--

Upon the 7th day of the First Month I was brought to the bar,
and the clerk of the court session said there was an indictment
against me for refusing the oath of allegiance;
and asked, whether I would traverse or submit?

[.discourse-part]
_John Whitehead._--I have been imprisoned ever since the last court session,
as a person convicted of premunire, and have not seen the indictment, nor pleaded to it,
and therefore desire that I may have a copy of the indictment,
and time to advise with counsel before I plead.
For I have been hardly dealt with;
having been first sent to prison upon a groundless suspicion
of being a Jesuit and seducer of the king`'s subjects,
which no man was able to prove,
and therefore I expected to have been quit according to law.

[.discourse-part]
_Judge Gregory._--Do you deny that you are a Jesuit?

[.discourse-part]
_John Whitehead._--I do deny that I am a Jesuit, and ever did so.

[.discourse-part]
_Judge._--But are you not in orders as a Romish priest?

[.discourse-part]
_John Whitehead._--I am not,
but am able to manifest the contrary by good and authentic certificates,
from my neighbours, which I produced in court at the last court session,
which showed my manner of life and reputation among my neighbours for thirty years;
which I have here in readiness if the Court please to view them again.

[.discourse-part]
_Judge._--That is no matter now: but are you not a preacher, and speak in meetings?

[.discourse-part]
_John Whitehead._--Where are my accusers?
If any have anything to charge me with, I shall answer.

[.discourse-part]
_Judge._--Will you plead to the indictment?

[.discourse-part]
_John Whitehead._--I desire a copy of it,
and time to consider of it till next court session.

[.discourse-part]
_Judge._--Will you take the oath?
If you will take it, you may be discharged.

[.discourse-part]
_John Whitehead._--The law requires due process, from first to last, which I have not had,
being never discharged from my first court order, by which I was committed:
and when I last appeared in court,
and expected to have a trial of the matters therein suggested,
which were slanderous and could not be proved,
then I was surprised with the tender of an oath,
knowing no reason they had to call my allegiance in question:
I having faithfully performed it, and do still intend to perform it,
as becomes a good christian and protestant subject.

[.small-break]
'''

It was observed by some, that Doctor Fuller the chancellor,
and justice Harrington whispered with the judge,
and instigated him against me with great earnestness;
which occasioned this reflection from me afterwards--"`If you be men, act like men;
and if you have anything to say against me, speak openly, that I may know what it is,
and answer to it.`"

[.discourse-part]
_Judge._--You being suspected as a Jesuit or Papist, and preaching up and down,
the law provides that oath as an expedient whereby you may purge and clear yourself.

[.discourse-part]
_John Whitehead._--I have offered other expedients to clear myself,
both by certificates and offering to subscribe the substance of the oath;
for I scruple not at the allegiance.
If I could take any oath at all, I should not refuse that oath;
and since the law supposes every man clear till the contrary appears,
I think it very hard measure that I should be imprisoned
for one thing and then put to answer for another,
being not discharged of that for which I was first committed.

[.discourse-part]
_Judge._--You were discharged from that court order and then required to take the oath;
and if you will yet take it you may be discharged.

[.discourse-part]
_John Whitehead._--I was never discharged but conditionally,--if I would take the oath;
which to me is a case of conscience, because Christ Jesus says, "`Swear not at all.`"
Let me not perpetually be brought into the court to have the oath tendered as a snare,
that I may be made a transgressor; but let me have a fair trial for what I have done.

[.discourse-part]
_Court._--Take him away; we will consider of it till the afternoon.

[.offset]
Adjourn the court.

After dinner I was again brought into the court.
The officers seemed much instigated against me;
(by whom they best knew;) but I have ground to think,
the chancellor and subdean are not clear of being the occasion of my suffering,
which I am induced to, by reason of the chancellor`'s whispering against me in court,
and the unusual huffing of the clerk of the court session,
after he had dined at the subdean`'s,
who threatened some of my friends that came many miles to hear my trial,
with the oath of allegiance.
Notwithstanding, I again moved the court, that I might have a copy of my indictment,
and time to advise with counsel, before I was put to answer.

[.discourse-part]
_Judge._--You have heard the indictment, and I cannot grant a copy till you plead to it.

[.discourse-part]
_Clerk._--Are you guilty of the indictment or not?

[.discourse-part]
_John Whitehead._--Not guilty.

[.discourse-part]
_Judge._--That is a traverse in law, let it be tried.
So the traverse was entered, and a jury ready to try it.

[.discourse-part]
_John Whitehead._--I desire I may not be so hastily run upon to a trial,
before I have a copy of the indictment, and time to advise with counsel,
my case being very singular; for at the last court session,
I was returned as a person already convicted of premunire,
and therefore not prepared for a trial now;
and therefore desire a copy of the indictment, and time till next court session,
that I may have counsel in the case.

[.discourse-part]
_Judge._--I see you seek to gain time, and flourish before the country,
and reflect upon the court; and you wrote a letter after the judge, last court session,
wherein was railing language.^
footnote:[That letter follows their proceedings last court session,
which will witness for itself.]
I cannot grant you time till next court session; but you may have time till the morning,
and I shall come in on purpose to try you;
and in the mean time you may have a copy of the indictment; but it will signify nothing:
for I will tell you, that you must either prove that you did take the oath,
or else take it, or you cannot be cleared.

[.discourse-part]
_John Whitehead._--I intend not reflection on the court, but do think it very hard,
that I must first be surprised with the tender of an oath,
when I was to answer upon other things premised in my court order;
and now surprised with a trial,
after I have been so long imprisoned as a person convicted.

[.discourse-part]
_Judge._--There was a mistake in that, but now we shall right it;
but there is nothing will advantage you, but either taking the oath,
or proving you did take it.

[.discourse-part]
_John Whitehead._--I hope it will not be put on me to prove the negative,
till it be first proved, that the oath was legally tendered to me, and denied by me.

[.discourse-part]
_Judge._--That will be proved, I warrant you; if you will traverse it now,
the jury is ready; or if you desire time till the morning, you shall have it.

[.discourse-part]
_John Whitehead._--If it may not be put off till next court session,
I do desire time till the morning.

[.discourse-part]
_Judge._--Well you shall have it: adjourn the court,
and let him have a copy of the indictment--which was immediately delivered,
and the court adjourned till six o`'clock next morning.

[.small-break]
'''

The court being again set, I was called to the bar, and the jury called over.

[.discourse-part]
_Judge._--Come, are you ready for trial?

[.discourse-part]
_John Whitehead._--I have no counsel, having been kept within the prison;
and they all so busy, none could come to me,
and therefore again desire that my trial may be put off till next court session.

[.discourse-part]
_Judge._--That cannot be: clerk, swear the jury;
and if you will challenge any of them before they are sworn, you may.

[.discourse-part]
_John Whitehead._--They are all strangers to me,
and therefore I shall challenge none of them.

[.small-break]
'''

After the jury were sworn, the indictment was read, a copy of which follows:--

[.embedded-content-document.legal]
--

The jurors of our sovereign lord the king, upon their oaths, present,
That at the open court session for the county of Lincoln aforesaid,
held at the Castle of Lincoln in the same county of Lincoln,
on Monday the one and thirtieth day of July,
in the year of the reign of our sovereign lord, Charles the Second, by the grace of God,
of England, Scotland, France and Ireland, King, Defender of the Faith,
etc. the thirty-fourth; before William Gregory, knight,
one of the barons of the Exchequer of the said lord the king, and Thomas Street, knight,
another baron of the Exchequer of the said lord the king,
to take the court sessions in the county aforesaid;
and also the jail of the said lord the king, of the county aforesaid,
of the prisoners in the same, being to be delivered,
assigned in the open court sessions aforesaid, the said justices then,
(namely) the said one and thirtieth day of July,
in the four and thirtieth year aforesaid, at the Castle of Lincoln aforesaid,
in the county aforesaid, did tender to John Whitehead, late of the Bale of Lincoln,
in the county aforesaid, labourer, then not being a nobleman,
but then being above the age of eighteen years,
the oath contained in a certain act of Parliament, of the lord James,
late king of England, held by prorogation at Westminster, in the county of Middlesex,
the fifth day of November in the year of his reign of England, France, and Ireland,
the third, and of Scotland, the nine and thirtieth, late enacted and provided,
in these English words following (that is to say) "`I, John Whitehead, etc.,
So help me God:`" and that the said justices then, (that is to say) the said Monday,
the one and thirtieth day of July, in the four and thirtieth year abovesaid,
at the Castle of Lincoln aforesaid, in the county aforesaid,
in the said open court sessions,
the same John Whitehead requested to take that oath upon the Holy Evangelists,
and that the same John, the said oath, so by the afore-named justices, to the said John,
as aforesaid, offered and requested, then and there refused to take,
to the evil example of all others, of our said lord the king,
that now are his faithful subjects, in contempt of the said lord the king that now is,
against his laws, against the form of the said statute,
and against the peace of our said lord the king, his crown and dignity.

--

[.discourse-part]
_Judge._--(To the clerk) Come, where are your witnesses.

[.small-break]
'''

Then two witnesses were sworn, and gave evidence,
that they were at the last court session,
and then and there the oath of allegiance was tendered to me, and that I refused it.

I asked whether I refused it on the 31st July?
but that they could not affirm,
the whole country knowing that I had time to consider of it till next day.
And seeing neither of the witnesses could affirm that it was denied that day,
as the indictment affirms very untruly;
therefore (seeing the court ought to be of counsel with the prisoner,
to see that nothing be urged against right,) I desired the judgment of the court,
whether I ought not to be quit, seeing there was no proof that it was denied,
as the indictment affirms;
and whether there ought not to be a first and second tender of the oath,
and refusal upon both, before an indictment upon this statute, the third of king James?

[.discourse-part]
_Judge._--In some cases we ought to be counsel with the prisoner;
but need not be so in this case.
Yet I will tell you, that if it was tendered and refused any day of the court session,
it may be said to be on the first day of the court session;
for every day that the court session holds here, is but one day in law.
Yet there ought to be a first and second tender, and a refusal upon both;
for it is the second refusal that incurs a premunire.

[.discourse-part]
_John Whitehead._--Well then,
seeing the indictment does but charge me with once having the oath tendered unto me,
which I did not positively refuse, but gave reasons why it should not have been tendered,
and why I ought not to take it, I hope the indictment ought not to be found against me,
seeing I had not a first tender of the oath out of court, and a second in court,
according to the form of the statute upon which the indictment is grounded.

[.discourse-part]
_Judge._--You shall now have it tendered a second time,
and if you will yet take the oath of allegiance,
you may retrieve what is past and have your liberty?

[.discourse-part]
_John Whitehead._--If my life were concerned, as it is but my liberty and small estate,
I dare not break the command of Christ; but if I could take any oath whatsoever,
I should not refuse that oath; for I own allegiance due to the king,
and am willing to subscribe the substance of it; but to me it is a case of conscience,
so that I cannot take any oath; for Christ Jesus has said,
"`Swear not at all;`" therefore I desire, seek not to ensnare me with an oath.

[.discourse-part]
_Judge._
You say well; for in charity I do think that you make conscience of an oath;
and if you be so tender and scrupulous of taking an oath,
I ought to take heed of breaking an oath;
and I am by oath obliged to put the laws in execution;
and the law requires you to take this oath.
I must tell you,
there is cause to suspect that Jesuits first broached this principle among you,
not to swear; and I am persuaded I can convince any man here, but you,
of the lawfulness of an oath; for you ought to consider, not only the text,
but the scope of the matter and context, and then you will find,
Christ did not intend to forbid all oaths,
but vain oaths in communication and ordinary discourse, and oaths by the creatures,
as by heaven, and earth, and Jerusalem, and a man`'s head;
which were brought in by the corrupt gloss of the ancients.

[.small-break]
'''

--Upon this subject he did enlarge,
saying as much as a natural man can reach in that case, concluding,
that an oath for confirmation was to be the end of all strife.

[.discourse-part]
_John Whitehead._
All this cannot satisfy my conscience, in which I do believe, that not Jesuits,
but Christ Jesus has taught us this principle; for the whole scope of his words,
recorded in the fifth of Matthew, when I read and consider them,
I find he says something more than the letter of
the law says in most cases mentioned in that chapter,
and particularly in this case of swearing; for it cannot be denied,
but that swearing by the creatures, as heaven, earth,
etc. and likewise idle vain oaths in communication were forbidden in the time of the law;
and the oaths which Christ intended to forbid, were solemn oaths,
such as were to be kept and performed to the Lord,
as appears by the words going before the prohibition of all swearing, verse 33,
and 34. "`But I say unto you, Swear not at all,`" etc.
And I think the Apostle James is the best interpreter of Christ`'s mind in that case,
who said, "`Above all things, my brethren, swear not, neither by heaven,
neither by earth, neither by any other oath; but let your yes be yes, and your no, no,
lest you fall into condemnation,`" James 5:12.
For against these plain texts no argument lies good;
therefore urge me no further to it, for there are but these words,
"`any other person whatsoever`" in this statute,
that gives power to tender the oath in court,
and they are left out in the following statutes about the oath.
(Here the Judge was observed to say,
"`That is true.`") And the words of the Apostle are equivalent;
for after he has particularised the manners of swearing, he says,
"`nor by any other oath;`" which to me is a general prohibition of all oaths;
this in conscience I am bound to observe, and not follow the example of men in strife,
who take oaths.

[.discourse-part]
_Judge._
I shall not further dispute it with you, but shall tender you the oath;
give him the book: What say you, will you take it?

[.discourse-part]
_John Whitehead._
I am upon the traverse of the indictment,
and shall not answer to new matter till that be tried; and therefore, jury,
consider,--the indictment is the matter before you, with which you were charged,
to try according to your evidence, and not any new matter,
which is not in the indictment;
therefore if you find that the oath was not twice tendered, and twice refused,
before I was indicted, and you sworn to try the issue, you ought to acquit me;
for the indictment is the matter in question and not any new matter since you were sworn.

[.discourse-part]
_Judge._
You that are of the jury,
the indictment is laid but for once refusal of the oath of allegiance,
and here are two witnesses who prove that it was tendered to him the last court session,
and he has not proved that he did take it; and you see he still refuses it;
so gentlemen go together and consider of it.

[.small-break]
'''

The jury went forth, and in a short time returned to court.

The clerk called over their names, and said, Are you agreed of your verdict?

[.discourse-part]
_Jury._--Yes.

[.discourse-part]
_Clerk._--Who shall say for you?

[.discourse-part]
_Jury._--Our foreman.

[.discourse-part]
_Clerk._--Do you find for the king, or for the defendant?

[.discourse-part]
_Jury._--For the king.

[.small-break]
'''

Howbeit the judge forbore to pass sentence against me, and the court adjourned.

And I am returned in the calendar, as I was before, to remain in jail,
being convicted of a premunire for refusing the oath of allegiance.

[.numbered-group]
====

[.numbered]
Observe, _First,_--that the indictment was but for once refusing of the oath of allegiance,
which, according to the judge`'s own words, incurs not a premunire,
though it was found against me.

[.numbered]
_Secondly,_--that the oath of allegiance was not read to me in court,
when I was upon my traverse this court session, therefore not legally tendered:
and whether I had not law and reason to decline answering to new matter,
till the indictment was tried?

[.numbered]
_Thirdly,_--upon the whole matter,--whether by certificates and otherwise,
I have not fairly quit myself from that malicious slander cast upon me,
That I was a Jesuit; seeing they never could prove anything of it,
nor touch me for what I had already done;
but time after time they sought to ensnare me with an oath,
which they knew for conscience sake I could not take;--as the Papists
used to ensnare the Protestant martyrs with the sacrament of the altar,
wherein they knew they could not confess the real presence.
And this I have some reason to believe was not done
through prejudice or malice in the judges,
who both carried it fairly to me, especially the latter of them,
but rather through the instigation of some of the doctors belonging to Lincoln Cathedral,
who have hated me without a cause.

====

+++[+++The following remonstrance to the Justices, etc., without date,
was probably written soon after John Whitehead had
been thus again unjustly remanded to prison.]

[.embedded-content-document]
--

[.blurb]
=== To the King`'s Justices of the Court Session, Justices of the Peace, Grand Jurymen, Chief Constables, etc. An Apology Written by John Whitehead, a Sufferer for the Word of God and Testimony of Jesus Christ, and Presented to You in Behalf of that Peaceable, Suffering People, called Quakers.

You, being our countrymen who are in authority,
among whom we had our citizenship many years,
cannot but know that we are a harmless and peaceable people, who hurt no man,
but are willing to live honestly, and to give to every man his own.
Why then should we be ruined and destroyed for the
exercise of our conscience towards God,
whom we serve and worship in Spirit and Truth, as he requires us, and has taught us? John 4:23.
And therefore we dare not depart from his precepts and doctrine,
to receive "`for doctrine the commandments of men,`" lest we should worship in vain,
and not find acceptance with God, Matt. 15:9,
before whose judgment seat we must appear, to give an account for ourselves unto him.
Then the faces of all those shall gather paleness
who have not worshipped him according to his will;
and neither the commandment of princes nor the doctrine
of priests can excuse us at that day,
if our conscience condemn us; for God is greater than man,
and therefore unto God we must give the dominion in our consciences;
and dare not but be subject and obedient to his will, whatever we suffer;
though we have ever been, and are willing to render unto the king that subjection,
which the laws of God, nature, and the nation, agreeable thereto, enjoin; and shall,
as we have hitherto done, ever live peaceably under the king`'s government,
and desire nothing but that we may be protected in sobriety and virtue,
and not forced either to lose our liberties and properties,
or to do those things which are contrary to our conscience.

For certainly it can neither turn to the king`'s profit nor yours,
that so many hundreds in this county,
who are known to be laborious and industrious people,
should be ruined to gratify a company of envious persons,
and to enrich a sort of informers, promoters and other idle persons,
who are never likely to be farmers and tradesmen,
better knowing how to live by rapine and spoil,
than how to get means to live by honest industry:
and whether this may not in time tend both to the king`'s damage and your own,
and to the weakening and impoverishing of the nation,
is worthy of your serious consideration.

And consider well, that though imprisoning men`'s persons, taking away their goods,
and other punishments tending to ruin and destroy families,
may work upon earthly-minded men and hypocrites,
to make them outwardly conform to modes and manners of religion,
yet are they no good arguments to persuade people into the love of any religion.
For how should a man in his senses think their religion right,
who will bereave their neighbours of liberty and estate, if they will not conform to it?
Surely neither the true Christian religion at first, nor the Protestant religion since,
did by these methods gain reputation in the world; nor can yours now.
But through faith, sound doctrine and good works,
the first Christians and first Protestants overcame the world and convinced gainsayers;
for, indeed, the true Christian religion needs no outward force to uphold it,
having a witness in every man`'s conscience to its
holiness and righteousness which sustains it.

They who are true Christians and spiritually minded men, neither value liberty, estate,
nor life itself, in comparison of their religion and the true worship of God.
From this we can never be forced;
believing that as certainly as all divine worship and service belongs unto God,
so it belongs unto him to teach us how and in what manner we shall worship him;
and whether we do well to hearken unto him, rather than to changeable men, you judge.
For although we can willingly suffer for our religion,
and the exercise of our consciences towards God,
yet do we think it hard measure to be ruined and destroyed in our persons and estates,
by you who are mainly concerned in this matter;
and therefore we entreat you seriously to consider the fatal
consequences that these kinds of severities draw after them:--

[.numbered-group]
====

[.numbered]
_First,_--in provoking the Lord to anger, who never was pleased with persecutors,
since Cain slew his brother Abel.

[.numbered]
_Secondly,_--because of the discouragements brought upon industrious farmers and tradesmen;
who dare not lay out themselves; being in jeopardy every day,
to have their liberty or estate seized for their religion.

[.numbered]
_Thirdly,_--this severe course also, in its own nature,
tends to put industrious people upon the extremity to transport themselves;
whereby the nation is weakened, rents brought down, and trades decayed.

[.numbered]
_Fourthly,_--informers and other loose, idle persons,
who live by the ruin of their neighbours, are encouraged;
of which we that are sufferers make bold to remind you,
because you have had large experience of our peaceable conduct,
and cannot but know that we are no popish recusants, nor plotters,
nor contrivers of evil designs against the government:
and therefore you ought not to expose us to suffer as such,
but rather intercede for us to those that are in higher authority, who,
peradventure do not know us so well as you;
that we may no longer suffer by laws made in times of great provocation,
against such as were seditious and injurious to government.
We have a due esteem and reverence for this authority,
and desire nothing more than that we may live peaceably in the land of our nativity,
and be permitted the exercise of our conscience towards God,
while we are void of offence towards men;
and in allowing this you may fulfill the royal law of Christ, who says,
"`Whatever you want that men should do to you, even so do to them.`"

====

So consider our case as if it were your own,
and do your endeavour to ease us of those manifold oppressions
which lie upon us for our obedience to God;
that we may be set at liberty, and encouraged in our trades and callings,
to labour and improve that talent which God has given us,
for the good and benefit of the king and kingdom, yourselves, and all men;
to whom we have nothing but love and good-will in our hearts.
We shall ever seek the peace and tranquillity of this nation,
though in it we do suffer hard things,
by misinterpretation of laws made against papists and seditious persons,
which are turned upon us and against our peaceable, Christian meetings,
and for not swearing, in obedience to Christ, who said, "`Swear not at all.`"
All which we lay before you, hoping that God will put it into the heart of the king,
and dispose of you who are in authority, to ease and relieve us in due time.

--
